### ISSUE TITLE
Weird reformatting of commented out struct fields

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/rustfmt#1031]
input:

``` Rust
struct Foo {
    field1: u32,
    // field2: u32,
    // field3: u32,
}

```

output:

``` Rust
struct Foo {
    field1: u32, /* field2: u32,
                  * field3: u32, */
}

```

**Comment by edmccard** [comment]
This also happens inside enums. The problem only occurs whenever the final struct member/enum variant is commented; so this is fine

```
enum Foo {
    // bar = 1,
    // baz = 2,
    quux = 3,
}
```

but it messes up even if the last member is the only one commented, looking like this:

```
enum Foo {
    firstVariant = 1,
    secondVariant = 2, // thirdVariant = 3
}
```

**Comment by nrc** [comment]
This is now fixed, unless you set the normalise comments option.
