### ISSUE TITLE
Lost comment after struct generics

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rustfmt#1096]
Before:

``` rust
struct S<T> /* comment */ {
    t: T,
}
```

After:

``` rust
struct S<T> {
    t: T,
}
```

**Comment by nrc** [comment]
We have a lot of problems like this in rustfmt, it basically comes down to the fact that we don't have spans for every token in the AST. There is no easy fix. The long term fix is getting those spans and I'm not really keen to spend time on hacky fixes in the meantime.

For the Serde issue, I'd recommend either moving the comment or skipping this struct.

**Comment by dtolnay** [comment]
Makes sense, I am okay with won't fix. We cleaned up our code. It was junk left from years ago.
