### ISSUE TITLE
Leading commas

### ISSUE THREAD

**Issue by tuncer** [rust-lang/rustfmt#1152]
Writing a list of elements or clauses in leading-comma style is one of those things you miss very much, once you've gotten used to it. It also helps with seeing what line has a comma.

The example below is very simple and not representative of real code, so please ignore how the list of ints may or may not deserve to be written in this style. If needed, I can expand with other examples, where the benefit is much more evident.

Say you have

```
    let foo = vec![ 1
        , 2
        , 3
        , 4
        , 5
        , 6
        , 7
        , 8
        , 9
        , 10
        , 11
        , 12
        , 13
        , 14
        , 15
        , 16
        , 17
        , 18
        , 19
        , 20
        , 21
    ];
```

What I really want do is use leading-comma style as follows:

```
    let foo = vec![ 1
                  , 2
                  , 3
                  , 4
                  , 5
                  , 6
                  , 7
                  , 8
                  , 9
                  , 10
                  , 11
                  , 12
                  , 13
                  , 14
                  , 15
                  , 16
                  , 17
                  , 18
                  , 19
                  , 20
                  , 21
                  ];
```

The alignment of the comma is very important, but the column of the last line is open for stylistic debate. I use this style in Haskell, where it's very popular, but also in Erlang, where it also helps with avoiding mistakes in case..of (Rust match) clauses.

If I run it through rustfmt, this is what I get:

```
let foo = vec![1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21];
```

Problems with this:
1. reverses leading-comma style
2. exceeds column limit

Not everybody wants to use leading-comma style, so this should probably be opt-in.

**Comment by sinkuu** [comment]
```rust
    let foo = vec![1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21];
```
This exceeds ideal_width (=80) but is shorter than max_width (=100). You can set max_width smaller value to get this line splitted into new lines.

I grepped rustfmt code with `ideal_width` and found that it is hardly used (only formatting `where` clauses, trait bounds and attributes). Not sure what `ideal_width` is supposed to be.
