### ISSUE TITLE
Not aware of conditional path attribute

### ISSUE THREAD

**Issue by anowell** [rust-lang/rustfmt#1208]
```rust
#[cfg_attr(feature="with-serde", path = "json-serde.rs")]
#[cfg_attr(feature="with-rustc-serialize", path = "json-rustc-serialize.rs")]
mod json;
```

results in this error preventing `cargo fmt` from completing:

```
error: file not found for module `json`
  --> /home/anowell/proj/algorithmia-rust/src/lib.rs:53:5
   |
53 | mod json;
   |     ^^^^
   |
   = help: name the file either json.rs or json/mod.rs inside the directory "/home/anowell/proj/algorithmia-rust/src"
```

I am able to work around it with:

```rust
#[cfg(feature="with-serde")]
#[path = "json-serde.rs"]
mod json;

#[cfg(feature="with-rustc-serialize")]
#[path = "json-rustc-serialize.rs"]
mod json;
```

**Comment by nrc** [comment]
Although Rustfmt really ought to cope with this, I'd recommend against using this pattern - I'd generally recommend against all uses of the `path` attribute.

**Comment by anowell** [comment]
In general, I also agree with avoiding `path` and sticking to the default path semantics. But I believe the snippet below is the closest equivalent without using `path` (where `json` is not exported outside of the crate, but is accessible everywhere within the crate). And I don't particularly find this easier to read or reason about, so IMO, I went from 3 lines to 6 lines to 10 lines without obvious gains - perhaps "one less concept to understand" (i.e. `path`) is a gain, but `path` seems to be the easiest concept to grok in these examples. `¯\_(ツ)_/¯`

```rust
mod json {
    #[cfg(feature="with-serde")]
    mod json_serde;
    #[cfg(feature="with-serde")]
    pub use json_serde::*;

    #[cfg(feature="with-rustc-serialize")]
    mod json_rustc_serialize;
    #[cfg(feature="with-rustc-serialize")]
    pub use json_rustc_serialize::*;
}
```
