### ISSUE TITLE
Change or (allow changing) the backup suffix from `bk` to `orig`

### ISSUE THREAD

**Issue by sunshowers** [rust-lang/rustfmt#1304]
`rustfmt` writes out its backups with a `.bk` suffix. This suffix appears to be non-standard: most systems that potentially modify code in-place (`patch(1)`, svn, git, mercurial) use a `.orig` suffix instead.

I'm not sure if it's too late to change the default yet, but if it isn't, and unless there's a good reason, could you switch the default to `.orig`?

If it is too late, could you add a config option for that?

Bonus: allow configuring the path for backups. For example, see `origbackuppath` in [hgrc(5)](https://www.selenic.com/mercurial/hgrc.5.html).

**Comment by sanmai-NL** [comment]
If accepted, please redo https://github.com/rust-lang/cargo/pull/3760 .

**Comment by nrc** [comment]
Sounds like orig would be better, but since we don't emit backups at all by default now, I don't think this is urgent.

**Comment by sanmai-NL** [comment]
@nrc: Isn't the more appropriate method to triage: what is the cost-benefit ratio? You are only touching upon the benefit part there. Cost would, I presume, be low. I suppose it comes down to changing the file extension literal, and downstream to update the default Cargo `.gitignore` to match it.

**Comment by nrc** [comment]
I agree cost would be low, but I don't think that affects the priority - I'd be happy for someone to do this, but I'd rather they tackled any of the p-medium or p-high issues.
