### ISSUE TITLE
Format type bounds as <T: ...> or where T: ...

### ISSUE THREAD

**Issue by mehcode** [rust-lang/rustfmt#1323]
Decide on a convention here and format it.

My guess would be if the type bound is singular it gets moved into the `<...>` if its on `where ...`.

**Comment by nrc** [comment]
There is some resistance to having Rustfmt make these kinds of changes (we discussed it a bit over on fmt RFCs). I would like an option to move bounds where possible and desirable though.

**Comment by nrc** [comment]
There is some resistance to having Rustfmt make these kinds of changes (we discussed it a bit over on fmt RFCs). I would like an option to move bounds where possible and desirable though.

**Comment by mehcode** [comment]
One of the awesome things about go is not everyone agrees on how it looks but everyone goes along with it because of gofmt.

I was under the impression rustfmt was aiming to be as opinionated as that. 

---

Perhaps by default rustfmt can make those changes but they can be turned off via the config file?

**Comment by nrc** [comment]
> Perhaps by default rustfmt can make those changes but they can be turned off via the config file?

This is what I meant by having an option to do it.

**Comment by nrc** [comment]
Although, to be clear, it would probably be off by default, not on - generally in Rustfmt options which just affect spacing of code (or adding blocks where it does not affect semantics) are on by default and any other changes (code motion or otherwise editing code) are off by default.

**Comment by Pursuit92** [comment]
I'd love rustfmt to have the capability to enforce one or the other convention where possible (though where clauses are strictly more powerful). At the very least, it would be nice to have the ability to move things into a where clause when the inline variant makes the function signature too long for the formatter to handle. It would be nice for readability's sake to make that change before making the argument list vertical and potentially splitting its types over multiple lines waaay over on the right.
