### ISSUE TITLE
Checkstyle creates brand new xml tree for each file

### ISSUE THREAD

**Issue by ahal** [rust-lang/rustfmt#1636]
If you lint multiple files with --write-mode=checkstyle, it'll create multiple xml documents like:

    <checkstyle><file name="file1.rs">...</file></checkstyle>
    <checkstyle><file name="file2.rs">...</file></checkstyle>

Instead there should only be a single root \<checkstyle\> tag:
    
    <checkstyle>
    <file name="file1.rs">...</file>
    <file name="file2.rs">...</file>
    </checkstyle>

**Comment by calebcartwright** [comment]
I'm not sure how far back this was fixed, but AFAICT it has been. I can't reproduce, and I also added some tests (like [this one](https://github.com/rust-lang/rustfmt/blob/master/src/emitter/checkstyle.rs#L89)) in https://github.com/rust-lang/rustfmt/pull/3694 to cover this scenario/prevent a regression. 

IMHO this can be closed

**Comment by topecongiro** [comment]
@calebcartwright Thank you for confirming!
