### ISSUE TITLE
Block indentation in chains

### ISSUE THREAD

**Issue by dragostis** [rust-lang/rustfmt#1762]
Shouldn't chains with visual indentation indent blocks to the same visual indentation?

```rust
let a = b.iter()
         .map(|m| {
             m.hi()
         });
```

Instead of

```rust
let a = b.iter()
         .map(|m| {
             m.hi()
});
```

**Comment by dragostis** [comment]
A simple example is:

```rust
let grammar: Vec<_> = ast.attrs.iter().filter(|attr| {
    match attr.value {
        MetaItem::NameValue(ref ident, _) => format!("{}", ident) == "grammar",
        _ => false
    }
}).collect();
```

which gets formatted to:

```rust
let grammar: Vec<_> = ast.attrs.iter()
                         .filter(|attr| match attr.value {
    MetaItem::NameValue(ref ident, _) => format!("{}", ident) == "grammar",
    _ => false
 })
                         .collect();
```

This is probably because the line is too long and it tries to find a solution.

**Comment by dragostis** [comment]
I'm interested to take a jab at this one if it doesn't require any major rearchitecturization.

**Comment by topecongiro** [comment]
Thank you for being interested in contributing to rustfmt!

I do not think we need major reachitecturization to fix this. However, mixing chains and closures with visual indent has been known to be complex. It may be difficult to come up with an implementation which works in every case.

FWIW in rustfmt 0.3.6, the above example will be formatted to somewhat better code:

```rust
    let grammar: Vec<_> =
        ast.attrs.iter()
           .filter(|attr| match attr.value {
                       MetaItem::NameValue(ref ident, _) => format!("{}", ident) == "grammar",
                       _ => false,
                   })
           .collect();
```
