### ISSUE TITLE
`cargo fmt` doesn't format files in sub-directories in `tests`

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rustfmt#1820]
I have a big integration test suite with sub-directories inside of the `tests` directory; running `cargo fmt` doesn't format these files.

**Comment by brauliobz** [comment]
`cargo fmt` only formats test code that is reached by `cargo test`, which basically follows the `mod` inclusions, from what I could see.

I tested the following scenario:
```
tests/
    root_test.rs
    subdir/
        mod.rs
        sub_test.rs
```
*sub_test.rs* is formatted only when:

* *root_test.rs* includes subdir by `mod subdir;`;
* and *subdir/mod.rs* includes sub_test.rs by `mod sub_test;`.

Is this behavior really desirable?

**Comment by nrc** [comment]
I think there are two kinds of `cargo test` - unit tests, which `cargo fmt` should reach if they are reachable via module includes (I think this is fine); and integration tests, which are not formatted at all (which we should address, though I'm not really sure how).

**Comment by calebcartwright** [comment]
Just a heads up that I've taken a pass at this and now have a working implementation locally.

Will open a PR for discussion/review/etc. within the next day or two
