### ISSUE TITLE
Add a new chain_indent option "BlockAlign"

### ISSUE THREAD

**Issue by canndrew** [rust-lang/rustfmt#2080]
**Edit:** I've edited this bug report to make it clearer what I'm asking for.

### The problem

Currently, `rustfmt` has two possible options for `chain_indent`, niether of which are ideal.

`"Block"`:

```rust
let lorem = ipsum
    .dolor()
    .sit()
    .amet()
    .consectetur()
    .adipiscing()
    .elit();
```

`"Visual"`:

```rust
let lorem = ipsum.dolor()
                 .sit()
                 .amet()
                 .consectetur()
                 .adipiscing()
                 .elit();
```

The advantage of `"Block"` is that avoids pushing code way out to the right and squashing it against the rightmost column. The advantage of `"Visual"` is that it's easier to see what the method chain is being applied to.

A problem with both is that they create indentation without a closing delimiter. In a curly-braced, non-significant-whitespace language like Rust it can be jarring to see indentation drop back multiples levels at once, it looks like there are missing parenthesis. Another problem with both is that, when writing combinator-heavy code (such as futures-based code), even `"Block"` creates a lot of unnecessary indentation. For example, consider a few nested `and_then` usages:

```rust
lorem
    .ipsum()
    .dolor()
    .and_then(|sit| {
        sit
            .amet()
            .consectetur()
            .and_then(|adipiscing| {
                adipiscing
                    .elit()
            })
    })
```

I only have three levels of nested combinators, yet 5 levels of indentation.  And the code starting with `.amet()` is disconnected, floating lonelily away from its `self` argument.

I'd like a new `chain_indent` option which gives the best of both `"Block"` and `"Visual"` and solves the above problems.

### The proposal

Add a new `chain_indent` option, call it `BlockAligned`, with the following behaviour:

If a method chain which is being split over multiple lines is part of a larger expression, then it get's put in its own block:

```rust
let lorem = {
    ipsum
    .dolor()
    .sit()
    .amet()
    .consectetur()
    .adipiscing()
    .elit()
};
```

Otherwise, if it's a standalone expression, it just gets aligned to the left (ie. without a block). For the nested `and_then` example this would look like:

```rust
lorem
.ipsum()
.dolor()
.and_then(|sit| {
    sit
    .amet()
    .consectetur()
    .and_then(|adipiscing| {
        adipiscing
        .elit()
    })
})
```

For the work I'm currently doing, which involves lots of chains of futures-combinators, this ends up looking much nicer. Would you guys consider merging patches to support this style?

**Comment by nrc** [comment]
I'd rather shrink the range of options than grow them right now (we're heading towards 1.0 and rustfmt needs focus). So I'd rather not add this kind of thing at the moment. However, once 1.0 is out of the way and if something like this is somewhat widely desired, then I'd be happy to have patches.

**Comment by asomers** [comment]
+1 for this.  I find rustfmt to be unusable for futures-based code for this one reason.

**Comment by stken2050** [comment]
> I'd rather shrink the range of options than grow them right now (we're heading towards 1.0 and rustfmt needs focus). So I'd rather not add this kind of thing at the moment. However, once 1.0 is out of the way and if something like this is somewhat widely desired, then I'd be happy to have patches.

Currently, version 1.4.21, when will the chain configuration be available? Thanks.
