### ISSUE TITLE
Tests relying on env vars are unreliable

### ISSUE THREAD

**Issue by nrc** [rust-lang/rustfmt#2183]
Env vars a global mutable state, so tests relying on them are intermittent. I've commented out these tests for now. Fixing them requires using a global lock to ensure they run sequentially.

**Comment by topecongiro** [comment]
Hmm, this looks like an issue for rls  :wink:

**Comment by nrc** [comment]
Yeah, I think I have PTSD from this kind of thing in the RLS

**Comment by topecongiro** [comment]
Ah, I first thought that you meant to open this in the rls issues. It turns out that I was missing the commit https://github.com/rust-lang-nursery/rustfmt/commit/96886cd67f1faa83bfb360c31c6614e1aea46bf7. My apologies.
