### ISSUE TITLE
Feature Request - Matching, no double indent (with/without leading vert)

### ISSUE THREAD

**Issue by strega-nil** [rust-lang/rustfmt#2234]
I'd like to be able to write code like this:

```
match foo {
| Bar(...) => ...,
| Baz(...) => ...,
}
```

it's also possible that some might not want to use leading verts?

```
match foo {
Bar(...) => ...,
Baz(...) => ...,
}
```

but that's outside of my need.

**Comment by ytmimi** [comment]
closing in favor of #2937
