### ISSUE TITLE
cargo fmt doesn't pass arguments to rustfmt when ran through rustup

### ISSUE THREAD

**Issue by YaLTeR** [rust-lang/rustfmt#2279]
```
└─ rustup run nightly cargo fmt -- --write-mode=diff
Unrecognized option: 'write-mode'
<help for cargo fmt>

└─ cargo +nightly fmt -- --write-mode=diff
<works>
```
Originally mentioned [here](https://github.com/rust-lang-nursery/rustfmt/issues/2227#issuecomment-350501555) where it was confirmed by @CraZySacX.

**Comment by sinkuu** [comment]
Rustup uses `clap` when not in proxy mode, and it removes `--`.

```rust
let res = App::new("")
    .arg(
        Arg::with_name("command")
            .required(true)
            .multiple(true)
            .use_delimiter(false),
    )
    .get_matches_from_safe(vec!["cargo", "fmt", "--", "--write-mode=diff"]);
println!(
    "{:?}",
    res.unwrap()
        .values_of("command")
        .unwrap()
        .collect::<Vec<_>>()
); // prints ["cargo", "fmt", "--write-mode=diff"]
```

**Comment by brandur** [comment]
Does anyone happen to have a workaround for this one? I'm trying to put rustfmt in a precommit hook, but this problem unfortunately makes it impossible as far as I can tell (without making `nightly` my default toolchain I mean).

**Comment by nrc** [comment]
It seems that there is no technical solution here and we just need to document the difference and the work around.

**Comment by ytmimi** [comment]
I don't think this is an issue anymore. I can run `rustup run nightly cargo fmt -- --emit=stdout` in the root of the rustfmt repo and it seems to pass the `--emit=stdout` to rustfmt just fine.

The workaround for the original issue `cargo +nightly fmt -- --emit=stdout` also works just fine.
