### ISSUE TITLE
`cargo test` integration

### ISSUE THREAD

**Issue by nrc** [rust-lang/rustfmt#2537]
What would it take to automatically (with some opt-in, perhaps the presence of rustfmt.toml) run `rustfmt --check` as part of `cargo test`? I assume we'd need to extend `cargo test` somehow to know about rustfmt, to do that  generically probably means some kind of test plugin thing.

**Comment by davepacheco** [comment]
This seems like it would be really useful.  Is there some reason not to support it or is it just a question of finding somebody to do the work?
