### ISSUE TITLE
custom delimiter in macro

### ISSUE THREAD

**Issue by kpp** [rust-lang/rustfmt#2570]
In [nom](https://gitter.im/Geal/nom) `>>` is used as expr delimiter but rustfmt treats it as a binop. Here is an example of formatted code:

```diff
 impl FromBytes for ClientHandshake {
-    named!(from_bytes<ClientHandshake>, do_parse!(
-        pk: call!(PublicKey::from_bytes) >>
-        nonce: call!(Nonce::from_bytes) >>
-        payload: take!(ENC_PAYLOAD_SIZE) >>
-        (ClientHandshake { pk, nonce, payload: payload.to_vec() })
-    ));
+    named!(
+        from_bytes<ClientHandshake>,
+        do_parse!(
+            pk: call!(PublicKey::from_bytes) >> nonce: call!(Nonce::from_bytes) >>
+                payload: take!(ENC_PAYLOAD_SIZE) >> (ClientHandshake {
+                pk,
+                nonce,
+                payload: payload.to_vec()
+            })
+        )
+    );
 }
```

config:
```
max_width = 100
binop_separator = "Back"
combine_control_expr = false
force_multiline_blocks = true
```

version:
```
rustfmt 0.4.1-nightly (374dba8 2018-03-22)
```

**Comment by nrc** [comment]
Sigh, it's kind of amazing that that parses as an expression :-) Probably just need to skip uses.

Long term, macro authors will be able to write instructions for rustfmt to format macro uses, but that is a long way off. Short term, we could blacklist some macro names, including `do_parse`.

**Comment by topecongiro** [comment]
What about having a config option which lets rustfmt skip formatting macros unless they are known (e.g. `println!`)?

Hopefully, once scoped attribute is implemented, we may be able to write like `#![rustfmt::skip::macro]` and only skip macros in the specific module.

**Comment by kpp** [comment]
There are to many modules with macro'ses I want to skip, and I don't want to mix my code with rustfmt directives. I would like to configure once and forget about special configuration and hacks.

**Comment by nrc** [comment]
> What about having a config option which lets rustfmt skip formatting macros unless they are known 

It seems a shame to do this because there are so many macros we *do* handle pretty well.

**Comment by kpp** [comment]
UPD:

```diff
 impl FromBytes for ClientHandshake {
-    named!(from_bytes<ClientHandshake>, do_parse!(
-        pk: call!(PublicKey::from_bytes) >>
-        nonce: call!(Nonce::from_bytes) >>
-        payload: take!(ENC_PAYLOAD_SIZE) >>
-        (ClientHandshake { pk, nonce, payload: payload.to_vec() })
-    ));
+    named!(
+        from_bytes<ClientHandshake>,
+        do_parse!(
+            pk: call!(PublicKey::from_bytes)
+                >> nonce: call!(Nonce::from_bytes)
+                >> payload: take!(ENC_PAYLOAD_SIZE)
+                >> (ClientHandshake {
+                    pk,
+                    nonce,
+                    payload: payload.to_vec()
+                })
+        )
+    );
 }
```

```
$ cargo fmt --version
rustfmt 0.99.1-nightly (da17b68 2018-08-04)
```

**Comment by scampi** [comment]
Formatting the macro can now be avoided using the attribute `#![rustfmt::skip::macros(do_parse)]`.

**Comment by kpp** [comment]
Tha's nice but can I configure it in rustfmt.yml config?

**Comment by scampi** [comment]
I don't think so, isn't it @rchaser53 ?

**Comment by rchaser53** [comment]
Yes, you don't need to use rustfmt.yml.
You can use attribute rustfmt::skip::macros like this.
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=35e31dfcbc37627a9dc22add8f056b27

**Comment by kpp** [comment]
But I don't want to pollute my code with `rustfmt` attributes. What's the point of rustfmt.yml then?
