### ISSUE TITLE
 cargo fmt doesn't find the servo crates used in gecko

### ISSUE THREAD

**Issue by emceeaich** [rust-lang/rustfmt#2654]
From: https://bugzilla.mozilla.org/show_bug.cgi?id=1454757

Running cargo fmt on top-level m-c makes changes in some crates, but doesn't seem to find the servo crates.

Running |cargo fmt --package mozurl| formats the mozurl crate. But doing the same thing for "style" gives me:

> package `style` is not a member of the workspace

This was discussed with FFx build engineering and after some consideration, we're moving it here.

**Comment by nrc** [comment]
How is Cargo used to build the Servo crates? And can you link me to the relevant Cargo.tomls please?

**Comment by bholley** [comment]
Sorry for the delay, was on leave.

The top-level Cargo.toml for Firefox is here: https://searchfox.org/mozilla-central/source/Cargo.toml

Getting to the style code requires the following hops:
* https://searchfox.org/mozilla-central/source/toolkit/library/rust/Cargo.toml
* https://searchfox.org/mozilla-central/source/toolkit/library/rust/shared/Cargo.toml
* https://searchfox.org/mozilla-central/source/servo/ports/geckolib/Cargo.toml
* https://searchfox.org/mozilla-central/source/servo/components/style/Cargo.toml

The error is simple to reproduce with a checkout of mozilla-central, no need to compile anything.

**Comment by topecongiro** [comment]
Since `servo` is excluded from a workspace, cargo fmt cannot find it. I don't think there is anything we can do to fix this issue, sorry.
