### ISSUE TITLE
Extend license check to automatically insert it

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rustfmt#2706]
Rustfmt can currently be told to check for a license header at the top of all files, but ideally it would insert it for you automatically.

While the current implementation supports regex parsers for things like the current year, we'd need to extend that so that rustfmt would understand what to expand to. Intellij uses a syntax like `${today.year}` for that: https://www.jetbrains.com/help/idea/copyright-profiles.html.

**Comment by calebcartwright** [comment]
Closing as we're going to [drop the license related features](https://github.com/rust-lang/rustfmt/issues/5103). License management is certainly a useful feature, but think this would be best served in dedicated tooling instead of an incomplete aside in rustfmt
