### ISSUE TITLE
Fixed location for global rustfmt.toml

### ISSUE THREAD

**Issue by erkin** [rust-lang/rustfmt#2710]
There seems to be two ways to have a global rustfmt config:
1. Put rustfmt.toml under `/`
2. Alias rustfmt to `rustfmt --config-file [file]` (which overrides higher priority configs, such as crate-specific ones, and doesn't work when invoked from non-shell environments, such as emacs)

both of which feel kludgy.

I think having a low-priority (overridden by everything else) config path at `$CARGO_HOME` (or perhaps `$XDG_CONFIG_HOME/rustfmt`) would be a simpler and friendlier solution.

**Comment by johnchandlerburnham** [comment]
One partial (but also kludgy) workaround I've discovered for this is if you're running Vim is to set:

```
let g:rustfmt_options='--config-path ~/.config/rustfmt/rustfmt.toml'               
```
in your `.vimrc`

This lets `:RustFmt` in vim run a custom global `rustfmt.toml`, but leaves the configurations for `rustfmt` and `cargo fmt` unchanged.

**Comment by m-ou-se** [comment]
#3280 Implements this.
