### ISSUE TITLE
Have a test-fail option for integration tests

### ISSUE THREAD

**Issue by nrc** [rust-lang/rustfmt#2724]
Several of the tests pass formatting just fine but fail because the repo's testing fails before rustfmt'ing. It would be nice to be able to mark tests so that we only check for successful formatting, not testing. Or, run tests before formatting and only check them after formatting if they passed before.

cc @gnzlbg

**Comment by gnzlbg** [comment]
Some of the rust-lang-nursery crates break every now and then with nightly changes. 

We can just finish the integration tests with success if the `cargo test` before the formatting changes fails. That is, if the crate currently doesn't build and pass its tests as is.
