### ISSUE TITLE
can Rustfmt avoid stripping form-feed characters?

### ISSUE THREAD

**Issue by db48x** [rust-lang/rustfmt#2757]
I spent a little time looking through the source, and made this change:

    diff --git a/src/visitor.rs b/src/visitor.rs
    index 4a0ce439..4695d74f 100644
    --- a/src/visitor.rs
    +++ b/src/visitor.rs
    @@ -727,7 +727,10 @@ impl<'b, 'a: 'b> FmtVisitor<'a> {
                 .opt_span_after(mk_sp(self.last_pos, end_pos), "\n")
             {
                 if let Some(snippet) = self.opt_snippet(mk_sp(self.last_pos, pos)) {
    -                if snippet.trim().is_empty() {
    +                if snippet
    +                    .chars()
    +                    .all(|c: char| c != '\x0c' && c.is_whitespace())
    +                {
                         self.last_pos = pos;
                     } else {
                         return;

This proved to be insufficient.

**Comment by nrc** [comment]
I'm not exactly sure what you are trying to do, sorry. But I think you can set the `newline_style` to `Windows` and then we will terminate with newline and form feed

**Comment by db48x** [comment]
Setting `newline_style` to `windows` would surely terminate lines with a carriage return + line feed, and therefore isn't what I'm referring to. I'm asking about form feed characters. If I have a Rust source file with form feed characters in it, I want them to remain when I run rustfmt on the file.

**Comment by mitsuhiko** [comment]
As the vast majority fo editors do not do anything useful with form feed I don't think that should be a default option at least. It makes for stupid diffs if form feeds are involved and most developers are not aware of them.

**Comment by db48x** [comment]
Those are not very good arguments. If you don't know how to use a form-feed character, then you won't ever notice that rustfmt leaves them in your source because you'll never use them. Meanwhile, people who do know how to use them will be able to.

**Comment by mitsuhiko** [comment]
This is not a made up issue. I have worked on projects before where people added form-feed characters and they got accidentally removed through edits. rustfmt is supposed to establish unified best practices and I do not believe that leaving form feed characters in sources which the vast majority of editors cannot deal with should be encouraged.

**Comment by db48x** [comment]
I didn't say that you made it up, just that it wasn't a very good argument. I'm working with an established project that has used form-feeds in the source for years.

**Comment by mitsuhiko** [comment]
So what's wrong for making it an option?

**Comment by db48x** [comment]
Of course it can be an option.

**Comment by nrc** [comment]
cc #1254

**Comment by topecongiro** [comment]
Closing in favor of #1254.
