### ISSUE TITLE
Use println style formatting for attributes with formatting strings

### ISSUE THREAD

**Issue by nrc** [rust-lang/rustfmt#2808]
E.g.,

```
    #[fail(
        display = "Could not find {}: Found: {}, expected: {:?}",
        0, 1, 2
    )]
```

rather than

```
    #[fail(
        display = "Could not find {}: Found: {}, expected: {:?}",
        0,
        1,
        2
    )]
```

**Comment by topecongiro** [comment]
Somewhat implemented (currently only supports `fail` attribute from `failure` crate).

**Comment by ytmimi** [comment]
@calebcartwright  since support for the `fail` attribute was added in #3067, and a test case for this can be found in `tests/target/enum.rs` is it alright to close this?
https://github.com/rust-lang/rustfmt/blob/a7bf0090347d8523dd62c0508a4c8413cdba099a/tests/target/enum.rs#L257-L261

**Comment by calebcartwright** [comment]
I'm ambivalent on this one @ytmimi. We could address this going forward via extending the [special case macros](https://github.com/rust-lang/rustfmt/blob/a7bf0090347d8523dd62c0508a4c8413cdba099a/src/overflow.rs#L63-L66) on a case by case basis which may not be terrible given how rarely this seems to have come up over the last few years.

However, aiui the original intent of this was to not have to explicitly enumerate special cases at rustfmt code-write/compile time, but to have rustfmt be capable of making these determinations at run time based on the actual args.

I think I'd be fine with closing this for now and planning on going the special case extension route unless and until the volume really increases

**Comment by ytmimi** [comment]
Getting back a little late on this, but I think it makes sense to close this for now. As you mention, this hasn't really come up in the last few years, and we always have the option to revisit / reopen this if the volume of requests starts picking up.
