### ISSUE TITLE
rustfmt 0.6.1 regression from previous stable: cargo fmt -- --write-mode diff return 0

### ISSUE THREAD

**Issue by Dushistov** [rust-lang/rustfmt#2832]
I use `cargo fmt -- --write-mode diff` on CI. And before rustc 1.27.0/rustfmt 0.6.1,
`cargo fmt -- --write-mode diff` return not zero exit code if code not match `cargo fmt`,
but now `cargo fmt -- --write-mode diff` always return 0 even if diff not empty

**Comment by nrc** [comment]
You should use the new `--check` flag if running on CI. `--write-mode` is no longer supported

**Comment by Dushistov** [comment]
@nrc 

> You should use the new --check flag if running on CI. --write-mode is no longer supported

Obviously I can not use it:

>$ cargo fmt --all -- --check
>Unrecognized option: 'check'
>$ rustfmt --version
>rustfmt 0.6.1-stable (49279d7 2018-05-08)

**Comment by dianpopa** [comment]
Hi, 

I have the same scenario as @nrc described. What is the recommended solution in this case for being able use **rustfmt** inside CI?

Thanks!

**Comment by nrc** [comment]
@dianpopa I would recommend using the beta or nightly channel and then you can just use `--check` (you don't need to run rustfmt with the same channel that you build with and switching is easy with rustup). Otherwise you can use `--write-mode diff` until the next stable release. https://medium.com/@ag_dubs/enforcing-style-in-ci-for-rust-projects-18f6b09ec69d has more info

**Comment by ashleygwilliams** [comment]
@nrc looks like there's been another regression on this 
<img width="890" alt="screen shot 2018-07-27 at 10 51 54 am" src="https://user-images.githubusercontent.com/1163554/43331490-0a9316be-9194-11e8-9fd7-ef3f27f963f3.png">

**Comment by ashleygwilliams** [comment]
(this was this morning, on stable, in CI)

**Comment by nrc** [comment]
urgh, thanks, yeah, that's wrong (although given it's only a week till the next stable release, we're unlikely to address it, tbh).
