### ISSUE TITLE
Unintuitive flag needed to format code blocks in comments

### ISSUE THREAD

**Issue by Seeker14491** [rust-lang/rustfmt#2844]
When I run rustfmt on the following code,

```rust
/// ```rust
/// fn main(){println!("Hello, world!");}
/// ```
fn main(){println!("Hello, world!");}
```

this is the formatted code produced:

```rust
/// ```rust
/// fn main(){println!("Hello, world!");}
/// ```
fn main() {
    println!("Hello, world!");
}
```

The code block in the doc comment is not formatted. **edit:** As topecongiro notes below, the `wrap_comments` flag needs to be set in order for the doc comment code block to be formatted, which is unintuitive.

I tested on the following two versions, and both have this issue.
```
rustfmt 0.8.2-nightly (08da30d 2018-06-06)
rustfmt 0.8.2-nightly (667ad76b 2018-07-12)
```

**Comment by topecongiro** [comment]
Code blocks in comments are not formatted by default. You need to use `wrap_comments`.

OTOH this is unintuitive: I think we should add a different config option other than `wrap_comments` (e.g. `format_code_block_in_doc_comments`). When it is set to `true` rustfmt formats code blocks in comments.

**Comment by scampi** [comment]
this is now done with the [format_doc_comments](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#format_doc_comments) options
