### ISSUE TITLE
Configuration option to preserve blank lines at beginning of block

### ISSUE THREAD

**Issue by cmbrandenburg** [rust-lang/rustfmt#2868]
It would be nice if `rustfmt` had a configuration setting for preserving blank lines at the beginning of blocks.

For example, it would be nice if `rustfmt` converted this program…

```rustfmt
fn main() {
    
    /* blah bleh bluh */
        println!("Hello world");
}
```

…into the following program:

```rustfmt
fn main() {
    
    /* blah bleh bluh */
    println!("Hello world");
}
```

This preservation of space is especially important when the function signature spans several lines, as sometimes it's nice to have a visual break between a complex signature and the body of code.

There once was a configuration option called `remove_blank_lines_at_start_or_end_of_block` that did this, but it was removed as part of #1974 for reasons unapparent.

**Comment by nrc** [comment]
We're unlikely to do this, tbh. In the complex signature case, there is always either a line with just `{` or indentation to guide the eye. There is a cost in implementation and UI complexity in having many options, so we want to make sure they pull their weight and this one has not been requested much.

**Comment by cmbrandenburg** [comment]
Thanks for keeping this ticket open despite its inactivity.

I understand your concern for having configuration options pull their weight. Perhaps what I want doesn't require a new option type but instead could be expressed as an alternative brace style?

I've distilled the “blank line” feature to the specific case that bugs me, as shown in the example below.

In this example, the second function is easier on my eyes because the signature is more clearly separated from the body. I can't imagine I'm alone on this. Yet the first function is what `rustfmt` gives by default—a wall of text.

```rust
impl MyType {
    fn normal_len_fn_name_1(
        &mut self,
        param1: SomeOtherType,
        param2: SomeOtherType, 
    ) -> Result<i32, Error> { 
        let a = param1.blah();
        let b = param2.bleh();
        let c = param2.bluh();
        return a + b + c;
    }

    fn normal_len_fn_name_2(
        &mut self,
        param1: SomeOtherType,
        param2: SomeOtherType) 
        -> Result<i32, Error> 
    {   
        let a = param1.blah();
        let b = param2.bleh();
        let c = param2.bluh();
        return a + b + c;
    }
}
```

Is it feasible to add or extend a configuration option to make `rustfmt` put the brace on its own line for multi-line function signatures? I think this a change that would better pull its weight.

**Comment by Rantanen** [comment]
> we want to make sure they pull their weight and this one has not been requested much.

I don't know where to 'request' that so I'll just add a comment here. I don't expect one comment to change anything really, but at least I can pretend it's counted. :)

(I was slightly disappointed to not find this as a feature, despite indication to make it a configuration option in the original RFC: https://github.com/rust-dev-tools/fmt-rfcs/issues/57#issuecomment-298441336 - I know priorities change and rustfmt has been actively aiming for "less options")

My workaround for now is to enable `brace_style = AlwaysNextLine` to force a bit of breathing space between the signature and the body.

**Comment by jcramb** [comment]
I've been running into this recently and it's been infuriating trying to find a way to configure it to leave blank lines at the start of a block. This is something I'd consider to be a vital configuration option, especially looking at some of the other options that are possible. If there's any way this feature can be brought back I'd really appreciate it!

**Comment by ayazhafiz** [comment]
@topecongiro @calebcartwright I am interested in taking a look at this if that's good

**Comment by calebcartwright** [comment]
That'd be great @ayazhafiz!
