### ISSUE TITLE
internal error: left behind trailing whitespace

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rustfmt#2916]
Source: https://github.com/bjorn3/rustc_codegen_cranelift/tree/rustfmt_error

```
$ cargo fmt
internal error: left behind trailing whitespace
   --> /home/bjorn/Documenten/rustc_codegen_cranelift/src/lib.rs:416
    |
416 |                     
    | ^^^^^^^^^^^^^^^^^^^^

warning: rustfmt may have failed to format. See previous 1 errors.
```

**Comment by minno726** [comment]
Same issue for me. The minimal reproduction I have is two lines:

```
a_macro!(name<Param1, Param2>, 
);
```

The error points to the trailing space on the first line. Removing one or both of the generic parameters removes the error.

**Comment by theduke** [comment]
I have run into the same issue.

Sadly it occurs all over the place for me with using a macro to build HTML.
