### ISSUE TITLE
Trailing comma left when collapsing vertical argument list to single line

### ISSUE THREAD

**Issue by staktrace** [rust-lang/rustfmt#2918]
Using `rustfmt 0.99.2-nightly (5c9a2b6 2018-08-07)` on this:

```rust
impl Foo {
    pub fn get_key(&self) -> Result<String, MailParseError> {
        Ok(
           try!(encoding::all::ISO_8859_1.decode(
               self.key,
               encoding::DecoderTrap::Strict,
           )).trim()
                .to_string(),
        )
    }
}
```

collapses the `decode` call onto a single line which is fine, but it keeps the trailing comma. My understanding is that the default value for `trailing_comma` is `Vertical` which should delete the comma.

**Comment by scampi** [comment]
@topecongiro as you mentioned in your comment, removing the comma could break some macros. Can we close this as a `no fix` then ?
