### ISSUE TITLE
Detect and Use EditorConfig Files

### ISSUE THREAD

**Issue by severen** [rust-lang/rustfmt#2938]
A feature that I believe would be useful is if rustfmt would use any relevant configuration it finds from an [EditorConfig](https://editorconfig.org/) file (`.editorconfig`) if it exists, such as the indent style, indent size, and other settings. This is useful if you, like me, don't really configure much beyond the tab style and size and a couple other things and would rather have one source of truth that various tools such as rustfmt and the editor itself can refer to. 

There is precedent for this in similar tools, such as in [Prettier](https://prettier.io/), see [here](https://github.com/prettier/prettier/issues/42) and [here](https://github.com/prettier/prettier/commit/8f58ca0f4802db62719ef6689bd5fb7c476c7afb).

Also, any settings in rustfmt.toml should take priority over those defined in `.editconfig`, since it is more specific to rustfmt.

**Comment by m-ou-se** [comment]
> Also, any settings in rustfmt.toml should take priority over those defined in .editconfig, since it is more specific to rustfmt.

What if the `rustfmt.toml` is found in a directory higher up than `.editconfig`?

    projects/
    ├── rustfmt.toml
    └── x/
        ├── .editorconfig
        └── the-file-being-formatted.rs

You could argue the `.editorconfig` here is more specific than the `rustfmt.toml`.

**Comment by h4x3rotab** [comment]
At each level of the directory, the priority can be defined as "rustfmt > editorconfig". Then the deeper level config can override the shallow level config

**Comment by calebcartwright** [comment]
Thanks for sharing the idea and to all for the discussion, but I'm going to close as we don't intend on implementing this. Please note that if anyone feels sufficiently strongly about this feature you are certainly still welcome to contribute a PR which we'll absolutely consider. However, I don't want to continue having this in open state 3+ years on and in doing so imply that the rustfmt team will/may implement it ourselves.

I definitely appreciate the desire for EditorConfig utilization, but given that rustfmt already has its own long standing configuration mechanism (which already has more than a few outstanding issues) I can't justify spending any of the little bandwidth we have in trying to bolt on support for yet another file.

In my experience, formatting tools which support configuration either use their own file or utilize EditorConfig files, but very few support both. I acknowledge prettier is an exception to that, though as I recall prettier started with support from editorconfig before later incorporating their own config files which supported the standard cosmiconfig-based model to which JavaScript devs are highly accustomed.

Finally, if anyone _does_ decide to take a pass at implementing this, I would recommend thoughtful considerations around whether to support EditorConfigs defined in the user's home directory and if/how precedence would be determined, both between any more localized EditorConfigs as well as the various rustfmt configs.
