### ISSUE TITLE
Silent fatal error when formatting code snippets

### ISSUE THREAD

**Issue by goffrie** [rust-lang/rustfmt#2941]
Minimal repro (need `wrap_comments = true`):
```rust
//! ```
//! \
//! ```
```
A fatal error occurs in the lexer while trying to consume the backslash, and then the entire process aborts without any error message.

Also it would be helpful for rustfmt to avoid trying to format such snippets if they're marked e.g. ` ```text`.

**Comment by topecongiro** [comment]
This is fixed in the latest master, just needs a test to get closed.
