### ISSUE TITLE
Running cargo fmt seems to break some macro expansion

### ISSUE THREAD

**Issue by fdb-hiroshima** [rust-lang/rustfmt#3004]
Running cargo fmt on [Plume-org/Plume](https://github.com/Plume-org/Plume) breaks it. It seems to remove curly braces around the macro invocation, which make macro expansion fail with `unexpected end of macro invocation`

Step to reproduce :
```sh
$ git clone https://github.com/Plume-org/Plume
$ cd Plume
$ cargo check #compile fine
$ cargo fmt --all
$ cargo check #fail
```
Reproducible with `rustfmt 0.8.2-nightly (5e59925 2018-07-02)` (specified by `rust-toolchain`) and `rustfmt 0.99.2-nightly (5c9a2b6 2018-08-07)` via `+nightly`

**Comment by topecongiro** [comment]
A minimal example:

```rust
fn main() {
    foo!(|_| { () });
}
```

becomes

```rust
fn main() {
    foo!(|_| ());
}
```

**Comment by eddyb** [comment]
Another case is `stringify!((foo+))`, where rustfmt removes the `+`.
Why does it even change that? Because it looks like a trait object type?

**Comment by eddyb** [comment]
@topecongiro Pretty much on any separated list, the separator can be trailing, in Rust.
