### ISSUE TITLE
windows: add a way to install rustfmt alongside MSI-based rust installation

### ISSUE THREAD

**Issue by ikostia** [rust-lang/rustfmt#3075]
For various reasons, I use MSI-based stable rust installer on Windows. For such an installation flavor, there seems to be no way to install `rustfmt`:
- I can't use `rustup`, because it's MSI installation
- I can't build it from source, because I use stable compiler

Can this be fixed or are there any workarounds?

**Comment by topecongiro** [comment]
To fix this we could put pre-built binaries on the release page, but even then I am not sure if you could run those binaries without installing the nightly.

**Comment by topecongiro** [comment]
Starting from the 2.0 release, we will provide pre-built binaries for Windows/macOS/Linux.

**Comment by calebcartwright** [comment]
@topecongiro - what are your thoughts on doing something like a tag-push based trigger in a GHA workflow that will create the pre-built binaries (presumably for all Tier 1 platforms) and create the GitHub Release with that tag and binaries as artifacts?

**Comment by topecongiro** [comment]
@calebcartwright Yeah, adding some kind of automation as you described is what I have in mind.

**Comment by SpecterShell** [comment]
@topecongiro The pre-built binary was not compiled statically and requires a library file that does not match the one in the latest Rust MSI installer.

![image](https://github.com/rust-lang/rustfmt/assets/56779163/2ad6a44f-8cca-41e1-a7a8-41991bafdff8)
