### ISSUE TITLE
tracking issues for unstable configuration options

### ISSUE THREAD

**Issue by softprops** [rust-lang/rustfmt#3111]
Similar to how the rust project has github tracking issues for all of its unstable options for interested parties to subscribe to, would it be possible for to have a similar way to subscribe and track updates to all the "stable: no" rust fmt configuration options listed in https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md?

This is of special interested to me because I depend on only on nightly to run `cargo +nightly fmt` but use stable for everything else. I'd be interested in have a way to be looped into the day I no longer have to do that.

**Comment by softprops** [comment]
just checking in on this issue. Without a better way to know what the progress is on stabling a specific config options is a very frustrating experience to be locked into +nightly in ci for stable focused projects

**Comment by scampi** [comment]
i'll try to create some tracking issues

**Comment by scampi** [comment]
https://github.com/rust-lang/rustfmt/commit/412dcc70a2fa8edc042b83af762c3741b54c61a0 I pushed by mistake to master, but there is an updated configuration file where tracking issue are mentioned for each of the options.

**Comment by softprops** [comment]
@scampi thats great! 

Minor feedback on that. 

It would be even better to have a hyper link on those and to have the issue not be part of the title. The reason being is because those are hyper links on github 
so changing the titles breaks existing likes. i.e  https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#fn_args_density is now https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#fn_args_density-tracking-issue-3375 ect

Should I hope another issue for that would would be be a quick change for you?

**Comment by softprops** [comment]
when I said hyper link above, i meant a hyper link to the gh issue. I can construct that by hand but even better would just be the ability to click a link

**Comment by scampi** [comment]
@softprops very good point, i'll fix that
