### ISSUE TITLE
document code block can be annotated with several attributes

### ISSUE THREAD

**Issue by scampi** [rust-lang/rustfmt#3158]
The `CodeBlockAttribute` enum needs to be updated to support attributes separated with commas, e.g.,:

```rust
// Rust and ignore attributes:
// ```rust,ignore
// foo! { x, y }
// ```
```

**Comment by scampi** [comment]
At the moment, that would be interpreted as a text block:

https://github.com/rust-lang-nursery/rustfmt/blob/2d718a3fc23fbe9a27c71709c54128b5305609c7/src/comment.rs#L393

However, I thought there could be some combinations where formatting could be wanted, e.g., `rust,no_run` or `rust,should_panic`.

**Comment by r00ster91** [comment]
Note: it is `format_code_in_doc_comments` now.

**Comment by nipunn1313** [comment]
@rustbot claim

does this work here?

**Comment by nipunn1313** [comment]
ah needs something like https://github.com/rust-lang/cargo/blob/master/triagebot.toml
