### ISSUE TITLE
error_on_line_overflow does not diagnose function attributes inside macros

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rustfmt#3164]
```rust
macro_rules! foo {
    ($id:ident) => {
        macro_rules! bar {
            ($id2:tt) => {
                #[cfg(any(target_feature = $id2, target_feature = $id2, target_feature = $id2, target_feature = $id2, target_feature = $id2))]
                fn $id() {}
            };
        }
    };
}

fn main() {}
```

`rustfmt`, as expected, does not format this code (its inside a macro), but with `error_on_line_overflow = true` in the `rustfmt.toml` I'd expect `cargo fmt -- --check` to diagnose that the line where the `#[cfg(...)]` macro is located is too long, yet no diagnostic is emitted.

**Comment by topecongiro** [comment]
I could not reproduce this locally with `rustfmt 0.99.6-nightly (750b2526 2018-10-18)`. Would you tell us the repository you were working on and the version of rustfmt you used?

**Comment by gnzlbg** [comment]
@topecongiro `packed_simd` using the preview, there are many lines (hundreds) starting with `#[cfg_attr(not(target_arch = "wasm32"), test)] #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test)]`  that go over the line limit, but I couldn't get rustfmt to error on those.

**Comment by topecongiro** [comment]
@gnzlbg Thank you!

When `error_on_line_overflow` is set to `true`, rustfmt reports any line that exceeds max width except comment and string literal. Looks like the logic is too pessimistic, and the string literals in `#[cfg_attr(not(target_arch = "wasm32"), test)] #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test)]` (`"wasm32"`) is preventing the error report.

**Comment by gnzlbg** [comment]
Ah damn, trying to find a MWE, the one I came up with does not use any string literals =/

**Comment by gnzlbg** [comment]
@topecongiro so it appears that `error_on_line_overflow` also fails in many more cases. 

`packed_simd` contains a script in `ci/max_line_width.sh` that checks the max line width for all `.rs` files and fails on a line if the line does not contain `http` (links cannot be split across line). It appears that all matches found by this script are errors, which finds many (the script currently fails on the first match, but you might want to disable that).
