### ISSUE TITLE
rustfmt wrap_comments breaks doc tests

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rustfmt#3193]
Rustfmt with `wrap_comments = true` and `max_width = 79` reformats this:

```rust
/// Foo
///
/// ```rust
/// # #![cfg_attr(not(dox),feature(cfg_target_feature, target_feature, stdsimd))]
/// # #[cfg(not(dox))]
/// # #[macro_use]
/// # extern crate stdsimd;
/// ```
fn foo() {}
```

to this:

```rust
/// Foo
///
/// ```rust
/// # #![cfg_attr(not(dox),feature(cfg_target_feature, target_feature,
/// # stdsimd))] # #[cfg(not(dox))]
/// # #[macro_use]
/// # extern crate stdsimd;
/// ```
fn foo() {}
```

which breaks rust doc because now there are two hashes `# #` in the second line.

**Comment by scampi** [comment]
With the latest from master, that won't because wrapping is disabled for doc tests.

**Comment by gnzlbg** [comment]
Thanks, I guess we can close this then. Or shall we wait till it hits nightly?
