### ISSUE TITLE
Process for config option stabilisation

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rustfmt#3197]
The `trailing_semicolon` configuration for example is currently unstable. What needs to happen in order for it to be stabilized?

(I would like to use it in a project that is otherwise compatible with the Stable channel.)

**Comment by SimonSapin** [comment]
To be clear, I don’t think there is much to discuss about this particular option. This is mostly about what is the process in general.

**Comment by SimonSapin** [comment]
Hello @rust-lang/dev-tools team. Now that the 2018 edition and rustfmt 1.0 have shipped, what are your thoughts on the desired process for configuration option stabilization?

**Comment by scampi** [comment]
Just writing down some ideas for stabilising an option, comments welcome!

# Conditions

- the option is well tested, both in unit tests and, optimally, in real usage
- there is no open bug about the option that prevents its use

# Steps for the stabilisation

Open a PR that closes the tracking issue:

- update the `Config` enum marking the option as stable
- update the the `Configuration.md` file marking the option as stable

# After the stabilisation

## Backward compatibility

The option should remain compatible with previous parameters of the option. For instance, if the option is an enum `enum Foo { Alice, Bob }` and the variant `Foo::Bob` is removed/renamed, existing use of the `Foo::Bob` variant should map to the new logic.
Maybe this is covered by the current version-gate scheme but I wanted to bring this aspect forward.
