### ISSUE TITLE
Support exclusions

### ISSUE THREAD

**Issue by epage** [rust-lang/rustfmt#3211]
Use case: I've vendored some code (benchmarks from related crates) and want to keep them pristine while enforcing rustfmt on the rest of my code.

Possible solution: Move all the lints into a table and add a table that selects what to format and uses gitignore syntax.

**Comment by topecongiro** [comment]
There is `ignore` configuration option which may solve you issue:

**Comment by epage** [comment]
Thanks!  I'll give that a try.

So I'm guessing this is turning into more of a discoverability issue.  I feel I missed it because in my quick scan, it looked like all the flags were for controlling formatting.  My recommendation, if its not too late, would be for the layout to not be flat but to explicitly divide up options that control formatting from options that control behavior of rustfmt itself.

**Comment by topecongiro** [comment]
Good point. Unfortunately it is not trivial as we have a test infrastructure that checks the content of Configurations.md (to see if we are not missing any configuration options or examples), so we need to update both the document and the test as well.

**Comment by topecongiro** [comment]
We now have a github page to look for configuration options. It should help a searchability of configuration options.

https://rust-lang.github.io/rustfmt/
