### ISSUE TITLE
cargo fmt --version does not work

### ISSUE THREAD

**Issue by scampi** [rust-lang/rustfmt#3214]
```sh
$ cargo run --bin cargo-fmt -- --version
```

This is not limited to `--version` actually, nothing gets printed with `--help` for instance.

**Comment by richardwhiuk** [comment]
(Note this breaks simple things like `cargo fmt --version`).

**Comment by scampi** [comment]
This is what I get running the command:

```sh
$ cargo fmt --version
rustfmt 1.0.1-nightly (be13559 2018-12-10)
```

What is breaking on your side ?

**Comment by richardwhiuk** [comment]
@scampi This was specific to a particular release of cargo fmt which has been fixed.
