### ISSUE TITLE
indent binop sub-exprs according to precedence

### ISSUE THREAD

**Issue by nrc** [rust-lang/rustfmt#322]
e.g.,

```
let inner_expr = match expr.node {
            ast::Expr_::ExprBlock(ref inner) if inner.stmts.is_empty() && inner.expr.is_some() &&
                                                inner.rules ==
                                                ast::BlockCheckMode::DefaultBlock => {
                inner.expr.as_ref().unwrap()
            }
            _ => expr,
        };
```

would, I think be better formatted as

```
let inner_expr = match expr.node {
            ast::Expr_::ExprBlock(ref inner) if inner.stmts.is_empty() && inner.expr.is_some() &&
                                                inner.rules ==
                                                    ast::BlockCheckMode::DefaultBlock => {
                inner.expr.as_ref().unwrap()
            }
            _ => expr,
        };
```

**Comment by marcusklaas** [comment]
Should we format
```
extremely_loooooooooooooooooooooooooooooooong &&
    fairly_loooooooooooong ==
    pretty_loooooooooong
```
as

```
extremely_loooooooooooooooooooooooooooooooong &&
    fairly_loooooooooooong ==
        pretty_loooooooooong
```
, or keep it as it was? What about long homogeneous chains a la
```
AAAAAAAAAAAAAAAAA ||
     BBBBBBBBBBBBBBBBB ||
     CCCCCCCCCCCCCCCC ||
     DDDDDDDDDDDDDDDDDDDD
```
?

**Comment by nrc** [comment]
I think the second one and no to the third. Which means I might not have a great idea about what to do. I guess I want to indent if it's of strictly less precedence?

**Comment by nrc** [comment]
@marcusklaas are you looking at this? If not, I'll have a shot.

**Comment by marcusklaas** [comment]
Go for it!

-----Original Message-----

**Comment by nrc** [comment]
This is 'fun'. Assuming that we want to indent the rhs of binops with lower precedence is a start. But we get into this nightmare of wanting to treat ASTs of binop'ed expressions as a list and then identify the precedence of items in that list and indent appropriately. I assume that once we're formatting a list rather than a tree, this will be easier, but on a tree this is really hard.

**Comment by nrc** [comment]
So, a complex example of what's desired:

```
AAAAAAAAAAAAAAAAA ||
BBBBBBBBBBBBBBBBB ||
CCCCCCCCCCCCCCCC ==
    CCCCCCCCCCCCCC ||
DDDDDDDDDDDDDDDDDDDD +
    EEEEEEEEEEEEEEE +
    FFFFFFFFFFFFFFF +
    GGGGGGGGGGGGGGG ==
        HHHHHHHHHHHHHHHHH ||
IIIIIIIIIIIIIIII ||
JJJJJJJJJJJJJJJJ
```

**Comment by nrc** [comment]
I don't have time to do this at the moment, but it'll be an interesting little project when I (or someone else) has a bit more time.
