### ISSUE TITLE
Long return statement needs two rustfmt runs to reach final format

### ISSUE THREAD

**Issue by faern** [rust-lang/rustfmt#3226]
Given the following code (which is a very stripped down example of something more sane):
```rust
fn main() {
    {
        {
            {
                return Err(ErrorKind::ManagementInterfaceError("Server exited unexpectedly").into())
            }
        }
    }
}
```
When I format it once I get (just added `;` at the end):
```rust
fn main() {
    {
        {
            {
                return Err(ErrorKind::ManagementInterfaceError("Server exited unexpectedly").into());
            }
        }
    }
}
```
And If I run rustfmt a second time on that I end up with:
```rust
fn main() {
    {
        {
            {
                return Err(
                    ErrorKind::ManagementInterfaceError("Server exited unexpectedly").into(),
                );
            }
        }
    }
}

```
This must be a bug I believe. We should always end up with the final format on one run? I have tried this, and get the same result, with both `1.0.0-nightly` and by building the latest master branch in this repo (`rustfmt 1.0.0-nightly (43206f41 2018-11-30)`).

**Comment by marcusklaas** [comment]
I can see how this could happen. The line splitting mechanism doesn't see that a semicolon will get added and thinks it can still fit the expression on one line. Could probably be solved by reordering those two formatting operations (semicolon add first, linebreak decision after).

**Comment by faern** [comment]
It feels logical to check if a line is too long or not after the line has been edited to it's final content indeed.
