### ISSUE TITLE
Unable to install on Rust 1.31.0 with rustup

### ISSUE THREAD

**Issue by fominok** [rust-lang/rustfmt#3233]
Trying to install it as shown in 1.31 update blogpost with `rustup component add rustfmt` and got
`toolchain 'stable-x86_64-unknown-linux-gnu' does not contain component 'rustfmt'...`

It might be related with same behaviour for Clippy https://github.com/rust-lang/rust-clippy/issues/3503

**Comment by fominok** [comment]
Complete reinstall of toolchain as mentioned in Clippy thread worked for me

**Comment by woodgear** [comment]
but why should i reinstall? is there some better way?
