### ISSUE TITLE
Cannot install on nightly

### ISSUE THREAD

**Issue by D4nte** [rust-lang/rustfmt#3246]
I have a fresh rustup install from today (default stable). I was able to install rustfmt for stable but nightly does not work. I followed the instructions as per the readme.

```
✔ ~/src/swap [266-rust-2018 L|⚑ 14]
02:17 $ rustup component add rustfmt --toolchain nightly
error: component 'rustfmt' for target 'x86_64-apple-darwin' is unavailable for download
✘-1 ~/src/swap [266-rust-2018 L|⚑ 14]
02:18 $ rustup toolchain list
stable-2018-12-06-x86_64-apple-darwin
stable-x86_64-apple-darwin (default)
nightly-2018-12-06-x86_64-apple-darwin
nightly-x86_64-apple-darwin
```

Can you please assist?

**Comment by sinkuu** [comment]
https://mexus.github.io/rustup-components-history/

Latest nightly actually doesn't have rustfmt. It should be available in the next one (have been delayed unfortunately: https://github.com/rust-lang/rust/issues/56667).

**Comment by D4nte** [comment]
Thank you, I had no idea that a component may not be delivered with a specific nightly release!

Will rustfmt and clippy (ie, without -preview) be ever added to nightly?

**Comment by xrl** [comment]
I'm tracking the issue over in #3244 as well.

**Comment by palfrey** [comment]
https://mexus.github.io/rustup-components-history/ says 2018-12-14 has it again

**Comment by topecongiro** [comment]
🎉
