### ISSUE TITLE
Space aligned comments are collpased

### ISSUE THREAD

**Issue by JoelScarfone** [rust-lang/rustfmt#3248]
Before:
```rust
SomeStruct::some_function()
    .do_more()                   // do more
    .do_a_lot_more()             // do a lot more
    .do_a_whole_lot_more()       // do a whole lot more
    .finish();
```
After:
```rust
SomeStruct::some_function()
    .do_more() // do more
    .do_a_lot_more() // do a lot more
    .do_a_whole_lot_more() // do a whole lot more
    .finish();
```
This was a recent change, and i'm not sure that it was ideal. This was found on rustfmt 1.0.0-nightly (1cc61cf 2018-11-19). (Edit: But that commit was not necessarily where the change was applied.)

**Comment by topecongiro** [comment]
In general rustfmt tends to avoid comment alignment as it tends to cause more diffs. However rustfmt could not format chain methods that contain comment, so in the above example the comment alignment was untouched. This was 'fixed', now rustfmt formats them, and as a result the comment alignment gets collapsed.

**Comment by CreepySkeleton** [comment]
So, does this mean there's no way to avoid such collapsing?

**Comment by topecongiro** [comment]
Currently no, sorry.

In the future we can add a config option which allows gofmt-ish formatting for some expressions (e.g., function calls and method chains). That is, to preserve the user's input as much as possible and do minimal reformatting unlike what rustfmt currently does.
