### ISSUE TITLE
format_doc_comments causes adjacent comments to be made multiline

### ISSUE THREAD

**Issue by DianaNites** [rust-lang/rustfmt#3268]
I have `format_doc_comments = true` in my `.rustfmt.toml`, and all of a sudden my adjacent comments are being formatted in C Style multiline instead of left alone. Not doc comments.

For example, this
```rust
// pub nice: String,
// pub nice_adjacent: String,
```

will be turned into this

```rust
/* pub nice: String,
* pub nice_adjacent: String, */
```

These are also unaffected by the `normalize_comments` option

----
Version details:

rustfmt 1.0.1-nightly (be135599 2018-12-10), via rustup component.
cargo 1.33.0-nightly (2cf1f5dda 2018-12-11)
rustc 1.33.0-nightly (2d3e909e4 2018-12-22)

**Comment by scampi** [comment]
If these comments are after a field inside a struct, that is on purpose. See #3209 and #93 for more details.

**Comment by DianaNites** [comment]
Well, thats disappointing.
