### ISSUE TITLE
modifies commented out multiline string literals

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rustfmt#3270]
I can have code like this
````rust
    let s = String::from(
        "
hello
world
",
    );

    assert_eq!(s, "\nhello\nworld\n");
````
and comment out the string
````rust
pub fn main() {
 /*   let s = String::from(
        "
hello
world
",
    ); */

    assert_eq!(s, "\nhello\nworld\n");
}
````

when I now rustfmt, rustfmt changes the indent of the comments  but it does not see that by indenting the code of the literal, it actually changes the literal.
````rust
pub fn main() {
    /*   let s = String::from(
            "
    hello
    world
    ",
        ); */

    assert_eq!(s, "\nhello\nworld\n");
 }
````
If I now remove the comment markers, the assertion will no longer hold.

**Comment by scampi** [comment]
if nobody's on that, I would like to try fix this
