### ISSUE TITLE
`cargo fmt` doesn't accept `--message-format`.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rustfmt#3274]
This means it can't easily be invoked by tools (e.g. editors) that want to avoid dealing with multiline error messages.

#2817 is related, in that `cargo fmt` should probably accept most general Cargo flags.

cc @Manishearth @oli-obk Does `cargo clippy` do anything special here?

**Comment by oli-obk** [comment]
Clippy calls cargo check and forwards all arguments, so I presume message-format will work, too.

I think we need a general way to invoke drivers like rustfmt, clippy-driver and others. I opened an issue on the cargo repo a while ago: https://github.com/rust-lang/cargo/issues/6356

Any discussion on my suggestions are very welcome
