### ISSUE TITLE
#[rustfmt::skip] does not work for whole modules recursively

### ISSUE THREAD

**Issue by sdroege** [rust-lang/rustfmt#3279]
The following has no effects outside the given module itself

```rust
#[rustfmt::skip]
mod foo;
// applies to foo::* but not to e.g. foo::bar::*
```

or inside `foo/mod.rs`

```rust
#![rustfmt::skip]
// applies to e.g.
struct Foo { ... }

// but does not apply to
mod bar;
```

This seems inconsistent with other such attributes, like the ones from clippy.

**Comment by topecongiro** [comment]
I could not reproduce this with neigher `rustfmt 1.0.0-stable (4a4e508 2018-11-29)` nor `rustfmt 1.0.1-nightly (be13559 2018-12-10)`. Could you provide us with the version of rustfmt you used, and if possible, the repository you hit this issue?

**Comment by sdroege** [comment]
I can't actually reproduce it anymore and switched to this solution now. Not sure what changed since I reported the issue. Sorry for the noise!
