### ISSUE TITLE
Use Unicode UAX#14 to format multi-line string

### ISSUE THREAD

**Issue by wada314** [rust-lang/rustfmt#3281]
A FIXME introduced by PR #3275 .

Currently we are using our own break_string() method to wrap multi-line string.
But Unicode has a standard algorithm to wrap a string:
http://www.unicode.org/reports/tr14/
It will be good if we can use this algorithm instead of our current code.
We can use xi-unicode crate:
https://crates.io/crates/xi-unicode

**Comment by topecongiro** [comment]
Closed via #3275.

**Comment by ahl** [comment]
This appears to have been closed prematurely. #3275 introduced this... it didn't close it. @topecongiro can you re-open?
