### ISSUE TITLE
Add `--print-config current`

### ISSUE THREAD

**Issue by alercah** [rust-lang/rustfmt#3283]
I would like my `vim` to be able to automatically detect the indent size based on `rustfmt.toml`. The easiest way to do that would be to support `--print-config current PATH` which loads all configuration files normally, as if formatting the file at `PATH`, and then prints the computed current config to stdout. IDEs with more advanced format-as-you-go features may wish to retrieve other configuration options too.

**Comment by topecongiro** [comment]
Closed via #3472.
