### ISSUE TITLE
Accept `all-features` flag

### ISSUE THREAD

**Issue by IsaacWoods** [rust-lang/rustfmt#3287]
Many cargo subcommands accept an `--all-features` flag, which enables all of a crate's features. I have a crate that conditionally includes files if features are set (which subsequently aren't formatted when running `cargo fmt`). It'd be great if `cargo-fmt` could accept this flag

**Comment by AngelLomeli** [comment]
Hello. I'm interested in starting to contribute to rustfmt, and I saw that this issue didn't seem to have anyone already looking.

While I'm familiar with git, I haven't gone through the workflows on GitHub lately. If there's anything I've missed or done incorrectly, just let me know and I'll be happy to fix it.

Thanks!
-Angel

**Comment by topecongiro** [comment]
AFAIK, rustfmt formats files behind `#[cfg(feature = "...")]` by default, but files behind `cfg_if!` are partially supported (#3763 should hopefully fix it, though).

**Comment by topecongiro** [comment]
I think that this is already fixed via the support of `cfg_if!`. Please feel free to re-open the issue if this is not the case.
