### ISSUE TITLE
Indentation characters are not replaced inside non-standard macro calls

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rustfmt#3292]
If rustfmt is unable to parse a macro call (because braces are used or because the contents are not parseable as a standard Rust construct), it will completely ignore the contents of the macro call. It should still do basic formatting: replace tabs by spaces, strip whitespace at the end of the line, etc.

**Comment by calebcartwright** [comment]
Closing as a duplicate of #8 amongst a few others. Until such time as we've got a better story for macro formatting, this is going to continue to be the behavior in the spirit of "first, do no harm"
