### ISSUE TITLE
Add reorder_attributes config to sort doc attributes before other attributes

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rustfmt#3303]
This was discussed in https://github.com/rust-dev-tools/fmt-rfcs/issues/72 with the conclusion that the style guide recommends doc comments before attributes, with an option in rustfmt to do the reordering that is off by default.

I did not find an existing option that does this, nor an issue to track, so here we go. :)

Expected diff:

```diff
- #[cfg(cfg)]
  /// doc
+ #[cfg(cfg)]
  struct S;
```

**Comment by ctaggart** [comment]
I think this issue and #3744 are the same. Even though this came first, #3744 has more active discussion. I'd recommend closing this @dtolnay.

**Comment by ytmimi** [comment]
Going to close this in favor of https://github.com/rust-lang/rustfmt/issues/3744
