### ISSUE TITLE
Appveyor is not working on CI

### ISSUE THREAD

**Issue by topecongiro** [rust-lang/rustfmt#3307]

**Comment by rchaser53** [comment]
I tried to run Appveyor in my fork repository. It's succeeded.
This is a link. https://ci.appveyor.com/project/rchaser53/rustfmt
What's happened?

**Comment by topecongiro** [comment]
I think Appveyor stopped working when the rustfmt repository moved from rust-lang-nursery to rust-lang.

@nrc It seems that currently I only have a permission to work on the nursery. Is it possible that I get more permission so that I could set up CI myself in the rust-lang namespace? Or if that is not possible, would you mind taking a look at this?

**Comment by nrc** [comment]
@topecongiro you still have the GitHub permissions, I couldn't figure out Appveyor permissions. I added a new Appveyor project for this repo. I'm not sure if that will fix things.

**Comment by topecongiro** [comment]
Looks like it's working now, thanks!
