### ISSUE TITLE
Expression attribute duplication

### ISSUE THREAD

**Issue by h2so5** [rust-lang/rustfmt#3313]
## input
[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=bebaaf5ac1a3d0957075ec03bf5f70b1)
```rust
#![feature(stmt_expr_attributes)]

fn main() {
    let foo;
    #[must_use]
    foo = false;
}
```

## output
```rust
#![feature(stmt_expr_attributes)]

fn main() {
    let foo;
    #[must_use]
    #[must_use]
    foo = false;
}
```

**Comment by topecongiro** [comment]
The problem is that the span of assignment (`foo = false`) does not include the attribute, so rustfmt incorrectly adds it as 'missing'.
