### ISSUE TITLE
Removed indentation after nested comments

### ISSUE THREAD

**Issue by martin-t** [rust-lang/rustfmt#3314]
The indentation on front of `println!` gets removed:
```rust
/*code
/*code*/
if true {
    println!("1");
}*/
```
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b9250fee7f0e366723f638422a1f7be0)

Nested comments are usually only temporary but I don't think this is expected behavior - I'd expect everything inside comments to stay unchanged.

**Comment by scampi** [comment]
fixed in #3318
