### ISSUE TITLE
De-glob glob imports

### ISSUE THREAD

**Issue by Xaeroxe** [rust-lang/rustfmt#3329]
Hi!

I don't know if rustfmt receives enough info to do this or not, but it would be neat if, via an opt-in configuration setting you could have rustfmt "de-glob" a glob import.  So in theory I could go from

```rust
use smallvec::*;

fn make_a_smallvec() -> SmallVec<[i32; 4]> {
    smallvec![];
}
```

to

```rust
use smallvec::{SmallVec, smallvec};

fn make_a_smallvec() -> SmallVec<[i32; 4]> {
    smallvec![];
}
```

Again I'm not sure if rustfmt receives enough information to do this or not, but it would be nice as it would enable me to glob during development, and then run rustfmt at the end to de-glob.

**Comment by topecongiro** [comment]
This feature is neat, but seems like it's out of the scope of rustfmt, sorry. rustfmt acts on AST, so it cannot tell what names are imported from modules.

Maybe rustfix has enough information to handle this kind of feature.
