### ISSUE TITLE
Regression in formatting Syn's token macro

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rustfmt#3331]
Our CI hit a surprising formatting change: https://travis-ci.org/dtolnay/syn/jobs/490139618.

```diff
 #[cfg(any(feature = "full", feature = "derive"))]
 pub fn fold_abi<V: Fold + ?Sized>(_visitor: &mut V, _i: Abi) -> Abi {
     Abi {
-        extern_token: Token![extern](tokens_helper(_visitor, &_i.extern_token.span)),
+        extern_token: Token ! [ extern ](tokens_helper(_visitor, &_i.extern_token.span)),
         name: (_i.name).map(|it| _visitor.fold_lit_str(it)),
     }
 }
```

I minimized this to:

```bash
echo 'Token ! [ extern ];' | cargo run --bin rustfmt
```

Before f4f9502e:

```rust
Token![extern];
```

Since f4f9502e:

```rust
Token ! [ extern ];
```

Mentioning @topecongiro and @scampi who were involved in that PR.

**Comment by topecongiro** [comment]
It looks like rustfmt fails to format a macro call whose argument is `extern`. Haven't confirmed, but I think that this is due to the recent change in the rustc parser (https://github.com/rust-lang/rust/pull/57572).
