### ISSUE TITLE
[unstable option] license_template_path

### ISSUE THREAD

**Issue by scampi** [rust-lang/rustfmt#3352]
Tracking issue for unstable option: license_template_path

**Comment by Robbepop** [comment]
Hi, I am using this feature and it helps me a lot in general with the license headers in my project.
So far I used something like this to specify the valid dates in the license:
```
{20\d{2}}-{20\d{2}}
```
This works and successfully validates date ranges such as `2018-2019`.
However, I also wanted to make the last part optional and thus only allow a single year to be valid as well.
I tried several things, none worked.
```
{20\d{2}}(?:-{20\d{2}})? // nope
{20\d{2}}(?:-{20\d{2}}?) // nope
{20\d{2}}{{20\d{2}}}? // nope
```
Maybe I am doing something wrong. (I am not used to work with regex.)
Or are there some limits to the regex parser for license headers?
If so we should either document those or maybe tackle them. :)

**Comment by thibault-martinez** [comment]
Hi @Robbepop, if still relevant, this works for me `{20\d{2}(-20\d{2})?}`.

**Comment by Robbepop** [comment]
Thanks I will try that out! :)

**Comment by mrbianchi** [comment]
Multiline template isn't working...

**Comment by mrbianchi** [comment]
Looks like my issue is using Windows and the break lines, I cloned repositories with that working and still failing, I'm using the last nightly version

**Comment by mrbianchi** [comment]
Switched CRLF to LF in the template file and now is working, I was using visual studio code
https://stackoverflow.com/a/39532890

**Comment by DMats** [comment]
I was confused about what regex formatting options were allowed. The comment at [license.rs#L70](https://github.com/rust-lang/rustfmt/blob/master/src/config/license.rs#L70) proved useful.

**Comment by calebcartwright** [comment]
Thanks for sharing @mrbianchi! line endings are a bit of a pain for rustfmt to work with as the rustc parser normalizes everything to unix style endings in the source map that rustfmt works with, and we then go back in towards the latter formatting phases (after the license template check is performed) to perform line ending checks and, if necessary, the converted value. 

It could be possible with a refactor to shift that check after the line ending conversions, if you or anyone else is interested in investigating. In the meantime, I imagine it'd be helpful if the documentation for the `license_template_path` configuration option explicitly called out the need to use unix style line endings in the template file? That can be updated [here](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#license_template_path) for anyone interested.

https://github.com/rust-lang/rustfmt/blob/30bda450be1c8ded7b0eda63838b89cdbe3594db/src/formatting.rs#L206-L227
https://github.com/rust-lang/rustfmt/blob/30bda450be1c8ded7b0eda63838b89cdbe3594db/src/formatting.rs#L308-L328

**Comment by calebcartwright** [comment]
@DMats - Thanks for sharing! Do you think the [wording of the description/help text for the config option](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#license_template_path) could be phrased differently to better express this?

**Comment by cbarrick** [comment]
The template path appears to be resolved relative to the current directory when running `cargo fmt`.

This causes an error when running the command from a sub-directory in a workspace:

```
Warning for license template file "header.rs": No such file or directory (os error 2)
```

I was not expecting `cargo fmt` to depend on me being in the workspace root directory.

My expectation:

- When specified in `rustfmt.toml`, resolve the template path relative to that file.
- When specified with `--config`, resolve the template path relative to the current directory.

**Comment by gilescope** [comment]
Hmm, got a few different licenses in one workspace.
I basically wanted to ensure that each file has got a license set:
`{.*}SPDX-License-Identifier: {.*}`

Seems like the regex's only span one line. Ideally I don't mind which line they put this in their header as long as they've got one. (Alternatively if `license_template_path` could take a list of templates and passed if it matched any of them that would work.)

If we wanted to go fancy then

**Comment by gilescope** [comment]
@cbarrick agree with you about the relative dir. Here's an attempt at fixing that: https://github.com/rust-lang/rust/pull/87627

**Comment by calebcartwright** [comment]
Going to close this because stabilization doesn't make sense given our intent to deprecate and remove the option, refs #5103
