### ISSUE TITLE
[unstable option] disable_all_formatting

### ISSUE THREAD

**Issue by scampi** [rust-lang/rustfmt#3388]
Tracking issue for disable_all_formatting

**Comment by VeaaC** [comment]
Very useful option for testing code generators: You want to store test cases in the repository (generated rust files), but prevent rustfmt to format them.

**Comment by scampi** [comment]
Ii doesn't sound like `disable_all_formatting` is the right option for what you described: what about the [ignore](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#ignore) option ?

**Comment by scampi** [comment]
Ii doesn't sound like `disable_all_formatting` is the right option for what you described: what about the [ignore](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#ignore) option ?

**Comment by VeaaC** [comment]
Yes, you are correct, ```ignore``` looks like it will solve this case nicely.

Wouldn't ignoring ```.``` be the same as ```disable_all_formatting```?

**Comment by scampi** [comment]
gave it a try and it looks like it
