### ISSUE TITLE
[unstable option] hide_parse_errors

### ISSUE THREAD

**Issue by scampi** [rust-lang/rustfmt#3390]
Tracking issue for hide_parse_errors

**Comment by sinistersnare** [comment]
I think this should be named `show_parse_errors` with a default of `true`. When configurations are in the negative, I always end up having to think through an annoying double negation. I try to name all configuration options in the affirmative for that reason.

**Comment by ytmimi** [comment]
Closed via https://github.com/rust-lang/rustfmt/pull/5961. This option was renamed `show_parse_errors`. The new tracking issue can be found at https://github.com/rust-lang/rustfmt/issues/5977
