### ISSUE TITLE
[unstable option] report_fixme

### ISSUE THREAD

**Issue by scampi** [rust-lang/rustfmt#3394]
Tracking issue for report_fixme

**Comment by calebcartwright** [comment]
Thanks @karyon. Couple minor additions/tweaks, I don't want to convey that 2.0 will _never_ happen, it's just increasingly unlikely that it will happen outside an entire Rust ecosystem 2.0, and certainly going to happen any time _soon_, refs #5018

I think there's still a strong argument for us to drop this from rustfmt (it's quite orthogonal to formatting of code) and we may still do so

**Comment by calebcartwright** [comment]
Going to close this because stabilization doesn't make sense given our intent to deprecate and remove the option, refs #5102
