### ISSUE TITLE
error: component 'rustfmt' for target 'x86_64-unknown-linux-gnu' is unavailable for download

### ISSUE THREAD

**Issue by softprops** [rust-lang/rustfmt#3404]
I'm seeing my nightly rust builds fail in travis fail because of the following error

```
error: component 'rustfmt' for target 'x86_64-unknown-linux-gnu' is unavailable for download
```

my builds attempt to install it using

```
rustup component add rustfmt
```

Thoughts?

**Comment by kentfredric** [comment]
https://rust-lang-nursery.github.io/rust-toolstate/
https://mexus.github.io/rustup-components-history/
https://github.com/rust-lang/rust/issues/56667

These links helped me understand :/, recurring issue.

**Comment by kentfredric** [comment]
After a bit of digging, if you want a version of nightly with both working rustfmt and clippy, do:
```bash
rustup toolchain add nightly-2019-02-08
rustup component add --toolchain nightly-2019-02-08 rustfmt clippy
```

**Comment by softprops** [comment]
awesome it would be great to make those pages a bit more discoverable for rustfmt uses. perhaps a second in this projects README.md file

**Comment by softprops** [comment]
Is there anyone looking at this or an tracking issue I can link to? I'm going to do this temporary work around but would like to track an issue to I can reset when its fixed

**Comment by topecongiro** [comment]
This will be fixed once https://github.com/rust-lang/rust/pull/58337 gets merged and the new nightly with the commit included gets published.
