### ISSUE TITLE
wrap_comments shouldn't imply format_doc_comments

### ISSUE THREAD

**Issue by RReverser** [rust-lang/rustfmt#3417]
This is similar to #3209, but a bit worse IMO: currently setting either `normalize_doc_attributes` or `wrap_comments` to `true` implies `format_doc_comments` as well and reformats docs, even if `format_doc_comments = false` is explicitly set in the config.

**Comment by xiongmao86** [comment]
What does `format_doc_comments` mean exactly? Isn't wrapping a doc comment some sort of formatting the doc comment? 

And is setting `wrap_comments` to `false` but `format_doc_comments` to `true` meaning do formatting other than wrapping to the doc comments?

**Comment by RReverser** [comment]
The description is somewhat vague, but from the included example (https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#format_doc_comments) and own experience, I've assumed it means just formatting code snippets within doc comments, and should work independently from wrapping comment text.

**Comment by xiongmao86** [comment]
Reproduce with two snippets:

`wrap_comments` implies `format_doc_comments`:
```rust
// rustfmt-wrap_comments: true

/// Foo
///
/// # Example
/// ```
/// # #![cfg_attr(not(dox), feature(cfg_target_feature, target_feature, stdsimd))]
/// # #![cfg_attr(not(dox), no_std)]
/// fn foo() {  }
/// ```
///
fn foo() {}

/// A long commment for wrapping
/// This is a long long long long long long long long long long long long long long long long long long long long sentence.
fn bar() {}
```
`normalize_doc_attributes` implies `format_doc_comments`:
```rust
// rustfmt-normalize_doc_attributes: true

/// Foo
///
/// # Example
/// ```
/// # #![cfg_attr(not(dox), feature(cfg_target_feature, target_feature, stdsimd))]
/// # #![cfg_attr(not(dox), no_std)]
/// fn foo() {  }
/// ```
///
fn foo() {}

#[doc = "Bar documents"]
fn bar() {}
```

**Comment by scampi** [comment]
@RReverser You are correct and that is what it should do. Maybe we can review the description of this option too.

**Comment by xiongmao86** [comment]
@RReverser, @scampi: Perhaps change `format_doc_comment` to `format_code_in_doc_comment`?

**Comment by RReverser** [comment]
@xiongmao86 That sounds reasonable to me.
