### ISSUE TITLE
readme `--check` example appears broken

### ISSUE THREAD

**Issue by valarauca** [rust-lang/rustfmt#3428]
Running the exact command within the provided examples

```bash
$ rustup update
$ rustup add component rustfmt
$ cargo fmt --all -- --check
```

Results in an error message where `cargo fmt` will display its possible flags instead of an error concerning formatting.

Is there a documented work around?

**Comment by topecongiro** [comment]
Hmm, strange...would you tell us the output of `rustfmt --version`? `rustup` somehow may have failed to overwrite the old `rustfmt` and `cargo-fmt`. Or could you try removing `rustfmt` and `cargo-fmt` manually, then re-run `rustup update` please?
