### ISSUE TITLE
Alternative to `rustfmt::skip`

### ISSUE THREAD

**Issue by flagello** [rust-lang/rustfmt#3432]
Would there be any interest for a shorter alternative to `rustfmt::skip` (such as, e.g., `fmtd`)? While I see the scoping issue, I find it verbose.

**Comment by topecongiro** [comment]
Sorry, but this is unlikely to happen, as adding our own attributes to global namespace could cause breakage. FWIW https://github.com/rust-lang/rfcs/blob/master/text/2103-tool-attributes.md refers to some context.

**Comment by flagello** [comment]
No worries! Thanks for the context!
