### ISSUE TITLE
Semantics of `use` item is not preserved

### ISSUE THREAD

**Issue by takano-akio** [rust-lang/rustfmt#3436]
The following is a valid module in Rust 2018, and `rustc` 1.33.0 happily accepts it:

```
use ::std::marker::PhantomData;

mod std {}

struct S(PhantomData<i32>);
```

If I run `rustfmt` on this module, however, it turns the import statement into `use std::marker::PhantomData;`, dropping the initial `::`. This creates ambiguity and causes a compile error.

In general this problem can arise whenever there is a local module whose name conflicts with a crate name.

**Comment by topecongiro** [comment]
You need to tell rustfmt that you are using edition 2018. There are several ways to do so:

1. Add `edition = "2018"` to rustfmt.toml
2. Pass `--edition 2018` to `rustfmt` directly
3. Use `cargo fmt` within a package whose Cargo.toml contains `edition = "2018"`
