### ISSUE TITLE
Option for splitting the imports

### ISSUE THREAD

**Issue by ilya-epifanov** [rust-lang/rustfmt#3437]
a.k.a. Java-style or VCS-friendly style.

use freetype::freetype::FT_Face;
use freetype::freetype::FT_Get_Char_Index;
use freetype::freetype::FT_GlyphSlot;
use freetype::freetype::FT_Init_FreeType;

**Comment by 9999years** [comment]
This is the `imports_granularity` option: https://github.com/rust-lang/rustfmt/issues/4991

**Comment by calebcartwright** [comment]
Indeed, thanks for pointing that out @9999years! Closing accordingly
