### ISSUE TITLE
Rustfmt doesn't recognize use crate:: statements

### ISSUE THREAD

**Issue by entropitor** [rust-lang/rustfmt#3438]
rustfmt is failing with the following error on all `use crate::` statements

```
error: expected identifier, found keyword `crate`
  --> /home/user/path/to/file.rs:17:13
   |
17 |         use crate::schema::users::dsl::users;
   |             ^^^^^

```

**Comment by topecongiro** [comment]
You need to tell `rustfmt` which edition you want to use. See https://github.com/rust-lang/rustfmt#rusts-editions and `rustfmt --help`.

**Comment by entropitor** [comment]
My cargo.toml has package.edition=2018 and I've added a rustfmt.toml but neither of both seem to be picked up, even though rustfmt is saying "Using rustfmt config file"

**Comment by entropitor** [comment]
I found the error, somehow there was an old version of rustfmt installed which was used to format (which didn't recognize the edition config variable)

**Comment by oknozor** [comment]
I have the same issue after a fresh install of rustfmt : 

Tool chain : 
```
rustup toolchain list 
stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)
```

```
rustup update         
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'

   stable-x86_64-unknown-linux-gnu unchanged - rustc 1.45.0 (5c1f21c3b 2020-07-13)
  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.47.0-nightly (d6953df14 2020-07-25)
``` 

Edition is set to `edition = "2018"` in my cargo.toml

Trying to run `cargo fmt` or `cargo +nightly fmt` produce the following warning:
```
This version of rustfmt is deprecated. Use rustfmt-nightly. Use --force to run deprecated rustfmt.
...
```
With `--force` flag rustfmt is throwing a bunch of errors like this one (even with the +nightly option) :
```
error: expected identifier, found keyword `crate`
 --> /home/okno/_WORKSHOP/Rust/bombadil/src/color/alacritty_colors.rs:1:5
  |
1 | use crate::color::{ToConfig, Theme};
  |     ^^^^
```  

So far I have tryied the following : 
- Using rust stable
- Removing and reinstalling rustfmt

I am missing something here ?

**Comment by calebcartwright** [comment]
@oknozor 

> Edition is set to edition = "2018" in my cargo.toml

If you are running `rustfmt` instead of `cargo fmt`, then you have specify which the edition to use. `rustfmt`, like `rustc`, does not read Cargo.toml files. https://github.com/rust-lang/rustfmt#rusts-editions

**Comment by oknozor** [comment]
Thank you @calebcartwright, it's know fixed but I have to use `cargo-fmt` instead of `cargo fmt`this was really confusing. Still don't get what is the difference.

**Comment by calebcartwright** [comment]
You've still got an issue with your system configuration. I'd advise checking to see if you have `rustfmt` and `cargo-fmt` in cargo's bin directory (~/.cargo/bin) and if so remove them. 

You should then be able to use rustup to manage rustfmt, `rustup component add rustfmt` and then `rustup update`. If you're still having issues it may be better to open a new issue or drop a message in Discord
