### ISSUE TITLE
Ident of macro+ident gets duplicated

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rustfmt#3439]
I have an attribute macro whose input is a macro with ident (like how macro_rules accepts an ident).

```rust
use repro::my_macro;

#[my_macro]
xyz! abc {
    ...
}
```

As of <kbd>rustfmt 1.0.3-nightly (d6829d6 2019-02-14)</kbd>, rustfmt applies the following diff which turns the above into syntactically invalid code:

```diff
- xyz! abc {
+ xyz! abc abc {
```

**Comment by topecongiro** [comment]
Closed by #3440.
