### ISSUE TITLE
.config/rustfmt/rustfmt.toml is skipped,

### ISSUE THREAD

**Issue by SRGOM** [rust-lang/rustfmt#3449]
Tested that  ~/.rustfmt.toml is read just fine

**Comment by devinalvaro** [comment]
This seems to have be fixed in `1.1.0-nightly`.

**Comment by scampi** [comment]
@SRGOM Can you try with the new version ? If it works for you as well we can close this issue.

**Comment by SRGOM** [comment]
If you guys say so, I'll close it. To be honest, I couldn't get rustfmt to run at all because of the following error but since you both seem to agree that it works then maybe it does.

```
Warning for license template file "": No such file or directory (os error 2)
Error: rustfmt version (1.0.3) doesn't match the required version (1.0.1)
Error writing files: version mismatch
```

**Comment by scampi** [comment]
@SRGOM Maybe try to remove then install rustfmt again with rustup. If you still see that error message, please open a separate issue! thanks
