### ISSUE TITLE
option to add leading and trailing whitespaces arround a function's arguments 

### ISSUE THREAD

**Issue by SRGOM** [rust-lang/rustfmt#3450]
I prefer 
`my_obj.my_fun( space_before_me_and_space_after_me ) ` over `my_obj.my_fun(use_space_key_sparingly_for_long_life)` . I searched the entire 1800 line .md for `space` and `parentheses` but couldn't find a relevant option.

EDIT: Actually added space after- I'm dumb

**Comment by topecongiro** [comment]
AFAIK the option existed in the past but got removed since it seemed to be unpopular. I know that other formatters offer an option similar to this, but I still believe this is not worth the implementation and design cost. Sorry.

**Comment by ifreund** [comment]
Too bad, it can make code much more readable in my opinion.

**Comment by SRGOM** [comment]
@ifreund Since you seem to agree, I wonder what you do? I don't use rustfmt at all.
