### ISSUE TITLE
Windows command line experience is painful

### ISSUE THREAD

**Issue by Darthfett** [rust-lang/rustfmt#3451]
I am new to rust, and I use VS Code on Windows, but I prefer running commands directly, rather than using the built-in right-click menu (so I know what it's doing, since I'm still new to rust).

Today I spent about a half hour trying to get rustfmt to run from the command line, and it appears to be completely impossible for me.  I was able to use the VS-Code right-click menu without issues, but here is a summary of the commands I tried without success:

    Microsoft Windows [Version 10.0.17134.590]
    (c) 2018 Microsoft Corporation. All rights reserved.

    $>cargo fmt
    This version of rustfmt is deprecated. Use rustfmt-nightly. Use --force to run deprecated rustfmt.

    usage: rustfmt [options] <file>...

    <snip>

    $>cargo fmt src\main.rs
    This version of rustfmt is deprecated. Use rustfmt-nightly. Use --force to run deprecated rustfmt.

    usage: rustfmt [options] <file>...

    <snip>

    $>rustfmt-nightly src\main.rs
    'rustfmt-nightly' is not recognized as an internal or external command,
    operable program or batch file.

    $>cargo fmt --force src\main.rs
    Unrecognized option: 'force'
    usage: cargo fmt [options]

    <snip>

    This utility formats all bin and lib files of mt ----force src\main.rs
    the current crate using rustfmt. Arguments after `--` are passed to rustfmt.

    $>cargo fmt ----force src\main.rs
    Unrecognized option: '--force'
    usage: cargo fmt [options]

    <snip>

    This utility formats all bin and lib files of the current crate using rustfmt. Arguments after `--` are passed to rustfmt.

    $>cargo +nightly fmt
    This version of rustfmt is deprecated. Use rustfmt-nightly. Use --force to run deprecated rustfmt.

    usage: rustfmt [options] <file>...

    <snip>

    $>cargo +nightly fmt src\main.rs
    This version of rustfmt is deprecated. Use rustfmt-nightly. Use --force to run deprecated rustfmt.

    usage: rustfmt [options] <file>...

    <snip>

    $>cargo +nightly fmt --force
    Unrecognized option: 'force'
    usage: cargo fmt [options]

    <snip>

    This utility formats all bin and lib files of the current crate using rustfmt. Arguments after `--` are passed to rustfmt.

    $>cargo +nightly fmt -- --force
    thread 'main' panicked at 'failed to emit error: operation not supported by the terminal', <snip>\.cargo\registry\src\github.com-1ecc6299db9ec823\syntex_errors-0.59.1\src\emitter.rs:1152:23
    note: Run with `RUST_BACKTRACE=1` for a backtrace.

    $>rustfmt
    This version of rustfmt is deprecated. Use rustfmt-nightly. Use --force to run deprecated rustfmt.

    usage: rustfmt [options] <file>...

    <snip>

    $>rustfmt --force src\main.rs
    thread 'main' panicked at 'failed to emit error: operation not supported by the terminal', <snip>\.cargo\registry\src\github.com-1ecc6299db9ec823\syntex_errors-0.59.1\src\emitter.rs:1152:23
    note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by scampi** [comment]
Are you on the `nightly` channel ? Can you try to update the `rustfmt` tool using rustup, e.g., `rustup update`.

**Comment by topecongiro** [comment]
You may have installed the deprecated version of `rustfmt`. Please uninstall them, then reinstall via `rustup`:

```
cargo uninstall rustfmt
rustup component add rustfmt
```

**Comment by Darthfett** [comment]
Thanks for the help!  I don't know how rustfmt was installed through cargo (maybe a long time ago?). At the time of writing this ticket, I didn't think I had manually installed at all, but perhaps I did.

Removing them from .cargo\bin and .cargo\.crates.toml (likely the same thing as `cargo uninstall rustfmt`) did the trick, which `rustup update` gave me a hint about.
