### ISSUE TITLE
fluent newlines being stripped

### ISSUE THREAD

**Issue by vektah** [rust-lang/rustfmt#3452]
code like this:
```rust
    let pro_que = ProQue::builder()
        .src(src)
        .dims(1 << 20)
        .build()?;
```

gets turned into this:
```rust
    let pro_que = ProQue::builder().src(src).dims(1 << 20).build()?;
```

using `rustfmt 1.0.1-stable (be13559 2018-12-10)`

**Comment by topecongiro** [comment]
This is by design: unlike `gofmt`, `rustfmt` does not rely on user's input when formatting method chains. That is, if two method chains are identical at AST level, then those two will get formatted in the same way.
