### ISSUE TITLE
Introduce github page for rustfmt.toml like rust-clippy

### ISSUE THREAD

**Issue by rchaser53** [rust-lang/rustfmt#3455]
Configurations.md is a bit big. It cannot feel free to read.
Can I make the github page for Configurations.md like [this](https://rust-lang.github.io/rust-clippy/master/index.html)?

**Comment by scampi** [comment]
That'd be cool I think !

**Comment by rchaser53** [comment]
WIP: https://rchaser53.github.io/rustfmt/

**Comment by scampi** [comment]
@rchaser53 that's a nice vue app you put together !
What are the things you want to further work on ?
Maybe extracting the description paragraph of elements at depth 2 would be a nice addition in order to improve the search https://github.com/rchaser53/rustfmt/blob/master/index.html#L118

**Comment by rchaser53** [comment]
Thank you. I added the feature to use the description paragraph for search condition.
If you don't mind, please make ```gh-pages``` branch. I want to send the PR to create GitHub page in rust-lang/rustfmt.

**Comment by scampi** [comment]
@topecongiro I don't have permission to do that, can you create that page please ?

**Comment by topecongiro** [comment]
We can also publish GitHub Pages by putting contents to `/docs` folder (cc https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages). Personally I prefer this style as it's easier to keep information up to date than creating a different branch. @rchaser53 @scampi What do you think?

**Comment by rchaser53** [comment]
I agree with your opinion. It's more maintainable than creating ```gh-pages``` branch.

**Comment by rchaser53** [comment]
I can change the PR target branch anytime, so I send the PR now.

**Comment by scampi** [comment]
@topecongiro I agree ! forgot about that.
