### ISSUE TITLE
format_strings option being ignored for strings with escaped newlines

### ISSUE THREAD

**Issue by Darthfett** [rust-lang/rustfmt#3456]
In my rustfmt.toml file, I have specified:

    format_strings = false

However, when I run rustfmt, I see my escaped strings getting formatted.  The following code:

    println!(
        "DirEntry {{ \
            binary_name: {:<64}, \
            context_id: {:>2}, \
            file_size: {:>6}, \
            offset: 0x{:>08X}, \
            actual_crc: 0x{:>08X} \
        }}",
        dir_entry.binary_name,
        dir_entry.context_id,
        dir_entry.file_size,
        dir_entry.offset,
        dir_entry.actual_crc
    );

Gets formatted to:

    println!(
        "DirEntry {{ \
            binary_name: {:<64}, \
            context_id: {:>2}, \
            file_size: {:>6}, \
            offset: 0x{:>08X}, \
            actual_crc: 0x{:>08X} \
            }}",
        dir_entry.binary_name, dir_entry.context_id, dir_entry.file_size, dir_entry.offset, dir_entry.actual_crc
    );

**Comment by Maxgy** [comment]
I replicated this situation, but the original formatting remains the same with or without the rustfmt.toml file.
