### ISSUE TITLE
Strange behaviour when tab_spaces = 8

### ISSUE THREAD

**Issue by Screwtapello** [rust-lang/rustfmt#3492]
### Steps to reproduce:

 1. I'm using rustfmt 1.0.1-stable, the version that comes with rust 1.33.0
 1. Create `test.rs`:

    ```rust
    fn main() {
        for each in &[1, 2, 3] {
            println!(
                "Here's a lovely number you might like if you have a taste for small integers: {}",
                each,
            );
        }
    }
    ```

 1. Create `rustfmt.toml`:

    ```toml
    hard_tabs = false
    tab_spaces = 8
    ```

 1. Format `test.rs` with `rustfmt`:

        $ rustfmt --emit stdout test.rs

### Expected results

Output identical to the original input file

### Actual results

```rust
fn main() {
        for each in &[1, 2, 3] {
                println!(
            "Here's a lovely number you might like if you have a taste for small integers: {}",                                                                          
            each,
        );
        }
}
```

  * There are 8-space indents, instead of the standard 4. `rustfmt.toml` says that tabs are 8 spaces, but it also says not to use tabs, so it shouldn't matter how many spaces they are.
  * Indents are inconsistent. There's two twelve-space indented lines, so it seems to be mixing 8-space and 4-space idents on the same line.

### Notes

[Kakoune](https://kakoune.org/), the editor I'm using, has separate options `tabstop` (the size of tabs, if they are present) and `indentwidth` (the amount to indent by, when indenting or dedenting lines). It's not unusual in this regard; for example, Vim has `tabstop` and `shiftwidth`.

[kak-lsp](https://github.com/ul/kak-lsp), the Language Server Protocol for Kakoune, supports the `textDocument/formatting` Language Server command, and passes Kakoune's `tabstop` as the LSP's [options.tabSize](https://microsoft.github.io/language-server-protocol/specification#textDocument_formatting) parameter.

RLS [passes `tabSize` to rustfmt as `tab_spaces`](https://github.com/rust-lang/rls/blob/609829a2d4477a20438bed00e3846098be898fdd/rls/src/actions/requests.rs#L691).

Each step of the process seems quite reasonable in isolation, but the combined system seems to me like it's doing the wrong thing.

**Comment by topecongiro** [comment]
This is because the line that starts with `"Here's ..."` will exceed `max_width` (= 100) with 8-space indents.

**Comment by allmywatts** [comment]
Setting `version="Two"` using nightly results in the following output
```
$ target/debug/rustfmt --config version=Two --emit stdout test.rs 

fn main() {
        for each in &[1, 2, 3] {
                println!(
                        "Here's a lovely number you might like if you have a taste for small integers: {}",
                        each,
                );
        }
}
```
As far as I can tell this is the expected output where we have 8 spaces per indent.

**Comment by topecongiro** [comment]
@allmywatts Thank you for your confirmation! I will close this issues as fixed but please feel free to reopen if there is any issue.
