### ISSUE TITLE
Running rustfmt on a file with a missing module fails even with `--skip-children`

### ISSUE THREAD

**Issue by flowbish** [rust-lang/rustfmt#3493]
With a lib.rs containing the following:
```rust
mod does_not_exist;
```
Running the following command will cause rustfmt to exist with a non-zero return code.

```shell
$ rustfmt --skip-children --unstable-features error.rs
Error writing files: io error: Failed to find module dne in "/home/psmith/tmp" None
$ echo $?
1
```
Creating a `does_not_exist.rs` causes this error to go away. Clearly `--skip-children` is working, as even if `does_not_exist.rs` does not contain valid Rust rustfmt exits successfully.

```shell
$ echo 'sdafjslk' > does_not_exist.rs
$ rustfmt --skip-children --unstable-features error.rs
$ echo $?
0
```

I would expect that using `--skip-children` on a Rust file with a should not fail even if it contains a module that does not exist.

**Comment by varleg** [comment]
I can look in to this. Any idea where to start?

**Comment by flowbish** [comment]
From what I can tell, [`rustfmt::modules::find_external_module`](https://github.com/rust-lang/rustfmt/blob/8e068510a4a7e0bf7ae1c4e641f8a790842f6f17/src/modules.rs#L108) is where the error is originating from.

**Comment by varleg** [comment]
Yes I backtraced it to there. Thanks :+1:

**Comment by topecongiro** [comment]
@varleg Thank you! I think that this could be fixed by not calling `visit_mod` when `config.skip_children` is set to `true`.

https://github.com/rust-lang/rustfmt/blob/8ec0750bb88dfe84ca2d54ddc29b13f5900641d6/src/modules.rs#L58-L61

**Comment by varleg** [comment]
@topecongiro: How to I check the boolean for set configurations in the format object? I am unable to identify which module to import to check if skip children is set? If I do

`let config = Config::default(); `
`println!("{}", config.skip_children());`

it always return false
