### ISSUE TITLE
Poor formatting of expression with attribute inside of slice

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rustfmt#3498]
```rust
static REPRO: &[usize] = &[
    #[cfg(feature = "zero")]
    0,
];
```

As of <kbd>rustfmt 1.2.0-nightly (09940a7 2019-03-27)</kbd>, rustfmt formats the static as:

```rust
static REPRO: &[usize] = &[#[cfg(feature = "zero")]
0];
```

I believe that it should be formatted as originally written. It looks as though rustfmt believes it is emitting `&[0]`, but the attribute and newline make that form not readable.

**Comment by scampi** [comment]
@dtolnay Thanks for the report! Out of curiosity, how woul you use the `REPRO` variable ?

**Comment by dtolnay** [comment]
@scampi this is minimized from code in Chromium OS.

https://chromium.googlesource.com/chromiumos/platform/crosvm/+/d59cb24741de02b81369bb11a78f9d8968a734b5/protos/build.rs#30
