### ISSUE TITLE
Rustfmt changes meaning of 2018 import starting with colons

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rustfmt#3501]
Repro against current master branch (8ec0750bb88dfe84ca2d54ddc29b13f5900641d6):

```bash
echo 'use ::serde::Serialize; mod serde {}' | cargo run --bin rustfmt
```

Output:

```console
use serde::Serialize;
mod serde {}
```

The original code imports `::serde::Serialize` which refers to the external crate `serde`, not the local module. The formatted code imports `serde::Serialize` which refers to the local module and does not exist.

Interestingly, `cargo fmt` against the same code does not break the code, presumably because `cargo fmt` somehow understands that the edition of this code is 2018 and so the leading `::` is meaningful. In the absence of knowing the edition for sure, would it be possible for `rustfmt` to treat this case more conservatively and keep the leading `::`? We can continue to remove the colons if the edition is known to be 2015.

**Comment by scampi** [comment]
If you put `edition = "2018"` in the config file that should be fine

**Comment by scampi** [comment]
`cargo fmt` picks up the edition from `Cargo.toml`

**Comment by topecongiro** [comment]
If you are running `rustfmt` directly you need to pass `--edition` flag to `rustfmt`: `cargo run --bin rustfmt -- --edition 2018`. As the default edition of rustc and cargo are both 2018, I think it's reasonable to change the default edition of `rustfmt` to 2018 in 2.0.

**Comment by dtolnay** [comment]
Thanks, I think this is user error and I should be passing `--edition 2018`.

I don't know if this is helpful but I filed #3517 to track bumping the default edition that is assumed when no `--edition` is passed.

**Comment by topecongiro** [comment]
@dtolnay That is indeed helpful, thank you!
