### ISSUE TITLE
`cargo fmt --version` emits nothing

### ISSUE THREAD

**Issue by rchaser53** [rust-lang/rustfmt#3505]
It seems that the reason why rustfmt version is ```()``` in [Rust Playground](https://play.rust-lang.org/).

**Comment by rchaser53** [comment]
![RustfmtVersion()](https://user-images.githubusercontent.com/9676954/56087335-292d6880-5ea4-11e9-8e0d-5958e4cb2dae.png)

**Comment by topecongiro** [comment]
Closed via #3506.
