### ISSUE TITLE
Rustfmt deletes comment in parentheses of argumentless Fn

### ISSUE THREAD

**Issue by Emerentius** [rust-lang/rustfmt#3508]
These are unusal cases, so I'll just show examples. I've had this happen in some WIP code where I temporarily commented out the argument types.

```rust
fn foo(
    bar: impl Fn(
        // this comment is deleted
    )
) {}
```
The same happens in where-clauses
```rust
fn foo<F>(bar: F)
where
    F: Fn(
        // this comment is deleted
    )
{}
```

It also occurs with generic traits
```rust
fn foo(
    bar: impl PartialEq<
        // this comment is deleted
    >
) {}
```

Block comments are deleted as well. As long as there is anything else in the parentheses / brackets, the comment is preserved.

**Comment by topecongiro** [comment]
Closed via #3518.
