### ISSUE TITLE
reorder_imports=false should still format the imports

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rustfmt#3515]
Input file *repro.rs*:

```rust
use std :: fmt :: { self , Display } ;
use std :: collections :: HashMap ;

fn main() {}
```

Rustfmt invocation:

```bash
cargo run --bin rustfmt -- \
    path/to/repro.rs \
    --config-path <(echo reorder_imports=false) \
    --emit=stdout
```

Output as of current master branch, 34bf13718a6af228260312139f646c7d79e6aa71:

```rust
use std :: fmt :: { self , Display } ;
use std :: collections :: HashMap ;

fn main() {}
```

Expected output, imports formatted but not reordered:

```rust
use std::fmt::{self, Display};
use std::collections::HashMap;

fn main() {}
```

I care about this for https://github.com/dtolnay/cargo-expand/issues/56 in which I receive imports from a proc macro in TokenStream-style spaced out formatting and want to format them without reordering anything.

**Comment by dtolnay** [comment]
Note that reorder_modules=false seems to handle this correctly already. It turns:

```rust
mod b ;
mod a ;
```

into:

```rust
mod b;
mod a;
```

which is how I would expect.

**Comment by scampi** [comment]
@dtolnay the rustfmt output was the original one in your description.

```rust
use std::collections::HashMap;
use std::fmt::{self, Display};

fn main() {}
```

**Comment by dtolnay** [comment]
@scampi you may not have set reorder_imports=false, since what you show has imports reordered.

**Comment by scampi** [comment]
@dtolnay indeed... sorry ;oD
