### ISSUE TITLE
rustfmt chokes on new-style submodule naming

### ISSUE THREAD

**Issue by dunmatt** [rust-lang/rustfmt#3529]
I have a submodule called output, it is comprised of `output.rs`, `output/macros.rs` and various other files in `output/`.  Everything tests just fine, so I know I'm using the language right, but when I try to `cargo fmt -- src/output.rs` it complains, saying  "error[E0583]: file not found for module `macros`", and it highlights the line `mod macros;` as the culprit.

I tried uninstalling and reinstalling rustfmt a few times, including one where I completely reinstalled the stable toolchain.  To be honest the update procedure for cargo subcommands is rather confusing, so I might have screwed something up somewhere... but AFAICT I'm all up to date.

**Comment by topecongiro** [comment]
What is the edition of your project and the submodule?

**Comment by dunmatt** [comment]
2018, I'm still writing it

**Comment by topecongiro** [comment]
Ah, if you are using stable rustfmt, then it could be slightly outdated. Since this is already fixed in nightly rustfmt, I will close this issue. Sorry for the inconvenience.
