### ISSUE TITLE
no formatting when using self outside of impl

### ISSUE THREAD

**Issue by hellow554** [rust-lang/rustfmt#3531]
```rust
fn foo(self) {}
```

This code will be rejected to format, because 

```none
error: unexpected `self` argument in function
 --> src/lib.rs:1:8
  |
1 | fn foo(self) {}
  |        ^^^^ `self` is only valid as the first argument of an associated function
```

which is of course correct, but it shouldn't affect the formatting of the code, or am I missing something?

**Comment by topecongiro** [comment]
As rustfmt works on the AST, it is only applicable to code that is syntactically correct. It does not require the code to be semantically correct, however.

With respect to your code example, using `self` outside of `impl` block is a syntax error in rust, and hence is rejected by rustfmt.
