### ISSUE TITLE
Comma in comment causes no formatting to happen

### ISSUE THREAD

**Issue by jgouly** [rust-lang/rustfmt#3532]
The following code passes with `rustfmt --check`:

    fn foo(a: T) {
        match a {
    1 => {}
        0 => {}
        // _ => panic!("doesn't format!"),
        }
    }

If you remove the comma after`panic!("doesn't format!"),`, `rustfmt --check` complains.

    $ rustfmt --check src/fmt.rs
    Diff in fmt.rs at line 1:
     fn foo(a: T) {
       match a {
    -1 => {}
    -  0 => {}
    -  // _ => panic!("doesn't format!")
    +    1 => {}
    +    0 => {} // _ => panic!("doesn't format!")
       }
     }

**Comment by scampi** [comment]
@jgouly is that with an option that pertains to comments ?
