### ISSUE TITLE
Executing a method on a match result makes rustfmt give up on formatting

### ISSUE THREAD

**Issue by marmistrz** [rust-lang/rustfmt#3534]
For example:
```
fn main() {
    let b = true;
    let f = match b {
                        true => "abc",
                false => "def"
    }.as_bytes();
}
```

**Comment by scampi** [comment]
What version of rustfmt do you have ? This is formatted with the latest and with the default options.

**Comment by marmistrz** [comment]
1.0.3 from repo and 1.1.0 from rustup, but I can't reproduce it anymore... :confused: 
I'll reopen if I encounter this again.
