### ISSUE TITLE
Error when trying dump the default config with `--print-config default`

### ISSUE THREAD

**Issue by updogliu** [rust-lang/rustfmt#3536]
Version: rustfmt 1.2.2-nightly (5274b49 2019-04-24)

`rustfmt --print-config default .`
gives
`Could not output config: can only flatten structs and maps (got a sequence)`

**Comment by sdht0** [comment]
Should this not have been backported to (then beta and now) stable?
I get the same error message on the newly released 1.36.0.

**Comment by Dawen18** [comment]
Same a @sdht0 
I have this message when a try to dump default

Version `rustfmt 1.2.2-stable (5274b49 2019-04-24)`
