### ISSUE TITLE
Windows paths in ignore setting no longer work

### ISSUE THREAD

**Issue by lzybkr** [rust-lang/rustfmt#3537]
Using: rustfmt 1.2.2-nightly (5274b49c 2019-04-24)

The following no longer works - the files unexpectedly get formatted. Changing to Unix style paths works, but I believe does not work with `stable`, or at least did not when we originally added this entry in our `rustfmt.toml`.

```toml
ignore = [
    "cratename\\src\\um",
]
```

**Comment by topecongiro** [comment]
We probably need to replace "\\" with "/".

**Comment by calebcartwright** [comment]
@topecongiro - I'd be happy to take a look at this one
