### ISSUE TITLE
Formatting from stdin and respecting ignore from rustfmt.toml

### ISSUE THREAD

**Issue by elmarco** [rust-lang/rustfmt#3543]
It would be useful if rustftmt could respect rustfmt.toml `ignore`, even when formatting from stdin. 

(my case is similar to #2668, I am using emacs rust-mode, which passes buffers as stdin)

Similarly to #2663, we could consider the current path as filename by default, or allow to specify the filename via environment variable. For ex `RUSTFMT_STDIN_FILENAME=..` ?

**Comment by scampi** [comment]
I would go more for setting the filename from the current path.

**Comment by elmarco** [comment]
@scampi so my #3544 RFC is ok?

**Comment by topecongiro** [comment]
As I stated in the PR's comment [0], the feature seems a bit off. As such, I am closing this as won't fix.

[0] https://github.com/rust-lang/rustfmt/pull/3544#issuecomment-544112913
