### ISSUE TITLE
set a configuration option from the command line

### ISSUE THREAD

**Issue by scampi** [rust-lang/rustfmt#3549]
It should be possible to set an option from the CLI, e.g.,

```shell
$ rustfmt --format_doc_comments=true
```

**Comment by shepmaster** [comment]
I was also just looking for this feature!

**Comment by scampi** [comment]
From @shepmaster on discord: for Linux users, you can do the following "hack":

```sh
rustfmt file.rs --config-path =(echo normalize_doc_attributes = true)
```

**Comment by shepmaster** [comment]
I'm unfamiliar with the syntax you show; I used Bash's [process substitution](https://www.gnu.org/software/bash/manual/html_node/Process-Substitution.html):

```
cargo +nightly fmt -- --config-path <(echo "format_doc_comments=true")
```

**Comment by scampi** [comment]
sorry, habit: that syntax is on zsh http://zsh.sourceforge.net/Doc/Release/Expansion.html#Process-Substitution. Thanks @shepmaster for spotting this.

**Comment by dannomayer** [comment]
Hi @shepmaster @scampi I would like to contribute and tackle this issue. It's my first time contributing to the project, could you provide me with a little guidance on how to get started on this?

**Comment by scampi** [comment]
@dannomayer Thanks for giving this a try!
I would add the logic to `src/bin/main.rs`:
- add a new CLI option called `--config`
- this accepts a pair of values separated by `=`
- the value set this way has precedence over what is set in a `rustfmt.toml` file
- add few tests ;o)

The module `config` contains everything that pertains to the `Config` struct.
Don't hesitate to open a WIP PR to get early feedbacks.

**Comment by Bruflot** [comment]
I took a crack at this and was hoping to get some feedback before possibly opening a PR.
Wasn't sure if we should support multiple config options, so for the time being it only supports setting a single option. I'm also not sure if I'm doing something super abhorrent by calling `Config::override_value`.

Please see https://github.com/Bruflot/rustfmt/commit/a657c6d91327bc62b4aaf8423c4831ea1a895279
Thanks.

@scampi

**Comment by scampi** [comment]
@Bruflot Thanks for giving this a try, looks good to me. I left some comments to the single option commit. Just open a PR in draft mode if you want to get early feedbacks ;o)

**Comment by CreepySkeleton** [comment]
Hi @scampi , could you please assign me to this issue. I'll give it a try in a day or so.

And a question:
- multiple `--config` invocations. Do we allow them? If so, what if some values are passed multiple times, either within one `--config` invocation or not? I'd suggest "later overrides former" policy.

**Comment by topecongiro** [comment]
@CreepySkeleton Thank you for your interest in contributing to rustfmt! I will assign you to this issue.

> multiple --config invocations. Do we allow them? If so, what if some values are passed multiple times, either within one --config invocation or not? I'd suggest "later overrides former" policy.

I think that we can allow multiple `--config` and I agree that the later should override the values when there are multiple key-value pairs with the same key.
