### ISSUE TITLE
Const generics are handled incorrectly

### ISSUE THREAD

**Issue by DutchGhost** [rust-lang/rustfmt#3554]
When I run `cargo fmt` over the following code:
```Rust
#![feature(const_generics)]

pub struct S<const N: usize>;
impl S<{ 0 }> {}
```

the impl block is formatted to this:
```Rust
impl S<{ 0 }> { 0 }> {}

```
which then obviously fails to compile.

playground: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=be54fe6369c6945d0a5e7a372ce49098

**Comment by scottmcm** [comment]
If anyone else ends up here to report this issue, note that playground is still using rustfmt from 2019-**04**-24, so hasn't picked up this fix yet.
