### ISSUE TITLE
Semicolon is replaced with a colon in a `vec`-inside-a-`vec` macro invocation

### ISSUE THREAD

**Issue by mexus** [rust-lang/rustfmt#3567]
Here's a Rust file:
```rust
fn check() {
    let _ = vec![vec!(0; 10); 10];
}
```

Here's a result of running `rustfmt --check` against it:
```diff
Diff in /tmp/check.rs at line 1:
 fn check() {
-    let _ = vec![vec!(0; 10); 10];
+    let _ = vec![vec!(0, 10); 10];
 }
```

This replacement actually breaks the code: instead of creating an inner vector of 10 zeroes, a vector with two elements (`0` and `10`) is constructed.

The issue is reproducible on both the following versions:
* stable — `rustfmt 1.0.3-stable (d6829d6 2019-02-14)`
* nightly — `rustfmt 1.2.2-nightly (5274b49 2019-04-24)`
* master — `rustfmt 1.2.2-nightly (421ed946 2019-05-18)`

I can't tell which behaviour is desirable: either keep the original declaration `vec![vec!(0; 10); 10]` or convert it into `vec![vec![0; 10]; 10]`, but it is definitely not `vec![vec!(0, 10); 10]` :)

**Comment by scampi** [comment]
as a side note: using square brackets instead of parenthesis would leave it as is.

**Comment by mexus** [comment]
Thanks for a fast fix and for a workaround :)
