### ISSUE TITLE
`use` normalization can break `self` imports

### ISSUE THREAD

**Issue by jrobsonchase** [rust-lang/rustfmt#3568]
There are rare cases where normalizing a `use a::b::{self};` into `use a::b;` will break things. Specifically, cases in which `b` already exists as a function or macro in the current namespace, and you *only* want to import it as a module.

Playground example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=12f1d13256258ac8b34d06b9592a86ef

Running rustfmt on this will cause it to no longer compile.

**Comment by topecongiro** [comment]
Thank you for pointing it out. Since one of rustfmt requirements is to not break the code, we need to disable this normalization. We could add a configuration option for this, but I am not sure if it would be all that useful.
