### ISSUE TITLE
Latest update of stable fails to format |foo = bar| (in a macro)

### ISSUE THREAD

**Issue by thomcc** [rust-lang/rustfmt#3583]
This file fails to format with the latest stable rustfmt (1.2.0, --version output at end). The macro below seems to be the cause https://github.com/mozilla/application-services/blob/eb72c9aa1e5ecfcf79c1444eb98910727c699f61/components/places/benches/search.rs#L66-L74 (We managed to fix that issue by changing the `=` to a `:`)

It also fails to report any errors beyond exiting with code 101, which appears to be issue https://github.com/rust-lang/rustfmt/issues/3008.

```
$ rustfmt --version
rustfmt 1.2.0-stable (09940a70 2019-03-27)
```

**Comment by rchaser53** [comment]
This is the rustfmt failed CI [link](https://circleci.com/gh/mozilla/application-services/14922?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) in your repository.
It seems that the other trouble(maybe ssh key related) so it's not a rustfmt bug.

I tried to reproduce your CI error in my fork repository. But rustfmt run correctly.
This is a CI [link](https://circleci.com/gh/rchaser53/application-services/20) in my repository.
It's also failed, but it's a correct behavior.
```cargo fmt -- --check``` founds the diff like below.

![cargo_fmt_check_diff](https://user-images.githubusercontent.com/9676954/58371347-798bf180-7f4b-11e9-8f09-9998b56913de.png)

**Comment by thomcc** [comment]
That's not the right link to a CI failure from this, here's one: https://circleci.com/gh/mozilla/application-services/15051

You can also repro by checking out commit `eb72c9aa1e5ecfcf79c1444eb98910727c699f61` and using rustfmt.

**Comment by rchaser53** [comment]
I can reproduce the problem, thank you.

**Comment by topecongiro** [comment]
A minimal working example:

```rust
foo!(|0 =);
```

rustfmt somehow aborts while parsing the argument of `foo!`. Since rustfmt catches unwinding panics from the parser, I suspect that in some cases the parser aborts the whole process. Not sure how this can be fixed from the rustfmt side.

**Comment by thomcc** [comment]
I'm not sure the rust parser aborting makes a lot of sense, since the code in the case I'm reporting compiles (and runs) fine.

**Comment by topecongiro** [comment]
@thomcc Yeah, you are right. I took another look at the code and found that panics raised while parsing macro arguments are not caught.
