### ISSUE TITLE
[RFC] Change the default behavior of rustfmt to not to format sub-modules

### ISSUE THREAD

**Issue by topecongiro** [rust-lang/rustfmt#3587]
### Summary

Change the default behavior of rustfmt to **not** to format sub-modules of the given files by default. The behavior of `cargo fmt` will not change with this proposal.

### Steps

1. Change the default behavior of rustfmt to not to format sub-modules
2. Deprecate `--skip-children` (as it will the default)
3. Add `-r,--recursive` command line option, when if present, rustfmt will format the given files and their sub-modules (the current default)

**Comment by otavio** [comment]
Given `cargo fmt` behavior does not change, I think it does make sense so it is, in fact, applying at the given file.
