### ISSUE TITLE
How to emit a diff?

### ISSUE THREAD

**Issue by RazrFalcon** [rust-lang/rustfmt#3588]
```
> cargo +nightly fmt -- --emit diff
Invalid value for `--emit`
```

**Comment by sinkuu** [comment]
>        --check         Run in 'check' mode. Exits with 0 if input is
>                        formatted correctly. Exits with 1 and prints a diff if
>                        formatting is required.

`cargo fmt -- --check`

**Comment by RazrFalcon** [comment]
Thanks!
