### ISSUE TITLE
Format long numeric literals

### ISSUE THREAD

**Issue by tesuji** [rust-lang/rustfmt#3594]
I got this warning from clippy:
```rust
warning: long literal lacking separators
  --> src/elf/gnu_hash.rs:38:43
   |
38 |         assert_eq!(hash("flapenguin.me"), 0x8ae9f18e);
   |                                           ^^^^^^^^^^ help: consider: `0x8ae9_f18e`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unreadable_literal
```

It would be better if rustfmt can handle it automatically.

**Comment by sinkuu** [comment]
`unreadable_literal` emits a machine-applicable suggestion, which would (hopefully) become auto-fixable by `cargo fix` with clippy integration in the future.

**Comment by scampi** [comment]
The rustfmt tool is not made for fixing such things

**Comment by lzutao** [comment]
What I mean is not fixing those clippy lints. But rustfmt could formats those long 
numeric literals while running?

**Comment by scampi** [comment]
@lzutao Given the assert expression in the description, what would you expect the formatting to be ?

**Comment by calebcartwright** [comment]
This is something rustfix is great for, but is not something that fits in rustfmt's purview and thus is not something we'll implement
