### ISSUE TITLE
Consider renaming --print-config to something that implies writing to a file

### ISSUE THREAD

**Issue by marienz** [rust-lang/rustfmt#3597]
While trying to work out what rustfmt's default config is, I overwrote my source with that config.

This is PEBKAC, but maybe some tweaks to rustfmt's behavior or help output could make it more idiot-proof? If `--print-config` had been called `--write-config` I probably would've paid more attention. Or maybe it should refuse to overwrite existing files by default?

Here's what I ran, and what I thought as I was running it:
```
$ rustfmt --help
...
        --print-config [minimal|default] PATH
                        Dumps a default or minimal config to PATH. A minimal
                        config is the subset of the current config file used
                        for formatting the current program.
...
```
(ah, `--print-config` will print the config, which is exactly what I want.)
```
$ rustfmt --print-config
Argument to option 'print-config' missing
```
(I don't know what it wants, but the help mentions "minimal" and "default", so let's try both.)
```
$ rustfmt --print-config minimal
WARNING: PATH required for `--print-config minimal`
```
(Path? Oh, the help mentions something about "for formatting the current program", so it wants to know what that program is.)
```
$ rustfmt --print-config minimal .
Error: `/home/marienz/src/my_first_rust_project` is a directory
Is a directory (os error 21)
```
(So it doesn't want the package directory. Let's try a file instead.)
```
$ rustfmt --print-config minimal src/my_module.rs
```
(No output? Hmm, maybe the minimal config is the empty one. Let's try the other mode.)
```
$ rustfmt --print-config default src/my_module.rs
```
(Still no output? Let's try without a path just in case paths only make sense for minimal)
```
$ rustfmt --print-config default
max_width = 100
...
```
(Ah, there's the config! Succes!)

...and then I noticed my_module.rs had mysteriously turned into a config file.

Looking at the help more closely, I finally noticed the "to PATH" bit I'd overlooked. And trying these commands again, they do indeed write a small or large config to the path I pass them.

I wasn't expecting rustfmt to make non-formatting changes to existing files at all, so I wasn't particularly careful where I ran it or what I pointed it at.

I installed rustfmt along with Rust 1,35.0 using the system package manager. Its `--version` says it is 1.2.0-stable.

**Comment by topecongiro** [comment]
On 2.0 the behavior of `--print-config` will be changed so that it has no side-effect outside of printing a set of configuration options to stdout.
