### ISSUE TITLE
top-level `use` statements are sometimes deleted when rearraged.

### ISSUE THREAD

**Issue by DR-BoneZ** [rust-lang/rustfmt#3609]
Tested in VSCode with latest rls and `Format on Save`:
```
use crate::stuff;
use failure::Error;
use r2d2::ConnectionManager;
use diesel::PgConnection;
```
becomes
```
use crate::stuff;
use diesel::PgConnection;
use r2d2::ConnectionManager;
```
This deleted an import.
I have observed this behavior consistently on any set of mis-ordered imports.

**Comment by topecongiro** [comment]
Couldn't reproduce this locally. This is probably due to a bug in VSCode extension. cc https://github.com/rust-lang/rls-vscode/issues/595.
