### ISSUE TITLE
Stabilization of ident_style?

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rustfmt#3622]
Hi,

Could we stabilize this feature please?

**Comment by topecongiro** [comment]
The current implementation of the visual indent is kind of broken and I would like to fix it by using the visual indentation only when the whole expression or the type is simple.

Unfortunately, this is unlikely to happen in the near future because I don't have much time to work on it.

**Comment by topecongiro** [comment]
Closing in favor of #3346.
