### ISSUE TITLE
method call is put a new line although there is enough horizontal space

### ISSUE THREAD

**Issue by scampi** [rust-lang/rustfmt#3637]
```rust
impl Foo {
    fn foo() {
        self.report.add_non_formatted_ranges(visitor.skipped_range.clone());
    }
}
```

```diff
 impl Foo {
     fn foo() {
-        self.report.add_non_formatted_ranges(visitor.skipped_range.clone());
+        self.report
+            .add_non_formatted_ranges(visitor.skipped_range.clone());
     }
 }
```

**Comment by topecongiro** [comment]
This is expected, as the width of the chain exceeds `chain_width` (which is 60 by default).

**Comment by xahon** [comment]
@topecongiro what is `chain_width`? It is not documented in https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

**Comment by scampi** [comment]
I think that is the property of the `width_heuristics`, but it is listed under `not user-facing` in the config.

https://github.com/rust-lang/rustfmt/blob/c0e616bc1d19eb9b08a5db2f265b8332569e7259/src/config/mod.rs#L150

https://github.com/rust-lang/rustfmt/blob/c0e616bc1d19eb9b08a5db2f265b8332569e7259/src/config/options.rs#L190-L191
