### ISSUE TITLE
Allow field access on same line when breaking long chain?

### ISSUE THREAD

**Issue by singpolyma-shopify** [rust-lang/rustfmt#3641]
rustfmt currently requires:

```rust
self.serializer
    .writer
    .write_u32::<LittleEndian>(array_offset)?;
```

It seems that it would be reasonable to have a setting for:

```rust
self.serializer.writer
    .write_u32::<LittleEndian>(array_offset)?;
```

**Comment by scampi** [comment]
@topecongiro Do you want to have a new config option for this ? Or an improvement to the default formatting of chains ?

**Comment by singpolyma-shopify** [comment]
@scampi either.  Having this be the default seems right to me, but if others disagree an option works fine.

**Comment by ytmimi** [comment]
Going to close this in favor of #4306, which has a lot more discussion on chain formatting
