### ISSUE TITLE
`FileLines::all().to_json_spans()` returns `[]` which is parsed as empty map

### ISSUE THREAD

**Issue by Xanewok** [rust-lang/rustfmt#3649]
This surfaced at https://github.com/rust-lang/rls/issues/1463 (fixed in https://github.com/rust-lang/rls/pull/1497).

The underlying data structure discerns a missing/"all" state in addition to actual set (possibly empty) of lines:
https://github.com/rust-lang/rustfmt/blob/26d370e9e52f5c2727b7289e339499aef0b7b3ec/src/config/file_lines.rs#L151-L157

whereas `to_json_span` only encodes a specified set of those changes (can't represent `FileLines(None)`):

https://github.com/rust-lang/rustfmt/blob/26d370e9e52f5c2727b7289e339499aef0b7b3ec/src/config/file_lines.rs#L218-L221

I think we should either:
1. panic/return err on `None` match in `to_json_spans` (since `vec![]` returned for `FileLines(None)` won't be parsed back into the `FileLines(None)` but rather `FileLines(Some(HashMap::new))`
2. Somehow discern or accept `null` lines in `--file-lines JSON` and make `to_json_spans()` return `Option<Vec<JsonSpan>>`

Thoughts?

cc @jsgf @ljw1004

**Comment by topecongiro** [comment]
> since vec![] returned for FileLines(None) won't be parsed back into the FileLines(None) but rather FileLines(Some(HashMap::new)

I think that it would be simpler to fix this part instead, `vec![]` should be parsed to `FileLines(None)`?

**Comment by Xanewok** [comment]
This would mean that `--file-lines []` would correspond to `FileLines::all()` - wouldn't that also be surprising?

**Comment by topecongiro** [comment]
Yeah, you are right. Actually `rustfmt --help=file-lines` explicitly states that `Specifying an empty array
will result in no files being formatted`.

In that case, I would prefer to go with your second option.

**Comment by topecongiro** [comment]
If we go with @Xanewok's second option, then it will introduce an update to the public API (`FileLines:: to_json_spans`), which in theory requires a major version update of rustfmt. However I am not planning to release 2.0 anytime soon, so the fix will be postponed for a few months. This does not sound great.

Rather, we could implement `Serialize` and `Deserialize` on `FileLines` to fix the issue, and deprecate `FileLines::to_json_spans`. This does not introduce any breaking changes.

A different approach would be to relax the stability guarantee of rustfmt so that 'small' breaking changes can be introduced with a minor version update. This sounds fine, as the main (or the only?) consumer of rustfmt-as-a-library is rls.

**Comment by Xanewok** [comment]
I'd probably lean towards the last option since it's more of a bugfix (comment mentions serializing into format accepted by `--file-lines JSON` but in this case the `None` match is wrongly deserialized to `[]`).

However, having a `(De)Serialize` impl sounds like a useful thing on its own.

What's puzzling is the difference between representation - `file-lines` accepts `Vec<(File, Range)>` while internally (which makes more sense) it's stored as `HashMap<File, Vec<Range>>`. Is it for backwards-compatibility and the internals were switched at some point?

I'd probably find it puzzling to see a slightly different `Serialize`d data layout to the one used internally (when the original could be trivially serialized as-is), so I'm -0.5 on the fix using these impls.

**Comment by calebcartwright** [comment]
@topecongiro I can take a look at this one

**Comment by calebcartwright** [comment]
Opened #3954 that implements the second option detailed by @Xanewok 

I didn't include the `Serialize` and `Deserialize` implementations for `FileLines` as it wasn't clear to me from this thread if we wanted to do so, and it also seems like we're already using those to bubble up some errors:

https://github.com/rust-lang/rustfmt/blob/7713d05c5bda4fb3bc3b01fd18b335b96d114d8a/src/config/file_lines.rs#L333-L354
