### ISSUE TITLE
rustfmt inserts unnecessary braces around if-expression

### ISSUE THREAD

**Issue by mulkieran** [rust-lang/rustfmt#3656]
```
match ... {
  C1 => if ... else ...
}
```

is rewritten to 

```
match ... {
  C1 => { if .. else ... }
}
```

by rustfmt.

See PR#: https://github.com/stratis-storage/stratisd/pull/1576.

The version of rustfmt is 1.2.0.

**Comment by mulkieran** [comment]
reproduced on today's Rust playground, stable and nightly.

**Comment by topecongiro** [comment]
This is by design, to make it easier to distinguish between the match guard and if the expression.

**Comment by mulkieran** [comment]
The match guard comes before the "=>" token, the if-expression comes after, so they can be distinguished w/out rustfmt special case behavior for that one type of expression.

The behavior is inconsistent w/ treatment for other expressions, like match-expressions, loop-expressions, etc. where rustfmt does not force the redundant braces.

AFAIC, this is more of an obfuscator than a clarifier, because the reader has occasionally to work pretty hard to figure out that the if-expression is the whole expression of the match arm in the cases where the braces could have been dropped.

**Comment by mulkieran** [comment]
Well, I took a look at #1889 where this was decided. I'ld say the decision makes things worse for me, _especially_ when the if-expression is long. On the other hand, I've so far avoided any configuration of rustfmt in my projects, and this is not bad enough for me to make me want to plunge into setting up a rustfmt configuration file, (and trying to add a configuration option to change this for people like me who prefer the pre #1889 approach).
