### ISSUE TITLE
Preserve trailing two whitespace in multi-lined doc comments

### ISSUE THREAD

**Issue by topecongiro** [rust-lang/rustfmt#3659]
From https://github.com/rust-lang/rustfmt/pull/2436#issuecomment-506679965 by @LucianoBestia:

---

I  tried this on nightly version rustfmt 1.3.0-nightly (d3345024 2019-06-09).

rustfmt preserves trailing double space in doc-comments that begin with `//!` 
But it does not preserve it in **multiline doc-comment** that begin with `/*!`
example:
```
/*! some text  
with trailing double space  
for markdown newline formatting  
*/
``` 
Writing or copy/paste long markdown text without having //! on each line is much easier.

**Comment by LucianoBestia** [comment]
I think this is not enough in `comment.rs`:
```
    /// Returns `true` if the commenting style is for documentation.
    pub(crate) fn is_doc_comment(&self) -> bool {
        match *self {
            CommentStyle::TripleSlash | CommentStyle::Doc => true,
            _ => false,
        }
    }
```
 I think this `CommentStyle` should also be doc_comments: 
    `DoubleBullet,  
    Exclamation,`

**Comment by LucianoBestia** [comment]
There are also 2 tests for this issue:
rustfmt/tests/source/markdown-comment-with-options.rs
rustfmt/tests/source/markdown-comment.rs

There could be added this 2 types of doc-comments:
```
/*! multiline doc-comment  
with trailing double space  
*/
/** multiline doc-comment  
with trailing double space
*/
```
and then also the one multiline comment that is NOT a doc-comment:
```
/* this multiline comment  
is not a doc-comment
*/
```
