### ISSUE TITLE
Skip Attribute

### ISSUE THREAD

**Issue by la10736** [rust-lang/rustfmt#3665]
Attributes are evolving and now are used also to create DSL. Now, by the rising of procedural macro and the possibility to use arbitrary rust code in attributes syntax formatting attribute by simple rules based on meta and nested meta can produce some formatting that make the procedural macro DSL not clear.

For instance I have a crate of mine [la10736/rstest](https://github.com/la10736/rstest) that you can use to write tests like this:

```rust
#[rstest_parametrize(foo, bar, baz,
    case(0, "a", "A"),
    case(1, "b", "B")
)]
fn mytest(foo: u32, bar: &str, baz: &str) {}
```
Now, use `rustfmt` on this file make it flat and hard to read:

```rust
#[rstest_parametrize(foo, bar, baz, case(0, 'a', 'A'), case(1, 'b', 'B'))]
fn mytest(foo: u32, bar: char, baz: char) {}
```

Or wrost:
```rust
#[rstest_parametrize(foo, bar, baz,
    case(0, "a", "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"),
    case(1, "b", "B")
)]
fn mytest(foo: u32, bar: &str, baz: &str) {}
```
in

```rust
#[rstest_parametrize(
    foo, 
    bar,
    baz,
    case(0, "a", "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"),
    case(1, "b", "B")
)]
fn mytest(foo: u32, bar: &str, baz: &str) {}
```

We can use `rustfmt::skip::macros()` or a brand new `rustfmt::skip::attributes()` to have the ability of skip attributes formatting too.

If you are ok I can work on it.

**Comment by topecongiro** [comment]
It seems like a good idea given that, like macro calls, attributes can have an arbitral token stream as their arguments.

**Comment by topecongiro** [comment]
Adding a new `rustfmt::skip::attributes()` seems better to me.

**Comment by la10736** [comment]
I'm done with base implementation but is just a _cut and paste_ of `rustfmt::skip::macros()` implementation. I tempted to refactor all skip's stuff before submit but I should decide if merge just `macros` and `attributes` stuffs or encapsulate `rustfmt::skip` responsibility too.

The second one solution touch lot of files so maybe is better do a separate pull request but merge just sub attributes left things less cohesive.

What do you think?

**Comment by scampi** [comment]
@la10736 a separate PR would probably be better

**Comment by la10736** [comment]
I already did the PR with just refactoring `macros` and `attributes`. I left `rustfmt::skip`'s stuff untouched.
