### ISSUE TITLE
Bug in formatting function pointer's return type

### ISSUE THREAD

**Issue by DanSnow** [rust-lang/rustfmt#3670]
Description
-----------

`rustfmt` will format this:

```rust
type F = fn() -> io::Result<()>;
```

into this:

```rust
type F = fn() -> io::Result<() -> io::Result<()>;
```

Environment
-----------

- `rustfmt --version`: `rustfmt 1.2.2-stable (5274b49 2019-04-24)`

**Comment by rchaser53** [comment]
It's already resolved. Please use latest version.

**Comment by DanSnow** [comment]
Thanks for quick reply. I have try the `v1.3.0` and it work.
But it seem that the rustfmt in rustup's stable channel is still on `v1.2.2`.I think I'll just use `#[rustfmt::skip]` as a workaround and wait for update.
