### ISSUE TITLE
Formatting empty function type adds additional empty return type

### ISSUE THREAD

**Issue by ryancerium** [rust-lang/rustfmt#3673]
A file consisting of:
```
type Action = fn() -> ();
```
gets formatted to:
```
type Action = fn() -> () -> ();
```
which no longer compiles.  Tested on Linux and Windows, with 1.2.2-stable.

```
PS C:\Users\rphelps\code\ryancerium\temp> rustfmt --version
rustfmt 1.2.2-stable (5274b49c 2019-04-24)

PS C:\Users\rphelps\code\ryancerium\temp> type sample.rs
type Action = fn() -> ();

PS C:\Users\rphelps\code\ryancerium\temp> rustfmt sample.rs

PS C:\Users\rphelps\code\ryancerium\temp> type sample.rs
type Action = fn() -> () -> ();

PS C:\Users\rphelps\code\ryancerium\temp>
```

**Comment by rchaser53** [comment]
Please use the latest version.

**Comment by ryancerium** [comment]
When will the latest version get pushed into `rustup`?  Right now `rustup update stable` leaves me with 1.2.2 and `rustup component add rustfmt` says it's up to date also.

**Comment by rchaser53** [comment]
You cannot use the latest rustfmt on stable rust. Please use it on nightly rust.

**Comment by fragrans** [comment]
I have the same issue. ` -> ()` was appended to the end after running `cargo fmt`


![image](https://user-images.githubusercontent.com/102768/61098445-99428f00-a491-11e9-901f-33e0abbd529a.png)

![image](https://user-images.githubusercontent.com/102768/61098630-30a7e200-a492-11e9-9d04-3a2707aceabe.png)

**Comment by topecongiro** [comment]
Closing as this should be fixed on the latest stable.
