### ISSUE TITLE
Format only already dirty files

### ISSUE THREAD

**Issue by NoraCodes** [rust-lang/rustfmt#3674]
It would be really nice, in the case where there is a recognized VCS, to have an option to format only files I've already touched, to avoid cluttering up PRs by formatting code irrelevant to my changes.

**Comment by scampi** [comment]
there's #1324 about this ;o)

**Comment by marc-hb** [comment]
#1234 seems focused on line-based filtering, which is MUCH more ambitious.

#4485 looks more similar.
