### ISSUE TITLE
rustfmt causes internal error when add comment between conditions

### ISSUE THREAD

**Issue by rchaser53** [rust-lang/rustfmt#3678]
source:
```
fn main() {
    if a
        // panic!
        && b
    {}
}
```

playground:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=856d116c793b74e6809441b4ccf7af68

error message:
![internal_error](https://user-images.githubusercontent.com/9676954/61055552-babd5f80-a42c-11e9-9ed4-7c9437a4d3e6.png)

**Comment by dvc94ch** [comment]
This works now, I guess the issue can be closed
