### ISSUE TITLE
fn_args_layout is marked as stable, but not available on stable toolchain

### ISSUE THREAD

**Issue by rzumer** [rust-lang/rustfmt#3692]
I don't know whether this is an issue with `rustfmt`, `rustup`, or something else, but I am on the latest stable Rust `x86_64-pc-windows-msvc` toolchain and `rustup component add rustfmt` indicates that I am up to date. Despite `fn_args_layout` being marked as stable in the documentation, running `cargo fmt` with it set returns an "Unknown configuration option" error.

Is there any estimate for when it will be available?

**Comment by topecongiro** [comment]
It has been stable since rustfmt 1.3.0 [1]. I cannot be certain about when the version will be available via the stable channel, though it's likely that it would be available in the next release.

[1] https://github.com/rust-lang/rustfmt/blob/master/CHANGELOG.md#130-2019-06-09

**Comment by rzumer** [comment]
The latest toolchain release was on July 3rd. I think it is odd that it is still not available. What makes you suggest that the next release will include it?
