### ISSUE TITLE
How to make chained calls to be on new lines

### ISSUE THREAD

**Issue by xahon** [rust-lang/rustfmt#3693]
Is there an option to allow >= 3 (or configurable number) calls in a row on self to be wrapped?
```rust
a.do_something()
 .another_thing()
 .build();
```

**Comment by scampi** [comment]
#2263 sounds related

**Comment by kellytk** [comment]
I would also like for chained calls to be on new lines as shown in @xahon's example.

**Comment by calebcartwright** [comment]
Closing as a duplicate of #2263
