### ISSUE TITLE
Inconsistent line breaks in short "if" expression

### ISSUE THREAD

**Issue by diwic** [rust-lang/rustfmt#3699]
Consider the following two functions:

    fn from(i: &'a Msg) -> Result<&'a OwnedFd, ()> {
        if let &Msg::A(ref b) = i { Ok(b) } else { Err(()) }
    }
    
    fn main() {
        let _x = if true { Ok(1) } else { Err(0) };
    }

All lines are shorter than `max_width`, so why does rustfmt change the upper one but not the lower one, into this:

    fn from(i: &'a Msg) -> Result<&'a OwnedFd, ()> {
        if let &Msg::A(ref b) = i {
            Ok(b)
        } else {
            Err(())
        }
    }
    
    fn main() {
        let _x = if true { Ok(1) } else { Err(0) };
    }

It looks inconsistent to me, but if this is indeed correct behavior, I would like an option to keep the upper one as it is, too.

**Comment by scampi** [comment]
This seems to be because of the `width_heuristics` option `single_line_if_else_max_width` which is set to `50` by default.

The following config would do what you want:

```toml
version = "Two"
use_small_heuristics = "Max"
```

**Comment by diwic** [comment]
> This seems to be because of the `width_heuristics` option `single_line_if_else_max_width` which is set to `50` by default.
> 
> The following config would do what you want:
> 
> ```toml
> version = "Two"
> use_small_heuristics = "Max"
> ```

Okay,

I tried having only these two in my `rustfmt.toml`, then I ran `rustfmt +nightly src/main.rs` but it did not help - the upper one was still translated into several lines.

**Comment by scampi** [comment]
Are you sure you have the latest version ? I ran with 1.3.3 and the upper if stays on one line.

**Comment by diwic** [comment]
Indeed, that was it! Thanks!

**Comment by scampi** [comment]
Glad you got what you wanted! ;o)
