### ISSUE TITLE
support auto import like goimports

### ISSUE THREAD

**Issue by jiacai2050** [rust-lang/rustfmt#3700]
ref: https://www.reddit.com/r/rust/comments/azk9vv/goimports_for_rust/

**Comment by topecongiro** [comment]
Unfortunately there are too much differences between the module system of Go and Rust. In Go you only need the AST to figure out the missing/unused packages, but in Rust you need to perform extra compilation processes like macro expansions and module resolutions. These are outside the scope of rustfmt.

IMHO, in Rust tools like goimports is nigh-impossible to implement outside of the special environment like IDE where you get to keep around the intermediate state of the compilation of the target crate.
