### ISSUE TITLE
Another "error[internal]: left behind trailing whitespace" bug

### ISSUE THREAD

**Issue by BartMassey** [rust-lang/rustfmt#3717]
Here's another "error[internal]: left behind trailing whitespace" bug: [gist](https://gist.github.com/BartMassey/850f05e9968b41da4042924fb08fc981). `rustfmt` 1.2.2-stable (5274b49 2019-04-24), 1.4.1-nightly (9e960e7 2019-07-30).

```
error[internal]: left behind trailing whitespace
   --> /usr/local/src/sokoban-rs/rs/rustfmtbug.rs:184:184:15
    |
184 |     let layer = 
    |                ^
    |

error[internal]: left behind trailing whitespace
   --> /usr/local/src/sokoban-rs/rs/rustfmtbug.rs:201:201:15
    |
201 |     let layer = 
    |                ^
    |

warning: rustfmt has failed to format. See previous 2 errors.
```

I tried to cut the example down to something reasonable, but the bug seems really fragile. Apologies.

**Comment by rchaser53** [comment]
Minimum example:

```
fn main() {
    {
        #[rustfmt::skip]
        let _ = 
        [1];
    }   
}
```

playground link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=673db728a775e9e6943975b63e9158f9

**Comment by topecongiro** [comment]
The code under `rustfmt::skip` should not trigger `left behind trailing whitespace` errors.

**Comment by 0xpr03** [comment]
I get this for `let toml` in [here](https://github.com/0xpr03/clantool/blob/cb53f1cc88400804c5328a4126e7a7fc760e219b/src/config.rs#L144) using a `r#"` in the next line.

**Comment by rchaser53** [comment]
@0xpr03 your bug seems to be another reason, so I created new issue #3786.
