### ISSUE TITLE
dyn and :: should have a space between

### ISSUE THREAD

**Issue by agrover** [rust-lang/rustfmt#3724]
When given this code:
```
fn foo(_x: &u64) -> Option<&(dyn ::std::error::Error + 'static)> {
    None
}
```
rustfmt 1.2.2 stable removes the space between dyn and ::, resulting in this:
```
fn foo(_x: &u64) -> Option<&(dyn::std::error::Error + 'static)> {
    None
}
```

**Comment by topecongiro** [comment]
We need to use edition 2018 to use the `dyn` syntax with a path that starts with `::`. If you are using edition 2015 in your project, then you need to write like (`dyn (::std::error::Error)`).

cc https://github.com/rust-lang/rust/issues/49218#issue-307018539

**Comment by agrover** [comment]
This is with edition 2018. Please reopen?

**Comment by sinkuu** [comment]
It seems that rustfmt (on playground) correctly adds spacing if edition is set to 2018. I guess https://github.com/rust-lang/rustfmt#rusts-editions fixes your problem.

**Comment by agrover** [comment]
No, we are using 2018 edition.

* `git clone https://github.com/mozilla/neqo.git`
* Observe that neqo-transport/Cargo.toml sets `edition = "2018"`
* Observe that neqo-transport/src/lib.rs line 120 is mis-formatted.

**Comment by agrover** [comment]
Oops, I can't repro with `cargo fmt -- --check`, this is happening with emacs rust-mode autoformat-on-save, so I think it is to blame, not rustfmt. Sorry to bother y'all.
