### ISSUE TITLE
Option for --check to list violating files only

### ISSUE THREAD

**Issue by abonander** [rust-lang/rustfmt#3738]
For our CI script we just want to say "cargo fmt needs to be run, here's the files that need it" which doesn't appear to be possible using `--check`. The diff output is kind of too noisy to be useful unless you expect the committer to actually fix the files by hand.

**Comment by calebcartwright** [comment]
I was just thinking about this one the other day

**Comment by topecongiro** [comment]
We can add a command line flag like the `-l,--files-with-matches` of `rg`:

```shell
# Run `cargo fmt -- --check` but only prints file names which will be formatted
cargo fmt -- --check -l
# Run `cargo fmt` and print file names that were formatted
cargo fmt -- -l
```

**Comment by calebcartwright** [comment]
Even better! I'd be happy to look at implementing this @topecongiro once I've finished up my work with the json and checkstyle emitters

**Comment by abonander** [comment]
That was quick! Awesome!
