### ISSUE TITLE
Command line interface for 2.0

### ISSUE THREAD

**Issue by topecongiro** [rust-lang/rustfmt#3739]
Notes on some ideas for CLI changes in rustfmt 2.0.

## Deprecate `--backup`

This should be done via any version control system.

## Add subcommands

Change format-diff/git-rustfmt into rustfmt's subcommands.

Also `rustfmt --print-config` could be one of subcommands as well instead of being a flag, as it takes multiple arguments.

## Add `--check` to cargo fmt

`cargo fmt -- --check` is one of the most common usage of rustfmt. Why require an additional `--`?

**Comment by calebcartwright** [comment]
> Add --check to cargo fmt

I'd like to work on that one!

**Comment by davidalexanderr** [comment]
Hey @topecongiro, is `add --check to cargo fmt` still up for grabs?

**Comment by calebcartwright** [comment]
The addition of `--check` to `cargo fmt` and the deprecation of `--backup` have already been completed. I don't think anyone is working on any of the subcommands though

**Comment by calebcartwright** [comment]
@topecongiro - the only thing left here is to move format-diff/git-rustfmt from separate binaries to subcommands on rustfmt right?

**Comment by topecongiro** [comment]
Yes, that's right. And since both of them aren't stable yet, I might as well remove them from the 2.0 milestone.

So there's nothing left to do with this issue, closing :tada:
