### ISSUE TITLE
Multiple function arguments per line

### ISSUE THREAD

**Issue by diwic** [rust-lang/rustfmt#3745]
Is there a way I can get the code to look something like this:

    fn lorem<Ipsum: Eq = usize, Dolor: Eq = usize, Sit: Eq = usize,
        Amet: Eq = usize, Adipiscing: Eq = usize, Consectetur: Eq = usize,
        Elit: Eq = usize
    >(ipsum: Ipsum, dolor: Dolor, sit: Sit, amet: Amet, adipiscing: Adipiscing,
        consectetur: Consectetur, elit: Elit
    ) -> T {

I find the current "new line for every argument" style very wasteful of screen space.

**Comment by topecongiro** [comment]
I think what you want is [`fn_args_layout = "Compressed"`](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#compressed).

**Comment by diwic** [comment]
Thanks, not sure how I missed that - but I would like this "compressed" style to apply for many other things, such as long struct initializers, long imports, etc. Is that possible?

**Comment by topecongiro** [comment]
rustfmt does not have a global configuration option for forcing compressed format throughout, but it does have some item-specific settings. For imports, the default (`imports_layout = "Mixed"`) is the most compressed format style that rustfmt offers.

**Comment by ytmimi** [comment]
We recently merged #5387, which renamed `fn_args_layout` -> `fn_params_layout`. That being said, the original issue was scoped to compressing the parameters, which is now achieved by setting `fn_params_layout=Compressed`.

A separate issue should be opened to discuss `Compressed` formatting for other ast nodes.
