### ISSUE TITLE
Formatting takes two runs to converge

### ISSUE THREAD

**Issue by YaLTeR** [rust-lang/rustfmt#3746]
This particular pattern:
```rust
f!(match a {
    4 =>
        &[
            (3, false), // Missing
            (4, true)   // I-frame
        ][..],
});
```
requires two steps to converge. The first step does the following:
```rust
f!(match a {
    4 => {
        &[
            (3, false), // Missing
            (4, true)   // I-frame
        ][..]
    }
});
```
and the second step adds the missing comma:
```rust
f!(match a {
    4 => {
        &[
            (3, false), // Missing
            (4, true),  // I-frame
        ][..]
    }
});
```
This works properly (in a single step) if `f!` is a function rather than a macro. The real use-case uses `assert_eq!`. Tested on `rustfmt` `1.3.0-stable` and `1.4.4-nightly (0462008 2019-08-06)`.

**Comment by topecongiro** [comment]
Inside macro calls rustfmt should not add or remove a block or a comma. With respect to the given example, rustfmt should emit:

```rust
f!(match a {
    4 => &[
        (3, false), // Missing
        (4, true)   // I-frame
    ][..],
});
```
