### ISSUE TITLE
Formatting changes semantics of imports

### ISSUE THREAD

**Issue by Robbepop** [rust-lang/rustfmt#3750]
I have a project with a module that re-exports other definitions as follows:
```rust
mod defs {
    #[cfg(feature = "std")]
    pub use std::vec;
    #[cfg(not(feature = "std"))]
    pub use alloc::vec;
}
```
Oftentimes I want to use the `vec!` macro and `Vec` type like so:
```rust
use defs::{
    vec,
    vec::Vec,
};
```
However, `rustfmt` thinks this is worse than
```rust
use defs::vec::{self, Vec};
```
However, this has different semantics since `vec` above refers to the `vec!` macro while `self` in the replaced variant refers to the `vec` submodule of `defs`. So I can no longer access the `vec!` macro whenever `rustfmt` replaced this.

To be honest: I don't know whether this is a `rustfmt` bug or a Rust compiler bug.

**Comment by topecongiro** [comment]
This is not reproducible with the latest rustfmt, both in stable and nightly. Would you mind telling us which version you have used?

**Comment by Robbepop** [comment]
`cargo fmt --version` yields `rustfmt 1.4.4-nightly (0462008 2019-08-06)`
Good to know that it is already fixed at `master`. Sadly I am not able to upgrade at the moment.

**Comment by topecongiro** [comment]
@Robbepop Never mind, this is actually reproducible with `merge_imports = true`. Do you set 
the option as well?

**Comment by Robbepop** [comment]
> @Robbepop Never mind, this is actually reproducible with `merge_imports = true`. Do you set
> the option as well?

yes it is enabled!
