### ISSUE TITLE
Unpublish from crates.io?

### ISSUE THREAD

**Issue by tdaede** [rust-lang/rustfmt#3755]
Some of our developers are confused that the version of rustfmt installed from crates.io does not match the version from rustup. The crates.io page does display a notice that it's deprecated, but I think it would be better if it wasn't installable at all.

**Comment by topecongiro** [comment]
For historical reasons, https://crates.io/crates/rustfmt is deprecated and https://crates.io/crates/rustfmt-nightly hosts the most up-to-date version. Ideally we could replace the former with the latter by renaming it, but I am not sure if that's possible in crates.io. Also I might not have the permission to do so. @nrc would you mind having a look?

**Comment by topecongiro** [comment]
Closing in favor of #4343.
