### ISSUE TITLE
Import grouping

### ISSUE THREAD

**Issue by theduke** [rust-lang/rustfmt#3766]
A common pattern is to separate imports into 3 groups: builtins (std/core/alloc), dependencies and crate-locals (separated by newlines).

Eg:

```rust
mod submodule;

use std::{sync::{Arc, Mutex}, time;:Duration};

use chrono::{DateTime, Utc};
use uuid::Uuid;

use crate::{...};
use submodule::X;
```
It seems like `rustfmt` should have all the information to do this grouping.

Is this common enough to potentially be implemented behind a setting?

The only potentially difficult part is distinguishing local imports from external crates, but this should be possible by checking for `super`, submodule declarations and enums.

**Comment by topecongiro** [comment]
This is certainly possible and personally I would like to add this to rustfmt behind a config option.

The other difficult point I can think of is how we handle imports that are intertwined with other items, especially those with comments:

```rust
use std::sync::Arc;
use crate::{...};
use submodule::X;

fn foo() {}

/*
  other items...
*/

// Pre-comment
use std::sync::Mutex; // Post-comment 1
// Post-comment 2
fn bar() {}
```

Ideally, we should not lose any comments and the `Pre-comment` and `Post-comment 1` should be moved along with `use std::sync::Mutex`, but leave the `Post-comment 2`.

For the initial implementation, we can just ignore out-of-place imports or imports with comment. Just sort & re-group imports that are syntactically consecutive.

**Comment by drrlvn** [comment]
Isn't this a duplicate of #2979?

**Comment by theduke** [comment]
It is indeed.
