### ISSUE TITLE
weird spacing and alignment with &&, !, and unsafe block

### ISSUE THREAD

**Issue by lopopolo** [rust-lang/rustfmt#3770]
rustfmt formats this code funnily. This is the formatted output:

```rust
            unsafe { sys::mrb_sys_value_is_false(value) }
            &&!unsafe { sys::mrb_sys_value_is_true(value) }
                && !unsafe { sys::mrb_sys_value_is_nil(value) }
```

An alternate branch in the conditional formats correctly:

```rust
            !unsafe { sys::mrb_sys_value_is_false(value) }
                && unsafe { sys::mrb_sys_value_is_true(value) }
                && !unsafe { sys::mrb_sys_value_is_nil(value) }
```

Attaching the `&&` to the expression causes rustc to take a double reference and the code does not compile.

**Comment by rchaser53** [comment]
It seems to be a compiler error. I added the dbg! to show the snippet and expr info.

### the place to add the dbg!
https://github.com/rchaser53/rustfmt/blob/issue-3770/src/expr.rs#L87

### input
```
fn main() {
    unsafe { a(value) }
        && !unsafe { b(value) }
        && !unsafe { c(value) }
}
```

### output dbg! info
```
[src/expr.rs:87] &lhs = expr(4294967040: &&!unsafe { b(value) })
[src/expr.rs:88] context.snippet(lhs.span) = "&& !unsafe { b(value) }"
```

**Comment by rchaser53** [comment]
I submitted the issue(#64093) and got the answer. The first formatted code seems to be correct. I didn't know that but rustc parser second expression as &&bool.

```
/* rustc parse like below */
unsafe { sys::mrb_sys_value_is_false(value) }  // bool
&& !unsafe { sys::mrb_sys_value_is_true(value) } // &&bool
&& !unsafe { sys::mrb_sys_value_is_nil(value) }  // bool
```

**Comment by topecongiro** [comment]
@rchaser53 Thank you for examining the issue! Looks like this is a limitation of the rustc parser and nothing can be done from rustfmt side.
