### ISSUE TITLE
rustfmt can't treat try_blocks.

### ISSUE THREAD

**Issue by HiraokaTakuya** [rust-lang/rustfmt#3778]
I use rustfmt 1.4.6-nightly (f800ce4 2019-08-28).
The source code is as follows.
```
#![feature(try_blocks)]
fn main() {
    let i: Result<i32, std::num::ParseIntError> = try { "1".parse::<i32>()? + "2".parse::<i32>()? };
println!("{:?}", i);
}
```
An error occurs.
```
error: expected identifier, found `"1"`
 --> /path/to/project/src/main.rs:3:57
  |
3 |     let i: Result<i32, std::num::ParseIntError> = try { "1".parse::<i32>()? + "2".parse::<i32>()? };
  |                                                   ---   ^^^ expected identifier
  |                                                   |
  |                                                   while parsing this struct
```

**Comment by topecongiro** [comment]
We need to use edition 2018 to enable `try_blocks`, but the default edition for rustfmt 1.X is 2015. If you are invoking `cargo fmt` inside a project using edition 2018, rustfmt should automatically detect it. If you are calling rustfmt directly, then you need to explicitly pass `--edition 2018` to rustfmt. E.g., 

```
rustfmt --edition 2018 main.rs
```

**Comment by HiraokaTakuya** [comment]
Thank you very much!
I understood `--edition 2018` and the difference between `cargo fmt main.rs` and `rustfmt main.rs`.
