### ISSUE TITLE
gracefully handle recoverable parser errors in ignored files

### ISSUE THREAD

**Issue by calebcartwright** [rust-lang/rustfmt#3779]
Refs https://github.com/rust-lang/rustfmt/pull/3777#issuecomment-528326806

**Comment by calebcartwright** [comment]
AFACIT, when there's a parser error in the main file, we hit the `Err(ErrorKind::ParseError)` arm (line 91) after calling `parse_crate` and don't even make it down to the `ModResolver` in such a scenario:
https://github.com/rust-lang/rustfmt/blob/1ded995ee79c44069b7832e5aba00162fc2113fa/src/formatting.rs#L82-L92


This is the case for the error we are seeing with the ice file in #3777. 

If I've got that right, then I see a couple options (let me know if there are others/better ones!):

1. Don't attempt to parse the input at all in `format_project` if the `main_file` is a match in the `ignore_path_set`. This could be done conditionally, such as only applying if the `main_file` is under `tests/` subdirectories and/or only if a new flag for `rustfmt` is provided (basically a Config setting that when enabled would make this check more of an OR than an AND)
https://github.com/rust-lang/rustfmt/blob/1ded995ee79c44069b7832e5aba00162fc2113fa/src/formatting.rs#L73-L75
2. Update the `Err(ErrorKind::ParseError)` arm (line 91) on the `parse_crate` to behave differently if the parse error came from a file that's a match in the `ignore_path_set`. Perhaps something like 
```rust
        // Surface parse error via Session (errors are merged there from report)
        Err(ErrorKind::ParseError) => {
            if ignore_path_set.is_match(&main_file) {
                return Ok(FormatReport::new());
            }
            return Ok(report)
        },
```

Between those two options, I think I'm inclined to go with option **1**, perhaps changing
https://github.com/rust-lang/rustfmt/blob/1ded995ee79c44069b7832e5aba00162fc2113fa/src/formatting.rs#L73-L75

to 
```rust
   // new config setting do_not_parse_ignore_matches
    if ignore_path_set.is_match(&main_file)
        && (config.skip_children() || config.do_not_parse_ignore_matches())
    {
        return Ok(FormatReport::new());
    }
```

**Comment by topecongiro** [comment]
Thank you for delving into this issue!

> when there's a parser error in the main file, we hit the Err(ErrorKind::ParseError) arm (line 91) after calling parse_crate and don't even make it down to the ModResolver in such a scenario

I think that you are right here.

I personally prefer the option 2, as that way we can avoid adding a new config option. If we go that route, we may also need to wrap `parse_crate` with `catch_unwind` as the rustc parser sometimes dies with panic on certain parse errors 🤷‍♂

**Comment by calebcartwright** [comment]
I've got option 2 working, and getting the desired zero exit code. There is already a `catch_unwind` within `parse_crate`:
https://github.com/rust-lang/rustfmt/blob/1ded995ee79c44069b7832e5aba00162fc2113fa/src/formatting.rs#L660
However, the parse error is still displaying on the terminal. Is that still the desired behavior? 

I suppose if we wanted to suppress we could use [panic::set_hook](https://doc.rust-lang.org/beta/std/panic/fn.set_hook.html) with a no op closure, or would wrapping the call to `parse_crate` supress that too?

**Comment by topecongiro** [comment]
> There is already a catch_unwind within parse_crate:

Great! Thank you for checking.

> However, the parse error is still displaying on the terminal. Is that still the desired behavior?

It would be better if we could not display the parser error from files that are specified in `ignore`. IIRC the code which displays parser errors is this:

https://github.com/rust-lang/rustfmt/blob/1ded995ee79c44069b7832e5aba00162fc2113fa/src/formatting.rs#L671

We can suppress these error messages by explicitly canceling it. rustfmt already does this when parsing macro arguments from the token stream:

https://github.com/rust-lang/rustfmt/blob/1ded995ee79c44069b7832e5aba00162fc2113fa/src/macros.rs#L108-L109

I think we can do the same thing here against errors from files that matches the ignore pattern.

**Comment by calebcartwright** [comment]
> IIRC the code which displays parser errors is this:

At least on my machine, the error is being printed to the console directly from that `catch_unwind` line. When I first started looking for the source I started on line 671 too, but it was already printed before that point.

I'll take another look at it though 👍

**Comment by topecongiro** [comment]
> At least on my machine, the error is being printed to the console directly from that catch_unwind line.

Ok, now I recall it correctly :smile: 
The rustc parser handles an error by either returning `Err` or panicking (sigh). Which is used depends on the kind of syntax error and we cannot tell beforehand. https://github.com/rust-lang/rustfmt/issues/3779#issuecomment-528658048 handles the former, and the `catch_unwind` implicitly handles the latter.

E.g, the parser will return `Err` against this snippet:

```rust
abc
```

but panics against this snippet:

```rust
fn main() {
    1x;
}
```

So if we want to completely silence the parser error against the skipped main file, we need to do both adding `panic::set_hook` and https://github.com/rust-lang/rustfmt/issues/3779#issuecomment-528658048.

**Comment by calebcartwright** [comment]
This one is turning out to be more involved than I'd originally thought 😄 

I tried `panic::set_hook` no avail, but that lead me to take a closer look at the emitter being used for the parse session. 

It now has me wondering if we could just set the emitter to `silent_emitter()` if the file is an ignore_set_match. I tested it out locally and works like I'd hoped. Any concerns with that?
