### ISSUE TITLE
wrap_comments breaks links with long URL

### ISSUE THREAD

**Issue by AlephAlpha** [rust-lang/rustfmt#3787]
With `wrap_comments = true`, the following code:

```rust
//! * [This is a link with a very loooooooooooooooooooooooooooooooooooooooooong URL.](https://example.com/This/is/a/link/with/a/very/loooooooooooooooooooooooooooooooooooooooooong/URL)
fn main() {
    println!("Hello, world!");
}
```

will be formatted as:

```rust
//! 
//! * [This is a link with a very loooooooooooooooooooooooooooooooooooooooooong
//!   URL.](https://example.com/This/is/a/link/with/a/very/
//!   loooooooooooooooooooooooooooooooooooooooooong/URL)
fn main() {
    println!("Hello, world!");
}
```

The URL is broken into two lines.

It seems that this only happens in lists.

**Comment by Juici** [comment]
This is still an issue.

When running `rustfmt` with `wrap_comments = true`, markdown links get chopped in half thus breaking them.

Version information:
```
rustfmt 1.4.11-nightly (1838235 2019-12-03)
rustc 1.42.0-nightly (859764425 2020-01-07)
cargo 1.42.0-nightly (6e1ca924a 2020-01-06)
rustup 1.21.1 (7832b2ebe 2019-12-20)
```

<details>
	<summary>Contents of rustfmt.toml</summary>
	<pre>
		max_width = 100
		hard_tabs = false
		tab_spaces = 4
		wrap_comments = true
		comment_width = 80
		normalize_comments = true
		merge_imports = false
		reorder_imports = true
		reorder_modules = true
		reorder_impl_items = true
		trailing_semicolon = true
		trailing_comma = "Vertical"
		match_block_trailing_comma = false
		blank_lines_upper_bound = 1
		blank_lines_lower_bound = 0
		merge_derives = true
		use_try_shorthand = true
		unstable_features = true
		edition = "2018"
	</pre>
</details>

Contents of `rustfmt.toml` relating to comments:
```toml
max_width = 100
wrap_comments = true
comment_width = 80
normalize_comments = true
unstable_features = true

edition = "2018"
```

Output with `--check` flag:
```diff
     /// Bots as well as users with the permission [`MANAGE_MESSAGES`] or
     /// [`MANAGE_CHANNEL`], are unaffected.
     ///
-    /// [`MANAGE_MESSAGES`]: ../permissions/struct.Permissions.html#associatedconstant.MANAGE_MESSAGES
-    /// [`MANAGE_CHANNEL`]: ../permissions/struct.Permissions.html#associatedconstant.MANAGE_CHANNEL
+    /// [`MANAGE_MESSAGES`]:
+    /// ../permissions/struct.Permissions.html#associatedconstant.
+    /// MANAGE_MESSAGES [`MANAGE_CHANNEL`]:
+    /// ../permissions/struct.Permissions.html#associatedconstant.MANAGE_CHANNEL
     #[serde(default, rename = "rate_limit_per_user")]
     pub rate_limit: u16,
     /// The ID of the parent category of the channel.
```
