### ISSUE TITLE
Trailing comments break subsequent comments

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rustfmt#3792]
I have a rustfmt.toml like this:

```toml
max_width = 79
comment_width = 79
error_on_line_overflow = true
```

and a line like this:

```rust
pub const IFF_MULTICAST: ::c_int = 0x0000000800; // Supports multicast
// Multicast using broadcst. add.
```

gets incorrectly formatted into a line like this

```rust
pub const IFF_MULTICAST: ::c_int = 0x0000000800; // Supports multicast
                                                 // Multicast using broadcst. add.
```

notice that the  comment is incorrectly wrapped to the right, and that as a consequence the 79 character limit is not satisfied after formatting, such that a subsequent `rustfmt --check` fails.

**Comment by scampi** [comment]
Related to #2996
