### ISSUE TITLE
Consider omitting trailing commas in function calls of one argument

### ISSUE THREAD

**Issue by wchargin** [rust-lang/rustfmt#3796]
Builder patterns are common in Rust’s standard library and ecosystem.
Here are a few real (adapted) examples, with current `rustfmt` output
(version 1.3.0-stable):

```rust
fn main() {
    let new_commit_oid = try_invoke_git(
        Command::new("git")
            .args(&["commit-tree", &tree, "-p", "HEAD"])
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .env("GIT_CONFIG_NOSYSTEM", "1"),
    );
    let app = clap::App::new("my_app").arg(
        Arg::with_name("verbose")
            .long("verbose")
            .help("Print more stuff"),
    );
    let data = parse_event_files(
        WalkDir::new(logdir)
            .follow_links(true)
            .same_file_system(true)
            .max_depth(10),
    );
}
```

Unfortunately, in all these cases the trailing comma is actively
unhelpful. The common modification pattern for such builders is not
adding an additional argument to the enclosing function call, but rather
additional mutations to the builder: like `.stderr(Stdio::piped())` to
`Command`, or `.short("v")` to `Arg`, or `.contents_first(true)` to
`WalkDir`. In such a case, one must **remove** the trailing comma
inserted by `rustfmt` before adding the desired change, and of course
`rustfmt` will insert a new trailing comma after that.

I’m a big advocate for trailing commas when they make sense, which is
most of the time—but the friction here is notable. Perhaps `rustfmt`
could accommodate this pattern by omitting trailing commas in function
calls of one argument. Python’s `black` is quite similar to `rustfmt` in
both spirit and output, and it follows this guideline (as of v19.3);
[here’s an example.][black]

I will be happy to contribute this change if it would be entertained.

(#3166 is related, but this is a feature request for a general pattern.)

[black]: https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AJbAPddAD2IimZxl1OAqkiw1qdEcpHC4ihMnPt7cMGTrxqhX-j7eT7JQUe2xsoFoJXjEzcX8q3hxUn-g7HCTlzyuDwE8DylzwUOthSuFY2FO6qrnvtLVE9yd0UaJbEJrz534R-ErnMEBGKnOtJH14G2frN3C8VX4MxFs_bqspfB9brq8MLM3O8EcstZy0dml3DgnCP5Zhd7sHOdiULQrz0Gd19d49clzWCcwrzZl8Jh56jgjJLz9MsbeEzblz2XqrrN_oes9QO6__VBJ4xd2nvfTfq0wgW02C1hqvRkTGggfs4FJz9LXT1zdorYYFMreXfQhJp6hnYt9qMOsQAAALhkJBMs5l4gAAGTAtwEAACtTexJscRn-wIAAAAABFla

**Comment by topecongiro** [comment]
Thank you for creating a feature request to rustfmt! I am sorry to say, however, that we are unlikely to accept this feature. One of the core design principles of rustfmt is consistency, and I feel that this feature does not have enough benefit to break it.

> one must remove the trailing comma
inserted by rustfmt before adding the desired change

Concerning a builder pattern, I think that we can just add a new element in the middle of the method chain, instead of appending it. That way the trailing comma should not bother you.

On a side note, it seems to me that the current behavior of `black` is just bugged, see https://github.com/psf/black/pull/826 or https://github.com/psf/black/issues/493.

**Comment by wchargin** [comment]
Okay, understandable. Thank you for your quick reply! Adding calls to
the middle of the chain of course isn’t ideal, but maybe it’s all right.

Thanks also for the references to Black’s behavior; that’s great to
know! :-)

**Comment by sweihub** [comment]
Hi, I am looking the solution, any way to disable the trailing comma inside function call? It bothers me much.
```rust
fn on_rsp_user_login(
    &mut self,
    pRspUserLogin: *mut CThostFtdcRspUserLoginField,
    pRspInfo: *mut CThostFtdcRspInfoField,
    nRequestID: ::std::os::raw::c_int,
    bIsLast: bool,     <==== HERE, I DON'T WHAT THIS COMMA!
) {
    debug!("user login");
    self.tx.send(Event::UserLogin).unwrap();
}
```

**Comment by ytmimi** [comment]
@sweihub you can try setting `trailing_comma=Never`, however this will remove all trailing commas.

```rust
fn on_rsp_user_login(
    &mut self,
    pRspUserLogin: *mut CThostFtdcRspUserLoginField,
    pRspInfo: *mut CThostFtdcRspInfoField,
    nRequestID: ::std::os::raw::c_int,
    bIsLast: bool
) {
    debug!("user login");
    self.tx.send(Event::UserLogin).unwrap();
}
```

**Comment by sweihub** [comment]
@ytmimi Hi, thanks for your suggestion, unfortunately, it dose't work at all, and I'm using the nightly build already.

The `trailing_comma` in document
https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#trailing_comma

```trailing_comma``` is a misleading name, it says ```How to handle trailing commas for lists```

**Comment by ytmimi** [comment]
@sweihub `trailing_comma=Never` should do what you're looking for. run `rustfmt --config=trailing_comma=Never  path/to/file.rs`. or add `trailing_comma = "Never"` to your project's `rustfmt.toml`.

The examples listed in the docs use functions. Perhaps the docs need some clarification, but `How to handle trailing commas for lists` refferes to any general list of items. In this case, the list of function parameters.

If you'd like to continue the discussion I think opening a new issue would be best.
