### ISSUE TITLE
macro fails to be wrapped if it is exactly one character beyond max_width

### ISSUE THREAD

**Issue by AaronKutch** [rust-lang/rustfmt#3805]
```
macro_rules! test {
    ($asdfghj:expr, $qwertyuiop:expr, $zxcvbnmasdfghjkl:expr, $aeiouaeiouaeiou:expr, $add:expr) => {{
        return;
    }};
}
```
Using rustfmt 1.4.8 nightly with a `.rustfmt.toml` with the following:
```
unstable_features = true
error_on_line_overflow = true
error_on_unformatted = true
#format_macro_matchers = true
```
If this is manually formatted, overflow will not happen. However, if the `format_macro_matchers = true` line is uncommented, the line will always be reformatted to overflow until another character is added.

**Comment by ytmimi** [comment]
Confirming I can reproduce the issue with `rustfmt 1.5.1-nightly (f2c31ba0 2022-07-19)`. rustfmt does not format the given input when `format_macro_matchers` is `true` even though it exceeds the `max_width` of 100.

**input** (length of the macro matcher line including indentation is 101)
```rust
macro_rules! test {
    ($asdfghj:expr, $qwertyuiop:expr, $zxcvbnmasdfghjkl:expr, $aeiouaeiouaeiou:expr, $add:expr) => {{
        return;
    }};
}
```

**output** `format_macro_matchers=true` (lunchanged)
```rust
macro_rules! test {  
    ($asdfghj:expr, $qwertyuiop:expr, $zxcvbnmasdfghjkl:expr, $aeiouaeiouaeiou:expr, $add:expr) => {{
        return;
    }};
}
```

<hr>

When the macro_matcher is 102 characters long, then it wraps.  I assume we're not taking the length of the 2nd `{` into account.

**input** (length of the macro matcher line including indentation is 102)
```rust
macro_rules! test {
    ($aasdfghj:expr, $qwertyuiop:expr, $zxcvbnmasdfghjkl:expr, $aeiouaeiouaeiou:expr, $add:expr) => {{
        return;
    }};
}
```

**output** `format_macro_matchers=true` (wrapped)
```rust
macro_rules! test {
    (
        $aasdfghj:expr, $qwertyuiop:expr, $zxcvbnmasdfghjkl:expr, $aeiouaeiouaeiou:expr, $add:expr
    ) => {{
        return;
    }};
}
```

For anyone who wants to take a look at this I'd start in `format_macro_args`, and then move on to `wrap_macro_args`

https://github.com/rust-lang/rustfmt/blob/f2c31ba04db6bf07c140c86bfbe2cb16f1b83a8e/src/macros.rs#L966-L987

Linking the `format_macro_matchers` tracking issue #3354

**Comment by davidBar-On** [comment]
Submitted PR #5582 with a suggested fix.
