### ISSUE TITLE
Enormous bug

### ISSUE THREAD

**Issue by RuralDependencies** [rust-lang/rustfmt#3806]
Apparently, we can't post any basic 3D ASCII titles on top of documents... 

Example 

`
______________________ ____________________
\__    ___/\_   _____//   _____/\__    ___/
  |    |    |    __)_ \_____  \   |    |   
  |    |    |        \/        \  |    |   
  |____|   /_______  /_______  /  |____|   
                   \/        \/            
`

I think an emergency fix is required, hope somebody can fork immediately rustfmt

**Comment by rchaser53** [comment]
Could you give us the minimum reproduction in Rust Playground?
link: https://play.rust-lang.org/

**Comment by RuralDependencies** [comment]
I can't i'm still shaking out of rage :(

**Comment by topecongiro** [comment]
Please feel free to reopen the issue once you have a mcve.
