### ISSUE TITLE
merge_imports will incorrectly format imports with `self`

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rustfmt#3808]
```
$ cat /tmp/test.rs 
use foo::{self};
$ rustfmt /tmp/test.rs --emit=stdout --config-path rustfmt.toml
/tmp/test.rs:

use foo::self;
```

The newly formatted code cannot compile because Rust requires `self` to appear within `{}`. Related: https://github.com/rust-lang/rustfmt/issues/3807.

**Comment by calebcartwright** [comment]
Yup, indeed a bug. Will open a PR with a fix shortly
