### ISSUE TITLE
Request: Configure how/when "fluent" call chains are chopped down.

### ISSUE THREAD

**Issue by ragnese** [rust-lang/rustfmt#3812]
I prefer that fluent call chains are aggressively chopped down. I.e., I never want to see this:

```
foo().bar().baz().a();
```

I would always rather see:

```
foo()  
  .bar()  
  .baz()  
  .a();
```

Or at least:

```
foo().bar()  
     .baz()  
     .a();
```

Thank you!

**Comment by calebcartwright** [comment]
Related #2263, #3693

**Comment by calebcartwright** [comment]
Closing as a duplicate
