### ISSUE TITLE
Rustfmt indents single-line comments weirdly

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rustfmt#3826]
Using `rustfmt 1.4.8-nightly (afb1ee1c 2019-09-08)`.

It indents such single-line comments weirdly (one tab and one space more indented):

![image](https://user-images.githubusercontent.com/535593/66127088-37567900-e5eb-11e9-9bdb-03b187ecf16c.png)

When I remove `// foo`, it indents them normally. But it should also indent them normally with `// foo` present!

**Comment by calebcartwright** [comment]
Sounds similar/related to #3792

**Comment by scampi** [comment]
Can you share a code snippet of your problem to ensure the PR fixes your issue ? The screenshot does not really show the context of `self.sort()`.

> It indents such single-line comments weirdly (one tab and one space more indented):

In addition, this sounds like there may be some additional problem compared to #3792 .

**Comment by Boscop** [comment]
@scampi `self.sort();` is the first line of the body of a method. Btw, I'm using `hard_tabs = true` and it didn't even align the lower single line comments with the one on the `sort()` line (as it did for the other examples that used spaces as indentation).

**Comment by scampi** [comment]
I created a snippet and it gets reformatted strangely. Hard tabs are not properly handled.

# Config

```
hard_tabs=true
version="Two"
```

# Snippet

```rust
impl Foo {
    fn foo() {
        bar(); // comment 1
        // comment 2
        // comment 3
        baz();
    }
}
```

# Rustfmt Output

```diff
 impl Foo {
-    fn foo() {
-        bar(); // comment 1
-        // comment 2
-        // comment 3
-        baz();
-    }
+	fn foo() {
+		bar(); // comment 1
+  // comment 2
+  // comment 3
+		baz();
+	}
 }
```
