### ISSUE TITLE
rustfmt strips `r#` (raw identifier prefix)

### ISSUE THREAD

**Issue by epage** [rust-lang/rustfmt#3837]
Copy
```rust
pub(crate) static r#break: &'statci str = "foo";
```
into https://play.rust-lang.org/ and you get
```rust
pub(crate) static break: &'statci str = "foo";
```

I ran into this with rustfmt 1.4.4-stable (0462008 2019-08-06)

Playground is using 1.4.8-nightly (2019-09-08)

**Comment by calebcartwright** [comment]
Confirmed bug. Will open a PR shortly support for raw identifier prefix in statics.
