### ISSUE TITLE
Rustfmt deletes multiline comment in struct definition

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rustfmt#3839]
before:
```rust
struct Foo {
	a: i32,
/*
asd
*/
	// sdf
	b: i32,
}
```

after:
```rust
struct Foo {
	a: i32,
	b: i32,
}
```

Please fix this! I lost some comments from this after running rustfmt on my whole workspace, and only noticed this behavior now, many commits later!

It seems to happen if a single-line comment after the multi-line comment is present.

**Comment by calebcartwright** [comment]
I'll take a look into this one

**Comment by calebcartwright** [comment]
Believe I've found the problem, will open a PR with a fix later tonight or tomorrow
