### ISSUE TITLE
Extra comma is inserted before line comment in type parameters.

### ISSUE THREAD

**Issue by bddap** [rust-lang/rustfmt#3843]
Given the input:

```rust
type T = Result<
    u32 // Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ornare
        // diam ac cursus. Aliquam condimentum in erat quis pretium. Curabitur
        // accumsan urna. Cras volutpat sit amet quam.
        ,
    bool,
>;
```

the following invalid output is generated:

```rust
type T = Result<
    u32, // Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ornare
         // diam ac cursus. Aliquam condimentum in erat quis pretium. Curabitur
         // accumsan urna. Cras volutpat sit amet quam.
         ,
    bool,
>;
```

**Comment by calebcartwright** [comment]
hi @bddap, what version of `rustfmt` are you using? I'm admittedly using the latest from the master branch, but the output I'm getting from the input you've provided is:
```rust
type T = Result<
    u32, // Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ornare
         // diam ac cursus. Aliquam condimentum in erat quis pretium. Curabitur
         // accumsan urna. Cras volutpat sit amet quam.
    bool,
>;
```

**Comment by bddap** [comment]
@calebcartwright I was using an older version. Don't remember which.

Looks like the problem is fixed in `rustfmt 1.4.4-stable (0462008d 2019-08-06)`.

**Comment by bddap** [comment]
Would this be a good unit test?

**Comment by calebcartwright** [comment]
> @calebcartwright I was using an older version. Don't remember which.

> Looks like the problem is fixed in rustfmt 1.4.4-stable (0462008d 2019-08-06).

Excellent!

> Would this be a good unit test?

I'm not sure I follow, what'd you have in mind?

**Comment by bddap** [comment]
I imagine a test for this would look something like:

```rust
// regression test for https://github.com/rust-lang/rustfmt/issues/3843
#[test]
fn extra_comma_not_added() {
    let src = r#"
        type T = Result<
            u32 // Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ornare
                // diam ac cursus. Aliquam condimentum in erat quis pretium. Curabitur
                // accumsan urna. Cras volutpat sit amet quam.
                ,
            bool,
        >;
    "#;
    let fmted = fmt(src).unwrap();
    syn::parse_file(&fmted).expect("produced invalid output");
}
```

**Comment by calebcartwright** [comment]
Ah okay I understand your question now. Sure, or you could add a test file under `tests/source/..` with your original input, and then one under `tests/target/..` with the formatted output

**Comment by bddap** [comment]
Found https://github.com/rust-lang/rustfmt/issues/3847 while adding that test.

**Comment by calebcartwright** [comment]
> Found #3847 while adding that test.

Glad you decided to add that test! Otherwise we wouldn't have known about that 👍
