### ISSUE TITLE
--check does not obey the newlines settings in rustfmt.toml

### ISSUE THREAD

**Issue by Herschel** [rust-lang/rustfmt#3849]
If you have a file with CRLF newlines and `newline_style = "Unix"` in `rustfmt.toml` or vice versa, then `cargo fmt -- --check` does not output any diff or exit with an error code.

Running `cargo fmt` itself updates the line endings as desired. `--check` seems to obey other settings in `rustfmt.toml`.

Occurs on both rustfmt 1.4.8-nightly (2019-10-04) and rustfmt 1.4.4-stable.

**Comment by calebcartwright** [comment]
Yup, confirmed bug. I have a theory on what's causing this, will take a look later today.

**Comment by calebcartwright** [comment]
I've got a fix for this, though while working on it I believe I found another bug 🐛 Will open a PR soon
