### ISSUE TITLE
Incremental formatting

### ISSUE THREAD

**Issue by nrc** [rust-lang/rustfmt#385]
We should have a formatting mode where we take a date/time as an arg and only format files which have been modified after that date/time. In conjunction with a make file or cargo plugin, that would allow us to do incremental (at the file-level) re-formatting.

**Comment by kamalmarhubi** [comment]
Could the aims of this be achieved by formatting based on a diff?

**Comment by nrc** [comment]
It could. It is a bit less flexible since it requires a diff which means you need to be running version control. OTOH, it would be more precise and thus less code would get reformatted. It does seem a much harder problem to solve too, although obviously it is a nice thing to have in its own right.

**Comment by topecongiro** [comment]
Is this still a high priority?

**Comment by kamalmarhubi** [comment]
@topecongiro you may also be interested in #434, and the initial work (almost a year ago now :/) in #1007.

**Comment by nrc** [comment]
@topecongiro It is not high priority, I think, though I would still like to do it (it would be very helpful, but only for very large codebases). #434 is much more important because it is useful for IDE support.

**Comment by topecongiro** [comment]
@kamalmarhubi @nrc Thanks for comments! I will take a look at #434.
