### ISSUE TITLE
rustfmt fails when encountering comment (+ trailing whitespace)

### ISSUE THREAD

**Issue by lesurp** [rust-lang/rustfmt#3851]
```
⮞ cargo fmt --version
rustfmt 1.4.4-stable (0462008 2019-08-06)
```

# No trailing whitespace

```rust
fn main() {
    let a =
            // asasddasas 
    if true {
     1.0
    };
}
```

output: exact same (the `1.0` line is not indented

# With trailing whitespace:

Please note the trailing whitespace after the `let a= ` line

```rust
fn main() {
    let a = 
            // asasddasas 
    if true {
     1.0
    };
}
```

output:

```
 ⮞ cargo fmt
error[internal]: left behind trailing whitespace
 --> /tmp/foo/src/main.rs:2:2:11
  |
2 |     let a = 
  |            ^
  |

warning: rustfmt has failed to format. See previous 1 errors.
```

**Comment by calebcartwright** [comment]
Thanks for the report @lesurp. I forget which version of rustfmt contains the fix for this (I want to say 1.4.6 or 1.4.7), but it has already been fixed. 

If you try your snippet with the latest nightly version of rustfmt (1.4.9) you'll see the snippet correctly formatted without error
