### ISSUE TITLE
How to proceed rustfmt 2.0 release

### ISSUE THREAD

**Issue by topecongiro** [rust-lang/rustfmt#3852]
It has been more than a year since the release of the rustfmt 1.0, and it's high time to prepare for the next major version update :tada:

I am thinking of moving things forward in the following way. Any thoughts on improvement or questions?

After the next patch release (1.4.10), the master branch will be a development branch for the rustfmt 2.0.  We will accept PRs to the master branch only if they belong to the 2.0 milestone. We will **NOT** accept PRs that fixes minor bug fixes. If there are critical bugs that we need to fix as soon as possible (e.g., the breaking changes from the rustc internal that requires updating `rustc-ap-*` crates), then we will create a branch for the 1.4.11.

We will start with removing version gates and separating rustfmt into multiple crates.

**Comment by calebcartwright** [comment]
I had one question, 

> We will NOT accept PRs that fixes minor bug fixes. If there are critical bugs that we need to fix as soon as possible (e.g., the breaking changes from the rustc internal that requires updating rustc-ap-* crates), then we will create a branch for the 1.4.11.

How long will that be the case? Will minor/bug fix PRs not be accepted until the 2.0 refactoring of the codebase (like #1583 and #3841) is complete, or not until after 2.0 is released, etc.

**Comment by topecongiro** [comment]
> How long will that be the case? Will minor/bug fix PRs not be accepted until the 2.0 refactoring of the codebase (like #1583 and #3841) is complete, or not until after 2.0 is released, etc.

At first I thought that it would be ~1 month, but unfortunately, it turns out that I won't be able to devote much time on rustfmt in the next few months. As such, I will relax the restriction and accept any PRs to the master branch. Backporting to 1.4.z will not likely to happen, though.

**Comment by calebcartwright** [comment]
@topecongiro - do we have a means today within rustup to provide an opt-in version of the rustfmt 2.0 release candidate (once we are ready) on nightly, or will rustfmt on nightly immediately transition from rustfmt 1.4.15 to rustfmt 2.0 once we update the submod?

Just trying to think through the impact that'll occur once we have 2.0 ready, especially for those folks building on nightly and running rustfmt as part of their CI since there will be a lot of formatting changes.
