### ISSUE TITLE
rustfmt doesn't format block of `if let Some` if it contains multiline comment

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rustfmt#3853]
rustfmt doesn't format block of `if let Some` if it contains multiline comment:

Before:
```rust
			if let Some(ref /*mut*/ state) = foo {
					}
```
After: same as above

In this example, the first line is on its correct indentation level, but the 2nd line is not. Anything in the body won't get formatted! This also happens with `/*asd*/` or other multiline comments. If the first line is not on its correct indent level either, only that line gets indented. 
The behavior is the same, no matter on which indent level the 2nd line (or body) is.

**Comment by Boscop** [comment]
Similarly, this stays unformatted:
```rust
	Fooobar => {
		if let Some(e) =
				// self.foo.bar(e, tx)
				self.foo.bar(e)
			{
				// body
			}
	}
```

**Comment by calebcartwright** [comment]
I've got a fix for the first scenario, and I think I know what the problem is for the second but still working on it.

Will open a PR once I figure out that second one with fixes for both
