### ISSUE TITLE
Please provide special case for name=name in format

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/rustfmt#3861]
I'd like to avoid reformats like this:

```diff
-                v.push(new.paint(format!("{:nwidth$}: {:idwidth$}", i2 + offset, c2_short_id, nwidth=nwidth, idwidth=idwidth).as_bytes().to_owned()));
+                v.push(new.paint(format!("{:nwidth$}: {:idwidth$}", i2 + offset, c2_short_id, nwidth = nwidth, idwidth = idwidth).as_bytes().to_owned()));
```

Could we special-case `samename=samename` in the arguments of `format!`-like macros, and avoid adding spaces around the `=`?

**Comment by topecongiro** [comment]
This seems a bit too narrow to special-case in rustfmt.

**Comment by joshtriplett** [comment]
It ends up producing a lot of noise when you have a long list of `x=x, y=y, z=z` in a format-like call, and rustfmt already has special-case logic for format-like calls.

**Comment by joshtriplett** [comment]
Nevermind, I think https://github.com/rust-lang/rfcs/pull/2795 would fully address the cases where I find myself wanting this.
