### ISSUE TITLE
Where clauses

### ISSUE THREAD

**Issue by silvioprog** [rust-lang/rustfmt#3877]
Hi.

Many parts in the Rust documentation shows `where` clause in front the user type and preserves the left brace in the same line of the `fn` keyword, e.g:

```rust
impl<T> PrintInOption for T where
    Option<T>: Debug {
    fn print_in_option(self) {
        println!("{:?}", Some(self));
    }
}
```
however, when we format those codes using `rustfmt`, they looks like this:

```rust
impl<T> PrintInOption for T
where
    Option<T>: Debug,
{
    fn print_in_option(self) {
        println!("{:?}", Some(self));
    }
}
```

Another example. Before formatting:

```rust
impl <A, D> MyTrait<A, D> for YourType where
    A: TraitB + TraitC,
    D: TraitE + TraitF {}
```

After formatting:

```rust
impl<A, D> MyTrait<A, D> for YourType
where
    A: TraitB + TraitC,
    D: TraitE + TraitF,
{
}
```

Notice the `where` and braces (wrong?) indentation.

I'm not sure if it is by design, so I decided to report that.

Thank you!

P.S.: All code examples was extracted from the official Rust online documentation.

**Comment by calebcartwright** [comment]
thanks @silvioprog 

> extracted from the official Rust online documentation

Are you referring to the [Book](https://doc.rust-lang.org/book/)? If so, I believe that's because they aren't running `rustfmt` on all the code snippets and examples used there (https://github.com/rust-lang/book/issues/1690 https://github.com/rust-lang/book/issues/2008)

**Comment by topecongiro** [comment]
@silvioprog This is intentional. As @calebcartwright noted, all the rust code is not formatted by rustfmt yet. Thanks for the report!

**Comment by silvioprog** [comment]
Thanks guys. Up-vote for auto-formatting all documentation examples! :smiley: :+1:
