### ISSUE TITLE
Fix CI failures

### ISSUE THREAD

**Issue by topecongiro** [rust-lang/rustfmt#3885]
https://travis-ci.com/rust-lang/rustfmt `cargo install --path . --force` is failling due to picking up the latest crossbeam-channel which is apparently broken with the latest nightly.

Possibly related: https://github.com/rust-lang/cargo/issues/7169.

**Comment by calebcartwright** [comment]
https://github.com/crossbeam-rs/crossbeam/issues/435 - looks like they've already fixed `crossbeam-channel` but have't released the new version yet

**Comment by topecongiro** [comment]
Yes, it looks like `cargo` has changed its behavior when passed `install --path` and ignores the Cargo.lock file. I added `--locked` in the script in #3889 to force `cargo` to use the dependencies specified in the Cargo.lock.

**Comment by calebcartwright** [comment]
Looks like a new 0.4.0 version of `crossbeam-channel` and a 0.7.0 version of `crossbeam-utils` have been published with the fix. Would it be worth updating the lockfile with these new versions?

**Comment by topecongiro** [comment]
Yes!

**Comment by calebcartwright** [comment]
Will open a PR in a bit with those bumps

**Comment by calebcartwright** [comment]
Unfortunately it seems that `ignore` is [pinned on](https://github.com/BurntSushi/ripgrep/blob/master/ignore/Cargo.toml#L21) `crossbeam-channel`  v0.3.6 which in turn has a ^v0.6.5 dependency on `crossbeam-utils`, basically preventing updating either. 

I'll follow up with an issue over in `ignore`
