### ISSUE TITLE
Add `--check` command-line flag to `cargo-fmt`

### ISSUE THREAD

**Issue by topecongiro** [rust-lang/rustfmt#3888]
cc @calebcartwright

**Comment by calebcartwright** [comment]
👍 - will open a PR for this later today. BTW should we target PRs to merge into master now that 1.4.10 has been release or still target the rustfmt-2.0 branch?

**Comment by topecongiro** [comment]
Thanks!

> BTW should we target PRs to merge into master now that 1.4.10 has been release or still target the rustfmt-2.0 branch?

We can target PRs against the master branch. I will mention this in the tracking issue.
