### ISSUE TITLE
rustfmt error -32603

### ISSUE THREAD

**Issue by samuela** [rust-lang/rustfmt#3899]
I'm getting this error when attempting to run rustfmt via VSCode:
```
[Error - 5:28:35 PM] Request textDocument/formatting failed.
  Message: Reformat failed to complete successfully
  Code: -32603 
```
Anyone know what this means and how it can be resolved?

**Comment by calebcartwright** [comment]
Are you using the RLS extension to run rustfmt, or one of the other VS Code extensions that provide formatting?

What happens when you run `rustfmt` or `cargo fmt` directly against the same repo/files?

**Comment by samuela** [comment]
> Are you using the RLS extension to run rustfmt, or one of the other VS Code extensions that provide formatting?

I believe I'm using RLS... This is via the "Format Document" command and I have the "rust-lang" extension installed.

> What happens when you run rustfmt or cargo fmt directly against the same repo/files?

On the command line I'm getting errors
```
busybox 🔥 cargo fmt miscutils/bc.rs
error: 'cargo-fmt' is not installed for the toolchain 'nightly-2019-10-04-x86_64-apple-darwin'
To install, run `rustup component add rustfmt --toolchain nightly-2019-10-04-x86_64-apple-darwin`
busybox 🔥 rustup toolchain list
stable-x86_64-apple-darwin (default)
nightly-2019-10-04-x86_64-apple-darwin
```
which is odd since stable is the default config... Also certain files in the project format just fine, others do not. Unclear what the difference is between them. Or why VSCode RLS is doing something different from `cargo fmt`.

**Comment by calebcartwright** [comment]
Thanks @samuela!
 
> I believe I'm using RLS... This is via the "Format Document" command and I have the "rust-lang" extension installed.

If you're referring to/using https://marketplace.visualstudio.com/items?itemName=rust-lang.rust then you are indeed. 

> On the command line I'm getting errors

Try:
`cargo fmt -- miscutils/bc.rs --check`
or
`rustfmt miscutils/bc.rs --check`

**Comment by calebcartwright** [comment]
> Or why VSCode RLS is doing something different from cargo fmt

RLS is one of the few (perhaps the only?) consumers of `rustfmt` as a lib, so it's RLS surfacing up that error code in the VS Code window based on whatever errors it is running into trying to format (that error code is not coming directly from rustfmt)

**Comment by samuela** [comment]
> RLS is one of the few (perhaps the only?) consumers of rustfmt as a lib, so it's RLS surfacing up that error code in the VS Code window based on whatever errors it is running into trying to format (that error code is not coming directly from rustfmt)

Ah, I see. That's a confusing setup.

> Try:
cargo fmt -- miscutils/bc.rs --check
or
rustfmt miscutils/bc.rs --check

This runs me into the same 
```
error: 'cargo-fmt' is not installed for the toolchain 'nightly-2019-10-04-x86_64-apple-darwin'
To install, run `rustup component add rustfmt --toolchain nightly-2019-10-04-x86_64-apple-darwin`
```
errors as before which is puzzling considering I should be on stable according to rustup. But anyways, went ahead and installed, ran `cargo fmt -- miscutils/bc.rs --check` and that works fine, although it takes a little while since the file is quite large. Perhaps RLS is timing out?

**Comment by samuela** [comment]
Turns out that c2rust had created a `rust-toolchain` file that seems to be telling cargo to use `nightly-2019-10-04-x86_64-apple-darwin`, so that's one mystery solved.

**Comment by calebcartwright** [comment]
> Turns out that c2rust had created a `rust-toolchain` file that seems to be telling cargo to use `nightly-2019-10-04-x86_64-apple-darwin`, so that's one mystery solved.

That makes sense, thanks for sharing! Presumably that was a likely candidate for the underlying error that RLS was seeing and bubbling up with the error code you were seeing. 

Are you still seeing the same error in VS Code after installing the rustfmt component for the target toolchain (and probably a good idea to restart VS Code or restart the RLS within VS Code if you didn't already)?

If you are, I think you may want to ask over in https://github.com/rust-lang/rls-vscode as the error does not appear to be directly associated with rustfmt

**Comment by samuela** [comment]
Sounds good, I'll go ahead and close this and reopen an issue on rls-vscode if it strikes again. Thanks!
