### ISSUE TITLE
Error writing files: io error: Failed to find module

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rustfmt#3901]
I have two source files:

#### src/lib.rs

```rust
#[path = "."]
pub mod a {
    pub mod b;
}
```

#### src/b.rs

```rust
// (empty file)
```

<br>

`cargo check` seems to be fine with this layout, and the code compiles. But `cargo fmt` fails with:

```console
Error writing files: io error: Failed to find module b in "." None
```

**Comment by josephlr** [comment]
I've also hit this issue. It seems like rustfmt does not like path-renamed modules.

**Comment by nocker01** [comment]
Hi, I think I'm still experiencing this issue.  I'm new to Rust...

I am using relative paths to access different modules.  My project compiles fine but "cargo fmt" does not work for me.  I'm using Windows 7 and have switched to a nightly build of rustup:
rustup 1.22.1 (b01adbbc3 2020-07-08)
nightly-i686-pc-windows-gnu

Previously when I ran the command "cargo fmt" I would get the error that is the subject of this thread.  I now when I run it I get the following error:
error: couldn't read \\?\C:\projects\application\main\..\common\debug.rs: The filename, directory name, or volume label syntax is incorrect. (os error 123)
Error writing files: failed to resolve mod `debug`: \\?\C:\projects\application\main\..\common\debug.rs does not exist

This does tell me more clearly the path that could not be found but the file is definately in the directory:
C:\projects\application\common\debug.rs
