### ISSUE TITLE
error[internal]: left behind trailing whitespace

### ISSUE THREAD

**Issue by samuela** [rust-lang/rustfmt#3904]
I'm trying to format a module and rustfmt is failing with
```
error[internal]: left behind trailing whitespace
     --> /rustybox/shell/ash.rs:13759:13759:0
      |
13759 |
      | ^^
      |

warning: rustfmt has failed to format. See previous 1 errors.
```

Here's the source file: [ash.rs.zip](https://github.com/rust-lang/rustfmt/files/3806503/ash.rs.zip)

**Comment by calebcartwright** [comment]
Hey @samuela - What version of rustfmt are you using?

**Comment by samuela** [comment]
Switching the comment from `/* */` to `// ...` seems to have resolved it.

**Comment by samuela** [comment]
@calebcartwright 

I'm running on the command line with
```
root@58f110f80b00:/rustybox# cargo fmt --version
rustfmt 1.4.9-nightly (33e3667 2019-10-07)
```

**Comment by samuela** [comment]
I have what seems to be a similar situation with this bit of code:
```rust
  checkkwd = (0x2i32 | 0x1i32) as smallint; /* unrecognized "\z": print both chars unless ' or " */
                                            
  rpp = rpp2;
```
where rustfmt is adamant that there must be a bunch of spaces on the second line in order to match up with the beginning `/` in the comment. Strangely `cargo fmt` doesn't throw an error in this case.`

**Comment by calebcartwright** [comment]
Thanks. I ask as there's been quite a few of various `trailing whitespace` errors fixed over the last few releases. Let me see if I can reproduce with the latest on master

**Comment by samuela** [comment]
Sounds good, thanks for taking a look!

**Comment by calebcartwright** [comment]
> Strangely cargo fmt doesn't throw an error in this case.

👀 That sounds really odd. `cargo fmt` basically just detects workspace info (edition, packge source file root, etc.) which it passes as args to `rustfmt`, but it's always `rustfmt` that's running

**Comment by samuela** [comment]
@calebcartwright Yeah, also thought it was kinda strange. Happy to provide the complete file for this case as well if you'd like.

**Comment by calebcartwright** [comment]
nearly 16k lines! That looks fun 😄 

I'm still getting the whitespace error with 1.4.10 (as well as a few `line formatted, but exceeded maximum width` errors). As far as the whitespace error, do you have a minimal reproducible example from the file you shared? That'd make it a bit easier for someone to work on a fix

**Comment by calebcartwright** [comment]
I think you may want to open separate issues for the two other items you've noted above, and keep this issue focused on the trailing white space issue
