### ISSUE TITLE
use_try_shorthand causes continuous indentation

### ISSUE THREAD

**Issue by vallentin** [rust-lang/rustfmt#3908]
I've encountered a case where code inside a macro is continuously indented, if method chains are separated by comments and `use_try_shorthand` is used. The code is continuously indented until `max_width`.

It doesn't happen inside functions.

**rustfmt.toml:**

```toml
use_try_shorthand = true
```

**Original Code:**

```rust
macro_rules! foo {
    () => {
        bar()
            // Baz
            .expect("Qux");
    };
}
```

**Formatted Once**

```rust

macro_rules! foo {
    () => {
        bar()
                // Baz
                .expect("Qux");
    };
}
```

**Formatted Twice:**

```rust
macro_rules! foo {
    () => {
        bar()
                        // Baz
                        .expect("Qux");
    };
}
```

**Formatted Thrice:**

```rust
macro_rules! foo {
    () => {
        bar()
                                // Baz
                                .expect("Qux");
    };
}
```

---

rustfmt 1.4.8-stable (afb1ee1c 2019-09-08)

**Comment by calebcartwright** [comment]
I can reproduce this with the latest 1.4.10
