### ISSUE TITLE
Rename --all to --workspace?

### ISSUE THREAD

**Issue by lnicola** [rust-lang/rustfmt#3911]
In https://github.com/rust-lang/cargo/pull/7241, `cargo --all` got deprecated in favor of `--workspace`. There's less chance of confusion in `cargo fmt` because there is no `--all-targets, but perhaps it's a good idea to support both for consistency.

**Comment by calebcartwright** [comment]
Thanks @lnicola, I wasn't aware of the change to `--workspace` in cargo! There's certainly a case to be made for consistency, and this would be as good a time as any as the current focus is on rustfmt 2.0 and there's other arg/option changes. There are, however, certain behaviors associated with cargo fmt's args that IMO are worth considering.

For example, when running `cargo fmt` in the root directory of a workspace, `cargo fmt` already formats all of the workspace members. Running `cargo fmt --all` formats the workspace _plus_ any local/path based dependencies of the packages in that workspace, regardless of whether those local deps are explicit workspace members. 

If the format strategy current used with `--all` were renamed to `--workspace`, would it be confusing/surprising for users that their entire workspace gets formatted when they run `cargo fmt` even _without_ the `--workspace` arg? Similarly, would it be confusing/surprising for users when running `cargo fmt --workspace` that those local/deps _outside_ the workspace were formatted?

**Comment by lnicola** [comment]
Sorry, I wasn't aware of what --all did. I went by the help message:

--all        Format all packages (only usable in workspaces)

So I hope you understand my confusion. If it really behaves like you described, I don't think it's worth making any change here.

**Comment by calebcartwright** [comment]
No worries! It may still be worth considering a rename, but I just wanted to note some of the other aspects that would need to be weighed against the consistency with cargo's `--workspace`

I can see how that message could be confusing, especially that suffix. I believe `--all` can technically be used today even outside an explicit workspace so we should probably update that message either way. Perhaps something like the below would be more clear?

```bash
--all Format all packages and their local path-based dependencies
```

**Comment by topecongiro** [comment]
@calebcartwright Seems good to me 🙌

**Comment by lnicola** [comment]
Filed https://github.com/rust-lang/rustfmt/pull/3914.
