### ISSUE TITLE
Consider dropping derive-new dependency

### ISSUE THREAD

**Issue by lnicola** [rust-lang/rustfmt#3915]
See https://github.com/salsa-rs/salsa/pull/201 for context. Avoiding `derive-new` sped up `salsa` builds by 6-8 seconds. There are four uses of `#[derive(new)]` in this repo. I'm not sure how you feel about this, but I can submit a PR if you're interested.

In this repo, `derive-new` takes for me 14 seconds:

![image](https://user-images.githubusercontent.com/308347/68513630-323cb780-0284-11ea-9350-4be79290ad7d.png)

There's also `failure` and `structopt`, but that's a little harder to replace, and you might not want to go that far.

**Comment by calebcartwright** [comment]
Sounds reasonable to me 👍 I'm also curious to see if the switch has other improvements beyond those ~14 seconds
