### ISSUE TITLE
Add fmt run for doc comment code examples?

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rustfmt#3921]
It'd be nice to be able to run `rustfmt` on code examples inside documentation.

**Comment by topecongiro** [comment]
Does [`format_code_in_doc_comments`](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#format_code_in_doc_comments) work for you?

**Comment by GuillaumeGomez** [comment]
It completely does! I didn't know it existed, it's awesome! Sorry for the noise, closing.
