### ISSUE TITLE
[Feature request] Autogenerate boilerplate

### ISSUE THREAD

**Issue by ckaran** [rust-lang/rustfmt#3924]
This is a request to implement what I wrote about at https://internals.rust-lang.org/t/tools-team-tell-us-your-sorrows/9657/27?u=ckaran.  Below is the copy/paste of what I wrote.

### Area

Source code generation

Basically, I find myself writing what a lot of what is essentially boilerplate.  For example, if I have the following function:

```rust
pub fn foo(a: Bar) -> bool {
// stuff here.
}
```

I will thereafter have to expand it into something like:

```rust
/// # Foo's Bars
///
/// Will Foo a Bar if it hasn't already been Foo'd.  Will not Foo a
/// if it has already been Foo'd, so this is safe to use on any Bar
/// you come across, without checking to see if it has already
/// been Foo'd.
///
/// # Example - added if needed
///
/// ```rust
/// use crate::bar::Bar;
/// fn main() {
///     let bar = Bar::new();
///     match foo(bar) {
///         true => println!("Did foo the bar"),
///         false => println!("Bar was already foo'd, not doing anything")
///     };
/// }
/// ```
///
/// # Parameters - added if needed
///
/// - `a` - A Bar that may or may not have already been Foo'd.  
///
/// # Returns - added if needed
///
/// `true` iff `a` wasn't Foo'd before this call.  If this call returns,
/// rather than panics, then `a` will have been Foo'd successfully.
///
/// # Panics - added if needed
///
/// Will panic if `a` has been Baz'd.
///
/// # Errors - added if needed
/// # Safety - added if needed
/// # Aborts - added if needed
/// # Undefined Behavior - added if needed
pub fn foo(a: &mut Bar) -> bool {
// stuff here.
}

// A whole bunch more functions

#[cfg(test)]
mod tests {
    use super::*;

    fn test_foo() {
        // Some kind of test
    }
}

```

That is a lot of boilerplate for each function, struct, union, etc.  What I want is a tool that is able to analyze the contents of a module (probably via the AST) and generate the boilerplate in place as needed (kind of like how `cargo fmt` figures out where whitespace should be added).  It should do the following:

- If there are no module-level docs, add the appropriate block at the top.  Put in a `FIXME` comment anywhere I need to fill something in.
- For each member of a struct, enum, union, etc., make sure that there is documentation in place.
- For each function/method, add in the docs as shown above **intelligently**.  That is, if my function doesn't have any parameters, don't bother with that section.  If it does have parameters, add in a single stub line for each parameter.  Same for every other heading.
- For each chunk of executable code, add in a unit test stub whose contents are `assert!(false)`, so that I know what I need to fill in.
- **Don't overrwrite what is already there!** I want this to be an idempotent operation, so that I can run it whenever I want, kind of like how I run `cargo fmt --all` on my code right before each commit.

### Is there a tool for this already?

Not as far as I can tell, but I may not be looking in the right places.

#### If not: which tool do you think it should be included in?

`cargo fmt`, probably with a new switch like `cargo fmt --generate_doc_stubs --generate_test_stubs`

### Did you manage to work around the lack of tooling?

Copy/pasting of function names, and then prefixing with `test_`, or copy/pasting home-grown documentation stubs, etc.

**Comment by topecongiro** [comment]
My first impression is that this is not the responsibility of rustfmt, but rather the one for IDE or an editor plugin (e.g., yasnippet).

**Comment by calebcartwright** [comment]
I agree. I can certainly see the value in the request capabilities, but strikes me as outside the scope of rustfmt

**Comment by ckaran** [comment]
@topecongiro I can see where you're coming from, but I think it would be better to have it in one of the rust tools (maybe `rustfmt`, or maybe `rustdoc`).  There are two big advantages to doing so:

1. With an official tool in place, all IDEs, plugins, etc., can use the tool to generate the same boilerplate.  That will ensure that everyone is using the same standard, which will be helpful when developing new tools to ingest the information.
2. Command-line tools can be scripted.  This makes it particularly easy to write commit hooks that automatically check to make sure that the code is documented, etc.

That said, both @topecongiro and @calebcartwright are probably right that this should be in a different tool.  Maybe `rustdoc`?  What about the automatic test generation code, is there a better place for it?

**Comment by calebcartwright** [comment]
> this should be in a different tool. Maybe rustdoc? What about the automatic test generation code, is there a better place for it?

One option would be to build out some new cargo subcommands, which seems to be a pretty popular path for extending functionality. 

For baking the capabilities into some existing tools..

Not sure how the rustdoc team would feel about adding the doc generation feature, but I could see the logic in that feature being part of rustdocs capabilities. 

For the test stub generation, maybe as a new sub-subcommand of cargo test 😄? Again I've no idea of that's something the cargo team would consider, but perhaps that'd be an option since cargo does generate a test stub as part of `cargo new`

**Comment by ckaran** [comment]
@calebcartwright OK, thank you!  I'll raise the issues with those teams.  Thanks!
