### ISSUE TITLE
Multiline closures with a single expression that's a macro call with {} are always wrapped in a block, but [] macro calls aren't. 

### ISSUE THREAD

**Issue by arilotter** [rust-lang/rustfmt#3927]
Using this sample macro which turns a list of token trees into a block (simplified from a real macro that does more transformations)
```rust
macro_rules! blockify {
  ($($block:tt)*) => {
    { $($block)* }
  };
}
```

rustfmt will transform the following expression
```rust
drop(|| blockify! {
    // do something
});
```
into 
```rust
drop(|| {
    blockify! {
        // do something
    }
});
```

However, it doesn't do the same with macros that use [] until they're significantly longer.
```rust
    drop(|| vec![1 + 1, 2 + 2, 3 + 3]);
    drop(|| {
        vec![
            1 + 1 + 1 + 1 + 1 + 1 + 1,
            2 + 2 + 2 + 2 + 2 + 2 + 2 + 2,
            3 + 3 + 3 + 3 + 3,
        ]
    });
}
```

I would expect the same behaviour with `[]` and `{}` macro calls, or at least an option so I can make `{}` macros use the same rules as `[]` macros here.

**Comment by calebcartwright** [comment]
At first glance this seems to have similarities with #3605 where a block is being added to the body of the closure

**Comment by arilotter** [comment]
Closing this as a duplicate of #3605, and adding my additional context in that ticket.

**Comment by arilotter** [comment]
I believe this is not a duplicate, though, it might be documenting the same behavior. This happens regardless of whether the closure takes parameters.

**Comment by topecongiro** [comment]
IIRC rustfmt adds a block if the body of the closure is multi-lined.

**Comment by arilotter** [comment]
> IIRC rustfmt adds a block if the body of the closure is multi-lined.

Ah, I see how this rule applies to my examples. 

Would rustfmt take a PR that adds a way to disable this?

**Comment by arilotter** [comment]
I'm closing this issue because the behavior is "rustfmt adds a block if the body of the closure is multi-lined", which is consistent - there's no issue here.
