### ISSUE TITLE
Rustfmt deletes HRTB-for bound if it is over types

### ISSUE THREAD

**Issue by MikailBag** [rust-lang/rustfmt#3929]
Before: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=0d4ba26dbbdd64ad7d4ed530cf772919

After: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=b2355389de4ef0cc15ca5e3fb2818ba6

You can see that `for` clause disappeared

**Comment by CAD97** [comment]
This can break code when it happens in a macro.

Before: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f7cbe5945f6caf7269a1b43a87038c9f  
After: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=2129bcc52189c45ca472005ac9bdbbd5

I think that should upgrade this to at least p-medium
