### ISSUE TITLE
Strange comment formatting

### ISSUE THREAD

**Issue by ghost** [rust-lang/rustfmt#3937]
```
$ rustfmt --version
rustfmt 1.4.9-nightly (33e3667 2019-10-07)
```

------

Code:

```rust
struct Foo {
    // a: i32,
    //
    // b: i32,
}
```

Formatting with `rustfmt foo.rs`:

```rust
struct Foo {
    // a: i32,
//
// b: i32,
}
```

I expected rustfmt to leave the code unmodified.

--------

Code:

```rust
struct Foo {
    a: i32,
    //
    // b: i32,
}
```

Formatting with `rustfmt format_code_in_doc_comments=true src/foo.rs`:

```rust
struct Foo {
    a: i32,
    /*
     * b: i32, */
}
```

I expected rustfmt to leave the code unmodified.

**Comment by pickfire** [comment]
Maybe off-topic, I just wonder if I should create a new issue (or I am lazy).

```rust
/// Hello
/// world.
```
Should be formatted as
```rust
/// Hello world.
```
But if the sentence already ends.
```rust
/// Hello.
/// World.
```
Then it should be the same. Other languages may need to be checked as well.

**Comment by ytmimi** [comment]
Going to close this as #5171 fixes the indentation for empty struct comments and #5091 fixes the `format_code_in_doc_comments=true` issue.
