### ISSUE TITLE
Async on lambda function break compiling code.

### ISSUE THREAD

**Issue by jannickj** [rust-lang/rustfmt#3945]
```rust
|x| async {
                 ...
        }
```

Is formatted into

```rust
|x|  {
    async {
                 ...
        }
}
```
Which then gives the compiler error that x is moved out of context.
Currently the only way to fix it and use the formatter is to write

```rust
|x|  {
    async move {
                 ...
        }
}
```

**Comment by topecongiro** [comment]
Ouch. We should make 1.4.11 release for this.
