### ISSUE TITLE
Add option to skip generated files

### ISSUE THREAD

**Issue by Timmmm** [rust-lang/rustfmt#3958]
There's a growing de facto standard to mark generated files by putting `@generated` in a comment at the top of the file. E.g. check the top of `Cargo.lock`.

It would be great if there were an option to have Rustfmt skip files that contain `@generated`.

**Comment by topecongiro** [comment]
I have seen `@Generated` annotation in Java, but to be honest, I have not seen usages of `@generated` in the Rust community besides Cargo.lock. @Timmmm Are you aware of any tools/projects that add `// @generated` comment on generated files?

**Comment by Timmmm** [comment]
[Capnp does](https://github.com/capnproto/capnproto-rust/pull/153) (I added that change). I also have an internal tool that does.

Phabricator supports it and shows files containing `@generated` as collapsed in diff views by default (you can still expand them). For reference [here is the diff that added it to `Cargo.lock`](https://github.com/rust-lang/cargo/issues/6180).

**Comment by topecongiro** [comment]
Thank you for your information. It seems reasonable to have the option in rustfmt.

**Comment by stepancheg** [comment]
`@generated` is a standard way to mark a file as generated [in Phabricator](https://stackoverflow.com/a/31815073).

Would be nice if rustfmt supported that out of the box.
