### ISSUE TITLE
Subsequent passes of formatter lead to incorrect indentation

### ISSUE THREAD

**Issue by rogday** [rust-lang/rustfmt#3987]
Formatting of the following code repeatedly leads "42" to move right up until the line is too long:
```rust
macro_rules! macros {
    () => {{
        Struct {
            field: (
                42 + //comment 1
                42
                //comment 2
            ),
        };
    }};
}
```

**Comment by ytmimi** [comment]
unable to reproduce this using `rustfmt 1.5.1-nightly (4c78c738 2022-07-20)` and `format_macro_bodies=true`
