### ISSUE TITLE
Don't move comments around, or at least move them up instead of down

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rustfmt#3994]
For some reason, rustfmt arbitrarily decides to move the comment around in the following snippet:
```rust
fn main() {
    if true { // explanation.
        println!("hello");
    }
}
```
(I am saying "arbitrarily" as [this page has no explanation for why this happens](https://doc.rust-lang.org/1.0.0/style/style/comments.html))

This becomes:
```rust
fn main() {
    if true {
        // explanation.
        println!("hello");
    }
}
```
This is bad for 2 reasons:
1. Why even move the comment? Having the explanation for the conditional on the same line as the conditional is perfectly fine, very readable and can help save some vertical space.
2. If rustfmt for some reason must move the comment, it should be moved *up*. The comment was explaining the `if true`, and a comment explaining something should not come after the thing already happened! Currently, rustfmt actively degrades the quality of such comments. The reformatted code looks like the comment is explaining the `println!`.

I am very worried now how many such comments that were in the compiler are wrong / confusing now because of this. :/

**Comment by calebcartwright** [comment]
Agreed, though I think this is a duplicate of #3255. 

I _think_ rustfmt is assuming the same-line comment after the opening `{` is associated to the first statement in the block, instead of the control flow expression condition.

**Comment by RalfJung** [comment]
Yes, this is a duplicate of https://github.com/rust-lang/rustfmt/issues/3255 indeed.

**Comment by RalfJung** [comment]
Closing as duplicate of https://github.com/rust-lang/rustfmt/issues/3255.
