### ISSUE TITLE
Option to exempt certain macros from formatting

### ISSUE THREAD

**Issue by jhpratt** [rust-lang/rustfmt#4021]
Sometimes, it may not be desired to format the macro body. As this is a macro I'm providing in a crate, asking the user to add `#[rustfmt::skip]` on every invocation seems excessive.

This macro is of the format `date!(2020-01-15)`, which gets formatted to `date!(2020 - 01 - 15)`. While this may be desirable elsewhere, in the case of this macro, it would certainly be preferred to have the former.

**Comment by calebcartwright** [comment]
rustfmt does support skipping macros via the `#[rustfmt::skip::macros(...)]` attribute already, would that work for your use case? There's also the [`format_macro_bodies`](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#format_macro_bodies) config option 

https://github.com/rust-lang/rustfmt#tips

**Comment by jhpratt** [comment]
@calebcartwright I was actually seeking a bit more of something the library author controls, but a single line is definitely something I can document as useful to have certainly works as well.

Thanks for the quick response!
