### ISSUE TITLE
Rustfmt puts single-line comment after wrong import when reordering imports

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rustfmt#4027]
before rustfmt:
```rust
pub use views::*;
pub use foo::bar; // re-export for frontend
```
after (with import reordering enabled):
```rust
pub use foo::bar;
pub use views::*; // re-export for frontend
```
The comment is at the wrong import now. It should not just reorder the imports but also their comments with them!

**Comment by mbarbar** [comment]
Looks like #3720.

**Comment by whizsid** [comment]
I am working on this issue.

**Comment by mbarbar** [comment]
This comment may make getting started a little easier, though it may be outdated.
https://github.com/rust-lang/rustfmt/issues/3720#issuecomment-564570935

**Comment by ytmimi** [comment]
closing this as a duplicate of #3720
