### ISSUE TITLE
Illformed derive is removed

### ISSUE THREAD

**Issue by jfrimmel** [rust-lang/rustfmt#4029]
When I wrote the following code:
```rust
#[derive(Debug, Clone, Default Hash)]
//                            ^-- Note the missing comma
struct S;
```
it got reformatted as `#[derive()]`, i.e. the traits were removed automatically.
Since my editor did formatting on save, the code was always altered before I could try to compile it (which would have shown me the syntax error) and thus I had to stare at the code for some time until I figured it out (sometimes such obvious errors don't reach your brain). It is not directly obvious, why the derived traits are removed on `Ctrl+s` :smile: 
I expected rustfmt to not alter the code on such syntax errors.

This issue is similar  to #3898.

<details>
<summary>Reproduction</summary>

```bash
cat <<EOF > test.rs
#[derive(Debug, Clone, Default Hash)]
struct S;
EOF
rustfmt test.rs 
cat test.rs
#[derive()]
struct S;
```
</details>

Tested versions are:
```
rustfmt 1.4.9-stable (33e3667 2019-10-07)
rustfmt 1.4.11-nightly (1838235 2019-12-03)
```

**Comment by calebcartwright** [comment]
It's the same underlying problem as #3898, where parseable, but malformed, derives have the contents eaten. the base solution outlined in 3898 to keep the original span contents would solve the issue (whether the cause is double commas, missing commas, etc.
