### ISSUE TITLE
Config option for spacing around `=` in Attributes

### ISSUE THREAD

**Issue by calebcartwright** [rust-lang/rustfmt#4039]
A question/request came up in the wg-rustfmt channel in Discord about a config option that could be used to control spacing around `=` in Attributes like we have for various other config options (`space_after_colon`, `space_before_colon`, `spaces_around_ranges`, `type_punctuation_density`, etc.)
```rust
#[cfg(target_os="linux")]
// vs
#[cfg(target_os = "linux")]
```

AFAIK this is not configurable today, but it seemed like a reasonable request to me (and a relatively easy/good-first-issue candidate), so opening for consideration.

For anyone interested in implementing..

The core bit of the code that controls the spacing is the last line in this snippet
https://github.com/rust-lang/rustfmt/blob/facba6a58a50fbdb1592748bb25defd95b5322c4/rustfmt-core/rustfmt-lib/src/attr.rs#L243-L255

That would need to be changed to conditionally add the spacing depending on whether the (new) config option was `true` or `false`. 

The config option would be added in the rustfmt_configuration crate, probably down in [this](https://github.com/rust-lang/rustfmt/blob/master/rustfmt-core/rustfmt-config/src/lib.rs#L71) section with the other spacing-related options, and the option would also need to be added and described in the Configuration docs https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

The last bit would be adding/updating the tests.

**Comment by thedodd** [comment]
@calebcartwright thanks for reporting. I'll see if I can get a PR open.
