### ISSUE TITLE
Rustfmt sometimes breaks lists in doc-comments

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rustfmt#4041]
Rustfmt breaks sub-list with `+` (diff from `cargo +nightly fmt -- --check --config "wrap_comments=true"`)

```diff
 //! List:
-//! - Sub list:
-//!   + very long #1 blah blah blah blah blah blah blah blah blah blah blah blah
-//!   + very long #2 blah blah blah blah blah blah blah blah blah blah blah blah
+//! - Sub list: + very long #1 blah blah blah blah blah blah blah blah blah blah
+//!   blah blah + very long #2 blah blah blah blah blah blah blah blah blah blah
+//!   blah blah
 //! - ...
```

Changing `+` in sublist to `-` fixes that.

**Comment by glfmn** [comment]
It's worth nothing that since Rust's doc comments use markdown syntax the only syntax for unordered list is to use `*` and `-`.  Should this not be the expected behavior using a `+`?

**Comment by ytmimi** [comment]
Confirming I can reproduce this with `rustfmt 1.5.1-nightly (a451a39d 2022-07-25)`. using the following input:

```rust
//! List:
//! - Sub list:
//!   + very long #1 blah blah blah blah blah blah blah blah blah blah blah blah
//!   + very long #2 blah blah blah blah blah blah blah blah blah blah blah blah
```

For anyone wanting to work on this this issue is that we don't consider `+ ` the start of an itemized line.

The relevant code can be found here:

https://github.com/rust-lang/rustfmt/blob/a451a39dec2bd5d7f0822eaa092e1423b42ea1d3/src/comment.rs#L433-L453

**Comment by ytmimi** [comment]
linking tracking issue for `wrap_comments` #3347

**Comment by thaqib0437** [comment]
Maybe I can help this!

**Comment by ytmimi** [comment]
@thaqib0437, that's great news! feel free to reach out if you have any questions

**Comment by thaqib0437** [comment]
Is there a guide on building, testing my changes with custom inputs, and adding teat cases?

**Comment by ytmimi** [comment]
@thaqib0437 check out the [Create Test Cases](https://github.com/rust-lang/rustfmt/blob/master/Contributing.md#create-test-cases) section of the contributing guide. Running `cargo build` is all you need to do in order to build rustfmt locally?

**Comment by thaqib0437** [comment]
Trying to add a test case but its not running with ``warp_comments=true``
test file: 
```
//  rustfmt-wrap_comments=true
//! List:
//! - Sub list:
//!   + very long #1 blah blah blah blah blah blah blah blah blah blah blah blah
//!   + very long #2 blah blah blah blah blah blah blah blah blah blah blah blah
```

**Comment by thaqib0437** [comment]
Created a PR 
https://github.com/rust-lang/rustfmt/pull/5560
