### ISSUE TITLE
Automatically nest use statement paths

### ISSUE THREAD

**Issue by iago-lito** [rust-lang/rustfmt#4045]
I read in [the book](https://doc.rust-lang.org/book/ch07-04-bringing-paths-into-scope-with-the-use-keyword.html#using-nested-paths-to-clean-up-large-use-lists) that mod statements like 

```rust
use a::b;
use a::c;
use a::d::e;
use a::d::f;
```

Can be reformatted with nested paths like

```rust
use a::{
    b, c,
    d::{e, f},
};
```

What's a consensus about the right way to go?
Is it in the scope of `rustfmt` to automatically handle this?  
If yes, how to configure `rustfmt` so it does?

**Comment by cynecx** [comment]
`merge_imports` (https://github.com/rust-lang/rustfmt/blob/master/Configurations.md).

**Comment by iago-lito** [comment]
@cynecx Thanks, so `merge` is the keyword I was missing instead of `nest` ;)

I read that the default value for this option is `false`, because the feature is not stabilized yet. See this #3362 for discussion about it.
