### ISSUE TITLE
Multiline long params with attributes

### ISSUE THREAD

**Issue by calebcartwright** [rust-lang/rustfmt#4059]
Formatting of params with attributes should be multilined if the formatting result length exceeds `max_width`. 

rustfmt does this in the **vast** majority of cases, but there is currently an edge case where rustfmt falls back to the original one-line snippet for the param

this snippet:
```rust
fn a1(#[aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa] a: u8) {}
```

is formatted to:
```rust
fn a1(
    #[aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa] a: u8,
) {
}
```

It seems that all of the below conditions must be true in order for the line to not be split as desired:
* only one attribute on the param
* neither the attribute nor the param individually exceed the max width
* param is named and not an empty infer/closure param
* the combination of the formatted attributed and the param pattern is under the max width, but the addition of the colon and param type causes the total line length to exceed max width

I suspect that the `rewrite` for `Param` is what would need to be tweaked to handle this case:
https://github.com/rust-lang/rustfmt/blob/4464ab7188d992440bbe5fad9683b98678b84b20/rustfmt-core/rustfmt-lib/src/items.rs#L2047-L2100

Refs #4047

**Comment by davidBar-On** [comment]
Pull request #4390 hopefully resolve the issue. The problem is because the attribute and name are combined before the type is combined.  The change is that name and type are combined together and then the result is combined with the attribute and comment.
