### ISSUE TITLE
Empty match arms

### ISSUE THREAD

**Issue by pickfire** [rust-lang/rustfmt#4065]
`=> ()` should be `=> {}` https://github.com/rust-dev-tools/fmt-rfcs/issues/146

**Comment by pickfire** [comment]
I took my time trying to write this but I looked at the wrong line instead (`is_empty_block`). T_T

**Comment by laysauchoa** [comment]
@pickfire are you working on this? I would like to contribute. What should be done mainly here?

**Comment by pickfire** [comment]
@laysauchoa No, I tried checking this but I didn't spend much time on this issue. My guess is somewhere around https://github.com/rust-lang/rustfmt/blob/master/rustfmt-core/rustfmt-lib/src/matches.rs#L219 but I don't quite grasp the workflow of rustfmt yet, I don't quite know how to debug stuff here.

**Comment by ayazhafiz** [comment]
@laysauchoa take a look at [matches#rewrite_match_body](https://github.com/rust-lang/rustfmt/blob/99edc8826ee6d7a5d529e8749cdf4ac999dfd954/rustfmt-core/rustfmt-lib/src/matches.rs#L341-L349). It should be enough to check if the arm body is an empty block, which is resolved here:

https://github.com/rust-lang/rustfmt/blob/99edc8826ee6d7a5d529e8749cdf4ac999dfd954/rustfmt-core/rustfmt-lib/src/matches.rs#L360-L362

And if so, rewrite the original arm body with `()`, maybe in the `combine_orig_body` closure which is one method responsible for formatting the rewritten arm body:

https://github.com/rust-lang/rustfmt/blob/99edc8826ee6d7a5d529e8749cdf4ac999dfd954/rustfmt-core/rustfmt-lib/src/matches.rs#L370-L377

Or something like that..
