### ISSUE TITLE
unstable features are usable on stable with the '--config' option

### ISSUE THREAD

**Issue by bmwill** [rust-lang/rustfmt#4081]
If you place an unstable config in a rustfmt.toml config file and run
using a stable version of rustfmt the config is ignored and you get the
following:

    $ cargo fmt
    Warning: can't set `merge_imports = true`, unstable features are only available in nightly channel.

But if you instead pass the config using the '--config' option rustfmt
happily applies and uses the unstable config:

    $ cargo fmt -- --config merge_imports=true

I don't know if this is intentional or not but it gave me a workaround for using the 'merge_imports' feature while using a stable toolchain: https://github.com/libra/libra/pull/2926

**Comment by calebcartwright** [comment]
Yeah I noticed this the other day too (https://github.com/rust-lang/rustfmt/pull/4064). I don't _think_ it's intentional currently, and it's possible that cli config override support for unstable options on stable will be dropped as part of the rustfmt 2.x release

**Comment by calebcartwright** [comment]
@topecongiro are we planning to remove this (unstable opts on stable via `--config`) for the 2.0 release?
