### ISSUE TITLE
Macro-generated structs/enums are not indented properly

### ISSUE THREAD

**Issue by connorkuehl** [rust-lang/rustfmt#4085]
For example, this enum whose definition is supplemented by an enum, which is indented correctly:

```rust
enumerate! {
    pub enum IoctlCode: u32 {
        PlatformReset = 0,
        PlatformStatus = 1,
        PekGenerate = 2,
        PekCertificateSigningRequest = 3,
        PdhGenerate = 4,
        PdhCertificateExport = 5,
        PekCertificateImport = 6,
        GetIdentifier = 7,
    }
}
```

will be formatted like this after running `cargo fmt`:

```rust
enumerate! {
    pub enum IoctlCode: u32 {
    PlatformReset = 0,
    PlatformStatus = 1,
    PekGenerate = 2,
    PekCertificateSigningRequest = 3,
    PdhGenerate = 4,
    PdhCertificateExport = 5,
    PekCertificateImport = 6,
    GetIdentifier = 7,
    }
}
```

Here is [enumerate!'s definition](https://github.com/enarx/enarx/blob/master/enumerate/src/lib.rs#L38).

**Comment by connorkuehl** [comment]
Okay, not sure if this is a bug at all. We determined it's because my editor was using tabs, not spaces, and `cargo fmt` was replacing the tabs with4 spaces but not performing any other work inside the block enclosed by the macro invocation.

**Comment by calebcartwright** [comment]
> We determined it's because my editor was using tabs, not spaces, and cargo fmt was replacing the tabs with4 spaces

Yup that'd do it. If you haven't seen it already, note you can leverage the [`hard_tabs`](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#hard_tabs) config option to control that. 

> but not performing any other work inside the block enclosed by the macro invocation.

I'm not entirely clear what all `other work inside the block` would entail in the context of the snippet, but guessing you may be seeking something similar to #3445?

**Comment by connorkuehl** [comment]
> > but not performing any other work inside the block enclosed by the macro invocation.
> 
> I'm not entirely clear what all `other work inside the block` would entail in the context of the snippet, but guessing you may be seeking something similar to #3445?

Yes, I think that issue you linked describes what indentation I'd expect to happen.

Duplicate of #3445.
