### ISSUE TITLE
--check output is editor-unfriendly.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rustfmt#4092]
While the ergonomic problem will likely go away whenever I get around to moving my setup to VSCode Remote, the current `--check` diff output is still pretty frustrating, and inconsistent with compiler output.

The head of each diff chunk looks like this: (base dir omitted for clarity)
```
Diff in .../src/librustc_infer/infer/error_reporting/need_type_info.rs at line 48:
```

I suspect the ` at line 48:` formatting is trying to be user-friendly or something, but if it was like this, it would be accessible without having to go to the line manually:
```
Diff at .../src/librustc_infer/infer/error_reporting/need_type_info.rs:48:
```

For me it's <kbd>Ctrl</kbd>+click that I use, but I recall seeing an issue about some other editor (emacs perhaps?), where a more specific format might be needed, I just can't find that issue now.

**Comment by calebcartwright** [comment]
When you say editor-unfriendly, what's the context? Editor/IDE plugins that facilitate running rustfmt (on-demand, format-on-save) or something else?

Would the `json` rustfmt output be helpful at all?

**Comment by eddyb** [comment]
I mean editors/IDE natively handling the text output, where `file:line:col` is sort of the "standard".

In my case, `rustfmt` is ran by `x.py` aka bootstrap/"rustbuild" in the `rust-lang/rust` repo, and the output is just in a terminal window, but like I was saying earlier, if it were adhering to `file:line`, <kbd>Ctrl</kbd>+click would "just" work to let me jump to that file and line.
Curretly, I have to <kbd>Ctrl</kbd>+click to open the file and <kbd>Ctrl</kbd>+<kbd>G</kbd> to the line manually.

> Would the `json` rustfmt output be helpful at all?

No, since something would have to process it. At that point I should bite the bullet and switch to VSCode Remote to the server, where I could just run RLS, have format on save, etc.

<hr/>

What I'm hoping for is a tiny tweak to the `--check` diff output, to be clear.

**Comment by calebcartwright** [comment]
> if it were adhering to file:line, Ctrl+click would "just" work to let me jump to that file and line.

:+1: makes sense, thank you. I'd never noticed that type of navigation in editors before

> What I'm hoping for is a tiny tweak to the --check diff output, to be clear.

Seems reasonable to me. It's indeed a really easy change if anyone is interested in making the update, otherwise I can probably get around to it eventually

https://github.com/rust-lang/rustfmt/blob/9124dd88d6ef14d0ae77dc52ff5e9598f24a75a0/rustfmt-core/rustfmt-emitter/src/diff.rs#L34-L38

**Comment by eddyb** [comment]
FWIW, I found a way to run `rustfmt` on save without RLS, so just in case it helps anyone:
https://marketplace.visualstudio.com/items?itemName=pucelle.run-on-save + this config:
```json
    "runOnSave.commands": [
        {
            "match": "\\.rs$",
            "command": "rustfmt ${file}",
            "runIn": "backend",
        }
    ],
```
