### ISSUE TITLE
Closing brace in `{}` can be separated

### ISSUE THREAD

**Issue by varkor** [rust-lang/rustfmt#4098]
See [here](https://github.com/rust-lang/rust/pull/70261/files/69c78c8fadf9e2023eac7d0960f618b1e40f47c7#diff-fc6824b30ee91a124e3ff9764f25108aR660-R661), for instance, where rustfmt decided that
```rust
                (AngleBracketedArg::Arg(_), None) | (AngleBracketedArg::Constraint(_), Some(_)) => {
                }
```
was ideal. This looks silly — `{}` (and any other paired symbols) should be kept together.

**Comment by topecongiro** [comment]
Thank you for the report. However this is expected, `{` is the 100th character on the line, and putting `}` on the same line will exceed the max width.

**Comment by varkor** [comment]
I understand why it happens. However, I think this behaviour is wrong: according to the formatting RFC, empty blocks should be written `{}`: https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/expressions.md#blocks. The current behaviour is also ugly.

**Comment by varkor** [comment]
cc @topecongiro: I think this should be reopened following https://github.com/rust-lang/rustfmt/issues/4098#issuecomment-606696313.
