### ISSUE TITLE
Bug: trailing_comma + struct_field_align_threshold -> removing a struct's commas

### ISSUE THREAD

**Issue by usagi** [rust-lang/rustfmt#4099]
- `rustfmt 1.4.12-nightly (9f53665f 2020-02-10)`
- `rustc 1.44.0-nightly (f509b26a7 2020-03-18)`

### Minimal repro

1. Prepare the nightly repos:

```sh
cargo new aaa
cd aaa
echo 'nightly' > rust-toolchain
```

2. Prepare the `.rustfmt.toml`:

```toml
struct_field_align_threshold = 127
trailing_comma = "Never"
```

3. Prepare the `src/main.rs` with a `struct` like it:

```rust
struct S {
  aaa: f32,

  bbb: f32,

  ccc: f32
}

fn main() {
  println!("Hello, world!");
}
```

4. `cargo fmt`

#### The actual result of `src/main.rs`:

```rust
struct S {
    aaa: f32

    bbb: f32

    ccc: f32
}

fn main() {
    println!("Hello, world!");
}
```

Note: The commas are removed. Unfortunately, this result could not be compiled then I think it is high priority bug maybe.

#### The Expected result of `src/main.rs`:

```rust
struct S {
    aaa: f32,

    bbb: f32,

    ccc: f32
}

fn main() {
    println!("Hello, world!");
}
```

Note: I tried some different versions of the minimal repro code. So, I found two variations that could be format expectedly.

1. The No empty lines pattern:

```rust
struct S {
  aaa: f32,
  bbb: f32,
  ccc: f32
}
```

2. No White space characters pattern:

```rust
struct S {
aaa: f32,

bbb: f32,

ccc: f32
}
```

Note: These variant patterns be retained these commas `cargo fmt` once. However,  once again `cargo fmt`, then these are removed.

**Comment by calebcartwright** [comment]
Closed via #4201
