### ISSUE TITLE
Imports: Leading :: shouldn't be stripped.

### ISSUE THREAD

**Issue by rickvanprim** [rust-lang/rustfmt#4102]
```rust
pub(crate) use ::fnv::FnvHasher;

pub mod fnv;
pub use self::fnv::*;
```
gets transformed into
```rust
pub(crate) use fnv::FnvHasher;

pub mod fnv;
pub use self::fnv::*;
```

In this case where there's a name overlap, this has a semantically different meaning.  I don't think rustfmt should be stripping the leading `::`.

**Comment by calebcartwright** [comment]
Believe this is a duplicate of #3501. Make sure you are specifying the edition value (either in rustfmt.toml or cli arg) if you are running `rustfmt` directly

**Comment by rickvanprim** [comment]
Good catch, thank you @calebcartwright that appears to fix it!
