### ISSUE TITLE
Add `recursive` config setting to appropriate tests

### ISSUE THREAD

**Issue by calebcartwright** [rust-lang/rustfmt#4113]
rustfmt 1.x ran in "recursive" mode by default wherein all the mods within the AST would be visited and formatted, including those mods defined in external files not explicitly passed as args to `rustfmt`. 

rustfmt 2.x inverts that behavior and will now only format files explicitly passed to `rustfmt` unless the `--recursive` flag is passed (in which case rustfmt 2.x formats everything like rustfmt 1.x)

As such a few of our test cases needed to be updated to explicitly include the `recursive`. Currently these tests are running in "non-recursive" mode and unintentionally ignoring some files which has resulted in a few false positves.

This can be addressed by adding the below snippet to the top of the corresponding pairs of test files under `rustfmt-core/rustfmt-lib/tests/{source, target}/**`
```rust
// rustfmt-recursive: true
```

Some (perhaps all) of the tests that need this change can be found by reviewing the skipped files in `rustfmt-core/rustfmt-lib/src/test/mod.rs` to determine the corresponding entry point files that need `recursive` enabled.

https://github.com/rust-lang/rustfmt/blob/a0eb97b8b67cc5412c86037232c5ed33f17b4559/rustfmt-core/rustfmt-lib/src/test/mod.rs#L23-L43

For example, we can see there's some test files within the `cfg_if` directory (`rustfmt-core/rustfmt-lib/tests/{source,target}/cfg_if/mod.rs` that are being explicitly ignored to validate the target behavior, so the entry test file in this case (`rustfmt-core/rustfmt-lib/tests/{source,target}/cfg_if/lib.rs`) needs to have recursive mode included by adding `// rustfmt-recursive: true`

This would be a good first issue for anyone interested in working on rustfmt!

**Comment by Krout0n** [comment]
Hi, can I tackle this for my first time contributing?

**Comment by calebcartwright** [comment]
Hi @Krout0n :wave: Thanks for your interest in contributing to rustfmt! 

@bradleypmartin is working on this one already (see #4142), but there are plenty of other issues in the backlog if you'd be interested in working on a different one (though don't feel constrained to that list)

You may want to check out the issues that have been tagged with [good-first-issue](https://github.com/rust-lang/rustfmt/issues?q=is%3Aissue+is%3Aopen+label%3A%22good-first-issue%22) and/or those with [help-wanted](https://github.com/rust-lang/rustfmt/issues?q=is%3Aissue+is%3Aopen+label%3A%22help-wanted%22) to see if you'd like to try any of those. 

If you find one that you want to work on just drop a note on that issue, and you can ask us any questions on that thread and/or in the [wg-rustfmt channel on the Rust Discord server](https://discordapp.com/invite/rust-lang)

**Comment by kellda** [comment]
Seems this issues should have been closed by #4142

**Comment by calebcartwright** [comment]
Thanks @kellda, but #4142 explicitly didn't cover all the tests that needed to be update which is why this was deliberately left open. It's possible the other tests may have been subsequently addressed via other PRs but going to keep this open until that's definitively determined.

**Comment by sasurau4** [comment]
The list to add `recursive` config is following.
I'd happy adding these checks in the issue description.

- [ ]     `issue-3434/no_entry.rs` 
- [ ]     `issue-3665/sub_mod.rs` 
- [ ]     `issue-3779/ice.rs` 
- [x]     `cfg_if/mod.rs` 
- [x]     `cfg_if/detect` 
- [ ]     `issue-3253/foo.rs` 
- [ ]     `issue-3253/bar.rs` 
- [ ]     `issue-3253/paths` 
- [ ]     `cfg_mod/dir` 
- [ ]     `cfg_mod/bar.rs` 
- [ ]     `cfg_mod/foo.rs` 
- [ ]     `cfg_mod/wasm32.rs` 
- [ ]     `configs/recursive/disabled/foo.rs` 
- [ ]     `configs/recursive/enabled/foo.rs`

**Comment by sasurau4** [comment]
@calebcartwright This issue seems completely done. :tada:
Could this issue be close?
