### ISSUE TITLE
Why was `single_line_if_else` removed?

### ISSUE THREAD

**Issue by jannickj** [rust-lang/rustfmt#4114]
I really like rustfmt, but everytime I have a oneline condition I run into the same issue.

something like  
```rust
let r = if b { x } else { y };
```
becomes 
```rust
let r = if b {
    x 
} else {
    y
};
```

Which really ruins the experience :(

**Comment by calebcartwright** [comment]
What version of rustfmt are you using?

The latest version of rustfmt (1.4.13) keeps your original input on one line:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=75b3b60aa7c96b6fe1ec6654e9c2b198

**Comment by jannickj** [comment]
Ah my bad, I've run into it a couple of times, but I guess I just happened to be at the max width limit. And when I looked at the issues and found there used to be a `single_line_if_else` I assumed it was a removed feature.

**Comment by calebcartwright** [comment]
No worries! It was a config option previously, but I believe it was removed since rustfmt will always try to keep those simple ones (no nested statements, comments, etc.) on one line unless it exceeds `max_width`
