### ISSUE TITLE
rustfmt can delete comments within an attribute

### ISSUE THREAD

**Issue by ahl** [rust-lang/rustfmt#4115]
source:
```rust
#[derive(A,
    B,
    C,
    D,
    // E,
)]
fn foo() {
    bar(1,
        2,
        3,
        4,
        // 5,
    );
}
```

post-rustfmt:
```rust
#[derive(A, B, C, D)]
fn foo() {
    bar(
        1, 2, 3, 4,
        // 5,
    );
}
```

I would expect something like:
```rust
#[derive(
    A, B, C, D,
    // E,
)]
fn foo() {
    bar(
        1, 2, 3, 4,
        // 5,
    );
}
```

I'd be happy to submit a PR for this.

**Comment by calebcartwright** [comment]
> I'd be happy to submit a PR for this.

Awesome, thank you! Don't feel obligated to look into this by any means, but there's another issue with derives where they get dropped when malformed (#4029/#3898), and the respective fixes would likely touch a lot of the same code.

**Comment by ahl** [comment]
@calebcartwright ok, I fixed all three.

**Comment by calebcartwright** [comment]
Awesome! Thank you so much @ahl :tada:
