### ISSUE TITLE
Inconsistent formatting of Stdin

### ISSUE THREAD

**Issue by mookid** [rust-lang/rustfmt#4117]
When formatting source code location errors, the formatting in the stdin case depends on the error level:

+ case of a formatting error: `<stdin>:line:column`
```
  --> <stdin>:14:33
   |
14 |                         .takes_ value(true)
   |                                 ^^^^^ expected one of `)`, `,`, `.`, `::`, `?`, or an operator here

```

+ case of an internal error: `stdin:line:column`
```
error[internal]: left behind trailing whitespace
  --> stdin:13:13:0
   |
13 |
   | ^^^^^^^^^^^^^^^^
   |

```

This is confusing for anyone that consumes the output of the command (https://github.com/rust-lang/rust-mode/issues/365)

**Comment by topecongiro** [comment]
The first error looks like it is from the rustc parser, while the second one is from rustfmt itself.
