### ISSUE TITLE
Closing brace in `{}` can be separated

### ISSUE THREAD

**Issue by varkor** [rust-lang/rustfmt#4125]
See [here](https://github.com/rust-lang/rust/pull/70261/files/69c78c8fadf9e2023eac7d0960f618b1e40f47c7#diff-fc6824b30ee91a124e3ff9764f25108aR660-R661), for instance, where rustfmt decided that
```rust
                (AngleBracketedArg::Arg(_), None) | (AngleBracketedArg::Constraint(_), Some(_)) => {
                }
```
was ideal. This looks ugly — `{}` (and any other paired symbols) should be kept together.

I originally opened this as https://github.com/rust-lang/rustfmt/issues/4098, but had not pointed out that this is in violating of the formatting spec: according to the RFC, empty blocks should be written `{}`: https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/expressions.md#blocks. This rule should take precedence over the line width rule.

**Comment by topecongiro** [comment]
Hmm, so I think that we should try to break the arm patterns into multiple lines if the arm body is empty. If that is not possible, then put the empty block on the next line:

```rust
(AngleBracketedArg::Arg(_), None)
| (AngleBracketedArg::Constraint(_), Some(_)) => {}
```

```rust
// <= max width
UnsplitableVeryLongArmPattern =>
    {}

// > max width
UnsplitableVeryLongArmPattern => {}
```
