### ISSUE TITLE
Eats r#try! -> try! in macros

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rustfmt#4138]
I've not had time to do a lot of debugging here, but when doing an update of rustfmt in Rust (see the linked PR) we encountered a bug that rustfmt will apparently replace r#try! with try!, which is not an acceptable change to make on 2018 edition code. I've not attempted a reproduction outside of that one instance -- if this doesn't easily reproduce I'm not too worried by it.

We've fixed this in rust-lang/rust I believe with a manual #[rustfmt::skip] annotation. 

_Originally posted by @jonas-schievink in https://github.com/_render_node/MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxMzM3MzI4OA==/comments/review_comment_

**Comment by topecongiro** [comment]
Thank you for the report, though the link seems to be broken.

**Comment by calebcartwright** [comment]
GitHub is being weird with the links, but I believe this is it: https://github.com/rust-lang/rust/pull/71439#discussion_r413373288

**Comment by topecongiro** [comment]
@calebcartwright Thanks!

@Mark-Simulacrum I am not sure how the rustc repository uses rustfmt, but it seems that rustfmt is using edition 2015 to format the file.

**Comment by Mark-Simulacrum** [comment]
Ah, I think it might've actually been a bug with my editor configuration. Sorry for the noise!
