### ISSUE TITLE
Install is broken

### ISSUE THREAD

**Issue by beevans** [rust-lang/rustfmt#4143]
Running the install in step 1 takes 30+ minutes on my machine.  For comparison, building a linux kernel takes 5.

After it finally succeeds, I get "Could not run rustfmt, please make sure it is in your PATH".

**Comment by calebcartwright** [comment]
> Running the install in step 1 

Could you explain what you mean by "step 1"? Are you using rustup to grab rustfmt (`rustup component add rustfmt`) or are you trying to build and install rustfmt from source?

**Comment by beevans** [comment]
Turns out I had my environment all screwed up.  One of my teammates helped me out.

I wound up completely repaving and reinstalling rust from the ground up, which was helpful as I was getting binaries, not source.

I did have to run “rustup update” to actually get it to work after adding it.

**Comment by calebcartwright** [comment]
No worries, glad you got it working! For future reference you can also get in touch with the rustup folks over in https://github.com/rust-lang/rustup and/or in the wg-rustup channel on Discord if you have any questions/issues with rustup. 

Going to close this out accordingly
