### ISSUE TITLE
Extra indentation in matches! macros when many patterns

### ISSUE THREAD

**Issue by UltraMachine** [rust-lang/rustfmt#4153]
Code with `matches!` macros:
```rust
matches!(
    expr,
    Enum::Variant1
        | Enum::Variant2
        | Enum::Variant3
        | Enum::Variant4
        | Enum::Variant5
        | Enum::Variant6
);
```
The same code without macros (correctly formatted):
```rust
match expr {
    Enum::Variant1
    | Enum::Variant2
    | Enum::Variant3
    | Enum::Variant4
    | Enum::Variant5
    | Enum::Variant6 => true,
    _ => false,
}
```

**Comment by calebcartwright** [comment]
Thanks for the report @UltraMachine. This is the expected/correct formatting per the Style Guide (also a dup of #3208) so I'm going to close this.

In the former/`matches!` snippet, it's a binop expression as an arg, and [binop expressions must be indendented when multilined](https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/expressions.md#binary-operations). 

In the latter/`match` case, [match arm patterns](https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/expressions.md#match) are not indented

> If required to break the pattern, put each clause of the pattern on its own line with no additional indent, breaking before the |
