### ISSUE TITLE
#[cfg_attr(rustfmt, rustfmt::skip::macros(...))] does not work

### ISSUE THREAD

**Issue by tmandry** [rust-lang/rustfmt#4156]
Using `#[rustfmt::skip::macros(gen)]` successfully skips formatting in the following example. So does `#[cfg_attr(rustfmt, rustfmt::skip)]`. But combining these into `#[cfg_attr(rustfmt, rustfmt::skip::macros(gen))]` fails.

This also applies for #! attribute declarations. I want to use `cfg_attr` to avoid "unused attribute" lints on these.

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=32cffb86f11863ca3b2674b91063dbeb)

```rust
fn example() {
    gen!(f, "
        trait $trait_name {
            fn $func_name(self, $args_sig);
        }
    ")?;
}
```

**Comment by jhpratt** [comment]
#![doc(test(attr(rustfmt::skip::macros(date))))]` doesn't work either, presumably for similar reasons.

**Comment by topecongiro** [comment]
`#[cfg_attr(rustfmt, ...)]` is deprecated, you should use `#[rustfmt::...]` instead.

> I want to use cfg_attr to avoid "unused attribute" lints on these.

This seems like a compiler or a linter error to me. IIUC, the tool attribute has already been supported, and any attributes starting with `rustfmt` should trigger warnings or lints (cc https://github.com/rust-lang/rust/issues/44690).
