### ISSUE TITLE
rustfmt removes absolute import prefix

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rustfmt#4176]
It seems that rustfmt will convert absolute imports into relative imports.

I had my `rustfmt.toml` file with `merge_imports` on and I thought it was at fault, but even when I turn it off this happens. Even with a totally blank `rustfmt.toml` this happens.

This wouldn't be a huge deal except that within a macro that uses unsafe the macro _really_ needs to stick to an absolute import in the expansion.

This code:
```rust
#[macro_export]
#[cfg_attr(docs_rs, doc(cfg(target_feature = "avx2")))]
macro_rules! blend_i32_m128i {
    ($a:expr, $b:expr, $imm:expr) => {{
        let a: $crate::m128i = $a;
        let b: $crate::m128i = $b;
        const IMM: ::core::primitive::i32 = $imm;
        #[cfg(target_arch = "x86")]
        use ::core::arch::x86::_mm_blend_epi32;
        #[cfg(target_arch = "x86_64")]
        use ::core::arch::x86_64::_mm_blend_epi32;
        $crate::m128i(unsafe { _mm_blend_epi32(a.0, b.0, IMM) })
    }};
}
```
incorrectly becomes
```rust
#[macro_export]
#[cfg_attr(docs_rs, doc(cfg(target_feature = "avx2")))]
macro_rules! blend_i32_m128i {
    ($a:expr, $b:expr, $imm:expr) => {{
        let a: $crate::m128i = $a;
        let b: $crate::m128i = $b;
        const IMM: ::core::primitive::i32 = $imm;
        #[cfg(target_arch = "x86")]
        use core::arch::x86::_mm_blend_epi32;
        #[cfg(target_arch = "x86_64")]
        use core::arch::x86_64::_mm_blend_epi32;
        $crate::m128i(unsafe { _mm_blend_epi32(a.0, b.0, IMM) })
    }};
}
```

What's confusing is that I _cannot_ seem to reproduce this problem within the rust playground. I don't know if it's because I have this macro within a module and not at the top level of the crate or what.

My rustfmt version is `rustfmt 1.4.14-nightly (a5cb5d26 2020-04-14)`

**Comment by calebcartwright** [comment]
Are you running rustfmt via `cargo fmt` or via `rustfmt`, and if the latter, do you have `edition = "2018"` set in your rustfmt config file?

**Comment by Lokathor** [comment]
I was using `rustfmt` because that seems to be how the "format on save" of VS Code seems to do it.

And no, I did not have that set. Putting it in seems to solve this issue. Thanks!
