### ISSUE TITLE
Not doing anything on a simple piece of code

### ISSUE THREAD

**Issue by sylvestre** [rust-lang/rustfmt#4183]
rustfmt isn't doing anything on the following code:
```
pub fn uumain(args: Vec<String>) -> i32 {
    let matches = App::new(executable!())
        .arg(            Arg::with_name(OPT_CHANGE)
            .short("c").long("ch")
)
        .arg(
            Arg::with_name(OPT_DEREFERENCE).help("aazezae affect the referent of each symbolic link this is qthe default the symbolic link itself"));
}
```
which is obviously incorrect formatted
(I am experiencing the same issue on a file which compiles)

```
$ rustfmt --check a.rs ; echo $?
0
```
with rustfmt 1.4.12-stable (a828ffe 2020-03-11)

**Comment by sylvestre** [comment]
This is because help(STRING) is too long. But rustfmt should still try to reformat the rest.

**Comment by calebcartwright** [comment]
Closing as a duplicate in favor of #3863
