### ISSUE TITLE
Set CFG_RELEASE_CHANNEL and CFG_RELEASE env vars when building rustfmt

### ISSUE THREAD

**Issue by topecongiro** [rust-lang/rustfmt#4185]
After updating rustc-ap-* crates to 659.0.0, it is now required to set both `CFG_RELEASE_CHANNEL` and `CFG_RELEASE` environment variables.

Unfortunately, cargo does not seem to provide a way to pass environment variables down to dependencies; we need to define it before running cargo.

We need to write a build script or add a build tool like `cargo-make`, which sets both environment variables to `nightly` when they are undefined. 
 We need this check before `cargo check`, `cargo build`, `cargo test` and `cargo publish`.

**Comment by calebcartwright** [comment]
I'm not opposed to leveraging additional scripts or tooling, but I wonder how well those would play with editor/IDE extensions and the impact that may have on contributors (for example I believe Rust Analyzer uses `cargo check` extensively and we'd have to advise users on how to configure things when working on rustfmt).

I wonder if we could leverage the existing cargo settings file we have (though not immediately sure which config key(s) it would be)
https://doc.rust-lang.org/cargo/reference/config.html#configuration-format

**Comment by ayazhafiz** [comment]
I can't get master to build even with the env variables set (mac, `rustc 1.45.0-nightly (a74d1862d 2020-05-14)` and `cargo 1.45.0-nightly (cb06cb269 2020-05-08)`):

```
export CFG_RELEASE_CHANNEL=nightly
export CFG_RELEASE=nightly
cargo build
# fails to build rustc_span-659
```

Am I missing something?

**Comment by topecongiro** [comment]
@ayazhafiz You are probably not using the latest nightly compiler. It is recommended to use the latest nightly when working on rustfmt.

**Comment by ayazhafiz** [comment]
You're right. Thanks.
