### ISSUE TITLE
Error formatting code which compiles, attributes not yet allowed on `if` statements

### ISSUE THREAD

**Issue by neandrake** [rust-lang/rustfmt#4193]
This code compiles with rust 1.43.1
```rust
fn main() {
    #[cfg(feature = "fmttest")]
    if true {
        println!("Hello, world!");
    }
}
```

Using `fmt` gives this error:
```console
$ cargo fmt
error: attributes are not yet allowed on `if` expressions
 --> ../fmttest/src/main.rs:2:5
  |
2 |     #[cfg(feature = "fmttest")]
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

It's not clear what happened. Here are different ways this error message could be interpreted
1. Does this mean that `fmt` error'd and possibly left formatting incomplete on the crate?
2. Does this mean that `fmt` does not support this code yet and this line will be left untouched, but other lines will be formatted?
2. Does this mean that rust doesn't yet support attributes on `if` statements? The phrase "not allowed" tells me that nothing about this should work, but both `rustc` and `clippy` succeed in compiling without any warnings.

I tried searching existing opened or closed tasks but did not find anything that seemed related.

**Comment by calebcartwright** [comment]
What version of rustfmt are you using (`rustfmt --version`)?

rustfmt internally uses a pinned version of the rustc parser, and even on nightly, that version of the parser is typically a few weeks old.

**Comment by neandrake** [comment]
It should be whatever version is installed with rustup using stable toolchain (I don't have any other version toolchain installed)

```
$ rustfmt --version
rustfmt 1.4.12-stable (a828ffea 2020-03-11)
```

**Comment by calebcartwright** [comment]
Thank you @neandrake. rustfmt is versioned independently, so we always need to get back to the rustfmt version. It helps us out a lot when folks can provide their corresponding version of rustfmt because we're always working on the latest nightly toolchain and rustfmt.

This issue is already fixed within nightly rustfmt (at least in 1.4.14, perhaps even in 1.4.13) so I'm going to close this as there's nothing else we can do on our end. 

Not sure when 1.4.13 will land on stable, but in the interim you could either use rustfmt from nightly or leverage #[rustfmt::skip] (https://github.com/rust-lang/rustfmt#tips) if not.

**Comment by neandrake** [comment]
Thank you @calebcartwright, and I will make sure to include version of rustfmt in future reports. For the time being I only have one of these so I just comment it out when running `cargo fmt` and uncomment afterwards.

In general how should I interpret `error: ` from `rustfmt`? Does that mean the line was skipped for formatting, or does `fmt` stop processing the file altogether -- or the crate altogether when this happens?

**Comment by calebcartwright** [comment]
no worries @neandrake! 

I'm not clear if you are asking about the meaning/cause of the specific error discussed in this thread, and/or messages with an `error:` prefix, and/or if rustfmt formatted anything in your use case where you received this error, and/or something else. 

As such I'll try to cover the spectrum but feel free to ask follow ups if I've missed the question or anything is unclear. 

* The error you encountered was a rustc parser error. Think we covered that one above already
* The `error:` prefix is used in the event of a critical error condition that _prevents_ formatting (for example try running `rustfmt src/some_fake_file.rs)`. There are other things (like warnings or `internal error`) that can occur and be emitted during/after formatting
* At a really high level, rustfmt works by using the rustc parser to generate the corresponding AST for the specified input (be it the entire crate or a single file), and then that AST is used to format and emit the entirety of the specified input. If there's a parser error (like there was here), rustfmt cannot do any formatting; there is no partial formatting of lines/files.
    * Note you can also use the `--check`  and/or `-l` options if you want to see details about any formatting differences rustfmt would emit in the case of the former, or the files it did modify in the case of the latter.
