### ISSUE TITLE
`wrap_comments = true` breaks markdown tables

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rustfmt#4210]
`cargo fmt -- --config wrap_comments=true` turns this:
```rust
/// doc
///
/// Table that is > 80 symbols:
///
/// | table | xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx |
/// |-------|--------------------------------------------------------------------|
/// | val   | x                                                                  |
struct Item;
```
![image](https://user-images.githubusercontent.com/38225716/82982633-43b69880-9ff7-11ea-9998-8bd043489b66.png)

Into this:
```rust
/// doc
///
/// Table that is > 80 symbols:
///
/// | table | xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
/// |
/// |-------|--------------------------------------------------------------------|
/// | val   | x
/// |
struct Item;
```
![image](https://user-images.githubusercontent.com/38225716/82982706-647eee00-9ff7-11ea-94c4-f9d7a5420d0c.png)

It's possible to work around this issue by adding `#[rustfmt::skip]` to the struct (or other documented item), but I think it's a bug anyway.

**Comment by Nemo157** [comment]
What is necessary to perform the backport here? If it's just cherry-picking the commits onto another branch I'm willing to do that if you let me know which branch.

**Comment by ytmimi** [comment]
@Nemo157, thanks for your interest. It might be as simple as a cherry-pick, but I don't know. I believe this is the PR #4214
