### ISSUE TITLE
No opinion on the semicolon after items defined within functions?

### ISSUE THREAD

**Issue by iago-lito** [rust-lang/rustfmt#4222]
I have noticed that `rustfmt` leaves those 2 equivalent functions unchanged, although they are differently formatted:

```rust
fn first_function() -> ReturnType {
    struct inner_item {
        field: u32,
    }; // <- With a semicolon.
    last_expression
}

fn second_function() -> ReturnType {
    struct inner_item {
        field: u32,
    } // <- Without a semicolon.
    last_expression
}
```

Is this something that `rustfmt` should have an opinion about?

I would like the answer to be *yes*, because I would not have to choose myself whether to write this semicolon or not.

But I would understand that the answer be *no*, because `;` is an additional (empty) statement that does not appear in the `second_function`, so the two functions are somewhat different. However, if this is how `rustfmt` stands, then it should maybe reformat the first snippet to

```rust
fn first_function() -> ReturnType {
    struct inner_item {
        field: u32,
    }
    ; // <- Make it clear that this is additional, empty statement.
    last_expression
}
```

**Comment by iago-lito** [comment]
FWIW, I've found that [RFC2479](https://github.com/rust-lang/rfcs/pull/2479) is about this very semilon.

**Comment by ayazhafiz** [comment]
Rustfmt already elides empty statements (per [a comment](https://github.com/rust-lang/rfcs/pull/2479#issuecomment-397861880) on the RFC mentioned above, maybe this is actually unsafe?), so I think it is reasonable to elide the semicolon in this case too.
