### ISSUE TITLE
environment variable `CFG_RELEASE_CHANNEL` not defined

### ISSUE THREAD

**Issue by Timmmm** [rust-lang/rustfmt#4230]
I'm trying to build the latest version on Mac with this command:

    CARGO_NET_GIT_FETCH_WITH_CLI=true cargo +nightly install --force --branch master --git https://github.com/rust-lang/rustfmt.git

But it gives the following errors:

```
   Compiling rustc-ap-rustc_parse v659.0.0
error: environment variable `CFG_RELEASE_CHANNEL` not defined
   --> /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_attr-659.0.0/builtin.rs:655:27
    |
655 |             let channel = env!("CFG_RELEASE_CHANNEL");
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: environment variable `CFG_RELEASE` not defined
   --> /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_attr-659.0.0/builtin.rs:657:48
    |
657 |             let rustc_version = Version::parse(env!("CFG_RELEASE")).unwrap();
    |                                                ^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

Any ideas? I found it mentioned in #4174 but that seems to imply that it has been fixed. Am I missing something?

**Comment by Timmmm** [comment]
[This comment](https://github.com/rust-lang/rust/issues/72232#issuecomment-633156901) suggests I need rustc version `rustc 1.45.0-nightly (d79f1bd31 2020-05-17)` but I have a later one:

```
✗ ~/.rustup/toolchains/nightly-x86_64-apple-darwin/bin/rustc --version
rustc 1.45.0-nightly (fe10f1a49 2020-06-02)
```

**Comment by calebcartwright** [comment]
You're going to have to set the environment variables (`CFG_RELEASE_CHANNEL` and `CFG_RELEASE`) in order to build rustfmt from source due to recent upstream changes in the rustc tree. 

We've updated the Contributing docs to call this out, though looks like we forgot to update the corresponding section in the readme
https://github.com/rust-lang/rustfmt/blob/master/Contributing.md#building-and-testing

**Comment by Timmmm** [comment]
Ah cool, I changed the command to this:

    CFG_RELEASE_CHANNEL=nightly CFG_RELEASE=nightly CARGO_NET_GIT_FETCH_WITH_CLI=true cargo +nightly install --force --branch master --git https://github.com/rust-lang/rustfmt.git

And it compiled successfully! But then gives this error:

```
    Finished release [optimized] target(s) in 1m 47s
error: no binaries are available for install using the selected features
```

Any ideas?

**Comment by Timmmm** [comment]
Ah I see it doesn't build anything by default. This command works perfectly - might be worth adding to the Readme?

    CFG_RELEASE_CHANNEL=nightly CFG_RELEASE=nightly CARGO_NET_GIT_FETCH_WITH_CLI=true cargo +nightly install --force --branch master --git https://github.com/rust-lang/rustfmt.git --features "rustfmt cargo-fmt"

**Comment by ahl** [comment]
> We've updated the Contributing docs to call this out, though looks like we forgot to update the corresponding section in the readme
> https://github.com/rust-lang/rustfmt/blob/master/Contributing.md#building-and-testing

Should the main README.md be updated to refer to these docs? This is what it currently says:

```
## How to build and test

`cargo build` to build.

`cargo test --manifest-path rustfmt-core/Cargo.toml` to run all tests.
```

**Comment by calebcartwright** [comment]
Yes. I'm going to update this (and a few other minor items) in the docs later today
