### ISSUE TITLE
unexpected io error when formatting with `$`

### ISSUE THREAD

**Issue by derekdreery** [rust-lang/rustfmt#4231]
I get the following error: `Error writing files: io error: Failed to find module module in "/home/me/devel/non-work/sandbox-rs/rustfmt_issue/src" None`

from the following example

> `src/main.rs`
```rust
mod module;

pub fn main() {
}
```

> `src/module.rs`
```rust
fn some_fn() {
    $name
}
```

It seems that the dollar in a module is confusing rustfmt. Note that if you move the erroneous `$` into `main.rs` then rustfmt correctly emits an unexpected token error.

I checked and this also happens on nightly

**Comment by derekdreery** [comment]
Interestingly,  this is the content of `module.rs` after running `cargo fmt`

```rust
fn some_fn() {
    }
    }
}
```

**Comment by calebcartwright** [comment]
What version of rustfmt are you using? (`rustfmt --version`)

**Comment by derekdreery** [comment]
`rustfmt 1.4.14-stable (e417356 2020-04-21)`
and
`rustfmt 1.4.15-nightly (aedff61 2020-05-19)`

**Comment by calebcartwright** [comment]
Thanks! This was related to parser issue with invalid syntax in submods. It's already been fixed within rustfmt and will be included in the next release. I'm going to go ahead and close this accordingly
