### ISSUE TITLE
Multi-byte UTF-8 characters and spacing

### ISSUE THREAD

**Issue by ralpha** [rust-lang/rustfmt#4241]
Code with multi-byte characters when encoded as UTF-8 are counted as multiple characters.
This will will throw of spacing.
The code below is formatted using `rustfmt 1.4.15-nightly (aedff61 2020-05-19)`
```rust
fn test() {
    match b {
        0xf4 => "⌠", //  0x2320  TOP HALF INTEGRAL
        0xf5 => "⌠", //  0x2321  BOTTOM HALF INTEGRAL
        0xf6 => "÷",  //  0x00f7  DIVISION SIGN
        0xf7 => "≈", //  0x2248  ALMOST EQUAL TO
        0xf8 => "°",  //  0x00b0  DEGREE SIGN
        0xf9 => "∙", //  0x2219  BULLET OPERATOR
        0xfa => "·",  //  0x00b7  MIDDLE DOT
        0xfb => "√", //  0x221a  SQUARE ROOT
        0xfc => "ⁿ", //  0x207f  SUPERSCRIPT LATIN SMALL LETTER N
        0xfd => "²",  //  0x00b2  SUPERSCRIPT TWO
    }
}
```
You can see that the comment after char `√` (E2 88 9A in utf-8) and `·` (C2 B7) is indented differently.
`√` has 1 space in between `,` and `//` where as `·` has 2. This is because it want to match the bytes instead of the characters width. (as with monospaced fonts each character is 1 space\*)
*(\*) except from some emoticons, sometimes...*

It would be nicer if the character length was taken into account so both `√` would be counted as 1 char (not 2 or 3) `·` This would align all the `//`.

Example:
```rust
fn test() {
    match b {
        0xf4 => "⌠", //  0x2320  TOP HALF INTEGRAL
        0xf5 => "⌠", //  0x2321  BOTTOM HALF INTEGRAL
        0xf6 => "÷", //  0x00f7  DIVISION SIGN
        0xf7 => "≈", //  0x2248  ALMOST EQUAL TO
        0xf8 => "°", //  0x00b0  DEGREE SIGN
        0xf9 => "∙", //  0x2219  BULLET OPERATOR
        0xfa => "·", //  0x00b7  MIDDLE DOT
        0xfb => "√", //  0x221a  SQUARE ROOT
        0xfc => "ⁿ", //  0x207f  SUPERSCRIPT LATIN SMALL LETTER N
        0xfd => "²", //  0x00b2  SUPERSCRIPT TWO
    }
}
```

**Note:** emoticons will trow it of even more:
```rust
fn test() {
    match b {
        0x00 => "a",    // hex 61
        0xfb => "√",  // hex E2 88 9A
        0xfc => "ⁿ",  // hex E2 81 BF
        0xfd => "²",   // hex C2 B2
        0xfe => "■",  // hex E2 96 A0
        0xff => "😈", // hex F0 9F 98 88
    }
}
```
As `😈` is F0 9F 98 88 so 4 bytes long.

(Sorry if this is already address somewhere else could not find it.)

**Comment by topecongiro** [comment]
@ralpha Thank you for reporting an issue; this is indeed already fixed and will be included in the next major version release.

Closing as duplicate.
