### ISSUE TITLE
Comment removed in type bound

### ISSUE THREAD

**Issue by ayazhafiz** [rust-lang/rustfmt#4243]
```rust
    type Err : Debug /*Display*/ + Reifiable + Clone;
```
...goes to:
```rust
    type Err: Debug + Reifiable + Clone;
```

...I agree that I probably should not have put a comment there, though

_Originally posted by @paulstansifer in https://github.com/rust-lang/rustfmt/issues/2781#issuecomment-507064482_

**Comment by whizsid** [comment]
I am working on this issue,
