### ISSUE TITLE
Comment dropped between & and typename in parameter type

### ISSUE THREAD

**Issue by ayazhafiz** [rust-lang/rustfmt#4245]
```
pub fn a(_: &/*'static*/()) {}
```

becomes

```
pub fn a(_: &()) {}
```

any reason why this (kind of critical) bug hasn't been fixed yet? It's almost open for a year now.

_Originally posted by @hellow554 in https://github.com/rust-lang/rustfmt/issues/2781#issuecomment-496403822_

**Comment by ayazhafiz** [comment]
@hellow554 why is this kind of critical? I understand the intention to implicitly say this type is static, but it doesn't change the semantics of the program.

**Comment by whizsid** [comment]
I am working on this issue.
