### ISSUE TITLE
rustfmt breaks code even further

### ISSUE THREAD

**Issue by zakarumych** [rust-lang/rustfmt#4249]
Given the syntactically broken code
```
fn foo() {
    if foo => {
        bar
    }
}
```

rustfmt doesn't emit an error but simply rewrites it as

```
fn foo() {
    }
    }
}
```

This happens only if that code is part of the module and being formatted indirectly.

**Comment by zakarumych** [comment]
Here's [reproduction](https://github.com/zakarumych/rustfmt-issue)
Running `cargo fmt` or `rustfmt src\main.rs` yields this weird result.

Running `rustfmt src\foo.rs` has expected behavior:
```
  |
2 |     if foo => {
  |     --     ^^ expected `{`
  |     |
  |     this `if` expression has a condition, but no block
```

**Comment by zakarumych** [comment]
Only nightly channel is affected

**Comment by calebcartwright** [comment]
Thank you for the report @zakarumych! This is a duplicate (#4126) that has already been fixed in source. Closing accordingly
