### ISSUE TITLE
rustfmt eating up my where clauses on generic associated types

### ISSUE THREAD

**Issue by steffahn** [rust-lang/rustfmt#4257]
```rust
#![feature(generic_associated_types)]
#![allow(incomplete_features)]

trait Trait<T> {
    type Type<'a> where T: 'a;
    fn foo(x: &T) -> Self::Type<'_>;
}
impl<T> Trait<T> for () {
    type Type<'a> where T: 'a = &'a T;
    fn foo(x: &T) -> Self::Type<'_> {
        x
    }
}
```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=fcfc17ef1cfcda2193d1439a3ddaa511))

The result after applying `rustfmt`:
```rust
#![feature(generic_associated_types)]
#![allow(incomplete_features)]

trait Trait<T> {
    type Type<'a>;
    fn foo(x: &T) -> Self::Type<'_>;
}
impl<T> Trait<T> for () {
    type Type<'a> = &'a T;
    fn foo(x: &T) -> Self::Type<'_> {
        x
    }
}
```

**Comment by calebcartwright** [comment]
Thank you for the report @steffahn. This has already been fixed within rustfmt, just not yet released. Accordingly I am going to go ahead and close this as there's no additional changes to be made within rustfmt.

In the meantime you may want to consider using `#[rustfmt::skip]` on your types to keep rustfmt from mangling them.
