### ISSUE TITLE
max_width isn't documented in https://rust-lang.github.io/rustfmt/?#max_width

### ISSUE THREAD

**Issue by sourcefrog** [rust-lang/rustfmt#4265]
This page has many options that say "see also `max_width`" but that argument itself isn't documented anywhere in the page, when the version is set to 2.0.

If I set the version back to 1.4.17 it does show up.

Is it being removed?

**Comment by calebcartwright** [comment]
Thanks for the question @sourcefrog 

The detail sections for config options aren't URI accessible on the GH pages site (refs #4261), but the `max_width` section is indeed there (including when version is set to 2.0) and we're certainly not removing it; you just have to scroll down to it.

**Comment by sourcefrog** [comment]
Ah, yep, basically just a dupe of 4261.
