### ISSUE TITLE
cargo fmt stopped working since 1.44.0

### ISSUE THREAD

**Issue by xStrom** [rust-lang/rustfmt#4266]
I'm trying to format code for the [druid](https://github.com/xi-editor/druid) project.
Everything was working fine up until Rust 1.43.1 / rustfmt 1.4.12-stable (a828ffea 2020-03-11).

It no longer works properly with:
Rust 1.44.0 / rustfmt 1.4.14-stable (e4173566 2020-04-21)
Rust 1.44.1 / rustfmt 1.4.16-stable (939e164c 2020-06-11)

It does not seem to be platform dependant, the issue exists at minimum both on Windows 7 and macOS Catalina, and not just my machines.

The druid workspace consists of several packages including [`druid-shell`](https://github.com/xi-editor/druid/tree/master/druid-shell) which is the package that is problematic.

If I run `cargo fmt` inside the `druid-shell` package root then it works.

The problem is with using `cargo fmt` or `cargo fmt --all` in the workspace directory.
That used to also work, but now works only partially on `druid-shell`.

Some of the modules get formatted while others don't.
It seems to have something to do with the [`cfg-if`](https://crates.io/crates/cfg-if) macro.

A file of interest is [`druid-shell/src/platform/mod.rs`](https://github.com/xi-editor/druid/blob/master/druid-shell/src/platform/mod.rs), which has the following code:

```rust
cfg_if::cfg_if! {
    if #[cfg(target_os = "windows")] {
        mod windows;
        pub use windows::*;
    } else if #[cfg(target_os = "macos")] {
        mod mac;
        pub use mac::*;
    } else if #[cfg(all(feature = "x11", target_os = "linux"))] {
        mod x11;
        pub use x11::*;
    } else if #[cfg(target_os = "linux")] {
        mod gtk;
        pub use self::gtk::*;
    } else if #[cfg(target_arch = "wasm32")] {
        mod web;
        pub use web::*;
    }
}
```

If I delete that macro and replace it with a simple:
```rust
mod windows;
pub use windows::*;
```
Then the `windows` module gets formatted when I run `cargo fmt` in the workspace directory. However if the `cfg-if` macro is there, then none of these platform modules get formatted. Again, this is a recent regression and previously all those platform modules got formatted.

Any insight would be appreciated.

**Comment by topecongiro** [comment]
MWE:

```
rustfmt -cr \
        druid/examples/web/src/lib.rs \
        druid-shell/src/lib.rs
```

However, the below works correctly :thinking: 

```
rustfmt -cr \
        druid-shell/src/lib.rs

```

**Comment by calebcartwright** [comment]
I'm not sure we've ever fully supported this scenario (see #3253), even though I've convinced myself on a few occasions that we were previously close :laughing: 

Also FWIW, I'm able to reproduce the issue with rustfmt 1.4.12 in identical cfg_if scenarios

**Comment by calebcartwright** [comment]
It's also fixed in rustfmt 1.4.18 and on master/rustfmt 2.0. 

rustfmt 1.4.14 was the first rustfmt release that had to incorporate the fallout from the upstream parse/expansion split in rustc, and there were a few parser/mod resolution bugs that snuck through in rustfmt 1.4.14 and 1.4.16.

**Comment by topecongiro** [comment]
@calebcartwright I don't think this is fixed on the master; I can still reproduce this locally using the master branch.

--- 
This seems the problem: 
https://github.com/rust-lang/rustfmt/blob/5ac191d6451694ba9b5bb10766eb4a7f63353235/src/formatting/modules.rs#L24-L26

The `CFG_IF` is somehow changed to `//!` after formatting druid/examples/web/src/lib.rs. I have no idea why :shrug:

**Comment by calebcartwright** [comment]
well that's puzzling :thinking: I'll check again with 2.0

I'm pretty confident that 1.4.18 is fine though
```bash
$ cargo fmt --version
rustfmt 1.4.18-nightly (c1e9b7b8 2020-06-13)
$ cargo fmt -- --check
Diff in /home/caleb/dev/druid/druid-shell/src/window.rs at line 14:
 
 //! Platform independent window types.
 
-    use std::any::Any;
+use std::any::Any;
 use std::time::Duration;
 
 use _crate::application::Application;_
```

**Comment by topecongiro** [comment]
@calebcartwright You are modifying the wrong file :wink:  You should change one of the files under druid-shell/src/platform/ other than mod.rs.

**Comment by calebcartwright** [comment]
crikey :man_facepalming: 

sorry for the noise! I started looking at this earlier but had to stop, and assumed I had the right file up when I came back :laughing:
