### ISSUE TITLE
Formatting results in source code that GDB cannot properly parse

### ISSUE THREAD

**Issue by ryan-summers** [rust-lang/rustfmt#4269]
When running rustfmt on our source file, the resulting file appears to not be properly parsed by GDB. Specifically, setting break points no longer functions as expected and getting line info indicates invalid data.

It is not known whether  this is due to rustfmt or gdb.

Specifically, when running https://github.com/quartiq/stabilizer source code over gdb-multiarch, the following lines cause a parsing problem in GDB (although no error is displayed):
https://github.com/quartiq/stabilizer/blob/a3f5dbeae7af69696c7ddb907675086b20cc2a6e/src/main.rs#L174-L179

To demonstrate - 

* When running the code directly off `master`, GDB indicates the following:
![image](https://user-images.githubusercontent.com/8771450/85205847-28049080-b31e-11ea-9310-4256f2d3916e.png)
```
(gdb) b main.rs:200                                                                                                                                                                                        
Note: breakpoint 2 also set at pc 0x802fdfe.                                                         
Breakpoint 4 at 0x802fdfe: file src/main.rs, line 855.               
(gdb) info line main.rs:200                                                                                                                                                                                
Line 200 of "src/main.rs" is at address 0x802fdfa <HardFault> but contains no code.
(gdb)
```

* When updating the respective lines from 
```
net_interface: net::iface::EthernetInterface<
    `static,
    `static,
    `static,
    ethernet::EthernetDMA<'static>,
>,
```

to:
```
net_interface: net::iface::EthernetInterface<
    `static,
    `static,
    `static,
    ethernet::EthernetDMA<'static>>,
```

GDB will indicate the following:
![image](https://user-images.githubusercontent.com/8771450/85205906-aa8d5000-b31e-11ea-9b69-26af2e0c1161.png)
```
(gdb) b main.rs:200
Breakpoint 4 at 0x800e4ba: file src/main.rs, line 202.
(gdb) info line main.rs:200
Line 200 of "src/main.rs" is at address 0x800e4ba <stabilizer::init+90> but contains no code.
(gdb) info line main.rs:199
Line 199 of "src/main.rs" starts at address 0x800e4be <stabilizer::init+94> and ends at 0x800e4c2 <stabilizer::init+98>.
(gdb) 

```

Note that in the first example, continuing the program will never hit the configured breakpoint (because the breakpoint was not set to the correct memory address), but after the code is updated to remove the trailing comma after the template parameter, the breakpoint will behave as expected.

Take note that the breakpoints in both examples are set to drastically different addresses depending on whether or not the trailing comma and newline exist before the ending generic brace (`>`)

**Comment by ryan-summers** [comment]
https://doc.rust-lang.org/reference/items/generics.html#type-and-lifetime-parameters seems to indicate that the trailing comma within the template type is not allowed.

**Comment by ayazhafiz** [comment]
It seems like this is a bug with gdb's rust parser. Looking at the page you have linked, trailing commas in lifetime or type parameters are valid rust syntax. The grammar rule

```
TypeParams:
   ( TypeParam , )* TypeParam?
```

says "zero or more TypeParams with a comma, after which is an optional TypeParam". So the final TypeParam may or may not be followed by a comma.

**Comment by ryan-summers** [comment]
> It seems like this is a bug with gdb's rust parser. 

After looking into this more and playing around with the exact style (e.g. just deleting the trailing comma) and still seeing similar behavior from GDB, so I'm also leaning towards this being a GDB issue.

> Looking at the page you have linked, trailing commas in lifetime or type parameters are valid rust syntax. The grammar rule
> 
> ```
> TypeParams:
>    ( TypeParam , )* TypeParam?
> ```
> 
> says "zero or more TypeParams with a comma, after which is an optional TypeParam". So the final TypeParam may or may not be followed by a comma.

You're right here - when I first read it, I was misinterpreting the lexical structure as the last `TypeParam?` taking priority over the 0-or-more list of type params. However, It looks like a list of `<u16, u8, u16,>` should be accepted. Thanks for pointing that out

**Comment by ryan-summers** [comment]
I've now opened an issue with GDB: https://sourceware.org/bugzilla/show_bug.cgi?id=26148

**Comment by ryan-summers** [comment]
After some deubgging in the RTIC matrix channel, it was discovered that this is likely due to https://github.com/rust-lang/rust/issues/43081 - specifically, the rust compiler appears to be emitting invalid debug information. Because this doesn't relate to rustfmt (and a `rustc` issue already exists), I'm closing this one.
