### ISSUE TITLE
Would it be better to have "reorder_modules" default to false?

### ISSUE THREAD

**Issue by earthengine** [rust-lang/rustfmt#4275]
Say I have the following modules:

```
mod utils;
mod api;
```

and I put some local macros (only to be use within my crate) to `mod utils`, in this case the reordering of the modules will change the meaning of the program/module.

Unless it is not too hard to detect that `utils` module contains macros that would be used in `api` module, I think the safe default would be not to reorder it. Am I right? 

(FYI, I am experiencing this problem since I am using a real time formatter VS Code plugin)

**Comment by topecongiro** [comment]
Hmm, are you able to compile your code without `#[macro_use]` attribute on `mod utils;`? If the attribute is present, rustfmt will not reorder modules even when `reorder_moduels` is `true`.

**Comment by earthengine** [comment]
Yes I can. I put a `#![macro_use]` as the first line on my mod `utils`, so I didn't use a `#[macro_use]` attribute.

**Comment by Riateche** [comment]
I was hit by this issue today. Here's a MCVE, just to clarify the issue:

lib.rs
```
mod b;
mod a;
```

a.rs
```
my_macro!();
```

b.rs
```
#![macro_use]

#[macro_export]
macro_rules! my_macro {
    () => {};
}
```

This code compiles, but running `rustfmt` on it breaks the build because the macro is no longer visible in `a` module.
