### ISSUE TITLE
@-bindings are now formatted weirdly

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rustfmt#4287]
Just updated to `nightly-2020-06-23`.

@-bindings are now formatted weirdly. Please revert to how it was before:

![image](https://user-images.githubusercontent.com/535593/86001220-df7c5f80-ba0e-11ea-975b-bc529587dc81.png)

**Comment by topecongiro** [comment]
This issue is fixed on the latest master branch. We are planning to publish the next release in a couple of days. It will take a bit longer before the version gets available via rustup.
