### ISSUE TITLE
Comment disappearing after last where constraint

### ISSUE THREAD

**Issue by vincentisambart** [rust-lang/rustfmt#4289]
**Describe the bug**

When formatting, a comment after the last where constraint disappear.

**To Reproduce**

When formatting the following code, ` // comment on last constraint` disappears. It seems to happen on the last constraint, whatever the number of constraint is.
```rust
trait MyTrait
where
    Self: Clone, // comment on first constraint
    Self: Eq, // comment on last constraint
{
}
```

**Expected behavior**

The comment should not disappear.

**Meta**

- rustfmt version: rustfmt 1.4.18-nightly (c1e9b7b8 2020-06-13)
- From where did you install rustfmt?: rustup
- How do you run rustfmt: `rustfmt`

**Comment by calebcartwright** [comment]
Thanks for the report @vincentisambart. This reproducible with rustfmt 2.0 as well
