### ISSUE TITLE
destructive formatting when dealing with const generics

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rustfmt#4310]
When formatting 
```rust
#![feature(const_generics)]

fn foo<
    const N: [u8; {
        struct Inner<'a>(&'a ());
        3
    }],
>() {}
```
rustfmt changes the empty function argument list from `()` to  `(&'a ()`, which is incorrect.
```rust
#![feature(const_generics)]

fn foo<
    const N: [u8; {
        struct Inner<'a>(&'a ());
        3
    }],
>(&'a () {
}

```
Note that the original code snippet current does not yet compile due to the unfinished nature of const generics,
it should compile in the future though.

**Comment by calebcartwright** [comment]
Thanks for the report!

> Note that the original code snippet current does not yet compile due to the unfinished nature of const generics,
it should compile in the future though.

This is fairly common with new/unfinished syntax, and takes a little time for rustfmt to incorporate the upstream changes. The next snapshot of the rustc internals that rustfmt consumes will be published tomorrow so we'll take a look afterwards to see if the updated ast and parser mods will allow rustfmt to be able to format this correctly.
