### ISSUE TITLE
rustfmt silently removes code it can't parse

### ISSUE THREAD

**Issue by zserik** [rust-lang/rustfmt#4315]
**Describe the bug**

Currently, when rustfmt tries to format code which e.g. uses [`feature(generic_associated_types)`](https://github.com/rust-lang/rust/issues/44265), rustfmt produces no error messages, but removes code which causes previously working examples to fail compiling after formatting using `rustfmt`.

**To Reproduce**

The following diff describes the change currently performed by rustfmt:
```patch
 /// Helper trait for "stripping indention" from an object reference
 pub trait AsUnindented {
-    type Output<'ast> where Self: 'ast;
+    type Output<'ast>;
 
     /// Returns a reference to the unindented part of `Self`
     fn as_unindented<'ast>(&'ast self) -> Self::Output<'ast>;
 }
```

**Expected behavior**

Rustfmt should fail with either "Error writing files: failed to resolve mod `...`: cannot parse /...rs", or a more concise error message;
and skip the offending modules (not modifying them, except maybe removing simple stuff like trailing whitespace and double-newlines, which don't require fully parsed code) and all submodules of them.

**Meta**

- rustfmt version: `rustfmt 1.4.18-nightly (c1e9b7b 2020-06-13)`
- From where did you install rustfmt?: `rustup`
- How do you run rustfmt: `cargo fmt`

**Comment by ayazhafiz** [comment]
rustfmt should bail on non-parseable inputs today; for example,

```rust
fn f( {
}
```

fails quickly with a number of rustc parser error messages. The problem here is probably that rustfmt just isn't parsing the generic bound of the associated type.

**Comment by ayazhafiz** [comment]
I think this was fixed in https://github.com/rust-lang/rustfmt/pull/4106/files#diff-d5afe6fbd84797013d4e4b0fc11d83e9R540-R541 but we don't seem to have any tests for it
