### ISSUE TITLE
Warning: Unknown configuration option `attr_fn_like_width`

### ISSUE THREAD

**Issue by GOKOP** [rust-lang/rustfmt#4318]
According to [this page](https://rust-lang.github.io/rustfmt/?version=master&search=#attr_fn_like_width), option "attr_fn_like_width" exists, but when I put `attr_fn_like_width = 90` in my rustfmt.toml, I get a warning: "Warning: Unknown configuration option `attr_fn_like_width`"

- rustfmt version: rustfmt 1.4.16-stable (939e164 2020-06-11)
- From where did you install rustfmt?: rustup
- How do you run rustfmt: `$ rustfmt file.rs`

**Comment by calebcartwright** [comment]
You're looking at the config options for rustfmt in source on the master branch, but you are using rustfmt 1.4.16. Make sure you select the version of rustfmt that coincides with the version you are using.

Believe the direct link would be: https://rust-lang.github.io/rustfmt/?version=v1.4.16
