### ISSUE TITLE
Dealing with error retrieving tags/version on GitHub Pages Configuration documentation

### ISSUE THREAD

**Issue by calebcartwright** [rust-lang/rustfmt#4319]
Currently on the configuration documentation hosted on GitHub Pages (https://rust-lang.github.io/rustfmt/) if there's any error retrieving the tags from the GH API then the page will silently fail to populate the version dropdown. Version specific docs can still be retrieved by using the url query param to set the version, but the dropdown/selector behavior is not ideal. 

One use case where I can imagine this popping up (which I ran into myself) is when you've hit GH's rate limits

I'm not sure this is an entirely avoidable scenario as long as the dropdown's being populated dynamically, but some kind of error message/banner would be a helpful addition. 

![image](https://user-images.githubusercontent.com/13042488/87206455-6236d180-c2cf-11ea-9714-8d0e975d4e26.png)

**Comment by ayazhafiz** [comment]
Rejection of these two promises needs to be handled:

https://github.com/rust-lang/rustfmt/blob/e438529f736cd6d10e91eabafbc9db232c37e053/docs/index.html#L174
https://github.com/rust-lang/rustfmt/blob/e438529f736cd6d10e91eabafbc9db232c37e053/docs/index.html#L119

(the second one already is, but the error message is not helpful)

A backoff could be added as well: https://github.com/aishek/axios-rate-limit

[60 unauth'd requests per hour](https://developer.github.com/v3/#rate-limiting) seems rather ridiculous for GitHub...
