### ISSUE TITLE
String literals with unescaped \ in the end of line is not formatted

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rustfmt#4321]
**Describe the bug**

The Rust reference has an [exception rule](https://doc.rust-lang.org/nightly/reference/tokens.html#string-literals) about unescaped `\` at the end of line
of string literals, quoted here:

> when an unescaped `U+005C` character (`\`) occurs immediately before the line-break, 
> then the `U+005C` character, the line-break, and all whitespace at the beginning of 
> the next line are ignored.

It would be nice if rustfmt format this snippet:

```rust
pub fn foo() -> &'static str {
    "use of std::thread::current() is not \
                                          possible after the thread's local \
                                          data has been destroyed"
}
```

into

```rust
pub fn foo() -> &'static str {
    "use of std::thread::current() is not \
     possible after the thread's local \
     data has been destroyed"
}
```

**Meta**

- rustfmt version: 1.4.18-nightly (2020-06-13 c1e9b7b) which is the one on playground
- Might be a duplicate of #2876 .

**Comment by ayazhafiz** [comment]
I think the issues are different; in 2876, the whitespace is significant and it's more about formatting in the context of a call

**Comment by ayazhafiz** [comment]
You can already sort-of do this with the [format_strings option](https://rust-lang.github.io/rustfmt/?version=master&search=format_string#format_strings), which does a little more:

```rust
pub fn foo() -> &'static str {
    "use of std::thread::current() is not \
                                          possible after the thread's local \
                                          data has been destroyed"
}
```

would go to

```rust
pub fn foo() -> &'static str {
    "use of std::thread::current() is not possible after the thread's local data has been \
     destroyed";
}
```

Would that work for your use case?

**Comment by lzutao** [comment]
Thanks. Never know about this configuration.
Are there any reasons thus is off by default?

**Comment by ayazhafiz** [comment]
It just was never turned on as a stable option, there is a tracking issue here: #4036

**Comment by lzutao** [comment]
I try that configuration a bit. It is useful and nice. But I would like to preserve the ending '\'
in each line, which mean that the configuration would not join multiline together.
For example, this diff is harder to read:
```diff
             rustflags.arg("-Zsave-analysis");
             cargo.env(
                 "RUST_SAVE_ANALYSIS_CONFIG",
-                "{\"output_file\": null,\"full_docs\": false,\
-                       \"pub_only\": true,\"reachable_only\": false,\
-                       \"distro_crate\": true,\"signatures\": false,\"borrow_data\": false}",
+                "{\"output_file\": null,\"full_docs\": false,\"pub_only\": \
+                 true,\"reachable_only\": false,\"distro_crate\": true,\"signatures\": \
+                 false,\"borrow_data\": false}",
             );
         }
```

**Comment by lzutao** [comment]
Also, is this a bug?

**Comment by ayazhafiz** [comment]
> But I would like to preserve the ending `\`
> in each line, which mean that the configuration would not join multiline together.
> For example, this diff is harder to read:

Yeah that makes sense. I agree the formatted version is harder to read. But I think it is unlikely that an option to only format the alignment of a string without formatting other parts of the string would be accepted. In some sense this is a custom formatting.

> Also, is this a bug?

Yes, it looks like it. Can you share the entire bench function where that happened?

**Comment by lzutao** [comment]
Yes, it here: https://github.com/rust-lang/rust/blob/4007d4ef26eab44bdabc2b7574d032152264d3ad/src/liballoc/benches/str.rs#L131

I was trying to use that formatting configuration on Rust repo. But I'm afraid it couldn't be accepted
as the result is not nicer to read.

**Comment by ayazhafiz** [comment]
Yes I think it’s unlikely to be accepted.

________________________________
От: lzutao <notifications@github.com>
Отправлено: Saturday, July 11, 2020 9:40:52 PM
Кому: rust-lang/rustfmt <rustfmt@noreply.github.com>
Копия: hafiz <ayaz.hafiz.1@gmail.com>; Comment <comment@noreply.github.com>
Тема: Re: [rust-lang/rustfmt] String literals with unescaped \ in the end of line is not formatted (#4321)


Yes, it here: https://github.com/rust-lang/rust/blob/4007d4ef26eab44bdabc2b7574d032152264d3ad/src/liballoc/benches/str.rs#L131

I was trying to use that formatting configuration on Rust repo. But I'm afraid it couldn't be accepted
as the result is not nicer to read.

**Comment by ayazhafiz** [comment]
@lzutao is there any further action we can take here, aside #4323? If not, is it worth closing this issue?

**Comment by lzutao** [comment]
I still don't like that strings are merged and formatted. But that's probably a separate issue/RFC for fmts.
But I don't have strong desire for that.
Thanks for your helpful feedback. Closing!
