### ISSUE TITLE
`where` removed between type name and =

### ISSUE THREAD

**Issue by kgtkr** [rust-lang/rustfmt#4322]
Relation #4244
GAT: https://github.com/rust-lang/rust/issues/44265

**Describe the bug**
```rs
trait Bar {
  type X<'a> where Self: 'a;
}
```
↓format
```rs
trait Bar {
  type X<'a>;
}
```

Similar phenomenon occurs in impl Trait

**Expected behavior**
Code is not removed.

**Meta**

- rustfmt version: 
rustfmt 1.4.18-nightly (c1e9b7b8 2020-06-13)
- From where did you install rustfmt?: 
rustup
- How do you run rustfmt: 
editor save on format(vscode rls)

**Comment by ayazhafiz** [comment]
dupe of #4315

**Comment by kgtkr** [comment]
@ayazhafiz  Thanks, close this issue
