### ISSUE TITLE
error[E0642]: patterns aren't allowed in methods without bodies

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rustfmt#4324]
**Describe the bug**

rustfmt failed to format this [iterator.rs](https://github.com/rust-lang/rust/blob/9d09331e00b02f81c714b0c41ce3a38380dd36a2/src/libcore/iter/traits/iterator.rs) with the error message:

```rust
% rustfmt src/libcore/iter/traits/iterator.rs
error[E0642]: patterns aren't allowed in methods without bodies
    --> /home/lzutao/fork/rust/compiler/src/libcore/iter/traits/iterator.rs:1738:51
     |
1738 |     fn partition_in_place<'a, T: 'a, P>(mut self, ref mut predicate: P) -> usize
     |                                                   ^^^^^^^^^^^^^^^^^
     |
help: give this argument a name or use an underscore to ignore it
     |
1738 |     fn partition_in_place<'a, T: 'a, P>(mut self, _: P) -> usize
     |                                                   ^

```

**Expected behavior**

I think since rustc allow that code, rustfmt shouldn't disallow that code.

**Meta**

- rustfmt version: rustfmt 1.4.18-nightly (c1e9b7b 2020-06-13)
- From where did you install rustfmt?: rustup
- How do you run rustfmt: rustfmt

**Comment by ayazhafiz** [comment]
rustfmt uses the rustc parser. It is likely that the version of the parser being used in rustc is more up to date than the version of the parser shipped with rustfmt 1.4.18

**Comment by ayazhafiz** [comment]
This formats on master, just a rustc parser discrepancy

**Comment by lzutao** [comment]
Thanks for investigation. Should I leave this issue open until rustfmt is updated ?

**Comment by calebcartwright** [comment]
Up to you @lzutao! Feel free to go ahead and close if you'd prefer, otherwise we'll close as part of adding a regression test case for this (since it's already fixed in source and will be out in the next rustfmt release)

**Comment by lzutao** [comment]
Thanks.
