### ISSUE TITLE
Target behavior for handling stdin input

### ISSUE THREAD

**Issue by calebcartwright** [rust-lang/rustfmt#4342]
(opening this to facilitate a focused discussion on a topic brought up by another user in various other threads)

One requirement of rustfmt is that it must support formatting strings of Rust code via stdin (in addition to formatting .rs files of course), so this is indeed a provided feature in rustfmt 1.x today. 

Instead of running rustfmt against files (e.g. `rustfmt src/main.rs --edition 2018 --check`) rustfmt can be used with stdin which can either be piped:

```bash
$ echo "fn         foo   (   ) {         }" | rustfmt
fn foo() {}
```
Or in an active/edit mode if not piped:
```bash
$ rustfmt
fn
foo (   ) {  println!(     "bar")   ; }
# After flushing the buffer with `CTRL+D` the below is emitted
fn foo() {
    println!("bar");
}
```

This second mode is beneficial for users operating with stdin because it operates as a sandbox of sorts that allows for writing code more natively, doesn't require escaping things like quotations, explicit newline chars, etc. and is easier to copy/paste in code snippets from elsewhere for the same reasons. 

A tradeoff of sorts with this feature is that running `rustfmt` without any args or special flags (like `--help` or `--version`) is a valid command that takes users into the interactive stdin mode, which is a relatively unknown and currently not particularly well documented feature (though we're working to improve the docs #4336), so if a user assumes that `rustfmt` is an invalid command in and of itself then they could be surprised/expecting the rustfmt help text to display instead (which is common CLI behavior on invalid command, for example as seen with `cargo fmt adfasdf`).

**So the question**: whenever we have the next major/breaking version of rustfmt, do we want to maintain the interactive formatting mode and point users to `rustfmt --help` for help text _or_ do we want to drop the interactive formatting feature so that both `rustfmt` and `rustfmt --help` can be used to print help text. 

I'm strongly in favor of maintaining the current feature and behavior. 

cc @topecongiro

**Comment by calebcartwright** [comment]
@NickelCoating - I've opened this on your behalf because you seemed to feel pretty strongly that rustfmt should display help text instead of going into interactive formatting. If that's still true, then please use this issue to share your thoughts.

However, I would ask that you first please read the full issue description to familiarize yourself with the current feature and how it's leveraged by other users (even if that's not a usage pattern for you personally). If afterwards you still feel a change should be made, then please make your case for what you think should be changed, and why, so that we can have a constructive discussion.

**Comment by topecongiro** [comment]
I haven't gone through the original discussion, but I don't consider changing the default behavior as an option.

**Comment by ayazhafiz** [comment]
I agree, changing the default behavior breaks existing users who will then be wondering why rustfmt doesn't read from stdin by default. Imo it is easier and better to keep with the current and improve the documentation for new users.

**Comment by NickelCoating** [comment]
Personally, as somebody with a high level language and tooling background, I do prefer an IDE like VS Code for quick stuff. 

But, I agree, leaving the behavior the way it already is, is better. Those who already know it and most importantly use it, for them it's not even about getting them confused, that things work differently then. It worse than that, it's taking away their way of doing things they like the way they used to do until now for some time. They may not care about the reasons for that change, and they may not have to care. `rustfmt` is still a bit different than `cargo` and `rustup` undoubted. It got its _special needs_.

Extending the docs regarding the stdin instead, should be a good middle ground to fix this issue for new users who wonder why there is no usage information like with `cargo`, `rustup`, and even old jazz tooling for Quake 1 among other idiomatic terminal apps displaying the same behavior of printing usage information.

**Comment by calebcartwright** [comment]
Thanks for the discussion all, going to go ahead and close this accordingly
