### ISSUE TITLE
rustfmt as a lib on stable

### ISSUE THREAD

**Issue by Hywan** [rust-lang/rustfmt#4347]
Hello,

I try to use `rustfmt` as a library on stable Rust. In https://github.com/rust-lang/rustfmt/issues/4346, it is said that 1.4.16 is the most recent version on stable. However, when I try the following:

```toml
rustfmt-nightly = { version = "1.4.16", default-features = false }
```

I get those errors from `rustfmt`'s dependencies:

```
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> …/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_graphviz-669.0.0/lib.rs:278:1
    |
278 | #![feature(rustc_private, nll)]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> …/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.4.1/lib.rs:74:32
   |
74 | #![cfg_attr(feature = "union", feature(untagged_unions))]
   |                                ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /…/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.4.1/lib.rs:76:37
   |
76 | #![cfg_attr(feature = "may_dangle", feature(dropck_eyepatch))]
```

Am I doing something wrong?

Thank you!

**Comment by calebcartwright** [comment]
hi @Hywan - the aforementioned comment from #4346 is a reference to the rustfmt tools that ship with Rust itself, which is separate from trying to install/consume rustfmt from crates.io. 

In order to build rustfmt from source or consume the rustfmt-nightly crate, you must do so with a nightly toolchain.

**Comment by calebcartwright** [comment]
I'm going to go ahead and close this as it's not possible to use rustfmt as a lib on stable, and that will continue to be the case for the foreseeable future.
