### ISSUE TITLE
Patterns in trait methods with bodies

### ISSUE THREAD

**Issue by elrnv** [rust-lang/rustfmt#4348]
**Describe the bug**

Function signatures in traits with bodies should be allowed to use patterns:
```rust
trait Trait {
    fn f([x, y]: [f64; 2]) {
        println!("{} {}", x, y);
    }
}
```
Running `rustfmt` on the code above produces:
```
error[E0642]: patterns aren't allowed in methods without bodies
 --> /home/egor/proj/rust-proto/src/rotate.rs:2:10
  |
2 |     fn f([x, y]: [f64; 2]) {
  |          ^^^^^^
  |
help: give this argument a name or use an underscore to ignore it
  |
2 |     fn f(_: [f64; 2]) {
  |          ^
```

**To Reproduce**

Format the above code snippet using `rustfmt` or `rustfmt +nightly`.

**Expected behavior**

No errors

**Meta**

- rustfmt version: 1.4.15-stable (530eadf 2020-06-02) and 1.4.18-nightly (c1e9b7b 2020-06-13)
- From where did you install rustfmt?: rustup
- How do you run rustfmt: `rustfmt`

**Comment by ayazhafiz** [comment]
This is due to 1.4.15/18 using an older version of the rustc parser than the version that added support for patterns in this context. On master, the version of the parser is up to date (I think scheduled for 1.4.19 or 2.0 release). @calebcartwright has more context

**Comment by calebcartwright** [comment]
Correct. rustfmt's broken on nightly ATM, but once available again it will contain the updated versions of the rustc internals that will support the syntax.

Closing as there's no additional action to be taken within rustfmt.

**Comment by RalfJung** [comment]
I am seeing this error with the current stage 0 rustfmt in the rustc repository:
```
$ ./build/x86_64-unknown-linux-gnu/stage0/bin/rustfmt compiler/rustc_middle/src/mir/interpret/pointer.rs
error[E0642]: patterns aren't allowed in methods without bodies
  --> /home/r/src/rust/rustc/compiler/rustc_middle/src/mir/interpret/pointer.rs:55:31
   |
55 |     fn truncate_to_ptr(&self, (val, over): (u64, bool)) -> (u64, bool) {
   |                               ^^^^^^^^^^^
   |
help: give this argument a name or use an underscore to ignore it
   |
55 |     fn truncate_to_ptr(&self, _: (u64, bool)) -> (u64, bool) {
   |                               ~
```
The version seems recent enough, doesn't it?
```
$ ./build/x86_64-unknown-linux-gnu/stage0/bin/rustfmt --version
rustfmt 1.4.37-nightly (fdf6505 2021-09-07)
```

**Comment by RalfJung** [comment]
Oh, with `--edition=2018` added it works. Sorry for the noise.
