### ISSUE TITLE
internal error: entered unreachable code

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rustfmt#4357]
**Describe the bug**
In some situations, rustfmt will panic with the following error:

`thread 'main' panicked at 'internal error: entered unreachable code', src/tools/rustfmt/src/types.rs:764:59`

**To Reproduce**

This is a repost of https://github.com/rust-lang/cargo/issues/8388, so I don't know the original code (the reporter said it was close source and could not share).  However, here are some examples that can trigger it:

```rust
type T = typeof(1);
```

```rust
struct S;

impl T for .. {

}
```

Of course these aren't valid, but they hit [this line](https://github.com/rust-lang/rustfmt/blob/939e164c29f92bdbffdb156fa3d53aabbe9a2e0b/src/types.rs#L764).  I'm not sure if there are legitimate cases that would hit this.  Another guess is that maybe the user had format-on-save, and was in the middle of some unfinished code?

**Meta**

- rustfmt version: `rustfmt 1.4.19-nightly (cef1c0d5 2020-07-21)`
- From where did you install rustfmt?: rustup
- How do you run rustfmt: `cargo fmt`

**Comment by calebcartwright** [comment]
Thanks for sharing @ehuss , and providing the additional details and minimal repro!

Invalid code scenarios are a little tricky. The general rule of thumb is that if the rustc parser can still successfully generate an AST (which is clearly the case here) then rustfmt should be able to format. However, there's been a few other cases where invalid code was too problematic to be format-able.

If anyone knows a valid minimal repro scenario please feel free to share

**Comment by calebcartwright** [comment]
Backported in v1.4.30
