### ISSUE TITLE
Rename test references from `writemode` to `emit`

### ISSUE THREAD

**Issue by calebcartwright** [rust-lang/rustfmt#4364]
A long time ago (pre-1.0 release I believe), the nomenclature that described how rustfmt emitted formatting was called "write mode". This was subsequently renamed to "emit" (usable via the `--emit` flag/, however, there are still some tests and test directories that leverage the old "writemode" naming. 

It would be great to get those updated/renamed to utilize the "emit" naming for the features they are testing. 

Places that need to be changed to resolve this issue (there could potentially be others):
* Rename the `writemode` directory to `emit` under the `tests` directory (https://github.com/rust-lang/rustfmt/tree/master/tests/writemode)
* Rename the "writemode" references within the corresponding xml and json files that are currently located under `tests/writemode`
* Rename the references to the "writemode" directory in src/test/mod.rs, For example: https://github.com/rust-lang/rustfmt/blob/0921e1fbf35a9ef414516f0ee73927baa8f186e0/src/test/mod.rs#L204

**Comment by chansuke** [comment]
Hi. I'd like to work on this issue.

**Comment by calebcartwright** [comment]
Awesome, thank you @chansuke! Let us know if you have any questions
