### ISSUE TITLE
Feature: merge consecutive identical blocks

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rustfmt#4371]
I'd like an option to merge two extern or impl blocks if they come right after each other and are otherwise identical (same call abi, same cfg, same where bounds, etc).

This is primarily of use with `bindgen`, which places every single bound function in its own `extern "C"` block, but is useful with impl blocks as well.

**Comment by calebcartwright** [comment]
Thank you for the suggestion. Although I can see the value in such a capability, I do not think it's a capability that should be surfaced within rustfmt, and that it would be better deferred to some other scanning/analysis tool and/or the developer. 

rustfmt is just a formatting/styling tool at the end of the day, and although there are a handful of minor exceptions, a core tenant is that the AST produced from the code emitted by rustfmt match the AST of the original input code. Making significant changes like this would violate that tenant. 

Lastly, and challenging enough on its own, I fear that such an implementation would add far too much burden on rustfmt both in terms of runtime analysis as well as the rustfmt source itself.

**Comment by Lokathor** [comment]
That's fair. I couldn't decide if this world be a rustfmt thing or maybe rust-analyzer, but i figured to start by asking here.
