### ISSUE TITLE
Writing annotation inside closure with while passing to fn causes panic: Request to format inverted span...

### ISSUE THREAD

**Issue by up9cloud** [rust-lang/rustfmt#4374]
**Describe the bug**

Writing annotation inside closure with while passing to fn causes panic

**To Reproduce**

```rust
fn a<F>(_f: F) -> ()
where
  F: FnOnce() -> (),
{
}
fn main() {
  a(|| {
    #[allow(irrefutable_let_patterns)]
    while let _ = 0 {
      break;
    }
  });
}
```

[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=9183b5379532ab134d3fa1706a8af42e)

```console
thread 'main' panicked at 'Request to format inverted span: /playground/src/main.rs:8:5: 11:4', src/tools/rustfmt/src/missed_spans.rs:87:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Expected behavior**

It should work without panic...

**Meta**

- rustfmt version: `rustfmt 1.4.17-stable (8a93416c 2020-07-20)`
- From where did you install rustfmt?: `rustup`
- How do you run rustfmt: `rustfmt ./src/main.rs`

**Comment by calebcartwright** [comment]
This is fixed in source, but hasn't been backported to a rustfmt 1.x release yet. Going to go ahead and close as a dup, but will mark this for backport so the fix is included in the next release

**Comment by calebcartwright** [comment]
Should be able to get this backported with the 1.4.20 release (refs #4376) that will hopefully land on nightly soon
