### ISSUE TITLE
Macro use not formatted - braces, item position, trailing comma

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rustfmt#438]
When running rustfmt on https://github.com/rust-lang-nursery/rand/blob/master/src/rand_impls.rs

**Comment by nrc** [comment]
@nagisa Could you paste the long line here please?

**Comment by nagisa** [comment]
I’m not sure which the one that causes the issue, but removing https://github.com/rust-lang-nursery/rand/blob/master/src/rand_impls.rs#L220 seems to make it not fail anymore.

**Comment by nrc** [comment]
That's

```
array_impl!{32, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T,}
```

So possibly we're doing something silly with the macro use? Given that it fits on one line already, that seems weird.

**Comment by marcusklaas** [comment]
It doesn't fit within a 100 chars, right? We're not reformatting it yet because
- it's an item level macro use;
- it uses braces;
- it has a trailing comma.

**Comment by nrc** [comment]
Oh right, it doesn't, that would explain it!

Removing tags because we don't touch it yet and it's a known issue (also we're not making anything worse which is my usual criteria for p-high).

**Comment by marcusklaas** [comment]
This may be fixed now. I think we format item level macro uses and braces. Only the trailing comma may be an issue since there's no way to know if it's significant. Maybe we could just go ahead and assume it is not.?

**Comment by scampi** [comment]
As of 8ec0750bb88dfe84ca2d54ddc29b13f5900641d6 it formats as follows:

```diff
 fn foo() {
-    array_impl!{32, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T,}
+    array_impl! {32, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T,}
 }
```

The line is still over the limit, but an error would be displayed only if the `error_on_line_overflow` option is enabled:

```
internal error: line formatted, but exceeded maximum width (maximum: 100 (see `max_width` option), found: 117)
 --> /home/yfful/documents/code/rustfmt/438.rs:2
  |
2 |     array_impl! {32, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T,}
  |                                                                                                     ^^^^^^^^^^^^^^^^^

warning: rustfmt may have failed to format. See previous 1 errors.
```
