### ISSUE TITLE
Publish a new version of rustfmt-nightly on crates.io

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rustfmt#4380]
The `rustfmt-nightly` crates is still at 1.4.19 on crates.io. Publishing the [1.4.20 branch](https://github.com/rust-lang/rustfmt/tree/rustfmt-1.4.20) will unblock https://github.com/rust-lang/rust/issues/74812.

**Comment by calebcartwright** [comment]
This is planned, but as I noted in the comment on the linked issue (https://github.com/rust-lang/rust/issues/74812#issuecomment-669168164) it's not strictly blocking. Have already discussed with @Xanewok (in the wg-rustfmt channel on Discord for anyone interested) being able to utilize a git reference within rls to proceed.
