### ISSUE TITLE
rustfmt should use natural sorting

### ISSUE THREAD

**Issue by jgarvin** [rust-lang/rustfmt#4381]
Current behavior is to sort imports lexicographically:

`use std::num::{NonZeroU16, NonZeroU8, NonZeroU32, NonZeroU64};`

Natural sorting would be slightly nicer:

`use std::num::{NonZeroU8, NonZeroU16, NonZeroU32, NonZeroU64};`

**Comment by calebcartwright** [comment]
Not exactly a dup, though this has already been implemented within source (refs #3764). It's considered a breaking change and hasn't been released, but available in the rustfmt 2.0 beta if you build from source. Going to go ahead and close.

Side note, you may want to bump https://github.com/rust-dev-tools/fmt-rfcs/issues/143 in the Style Guide to try to get that codified.
