### ISSUE TITLE
Comments removed before unnecessary semicolon

### ISSUE THREAD

**Issue by HactarCE** [rust-lang/rustfmt#4383]
**Describe the bug**

When rustfmt deletes an unnecessary semicolon, it also deletes comments immediately before that semicolon.

Obviously this isn't a common scenario, but rustfmt should never delete comments.

**To Reproduce**

[Try it on the Rust Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=76ba1c9e31258e252c2eaa1d6292664e)

**Expected behavior**

The extraneous semicolon should be deleted but the comment should remain.

**Meta**

- rustfmt version: 1.4.20-nightly (2020-08-09 48f6c32)
- From where did you install rustfmt?: Rust Playground (also rustup)
- How do you run rustfmt: Rust Playground (also `cargo fmt`)

**Comment by ayazhafiz** [comment]
Fixed on master since #4180

**Comment by calebcartwright** [comment]
Thanks for confirming @ayazhafiz! Closing accordingly
