### ISSUE TITLE
formatting fails if closure is split into multiple lines by comment

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rustfmt#4384]
**Input**

```rust
fn main() {
    let v: Vec<i32> = vec![1, 2, 3, 4];

    v.iter()
        .filter(|    x| 
    // bla bla
             **x != 2)
        .for_each(|x| println!("{}", x));
}
```

**Output**

```rust
fn main() {
    let v: Vec<i32> = vec![1, 2, 3, 4];

    v.iter()
        .filter(|    x| 
    // bla bla
             **x != 2)
        .for_each(|x| println!("{}", x));
}
```

**Expected output**

Something more similar to
```rust
fn main() {
    let v: Vec<i32> = vec![1, 2, 3, 4];

    v.iter()
        .filter(|x| 
        // bla bla
         **x != 2)
        .for_each(|x| println!("{}", x));
}
```

**Meta**

- rustfmt version: `rustfmt 1.4.20-nightly (48f6c32 2020-08-09)`

- From where did you install rustfmt?: rustup component

**Comment by calebcartwright** [comment]
Presumably the issue is with rustfmt formatting the closure body as a non-block expression, losing the comments between the fn decl and body, and then realizing afterwards the comments were lost and reverting back to the original snippet.

https://github.com/rust-lang/rustfmt/blob/218593f2ac55030316c0b0546240843f0e32b292/src/formatting/closures.rs#L214

In many similar circumstances, an approach to fix is to utilize `combine_strs_with_missing_comments` instead of mashing the strings together with `format`, but in this case the closure body should really just be formatted as a block (requirement when there's comments in the body https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/expressions.md#closures)

**Comment by ayazhafiz** [comment]
regarding (2):

> This seems to fail to format the comment correctly though.

I am surprised this doesn't work. `combine_strs_with_missing_comments` generally works pretty well, weird that you are seeing poor formatting.

There is another way to do this, which is to eagerly format comments after the function header like `rewrite_fn_base` does:

https://github.com/rust-lang/rustfmt/blob/1eb8764e4043d80ad75f8bbb59ba3e6ce2d95975/src/formatting/items.rs#L2499-L2516

I think this has an advantage in that if a future issue reports comments being dropped in `where` clauses inside of closures, a fix for that would go in the same place this comment rewriting would (in `rewrite_closure_fn_decl`).

And as you mention, there are a ton of ways to do this.

**Comment by Solumin** [comment]
Here's the unexpected formatting that I'm seeing. I'm calling the function like so:
```rust
return rewrite_closure_with_block(body, &prefix, between_span, context, body_shape)
    .and_then(|rw| {
            let mut parts = rw.splitn(2, "\n");
            let head = parts.next().unwrap();
            let rest = parts.next().unwrap();
            combine_strs_with_missing_comments(context, head, rest, between_span, shape, true)
  })
```

The original test source:
```rust
     v.iter()
         .filter(|    x| 
     // bla bla
              **x != 2)
         .for_each(|x| println!("{}", x));
```

What I'm expecting:
```rust
    v.iter()
        .filter(|x| {
            // bla bla
            **x != 2
        })
        .for_each(|x| println!("{}", x));
```
What I'm getting:
```rust
combine_strs:
     v.iter()
         .filter(|x| {
         // bla bla
                     **x != 2
         })
         .for_each(|x| println!("{}", x));
```

Which, now that I look at it, is probably happening because the indentation needs to be increased by a level and `rest` needs to be trimmed.

**Comment by calebcartwright** [comment]
Closing as the fix has been applied in source per our usual policy. No ETA as of yet when the fix will be released, though please note that if this is backported to a 1.x release it will be gated behind the `version` flag
