### ISSUE TITLE
`Failed to find module` should be `Failed to parse module`

### ISSUE THREAD

**Issue by RefinedSoftwareLLC** [rust-lang/rustfmt#4385]
**Describe the bug**
fmt gives an error that it can't find a file, when it really means the file has a syntax error.
**To Reproduce**
in main.rs
```mod module_0;```
in module_0.rs
```pub fn init() { ); }```

run cargo fmt
```Error writing files: io error: Failed to find module module_0 in ...```

**Expected behavior**

```Error parsing files: syntax error: Failed to parse module module_0 in ...```

**Meta**

- rustfmt version: 1.4.17-stable
- From where did you install rustfmt?: rustup
- How do you run rustfmt: cargo fmt

**Comment by calebcartwright** [comment]
Thanks for reaching out! This has already been updated in source, but not included in a released version yet. 

```bash
error: mismatched closing delimiter: `)`
 --> /home/caleb/dev/rustfmt-sandbox/submod-parser/src/module_0.rs:1:17
  |
1 | pub fn init() { ); }
  |               - ^ mismatched closing delimiter
  |               |
  |               unclosed delimiter

failed to resolve mod `module_0`: cannot parse /home/caleb/dev/rustfmt-sandbox/submod-parser/src/module_0.rs
```

The current (in source) behavior is our expected/desired error message in this instance, so I am going to close this.
