### ISSUE TITLE
binop_separator documented as stable, but only runs in nightly

### ISSUE THREAD

**Issue by ChrisWhealy** [rust-lang/rustfmt#4389]
<https://rust-lang.github.io/rustfmt/?version=master&search=#binop_separator> reports `binop_separator` as stable, but version 1.4.20 of `rustfmt` rejects this option as being unstable.

```console
12:12 $ rustc --version
rustc 1.45.2 (d3fb005a3 2020-07-31)
12:13 $ rustfmt --version 
rustfmt 1.4.17-stable (8a93416c 2020-07-20)
12:13 $ rustfmt ./src/vector_clock.rs 
Warning: can't set `binop_separator = Back`, unstable features are only available in nightly channel.
```

However, if I run `rustfmt` with `+nightly`, then this option works fine.

My `rustfmt.toml` file contains

```toml
edition = "2018"
binop_separator = "Back"
```

**Comment by calebcartwright** [comment]
You are looking at the wrong version of the config option documentation. You're viewing the config options for rustfmt on master (v2.x) but using a different version, 1.4.20.

Make sure to view the config option documentation for the version of rustfmt you are using. You can change the rustfmt version on that page via the dropdown at the top. 

https://rust-lang.github.io/rustfmt/?version=v1.4.20
