### ISSUE TITLE
Option to preserve tokens

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/rustfmt#4401]
I would like to be able to do a "white-space only" re-formatting of code. I want to be able to re-parse the formatted code and match up the new TokenStream with the original, so that I can figure out where each original token is located in the formatted code, but this won't work if rustfmt does things like removing redundant brackets, etc.

Is there a set of options I can turn off to guarantee that the TokenStream will be unchanged?

**Comment by calebcartwright** [comment]
> I would like to be able to do a "white-space only" re-formatting of code.
> Is there a set of options I can turn off to guarantee that the TokenStream will be unchanged?

No, there is no such whitespace only formatting mode in rustfmt, nor any such combination of options. rustfmt will always reformat the input according to the [style guide](https://github.com/rust-dev-tools/fmt-rfcs), and that means such changes can potentially occur.

**Comment by ytmimi** [comment]
Going to close this as its been open for a while and isn't something that we're going to take on.
