### ISSUE TITLE
Directory name used by test_merged_config is not rust unique

### ISSUE THREAD

**Issue by davidBar-On** [rust-lang/rustfmt#4405]
`test_merged_config()` in _confi.rs_ creates and uses folder name **`a`**, usually under `/tmp` directory.  The problem is that `/tmp/a` is a commonly used for other purposes, and that can cause problems as happened to me in #4400.  It would be better if a more **rust unique name** will be used instead of "a".

**Comment by calebcartwright** [comment]
This can be addressed as simply as changing the parent directory name from `a` to something a bit more unique in:
https://github.com/rust-lang/rustfmt/blob/334e297ad7735ea010bfcc0d3a2d849a08fed255/src/config.rs#L644-L680
