### ISSUE TITLE
Is there a way to flatten use statements

### ISSUE THREAD

**Issue by qiujiangkun** [rust-lang/rustfmt#4407]
I have a project where use statements are nested ugly and I would like to separate them, or to flatten them. However, I didn't find the option to do it yet.

**Comment by calebcartwright** [comment]
Not at the moment, though this will likely be a supported variant of the import formatting config option. It's currently an unstable option that's binary and named `merge_imports, though will most likely be renamed once the default value is decided and non-default supported variants decided. More details on https://github.com/rust-lang/rustfmt/issues/3362#issuecomment-642564290

Going to close this for now, feel free to track the other issue
