### ISSUE TITLE
Standalone stable rustfmt ignore nightly configuration without a warning

### ISSUE THREAD

**Issue by qiujiangkun** [rust-lang/rustfmt#4412]
Standalone stable `rustfmt` ignore nightly configuration without a warning.
If I run `cargo fmt` (stable), it says 
```
Warning: can't set `struct_field_align_threshold = 60`, unstable features are only available in nightly channel.
Warning: can't set `enum_discrim_align_threshold = 60`, unstable features are only available in nightly channel.
Warning: can't set `match_block_trailing_comma = true`, unstable features are only available in nightly channel.
```
If I run `rustfmt`, it does read the configuration file but says no warning.

**Comment by calebcartwright** [comment]
Could you provide more detail, particularly about your project layout and location of the rustfmt.toml configuration files, and the exact rustfmt command you are running?

**Comment by calebcartwright** [comment]
Please also specify which version of rustfmt you are using (`rustfmt --version`)

**Comment by qiujiangkun** [comment]
Never mind. rustfmt was waiting for EOF to show the warning.

```log
$ rustfmt --version
rustfmt 1.4.17-stable (8a93416 2020-07-20)

$ rustfmt
<input>
struct Foo {
a: i32,
bbbbb: i32
}
<input end>
Warning: can't set `struct_field_align_threshold = 60`, unstable features are only available in nightly channel.
struct Foo {
    a: i32,
    bbbbb: i32,
}
```

**Comment by calebcartwright** [comment]
Thanks for the follow up! Yes, rustfmt is typically used to format specific files (`rustfmt src/lib.rs src/foo.rs --edition 2018 --check ...`) but it can also be used to format from stdin, which is what happens if you run rustfmt without any input

https://github.com/rust-lang/rustfmt#running-rustfmt-directly
