### ISSUE TITLE
Add documentation about RUSTFMT environment variable

### ISSUE THREAD

**Issue by topecongiro** [rust-lang/rustfmt#4426]
- [ ] Update README.md
- [ ] Update cargo's documentation. We should do this after we release the version with `RUSTFMT` support.

Related: https://github.com/rust-lang/rustfmt/pull/4419

**Comment by MonliH** [comment]
When is the new version going to be released? When it does, I could help.

**Comment by calebcartwright** [comment]
> When is the new version going to be released?

Have to get a few other PRs landed in other repos since the next version contains a bump of the rustc-ap-* crates. Will update here once we have a more concrete answer

> When it does, I could help.

Fantastic, thank you!

**Comment by calebcartwright** [comment]
rustfmt 1.4.22 has landed on nightly (and I believe beta now as well) so this should be good to go @MonliH if you are still interested in working on it

**Comment by MonliH** [comment]
Yep, sure! Will do.
