### ISSUE TITLE
rustfmt fails to remove trailing whitespace when next line is a comment before value

### ISSUE THREAD

**Issue by HeroicKatora** [rust-lang/rustfmt#4427]
**Describe the bug**

`cargo fmt` fails with:

```
error[internal]: left behind trailing whitespace
 --> /tmp/cargo-fmt-fail/src/lib.rs:1:1:16
  |
1 | const A: usize = 
  |                 ^
  |

warning: rustfmt has failed to format. See previous 1 errors.
```

**To Reproduce**

Copy and paste this into a new source file (note the trailing whitespace in first line):
```rust
const A: usize = 
    // Some constant
    2;
```

**Expected behavior**

**Meta**

- rustfmt version: rustfmt 1.4.18-stable (8157a3f 2020-07-15)
- From where did you install rustfmt?: rustup
- How do you run rustfmt: `cargo fmt`, `rustfmt`

**Comment by calebcartwright** [comment]
For anyone interested in working on this, the problem occurs because rustfmt is failing to capture the comment between the assignment operator and rhs, so when rustfmt detects that the comment would be lost, it reverts back to the original snippet which has the trailing space. 

Starting point for fixing this will probably be here: 
https://github.com/rust-lang/rustfmt/blob/4a88598ec7f76ac86b656d3daeaa06b1b1e1f197/src/formatting/items.rs#L1878-L1888

**Comment by whizsid** [comment]
I like to work on this issue. I will send a PR.

**Comment by whizsid** [comment]
@calebcartwright I think I figured out an approach. My aproach is Using https://github.com/rust-lang/rustfmt/blob/2927e89b5194ecc887d61249eed9739ff1c3a3d5/src/formatting/comment.rs#L160

in this line. https://github.com/rust-lang/rustfmt/blob/2927e89b5194ecc887d61249eed9739ff1c3a3d5/src/formatting/expr.rs#L1985

But we need to pass `Span` over several functions. Is this ok? Or have any other suggestions?

**Comment by calebcartwright** [comment]
> But we need to pass Span 

What's the Span covering? From the assignment operator to the lo of the rhs span?

**Comment by whizsid** [comment]
@calebcartwright  Yes. From the function doc:-
> `span` may contain comments between two strings.

So `lhs.between(rhs)` is enough.

**Comment by calebcartwright** [comment]
note that span will run through the _end_ of rhs which isn't really what we want. Generally speaking though I'd say yes to your proposal of using `combine_strs_with_missing_comments` to combine the lhs and rhs. There's probably quite a few ways that could be tackled, so feel free to open an early/draft PR with a proposal for discussion
