### ISSUE TITLE
Apply `brace_style` to extern blocks

### ISSUE THREAD

**Issue by calebcartwright** [rust-lang/rustfmt#4428]
When [brace_style](https://rust-lang.github.io/rustfmt/?version=master&search=#brace_style) is set to `AlwaysNextLine` then that should also apply to extern blocks. Until recently this config option was only utilized for items, but was recently updated to apply to `unsafe` blocks and makes sense to do the same for `extern`

Some relevant places to check in the code:

Perhaps `format_extern`, which adds a trailing space after the `extern` keyword or ABI. We don't want to leave trailing spaces at the end of a line so would need to make sure that there wouldn't be a trailing space left behind when the configured `brace_style` resulted in the opening brace going on the next line
https://github.com/rust-lang/rustfmt/blob/master/src/formatting/utils.rs#L149

And also `format_foreign_mod`/`format_item`
https://github.com/rust-lang/rustfmt/blob/4a88598ec7f76ac86b656d3daeaa06b1b1e1f197/src/formatting/items.rs#L317-L327

So when `brace_style` is set to `AlwaysNextLine` rustfmt would emit:
```rust
extern "C"
{
    fn foo(x: i32);
}
```

otherwise 
```rust
extern "C" {
    fn foo(x: i32);
}
```

**Comment by IceTDrinker** [comment]
I'll take a look tomorrow, not going to be super available next week, so unsure for a reasonable ETA

**Comment by blesson3** [comment]
I just opened a PR that allows `extern` blocks to conform to [brace_style](https://rust-lang.github.io/rustfmt/?version=master&search=#brace_style) when set to `AlwaysNextLine`.

I also made sure that there are no trailing spaces for the `extern "C"` line.

**Comment by IceTDrinker** [comment]
I also have a proposal not based on fixing the strings after the fact, I'll push it on my repo and not open a PR to spam you guys : https://github.com/IceTDrinker/rustfmt/tree/brace_style_always_new_line_extern

I took the liberty to reuse @blesson3 test files

Main issue I see with current extern formatting is comments between extern keyword and ABI string and comment between ABI string and opening bracket. Could be a separate issue

Cheers

**Comment by calebcartwright** [comment]
Thanks @IceTDrinker! I did go ahead and merge @blesson3's PR (actually didn't see the comments here til after) as it addressed the main issue. Please still feel free to submit your PR if you think we can improve, capture comments, etc.

**Comment by blesson3** [comment]
This feature has regressed in the `master` branch. I cannot seem to find where my PR (https://github.com/rust-lang/rustfmt/pull/4450) changes went. Either this is intentional or somehow those commits were lost. @calebcartwright I recommend this issue be re-opened until this is clarified.

**Comment by calebcartwright** [comment]
@blesson3 - please see #4801

**Comment by blesson3** [comment]
I had not seen that, thanks!
