### ISSUE TITLE
Error writing files: failed to resolve mod on missing semicolon

### ISSUE THREAD

**Issue by micouy** [rust-lang/rustfmt#4431]
**Describe the bug**

`rustfmt` returns
```
Error writing files: failed to resolve mod `error`: cannot parse <project dir>/src/error.rs
```

**To Reproduce**

`src/main.rs`:

```rust
mod error;

fn main() {}
```

`src/error.rs`:

```rust
pub struct S // missing semicolon
```

**Meta**

- rustfmt version: `rustfmt 1.4.21-nightly (01f2eadc 2020-09-04)`
- From where did you install rustfmt?: `rustup`
- How do you run rustfmt: `cargo fmt`

**Comment by calebcartwright** [comment]
Could you elaborate on what exactly you think the bug is here? The absence of the `^ expected `where`, `{`, `(`, or `;` after struct name` error details or something else?

`pub struct S` is invalid syntax, so an unrecoverable error encountered by the rustc parser is expected.

**Comment by micouy** [comment]
Oh sorry then. Yeah, I expected a message `cargo build` returns, I didn't know that's how it's supposed to work.

**Comment by calebcartwright** [comment]
No worries, thanks for clarifying. I'll double checking our parsing/rustc parser code later on, it's entirely possible we're intercepting an error that we need to emit ourselves, but aren't.
