### ISSUE TITLE
rustfmt won't look in the correct place for #[path = "..."] attributes of modules

### ISSUE THREAD

**Issue by unleashed** [rust-lang/rustfmt#4446]
When using the `#[path = "..."]` in a module, `rustfmt` will always take the value of the attribute as relative to the current working directory. However this is not the way `rustc` interprets these, which seems to be relative to the directory containing the file with this attribute.

Rustfmt ends ups calling `openat(AT_FDCWD, filename, ...)` instead of basing the lookup in the directory of the file.

**To Reproduce**

File structure (possibly not minimal):

```shell
$ ls -R
.:
Cargo.lock  Cargo.toml  src

./src:
api  main.rs

./src/api:
v1.mymod.rs
```

Contents of `src/main.rs`:
```rust
pub mod api {
    #[path = "."]
    pub mod v1 {
        #[path = "v1.mymod.rs"]
        pub mod mymod;
    }
}

fn main() {
    let _ = api::v1::mymod::MyModAPI;
    println!("Hello, world!");
}
```

Contents of `src/api/v1.mymod.rs`:
```rust
pub struct MyModAPI;
```

Compilation via `cargo`:

```shell
$ cargo run --quiet
Hello, world!
```

Format check via `cargo` and `rustfmt` from _the root directory of the project_:
```shell
$ cargo fmt --all
error: couldn't read ./v1.mymod.rs: No such file or directory (os error 2)

Error writing files: failed to resolve mod `mymod`: ./v1.mymod.rs does not exist
$ rustfmt --edition 2018 src/main.rs
error: couldn't read ./v1.mymod.rs: No such file or directory (os error 2)

Error writing files: failed to resolve mod `mymod`: ./v1.mymod.rs does not exist
```

Format check via `cargo` and `rustfmt` from the `src/api` directory (NB: successful status):
```shell
$ cd src/api
$ cargo fmt --all
$ rustfmt --edition 2018 ../main.rs
$
```

**Expected behavior**

`rustfmt` correctly locates the files containing Rust modules as interpreted by `rustc` from their `#[path = "..."]` attribute. My guess is the correct interpretation should build the relative path based off the directory in which the file being formatted is located rather than the process' current working directory.

**Meta**

- rustfmt version: rustfmt 1.4.18-stable (8157a3f 2020-07-15)
- From where did you install rustfmt?: rustup
- How do you run rustfmt: `rustfmt`, `cargo fmt`

**Comment by calebcartwright** [comment]
Could you check with rustfmt on nightly? There's been some fixes in the module resolution lately, some of which should be out on nightly though not yet on stable

**Comment by unleashed** [comment]
@calebcartwright sure, just tried it and indeed this issue is fixed on nightly, thanks! Will have to wait until the fixes hit stable for my particular needs, but feel free to close this meanwhile.

**Comment by calebcartwright** [comment]
Thanks for confirming!
