### ISSUE TITLE
Adding skip to macro definition causes import resolution and absolute path errors on import

### ISSUE THREAD

**Issue by Txuritan** [rust-lang/rustfmt#4449]
**Describe the bug**

Adding `#[rustfmt:skip]` to a macro definition causes rustc errors when trying to import it.

```
error: cannot determine resolution for the import
  --> src/main.rs:10:9
   |
10 |     use crate::o;
   |         ^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying other imports

error: macro-expanded `macro_export` macros from the current crate cannot be referred to by absolute paths
  --> src/main.rs:10:9
   |
10 |     use crate::o;
   |         ^^^^^^^^
   |
   = note: `#[deny(macro_expanded_macro_exports_accessed_by_absolute_paths)]` on by default
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #52234 <https://github.com/rust-lang/rust/issues/52234>
note: the macro is defined here
  --> src/main.rs:4:5
   |
4  | /     macro_rules! o {
5  | |         () => {};
6  | |     }
   | |_____^

error: aborting due to 2 previous errors
```

**To Reproduce**

Have two modules, in one add a macro definition with `#[rustfmt:skip]`, and in the other import the macro. The module with import will fail to compile

Heres a [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4b59abca4889ec3b06869952ddee8604) link used to create the log above.

**Meta**

- rustfmt version: rustfmt 1.4.18-stable (8157a3f0 2020-07-15)
- From where did you install rustfmt?: rustup
- How do you run rustfmt: `rustfmt`

**Comment by calebcartwright** [comment]
Thanks for reaching out @Txuritan, but rustc-related issues need to be reported in the main rust-lang/rust repo (note that this can be reproduced with other, non rustfmt tool attributes like `#[clippy::cyclomatic_complexity = "100"]`).

Sounds very similar to https://github.com/rust-lang/rust/issues/74087

Closing this accordingly

**Comment by Txuritan** [comment]
Nevertheless, thank you for pointing that issue out, I never found it when I was trying to figure out what was causing this.

**Comment by calebcartwright** [comment]
Sure thing! I thought it sounded familiar :smile:
