### ISSUE TITLE
Inconsistent formatting between consecutive Struct initializations

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rustfmt#4457]
*Note*: the snippet below doesn't pass rustc compilation.

**Input**

```rust
pub fn foo() {
    let toolchains = toolchains_between(
        cfg,
        ToolchainSpec::Nightly {
            date: first_success,
        },
        ToolchainSpec::Nightly { date: last_failure },
    );
}
```

**Output**

```rust
pub fn foo() {
    let toolchains = toolchains_between(
        cfg,
        ToolchainSpec::Nightly {
            date: first_success,
        },
        ToolchainSpec::Nightly { date: last_failure },
    );
}
```

**Expected output**

```rust
pub fn foo() {
    let toolchains = toolchains_between(
        cfg,
        ToolchainSpec::Nightly { date: first_success },
        ToolchainSpec::Nightly { date: last_failure },
    );
}
```

**Meta**

- rustfmt version: 1.4.21-nightly (2020-09-04 01f2ead)
- From where did you install rustfmt?: On playground and rustup stable toolchain.

**Comment by calebcartwright** [comment]
Thank you for the report, though this is expected behavior. The max one line width for a struct lit (with all default settings, as controlled via `use_small_heuristics` in rustfmt v1.x) is 18. Your first lit arg exceeds that so it's mutlilined, the second one just fits within the limit to be allowed to remain on one line.

As such I'm going to go ahead and close this

**Comment by lzutao** [comment]
Thank you. That explains rustfmt behaviour. 
But where is the number 18 from ? Is it a arbitrary number ?

**Comment by calebcartwright** [comment]
> But where is the number 18 from ? Is it a arbitrary number ?

`use_small_heuristics` is the available configuration option that controls this value. By default, `use_small_heuristics` calculates a handful of width limits for various constructs (struct literals, function calls, etc.) based on the value of `max_width`. For struct lits this is 18% of the value of `max_width`, which by default is set to `100`. The ratios, including the 18%, have been in place for a long time, and I'm not entirely positive of their origins but believe it was based on some discussions/reviews of what was perceived to be too long to fit on a single line.

At the moment the only way to control the value used for the struct lits from a released version of rustfmt is to either modify `max_width` or change `use_small_heuristics` to `Off` or `Max`.

There are **unreleased** enhancements to rustfmt that will expose the `struct_lit_width` option directly to the user and allow for overriding the default value of 18 independently 

https://rust-lang.github.io/rustfmt/?version=master&search=#struct_lit_width
