### ISSUE TITLE
Rustfmt 2.0: Consider making `newline_style` default to `Unix` on all platforms.

### ISSUE THREAD

**Issue by aloucks** [rust-lang/rustfmt#4465]
Carriage returns are a vestige of old versions of DOS and Windows and don't serve any practical purpose today. All modern editors support `LF` style newlines. The last holdout was `notepad.exe` which now supports `LF` style line endings in Windows 10.

**Comment by topecongiro** [comment]
Thank you for your feature request!

I agree that it's tempting to change the default value to `Unix`, but the current default `Auto` is a lot safer pick.

Note: with the current default, rustfmt will use the `LF` newline style on every platform if input files use the `LF` newline style.

I appreciate your request but will close this as won't fix.
