### ISSUE TITLE
#[cfg_attr] removed for function parameter

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rustfmt#4473]
**Describe the bug**

The `#[cfg_attr(not(debug_assertions), allow(unused_variables))]` gets removed completely.

**To Reproduce**

```rust
pub(super) fn optimize_function(
    ctx: &mut Context,
    #[cfg_attr(not(debug_assertions), allow(unused_variables))] clif_comments: &mut crate::pretty_clif::CommentWriter,
) {}
```

turns into

```rust
pub(super) fn optimize_function(
    ctx: &mut Context,
    clif_comments: &mut crate::pretty_clif::CommentWriter,
) {
}
```

**Expected behavior**

`#[cfg_attr(not(debug_assertions), allow(unused_variables))]` is kept.

**Meta**

- rustfmt version: rustfmt 1.4.22-nightly (97d0301 2020-10-04)
- From where did you install rustfmt?: rustup
- How do you run rustfmt: `cargo fmt`

**Comment by topecongiro** [comment]
Thank you for the report. This issue is already fixed on the latest master, but the fix hasn't been included in the release yet.
