### ISSUE TITLE
Update usage of deprecated GitHub Actions Commands

### ISSUE THREAD

**Issue by calebcartwright** [rust-lang/rustfmt#4480]
(At least) One of our GHA workflows is still leveraging the deprecated `::add::path` command, and this needs to be converted to the new model. 

The one place I know we're using this for sure is in the [Windows i686-pc-windows-gnu job](https://github.com/rust-lang/rustfmt/blob/master/.github/workflows/windows.yml#L72) though there may be others. 

Reference PR from rustup where similar updates were made:
https://github.com/rust-lang/rustup/pull/2513

**Comment by Nikhil0487** [comment]
@calebcartwright 

I would like to fix this issue.

**Comment by calebcartwright** [comment]
Excellent, thanks @Nikhil0487!

**Comment by calebcartwright** [comment]
Closed via #4497
