### ISSUE TITLE
Trailing comma is not added in macro invocation

### ISSUE THREAD

**Issue by camelid** [rust-lang/rustfmt#4490]
Perhaps this is intentional, but it is kind of frustrating so I thought I would report it.

**Input**

```rust
fn main() {
    let x = format!("hello, this is a long {} with {} format {}", "message", 2, "arguments");
    println!("{}", x);
}
```

**Output**

```rust
fn main() {
    let x = format!(
        "hello, this is a long {} with {} format {}",
        "message", 2, "arguments"
    );
    println!("{}", x);
}
```

**Expected output**

```rust
fn main() {
    let x = format!(
        "hello, this is a long {} with {} format {}",
        "message", 2, "arguments",
    );
    println!("{}", x);
}
```

(Note the trailing comma in the expected output that does not appear in the actual output.)

**Meta**

- rustfmt version: 1.4.22-nightly (2020-10-04 97d0301) [on the playground]
- From where did you install rustfmt?: on the playground

**Comment by calebcartwright** [comment]
This is indeed by design currently (#3065). At some point down the road we may introduce some additional special case handling for macros where we know this could always be done without issue, but for now rustfmt has to defer to the user in these cases

**Comment by calebcartwright** [comment]
Going to close in favor of #3065 as it has a more complete context on current state and possible future state
