### ISSUE TITLE
Error writing files: failed to resolve mod [path] not exist

### ISSUE THREAD

**Issue by jessehui** [rust-lang/rustfmt#4510]
**Describe the bug**
When running `cargo fmt` under the project's dir, I get following errors. These errors show after I change toolchain from `nightly-2020-04-07` to `nightly-2020-09-08`.

Please take a look on the log:
```
root@d301:~/occlum/src/exec# tree
.
|-- Cargo.lock
|-- Cargo.toml
|-- Makefile
|-- build.rs
|-- occlum_exec.proto
|-- rust-toolchain
`-- src
    |-- bin
    |   |-- occlum_exec_client.rs
    |   `-- occlum_exec_server.rs
    |-- lib.rs
    `-- server.rs

2 directories, 10 files
root@d301:~/occlum/src/exec# cargo fmt -- --check
Error writing files: failed to resolve mod `occlum_exec`: /root/occlum/src/exec/src does not exist
root@d301:~/occlum/src/exec# cargo fmt
Error writing files: failed to resolve mod `occlum_exec`: /root/occlum/src/exec/src does not exist
```

**To Reproduce**

Run `cargo fmt` under current dir
**Expected behavior**

**Meta**

- rustfmt version: 
rustfmt 1.4.21-nightly (01f2ead 2020-09-04)
- From where did you install rustfmt?: 
rustup
- How do you run rustfmt: 
cargo fmt

**Comment by calebcartwright** [comment]
Thanks for reaching out @jessehui.

Would you please provide some additional context, in particular the actual code where you are trying to import the mod?

**Comment by jessehui** [comment]
The actual code that the tree structure belongs can be found here: https://github.com/occlum/occlum/tree/master/src/exec.
Previously, when I use `nightly-2020-04-07`, rustfmt works well.

**Comment by jessehui** [comment]
This issue is due to the lack of modules when formatting. Because some modules are generated automatically by other tools during cargo build and when formatting, these modules have not been generated yet.

However, specifying in `rustfmt.toml` can't resolve this, which surprised me.
