### ISSUE TITLE
Wrong MSRV in README

### ISSUE THREAD

**Issue by YaLTeR** [rust-lang/rustfmt#4537]
> A minimal Travis setup could look like this (requires Rust 1.24.0 or greater):

However, the `rustfmt` component is only available starting from 1.31.0. Anything below gives:
```
└─ rustup toolchain add 1.30.0 -c rustfmt
info: syncing channel updates for '1.30.0-x86_64-unknown-linux-gnu'
info: latest update on 2018-10-25, rust version 1.30.0 (da5f414c2 2018-10-24)
error: component 'rustfmt' for target 'x86_64-unknown-linux-gnu' is unavailable for download for channel 1.30.0
```

**Comment by calebcartwright** [comment]
The docs originally mentioned the `rustfmt-preview` component which was subsequently corrected (as that component stopped being shipped a long time ago), but obviously the version wasn't updated accordingly.

Thanks for the report @YaLTeR!

For anyone interested in fixing this, the incorrect line can be found here:
https://github.com/rust-lang/rustfmt#checking-style-on-a-ci-server

**Comment by chansuke** [comment]
I'd like to fix this.
