### ISSUE TITLE
Strange format of if statement with comments

### ISSUE THREAD

**Issue by davidBar-On** [rust-lang/rustfmt#4549]
**Input**

```rust
fn main() {
    if /*w*/ 5 /*x*/ == /*y*/ 6 /*z*/ {}
}
```

**Output**

```rust
fn main() {
    if
    /*w*/
    5 /*x*/ == /*y*/ 6
    /*z*/
    {}
}
```

**Expected output**

**Same as input**.  (Test case is from #4518 test cases.)

**Meta**

- rustfmt version: rustfmt 2.0.0-rc.2-nightly (30bda450 2020-11-18)
- From where did you install rustfmt?: self build

**Comment by calebcartwright** [comment]
This is another case of non-ideal formatting, but a circumstance that seems odd/unlikely to be common place in real life. If I recall correctly, the formatting for control flow expressions is using a different comment handling helper than the rest of the codebase, and essentially will just always insert newlines around the comments.

I do not recall if that was done intentionally, or if it was simply done prior to the development of the more widely used comment util functions that utilize more complex heuristics to reformat in the presence of comments

**Comment by davidBar-On** [comment]
OK.  I see that a comment after the `{` is formatted properly, e.g.:
```rust
fn main() {
    if x == 5 { /*Do nothing in this case*/
    } else {
        // Do something
    }

    if x == 5 {} /*Do nothing in this case*/
}
```
I agree that this seem sufficient, so I am **closing the issue**. 

(Just for my record, the new lines before and after the control-flow comments are insetrted in [expr.rs extract_comment()](https://github.com/rust-lang/rustfmt/blob/6eba51117df3c43e1939b8acfa98aed17e92660d/src/formatting/expr.rs#L1208).)

**Comment by calebcartwright** [comment]
> OK. I see that a comment after the `{` is formatted properly, e.g.:

This is true, but is really unrelated. How comments are handled within the block portion of the if expression is separate from how comments are handled between the keyword and the condition expression, and from how comments between the condition expression and the start of the block are handled.

I actually think there's a decent case to be made that the comment handling could be improved in those latter two locations, but it's also not exactly a high priority, and any such changes would need to have their associated maintenance+runtime costs against any associated benefits of improved formatting (would also have to avoid making the formatting worse for other non-if control flow expressions)

**Comment by davidBar-On** [comment]
> ....comments between the condition expression and the start of the block are handled ....
I actually think there's a decent case to be made that the comment handling could be improved in those latter two locations ...

What about **removing comments handling in these cases** until such improvements are done?  If I understand correctly that means removing the 4 calls to `extract_comment()` in `Rewrite for ControlFlow rewrite()` to create `between_kwd_cond_comment`, `after_cond_comment`, `between_kwd_else_block_comment`, `after_else_comment`.

I ask that because currently [extract_comment()](https://github.com/rust-lang/rustfmt/blob/6eba51117df3c43e1939b8acfa98aed17e92660d/src/formatting/expr.rs#L1208) "essentially will just always insert newlines around the comment" (as you wrote above), so it may be better that the original code will be used when such comments exist.

**Comment by calebcartwright** [comment]
> What about removing comments handling in these cases until such improvements are done?

No, definitely not. That would be a step in the wrong direction and a notable regression, as that would result in such expressions, and all of the nodes within their respective subtree in the AST not being formatted at all.

If there's better comment extraction/formatting approaches then great, but we don't want to intentionally stop handling comments in places where rustfmt currently handles them.
