### ISSUE TITLE
vscode cargo fmt deletes comments in struct

### ISSUE THREAD

**Issue by Naddiseo** [rust-lang/rustfmt#4559]
Followup from https://github.com/rust-analyzer/rust-analyzer/issues/6634
**Describe the bug**

```rust
struct Foo {
    hello: i8,
    /*
    line
    line
    */
    // line
    field1: u8,
    field2: u8,
    //hello
}
```
Formats as:
```rust

struct Foo {
    hello: i8,
    field1: u8,
    field2: u8,
    //hello
}
```

I have removed the "rust" extension, and I have the rust-analyzer set as nightly (rust-analyzer version: nightly (9b512f8)), and also use the extension as the default formatter.

Interestingly, if I run `cargo fmt` on command line, it reproduces the issue, however, `cargo +nightly fmt` doesn't have the issue, which makes me think it's a vscode extension issue. 

Please let me know if there's other information/diagnostics you need.

**Meta**

- rustfmt version: rustfmt 1.0.1-nightly (be13559 2018-12-10)
  ```
   $ cargo +nightly fmt --version
   rustfmt 1.4.27-nightly (580d826 2020-11-16)
   ```

- From where did you install rustfmt?: rustup
- How do you run rustfmt: vscode format

**Comment by pksunkara** [comment]
> Interestingly, if I run cargo fmt on command line, it reproduces the issue, however, cargo +nightly fmt doesn't have the issue

Why would that make it a vscode issue?

**Comment by Naddiseo** [comment]
> > Interestingly, if I run cargo fmt on command line, it reproduces the issue, however, cargo +nightly fmt doesn't have the issue
> 
> Why would that make it a vscode issue? It looks like more a rustfmt bug but which is fixed in nightly.

Sorry, when I wrote that I wasn't sure how vscode interacts with rustfmt. However, you could consider that the issue is that vscode extention is using a very dated rustfmt.

**Comment by pksunkara** [comment]
IIUC vscode doesn't set the rustfmt version. It's your local setup that vscode uses.

**Comment by calebcartwright** [comment]
>     * rustfmt version: rustfmt 1.0.1-nightly ([be13559](https://github.com/rust-lang/rustfmt/commit/be135599ef5e54b5219f9adec68e1ee267ea0584) 2018-12-10)
>       ```
>        $ cargo +nightly fmt --version
>        rustfmt 1.4.27-nightly (580d826 2020-11-16)
>       ```

@Naddiseo - I'm a bit confused as this seems highly contradictory. Could you please provide the active toolchain in your project? You can find this by running the following from within the same directory as your project:

```bash
$ rustup show active-toolchain
```

**Comment by Naddiseo** [comment]
```
$ rustup show active-toolchain 
nightly-2019-01-24-x86_64-unknown-linux-gnu (default)
$ cargo +nightly fmt --version
rustfmt 1.4.27-nightly (580d826 2020-11-16)
$ cargo fmt --version
rustfmt 1.0.1-nightly (be13559 2018-12-10)
$ rustfmt --version
rustfmt 1.0.1-nightly (be13559 2018-12-10)
```

The nightly showing as 2019-01-24 is strange.. my rust is up-to-date:
```
$ rustup update
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: syncing channel updates for 'beta-x86_64-unknown-linux-gnu'
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2020-11-27, rust version 1.50.0-nightly (72da5a9d8 2020-11-26)
info: skipping nightly which is missing installed components 'rls', 'rustfmt'
info: syncing channel updates for 'nightly-2020-11-26-x86_64-unknown-linux-gnu'
info: latest update on 2020-11-26, rust version 1.50.0-nightly (b48cafd9e 2020-11-25)
info: skipping nightly which is missing installed components 'rls', 'rustfmt'
info: syncing channel updates for 'nightly-2020-11-25-x86_64-unknown-linux-gnu'
info: checking for self-updates

   stable-x86_64-unknown-linux-gnu unchanged - rustc 1.48.0 (7eac88abb 2020-11-16)
     beta-x86_64-unknown-linux-gnu unchanged - rustc 1.49.0-beta.2 (bd26e4e54 2020-11-24)
  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.50.0-nightly (1c389ffef 2020-11-24)

info: cleaning up downloads & tmp directories


```

**Comment by calebcartwright** [comment]
> The nightly showing as 2019-01-24 is strange.. my rust is up-to-date:

The toolchains you've installed in your system are a bit different than the default toolchain.

Do you have a toolchain file in your project that is pinned to that old nightly? If not, and you don't have a rustup directory override set (and it doesn't look like you do), then you've probably just set your system default to that nightly.

**Comment by Naddiseo** [comment]
> > The nightly showing as 2019-01-24 is strange.. my rust is up-to-date:
> 
> The toolchains you've installed in your system are a bit different than the default toolchain.
> 
> Do you have a toolchain file in your project that is pinned to that old nightly? If not, and you don't have a rustup directory override set (and it doesn't look like you do), then you've probably just set your system default to that nightly.

Yeah, that seems to be exactly what has happened; I must have pinned it to nightly-2019-01-24 as my system default thinking it would be "pin to latest nightly" instead of "pin to this nightly".

I've now changed my default toolchain back to stable and that seems to have updated the version of rustfmt used by default, and consequently fixed the formatting in my editor! I guess I didn't understand what the tools were telling me.

Thanks for your help with this!

**Comment by calebcartwright** [comment]
cheers!
