### ISSUE TITLE
Poor formatting in sequential tuple struct invocations

### ISSUE THREAD

**Issue by sanbox-irl** [rust-lang/rustfmt#4571]
**Input**

```rust
fn test() {
    self.1 .0;
}

```

**Output**

```rust
fn test() {
    self.1 .0;
}
```
Note the space after the `1`

**Expected output**

```rust
fn test() {
    self.1.0;
}
```

**Meta**

- rustfmt version: rustfmt 1.4.24-stable (eb894d53 2020-11-05)
- From where did you install rustfmt?: rustup

**Comment by calebcartwright** [comment]
Closing as duplicate, more context in https://github.com/rust-lang/rustfmt/issues/4355#issuecomment-723764276
