### ISSUE TITLE
rustfmt makes it impossible to explain attributes with comments in the same line

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rustfmt#4573]
**Input**

Sometimes an attribute needs a comment explaining why it exists:

```rust
#[cfg(not(miri))] // Miri does not deduplicate consts (https://github.com/rust-lang/miri/issues/131)
```

**Output**

Unfortunately rustfmt insists on putting the comment on a separate line (and it moves it *after* the attribute, which is even worse):

```rust
#[cfg(not(miri))]
// Miri does not deduplicate consts (https://github.com/rust-lang/miri/issues/131)
```

**Expected output**

Just like I can have comments to the right of code, explaining what the code does, I expect to have comments to the right of attributes, explaining what the attributes do:

```rust
#[cfg(not(miri))] // Miri does not deduplicate consts (https://github.com/rust-lang/miri/issues/131)
```

**Meta**

- rustfmt version: whatever `./x.py fmt` does in rustc

**Comment by jyn514** [comment]
> 
    rustfmt version: whatever ./x.py fmt does in rustc


This is currently nightly-2020-11-19 (you can tell by looking at `src/stage0.txt`).

**Comment by RalfJung** [comment]
This looks very similar to https://github.com/rust-lang/rustfmt/issues/3255 -- in both cases rustfmt changes comment-after-code to move the comment onto its own line, thus changing the semantic meaning of the comment. IMO rustfmt should never do this.

**Comment by ytmimi** [comment]
I'm unable to reproduce this on `rustfmt 1.4.38-nightly (2d9bc460 2022-04-07)`. Also It's not totally clear to me which PR resolved this. @calebcartwright any recollection of a PR that adjusted how missing comment spans were joined? without digging to deeply into it I'd assume that's where the fix was. I'll open a PR with tests cases for this.

**Comment by calebcartwright** [comment]
I don't recall anything offhand, though it is getting a bit late in the day. Could you make sure you're testing locally with the same configuration settings that are used in the rust-lang/rust repo?

**Comment by calebcartwright** [comment]
Closed as this does appear to be sorted, but please let us know if you see a recurrence @RalfJung
