### ISSUE TITLE
Canonicalise `use foo::{self}` with `merge_derives`

### ISSUE THREAD

**Issue by ndmitchell** [rust-lang/rustfmt#4574]
With `merge_derives` enabled, `rustfmt` (rustfmt 1.4.22-nightly (97d03010 2020-10-04)) changes:

* `use foo::{bar}` to `use foo::bar`
* `use foo::self` to `use foo`

But it doesn't change `use foo::{self}` to `use foo`. Such statements can arise through automated refactoring and would be useful to transform.

**Comment by goffrie** [comment]
I also find that converting `foo::{self}` to `foo` has always been what I want, but this is intentional as it is technically an unsound conversion: https://github.com/rust-lang/rust/issues/60941 / #3753

**Comment by calebcartwright** [comment]
> I also find that converting `foo::{self}` to `foo` has always been what I want, but this is intentional as it is technically an unsound conversion: [rust-lang/rust#60941](https://github.com/rust-lang/rust/issues/60941) / #3753

Correct. Thanks @goffrie!

Going to go ahead and close, but thanks for reaching out @ndmitchell

**Comment by ndmitchell** [comment]
Is `foo::{self}` to `foo::self` unsound? That isn't done and would be reasonable from reading above, I think.

**Comment by goffrie** [comment]
`foo::self` isn't legal Rust syntax, oddly enough.

**Comment by calebcartwright** [comment]
> `foo::self` isn't legal Rust syntax, oddly enough.

Correct, we actually used to have a bug where rustfmt would do the requested behavior (#3808). The requested feature is definitely not something we should do
