### ISSUE TITLE
rustfmt deletes derived traits in #[derive(...)]

### ISSUE THREAD

**Issue by ente76** [rust-lang/rustfmt#4584]
**Describe the bug**

Running `cargo fmt` on my project takes all `#[derive(Debug, Clone, PartialEq, Eq)]` and deletes exactly the last letter on each execution. It does not matter how many traits I derive. If I run it multiple times, it will stop at an empty `derive()`.

**To Reproduce**

Setup a new library and add the following lines:

```
#[derive(Debug)]
pub enum Case {
    Upper,
    Lower
}
```

run `cargo fmt`

**Expected behavior**

`cargo fmt` finishes my project while I watch funny cat videos on youtube. At least rustfmt does not make my life harder than it is.

**Meta**

- rustfmt version: rustfmt 1.4.29-nightly (70ce182 2020-12-04)
- From where did you install rustfmt?: rustup nightly version: rustc 1.50.0-nightly (d32c320d7 2020-12-10)
- How do you run rustfmt: cargo fmt (manually to test), usually via rust-analyzer during file saving

**Comment by ente76** [comment]
rustfmt 1.4.27-nightly (580d826 2020-11-16) works without the error.

**Comment by calebcartwright** [comment]
I'm unable to reproduce this locally. Can you provide some additional information so that we can be better equipped to assist?

Do you have a public repo or a CI run where we can observe the described behavior?

**Comment by ente76** [comment]
Please do run:
```
mkdir test
cd test
git clone https://gitlab.com/systemd.rs/sd-sys.git
git clone https://gitlab.com/systemd.rs/sd-id128.git
cd sd-id128
cargo fmt
```

file lib.rs in `test/sd-id128/src/lib.rs` has multiple derives that should be lacking the last letter now. I tested above process using rustup provided by arch linux (rustup 1.23.0-1).
rustup update has been executed approx. every day since Monday (that's approximately been the first time I hit the error).
rustup default nightly is been activated. I will go back to the working version now (currently I use nightly-20-11-2020).

**Comment by calebcartwright** [comment]
Thanks! This can be reproduced when `indent_style` is changed to `Visual`

**Comment by calebcartwright** [comment]
Backported in v1.4.30
