### ISSUE TITLE
Stable `ignore` config only available in nightly

### ISSUE THREAD

**Issue by SWW13** [rust-lang/rustfmt#4593]
**Describe the bug**
Using the `ignore = ["/"]` config doesn't work in stable `rustfmt` although https://rust-lang.github.io/rustfmt/?version=master&search=#ignore states otherwise.
As the documentation doesn't state a version when it went stable this might also be a documentation issue.

```
ignore = IgnoreList { path_set: {"/"}, rustfmt_toml_path: "" }`, unstable features are only available in nightly channel.
```

**To Reproduce**
```
cargo init
echo 'fn main() { if   false {   } }' > src/main.rs
echo 'ignore = ["/"]' > .rustfmt.toml
cargo fmt -- -v --check # doesn't work
cargo +nightly fmt -- -v --check # works
```

**Expected behavior**
Config is available in the latest stable `rustfmt`.

**Meta**
- rustfmt version: `rustfmt 1.4.24-stable (eb894d5 2020-11-05)`
- From where did you install rustfmt?: `rustup`
- How do you run rustfmt: `cargo fmt -- -v --check`

**Comment by calebcartwright** [comment]
> although https://rust-lang.github.io/rustfmt/?version=master&search=#ignore states otherwise.

You're using rustfmt 1.4.24 but looking at the documentation for the absolute latest and greatest in source control

Try using the same version of the docs as the version you are using: https://rust-lang.github.io/rustfmt/?version=v1.4.24
