### ISSUE TITLE
Rustfmt does not format some redundant imports

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rustfmt#4594]
**Describe the bug**

Rustfmt does not normalize `use std::rc::Weak as Weak;` to `use std::rc::Weak;` in some cases.

**To Reproduce**

`x.py fmt` on https://github.com/rust-lang/rust/blob/c3ed6681ff8d446e68ce272be4bf66f4145f6e29/compiler/rustc_data_structures/src/sync.rs#L224

**Expected behavior**

It should turn that line into `use std::rc::Weak;`, the same way it does on playground: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=2fbcb920f10e1ad6b4883e3970eba5cc. I'm not sure why this only breaks on rustc.

**Meta**

- rustfmt version: `rustfmt: nightly-2020-11-19`
- From where did you install rustfmt?: however x.py downloads it, probably CI artifacts directly?
- How do you run rustfmt: `x.py fmt`

**Comment by jyn514** [comment]
This might be because it's inside a `cfg_if!`?

**Comment by jyn514** [comment]
Ok yes, this was because of the macro: https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=b39c431c5fba50549d424848e86a009d

**Comment by calebcartwright** [comment]
> Ok yes, this was because of the macro:

Correct. Mac call formatting is intentionally pretty limited for various reasons (complexity, failure to be semantics preserving, high potential for butchering, etc.) and that definitely holds true for items within cfg_if. rustfmt will recurse into and format any mods defined or imported within cfg_if, but not the items themselves

**Comment by calebcartwright** [comment]
Going to go ahead and close as there's various other open issues like #8 around macro and mac call formatting
