### ISSUE TITLE
cargo fmt --all downloads dependencies

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/rustfmt#4599]
**Describe the bug**

When running `cargo fmt` with the `--all` argument, it will download all dependencies in the current workspace, including for targets not used on the current platform.

**To Reproduce**

1. Create a new empty crate and add a dependency on `serde = "1"`.
2. Remove `serde-*.crate` from `~/.cargo/registry/cache/github.com-*/`
3. Run `cargo fmt`
4. Check that no `serde-*.crate` files were downloaded into `~/.cargo/registry/cache/`
5. Run `cargo fmt --all`
6. Observe that the call takes longer, and that `serde-*.crate` was downloaded into `~/.cargo/registry/cache/`

Furthermore, do the above with a `cfg`-gated dependency on `serde` using

```toml
[target.'cfg(bogus)'.dependencies]
serde = "0.2"
```

Notice that `serde` is still downloaded with `--all`, even though it does not even meet the target platform.

**Expected behavior**

`cargo fmt` should never download dependencies, whether run with `--all` or not.

**Meta**

- rustfmt version: `rustfmt 1.4.24-stable (eb894d53 2020-11-05)`
- From where did you install rustfmt?: `rustup`
- How do you run rustfmt: `cargo-fmt`

**Diagnosis**

The origin of this issue is that `--all` invokes `cargo metadata` without `--no-deps`
https://github.com/rust-lang/rustfmt/blob/81ad114d12c2d7dd2253afd64f0d2019697aa6de/src/cargo-fmt/main.rs#L456

This behavior was introduced in https://github.com/rust-lang/rustfmt/pull/3664, and the reasoning is spelled out in https://github.com/rust-lang/rustfmt/pull/3664#discussion_r298844369. I think this probably requires a fix to upstream, but I'm not sure (ideas welcome!). I figured that regardless, a tracking issue would be useful.

The `target` issue could conceivably be fixed by passing `--filter-platform` to `cargo metadata` (it considers all targets by default). But, that would still only work subject to https://github.com/rust-lang/cargo/pull/8987, and would also mean that `cfg`-guarded workspace members would not be walked by `rustfmt` (I think?).

**Comment by jonhoo** [comment]
The requisite upstream feature we need is https://github.com/rust-lang/cargo/issues/7483

**Comment by calebcartwright** [comment]
Thanks for the report, but I'm going to close as a duplicate as there's a few open issues where this has been discussed already (e.g. #4247) and summarized in https://github.com/rust-lang/rustfmt/issues/4247#issuecomment-644957261

**Comment by jonhoo** [comment]
I'm terrible at searching, my apologies! I'll try to help pushing on upstream to figure out a fix :)

**Comment by calebcartwright** [comment]
No worries, and thanks for your work in this space! It's a tricky issue on both sides and has negative impacts on some portion of the user base so getting this resolved would be fantastic
