### ISSUE TITLE
`wrap_comments = true` breaks markdown tables

### ISSUE THREAD

**Issue by jhpratt** [rust-lang/rustfmt#4607]
To be 100% clear: I am aware this is a duplicate. It appears this is a regression, as presumably it worked at some point (the original is closed).

See #4210. This _exact_ situation occurs on latest rustfmt.

**Describe the bug**

Running `rustfmt --config wrap_comments=true example.rs` on

```rust
/// doc
///
/// Table that is > 80 symbols:
///
/// | table | xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx |
/// |-------|--------------------------------------------------------------------|
/// | val   | x                                                                  |
struct Item;
```

turns it into

```rust
/// doc
///
/// Table that is > 80 symbols:
///
/// | table | xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
/// |
/// |-------|--------------------------------------------------------------------|
/// | val   | x
/// |
struct Item;
```

This breaks the markdown.

**Meta**

- rustfmt version: rustfmt 1.4.29-nightly (70ce182 2020-12-04)
- From where did you install rustfmt?: rustup
- How do you run rustfmt: Reproducible with just plain old `rustfmt`

Related:
- #4214, which presumably fixed the issue initially. The code appears to be present [here](https://github.com/rust-lang/rustfmt/blob/367a874d04abfb2269ff1ea1974f06640546b7c5/src/formatting/comment.rs#L890-L896), but for some reason it's not being used (I haven't dug into this)
- #3347 for stabilization. This is likely one of the final blockers.

**Comment by calebcartwright** [comment]
> It appears this is a regression, as presumably it worked at some point (the original is closed).

Closing because this is both a duplicate and incorrect. I've also added the backport pending label to #4210 for clarity
