### ISSUE TITLE
Indentation in macros is handled oddly

### ISSUE THREAD

**Issue by delbonis** [rust-lang/rustfmt#4611]
**Input**

```rust
    tokio::select! {
	result = reader => {
            match result {
		Ok(v) => {
		    eprintln!(
                    "message: {}",
                    v
                    );
                },
		Err(_) => {
		    eprintln!(
                        "error: {}",
                        e
                    );
                },
            }
	},
	_ = writer => {
            // Comment
            eprintln!(
                "completed: {}",
                some_other_field
            );
	}
    }
```

This is basically what `company-mode` gives us.  I edited it slightly from the actual code but preserved the indentation.

**Output**

```rust
    tokio::select! {
    result = reader => {
            match result {
        Ok(v) => {
            eprintln!(
            "message: {}",
            v
            );
        },
        Err(e) => {
            eprintln!(
            "error: {}",
            e
            );
        }
            }
    },
    _ = writer => {
            // Comment
            eprintln!(
                "completed: {}",
                some_other_field
            );
    }
    }
```

**Expected output**

Something that resembles the input.

**Meta**

- rustfmt version: `rustfmt 1.4.30-nightly (acd9486 2020-12-20)`
- From where did you install rustfmt?: rustup

**Comment by calebcartwright** [comment]
Could you check to see if you have hard tabs in your original source (or more likely a mix of tabs/spaces) that are being converted to all spaces? rustfmt doesn't really format macro calls (outside a few cases with calls using parens instead of braces), so tabs --> spaces seems like the most likely cause

**Comment by alvatar** [comment]
Where was this completed @delbonis ? How can I use it? Formatting still doesn't work for the select macro.

**Comment by alishir** [comment]
@alvatar I have the same issue, do you have any workaround?

**Comment by calebcartwright** [comment]
rustfmt does not apply formatting rules to args when the call sites use brace delims, and the output should generally match the input. This particular issue was _not_ about rustfmt applying formatting rules to the contents of the `select` macro, but that rustfmt was seemingly modifying the leading indentation of the input (though given the closure of the issue, I assume the cause of this was differing whitespace strategy of tabs vs. spaces in the input vs. the configuration values for e.g. `hard_tabs`).

There's no point in asking for macro-specific formatting here (you can subscribe/follow along at #8 for those discussions), and if you're seeing the exact behavior described in the original description of this issue while 100% confident you don't have the referenced tabs vs. spaces cause, then please open a new issue with a minimal, complete repro
