### ISSUE TITLE
Format `struct Foo()` as `struct Foo`

### ISSUE THREAD

**Issue by camelid** [rust-lang/rustfmt#4625]
:clipboard: **Description**

Currently, rustfmt leaves this code as it is:

```rust
struct Foo();

fn main() {
    let x = Foo();
}
```

despite the fact that `Foo()` is equivalent to `Foo` here. It's confusing to leave the empty parentheses in since they don't make a difference and (to my knowledge) are not the standard way people write unit structs. Additionally, people may confuse `struct Foo()` with `struct Foo(())` – they are not the same thing.

It seems that it might be better to format the code as:

```rust
struct Foo;

fn main() {
    let x = Foo;
}
```

**Comment by camelid** [comment]
This should also be done for empty enum tuple variants:

```rust
enum Foo {
    Bar(),
}

fn main() {
    let x = Foo::Bar();
}
```

**Comment by calebcartwright** [comment]
Thanks for the suggestion. Though I understand and appreciate the desire for tooling to detect/assist in these cases, this isn't something we'll be able to do in rustfmt. Perhaps this could be implemented as a lint in Clippy if one doesn't already exist?

Rationale:
* rustfmt can't do this safely when formatting a single file/subset of a project (e.g. definition and all uses not all contained within a single file), as changing the definition without changing all uses (or vice versa) will break the code. That's not only a plausible scenario, but one highly likely to occur when you consider format-on-save behavior in editors.
    * This could also be confusing/frustrating for folks, especially new users, such as writing the definitions with placeholders during their inner dev loop and then saving
* Even when formatting an entire project, rustfmt would likely require some more exotic internal mechanisms than exists today to handle the edge cases (think comments)
* As a general rule of thumb, we want the AST parsed from pre-formatting and post-formatting to match. There's obviously a few exceptions to this, such as the elision of some redundant semis which results in the post-formatting AST not having the corresponding empty statement, but post-formatting AST modifications are definitely the exception, not the norm

Closing accordingly

**Comment by camelid** [comment]
Okay, I understand your reasoning :) Thanks for taking the time to write an expansive response!

> rustfmt can't do this safely when formatting a single file/subset of a project (e.g. definition and all uses not all contained within a single file), as changing the definition without changing all uses (or vice versa) will break the code. That's not only a plausible scenario, but one highly likely to occur when you consider format-on-save behavior in editors.

Note that you *could* turn uses like `Foo` into `Foo()` because both are valid for `struct Foo()`. That *might* be helpful since it makes it clear that `Foo` is not defined as a unit struct (or unit tuple variant).
