### ISSUE TITLE
Change default version used in configuration website from master to latest 1.x

### ISSUE THREAD

**Issue by calebcartwright** [rust-lang/rustfmt#4633]
rustfmt has a documentation site that enumerates all the configuration options available for a given version of rustfmt

https://rust-lang.github.io/rustfmt/

The site allows users to specify which version of rustfmt they want config documentation for, because the available/support config options can vary from one version of rustfmt to another (i.e. rustfmt v1.4.30 has different options than rustfmt v1.4.12)

The _default_ rustfmt version used on the site is actually pointing the `master` branch in the rustfmt source repo itself. However, this has proven to be problematic because:
* there's a huge difference between the configuration options in source control and the 1.x versions of rustfmt that are distributed and used by the community
* most users still don't realize/understand they need to select the version on the config site to match the version of rustfmt they are actually using
* there are comparatively very, very few users building and using rustfmt from source, so the current default of `master` is not a good default because it requires the vast majority of users to need to take an additional action on the config site.

The ask for this issue is to change that default from `master` to a different, new default. Ideally, the default could somehow be dynamically set to the latest (semver) `v1.*` version from the list, though if that proves impossible/too complex then simply hardcoding it to a different value (like `v1.4.31`) would suffice, and the rustfmt team will manually update that hardcoded value to the next value when we release a new version of rustfmt.

The code for the config site can be found here:
https://github.com/rust-lang/rustfmt/blob/master/docs/index.html

**Comment by gunadhya** [comment]
Hi @calebcartwright, I'd like to work on this issue.

**Comment by calebcartwright** [comment]
@gunadhya - great, thanks!

**Comment by iwahbe** [comment]
Should this issue still be open?

**Comment by calebcartwright** [comment]
> Should this issue still be open?

Yes indeed! Details in the PR linked to this issue https://github.com/rust-lang/rustfmt/pull/4644#issuecomment-764072051

**Comment by hdost** [comment]
It looks like this has been succesfully completed as the back port has also been complete #4958

**Comment by calebcartwright** [comment]
> It looks like this has been succesfully completed as the back port has also been complete #4958

@hdost - no, it hasn't. Please see my previous comment detailing why the issue is still open.

**Comment by gentoid** [comment]
#4644 is already merged, and I checked https://rust-lang.github.io/rustfmt/ seems to be already fixed. So can this issue be closed?

**Comment by calebcartwright** [comment]
Indeed, thanks all
