### ISSUE TITLE
corrupted output when using comments within generic type parameters of a trait

### ISSUE THREAD

**Issue by juliuste** [rust-lang/rustfmt#4643]
**Describe the bug**

When using comments within generic type parameters of a **`trait`**, rustfmt corrupts the code as follows:

##### Input

```rust
pub trait Something<
	A,
	// some comment
	B,
	C
> {
    fn a(&self, x: A) -> i32;
    fn b(&self, x: B) -> i32;
    fn c(&self, x: C) -> i32;
}
```

##### Output

```rust
pub trait Something<
    A,
    // some comment
    B,
    C,
> // some comment
B,
C
>
{
    fn a(&self, x: A) -> i32;
    fn b(&self, x: B) -> i32;
    fn c(&self, x: C) -> i32;
}
```

The same applies for `/* block comments */`:

##### Input

```rust
pub trait Something<
	A,
	/* some comment */
	B,
	C
> {
    fn a(&self, x: A) -> i32;
    fn b(&self, x: B) -> i32;
    fn c(&self, x: C) -> i32;
}
```

##### Output

```
pub trait Something<A, /* some comment */ B, C> /* some comment */
B,
C
>
{
    fn a(&self, x: A) -> i32;
    fn b(&self, x: B) -> i32;
    fn c(&self, x: C) -> i32;
}
```

However, this issue doesn't seem to appear for `fn`s and `struct`s.

**To Reproduce**

- Trait with single-line-comment (broken) - [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=23041730dad13ebbf47989bb8aa19132)
- Trait with block comment (broken) - [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1c76df0ad1364fb3d1b4299dad7a0d01)
- Struct with single-line-comment (**not** broken, just for comparison) - [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=699587c5f91a6ce4b007cf2f235fa3d2)
- Function with single-line-comment (**not** broken, just for comparison) - [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a7b1e0d1c0f1bff07e1d2edf0eece2a9)

I ran `rustfmt` without any parameters, so just `rustfmt some-file-containing-the-example-above.rs`.

**Expected behavior**

I would expect the same formatting as for `struct`s and `fn`s (see the struct playground linked above).

**Meta**

- rustfmt version: `rustfmt 1.4.30-nightly (acd94866 2020-12-20)`
- From where did you install rustfmt?: rustup (nightly toolchain)
- How do you run rustfmt: `rustfmt +nightly`

**Additional remarks**

- I didn't find any existing issues matching this problem description, #4263 looks a bit similar, though.
- Thank you all very much for maintaining this project, it's incredibly useful.
- I'm still a noob at writing rust, so I'm sorry if this is not actually a bug, but rather some mistake on my side.

**Comment by whizsid** [comment]
I will work on this issue.

**Comment by ytmimi** [comment]
@jmj0502 This issue was resolved by your PR #5446. I'd like to include a test case for this before closing it. If you have some interest and time to open up a PR with a test case for this that would be great! A PR similar to #5469 would be great 😁

**Comment by jmj0502** [comment]
@ytmimi Sure! No problem , I'll add a test case for this issue in a few minutes c:.

**Comment by jmj0502** [comment]
@ytmimi Donee! 👍

**Comment by juliuste** [comment]
Thank you all for the work! 🧡 🦀
