### ISSUE TITLE
rustfmt ignores the edition setting?

### ISSUE THREAD

**Issue by matthiasbeyer** [rust-lang/rustfmt#4645]
**Describe the bug**

My crate is `edition = "2018"`, but:

```
$ cargo fmt
error[E0670]: `async fn` is not permitted in the 2015 edition
  --> /home/m/archive/development/rust/butido/src/main.rs:73:1
   |
73 | async fn main() -> Result<()> {
   | ^^^^^ to use `async fn`, switch to Rust 2018
   |
   = help: set `edition = "2018"` in `Cargo.toml`
   = note: for more on editions, read https://doc.rust-lang.org/edition-guide
```

**To Reproduce**

1. clone https://git.sr.ht/~matthiasbeyer/butido or https://github.com/science-computing/butido
2. Make sure to `git checkout c638b21c1e09ba7a0a76e0fa5d930fbc11abe62d` (current master)
3. `cargo fmt`
4. see above error message
5. `grep edition Cargo.toml`

**Expected behavior**

It formats the code.

**Meta**

- rustfmt version: `rustfmt 1.4.25-stable (0f29ff6 2020-11-11)`
- From where did you install rustfmt?: `cargo install rustfmt`
- How do you run rustfmt: `cargo fmt`

**Comment by calebcartwright** [comment]
> From where did you install rustfmt?: cargo install rustfmt

Just want to verify this is correct and is indeed how you installed rustfmt? 

That `rustfmt` crate is deprecated incredibly outdated and not one of the distribution channels for rustfmt (https://crates.io/crates/rustfmt), so if that's how you installed it you've got a versioning issue on your system.

**Comment by matthiasbeyer** [comment]
grrr... I'm probably not the first one hitting this issue, right? Any chance the "rustfmt" crate gets yanked?

Not sure about the versioning issue you mentioned:

```
$ rustc --version
rustc 1.48.0 (7eac88abb 2020-11-16)
$ cargo --version
cargo 1.48.0 (65cbdd2dc 2020-10-14)
```

**Comment by calebcartwright** [comment]
> grrr... I'm probably not the first one hitting this issue, right? Any chance the "rustfmt" crate gets yanked?

see #4343

> $ cargo fmt --version
Unrecognized option: 'version'

This output is definitively indicative of having an issue on your system, notably a very, very old cargo fmt bin being invoked. Would advise explicitly uninstalling the `rustfmt` crate just in case

**Comment by matthiasbeyer** [comment]
Okay, so it seems that there was a `rustfmt` and a `cargo-fmt` in my `~/.cargo/bin`, which is obviously not what I want, hence I install them from nix.
That solved my issue.
