### ISSUE TITLE
imports_granularity: implement One/Single variant

### ISSUE THREAD

**Issue by calebcartwright** [rust-lang/rustfmt#4669]
Add a new variant and associated formatting to `imports_granularity` that reformats all imports into a single use statement. The variant name should be `One` or `Single`, with `One` being the leading contender (refer [here for One](https://github.com/rust-lang/rustfmt/issues/3362#issuecomment-752723437) and [here for Single](https://github.com/rust-lang/rustfmt/issues/3362#issuecomment-752777078) for respective community votes/feedback)

```rust
use {
    futures::{
        ready,
        stream::{Stream, StreamExt},
    },
    std::pin::{Pin, Unpin},
};
```

### Background

`imports_granularity` is a configuration option that allows users to control the granularity of their use declarations (https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#imports_granularity)

By default rustfmt will not modify the granularity and will preserve the developers original structure, but the `imports_granularity` option provides several different variants that users can leverage to instruct rustfmt to reformat their use statements with a specific level of granularity.

Several different styles/granularity levels have been identified (summarized [here](https://github.com/rust-lang/rustfmt/issues/3362#issuecomment-642564290), and already implemented, with the exception of the one/single granularity variant.

### Implementation
There will be 3 high level tasks required here

* Updating the configuration option information
* Updating the imports merging logic to support the new granularity style
* Adding tests

For the configuration side:
* [Documentation](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#imports_granularity) will need to be extended with the new variant details
* [Adding the new variant](https://github.com/rust-lang/rustfmt/blob/79c36960af85fa52ae4dc60ec1f83ec7f9b2733f/src/config/options.rs#L122-L133)

For implementation, refer to relevant sections in `src/formatting/imports.rs` and `src/formatting/reorder.rs`, some suggested starting points:
https://github.com/rust-lang/rustfmt/blob/79c36960af85fa52ae4dc60ec1f83ec7f9b2733f/src/formatting/imports.rs#L872-L875
https://github.com/rust-lang/rustfmt/blob/79c36960af85fa52ae4dc60ec1f83ec7f9b2733f/src/formatting/imports.rs#L550-L565
https://github.com/rust-lang/rustfmt/blob/79c36960af85fa52ae4dc60ec1f83ec7f9b2733f/src/formatting/reorder.rs#L231-L238

For tests (more information on writing tests [here](https://github.com/rust-lang/rustfmt/blob/master/Contributing.md#creating-test-cases)):
Some unit tests for the other variants can be found here
https://github.com/rust-lang/rustfmt/blob/master/src/formatting/imports.rs#L1032-L1087

Additional files for the system/idempotence tests can be found under `tests/{src,target}/imports_granularity_{crate,item,module}.rs` for reference

**Comment by magurotuna** [comment]
I'm interested in this issue. Can I work on it?

**Comment by calebcartwright** [comment]
> I'm interested in this issue. Can I work on it?

Absolutely! Let us know if you have any questions
