### ISSUE TITLE
Double Space between `pub &` when preceeded by long attribute

### ISSUE THREAD

**Issue by jonasbb** [rust-lang/rustfmt#4671]
**Describe the bug**

Formatting this code places two spaces between `pub` and `&`.

```rust
struct X<'a>(
    #[X(X = "_________________________________________________________________________")]
    pub  &'a u32,
    // ^^
);
```

**Expected behavior**

The usual formatting is `pub &'a u32` (single space). I would expect rustfmt to stay consistent. Removing the attribute, shortening it, or turning it into a comment all lead to the single space formatting.

**Meta**

- rustfmt 1.4.25-stable (0f29ff6 2020-11-11)
- rustfmt 1.4.30-nightly (acd9486 2020-12-20)
- rustfmt 1.4.32-nightly (2021-01-16 216a643) (playground)
- From where did you install rustfmt? rustup, playground
- How do you run rustfmt: cargo fmt, playground, VSCode

**Comment by calebcartwright** [comment]
Well that is extremely odd indeed, thanks for the report!

**Comment by whizsid** [comment]
I am working on this issue.
