### ISSUE TITLE
Rustfmt causes compilation error by inserting illegal trailing comma in macro

### ISSUE THREAD

**Issue by Aloso** [rust-lang/rustfmt#4675]
**Describe the bug**

Struct patterns that end with `..` can't have a trailing comma. However, rustfmt on nightly inserts one within `macro_rules!`.

**To Reproduce**

Run `rustup default nightly`, then format this code:

```rust
macro_rules! foo {
    ($s:ident ( $p:pat )) => {
        Foo {
            name: Name::$s($p),
            ..
        }
    };
}
```

**Expected behavior**

The comma should not be inserted to ensure that expanded code compiles.

**Meta**

- rustfmt version: `rustfmt 1.4.32-nightly (216a643 2021-01-16)`
- From where did you install rustfmt? Via rustup
- How do you run rustfmt: Either with `cargo fmt` or with rust-analyzer (makes no difference)

**Comment by Aloso** [comment]
@calebcartwright Thanks for fixing this so quickly!

**Comment by calebcartwright** [comment]
> @calebcartwright Thanks for fixing this so quickly!

Sure! It was really just a case of exceptionally fortuitous timing, as this popped up right as I was preparing to update rustfmt on nightly and it only needed a trivial fix.

Any future issues will almost certainly not have the same turnaround :smile:
