### ISSUE TITLE
A way to opt out from rustfmt

### ISSUE THREAD

**Issue by MikailBag** [rust-lang/rustfmt#4691]
# Problem
Some projects do not use rustfmt (e.g. [Rocket](https://github.com/SergioBenitez/Rocket)). When one contributes to such a project, their IDE can invoke rustfmt, resulting in many unrelated code changes. Contributor is then requested to rollback such formatting changes. That way accidental rustfmt invocation can result in spending much effort.

# Solution
Rustfmt should provide some way to explicitly say "I don't want this project to be formatted".
I imagine this should be implemented as a configuration option, e.g.
```toml
# rustfmt.toml
disable = true
```
when this option is enabled, rustfmt on every invocation should print a warning and exit without modifying any files.
# Workaround
Add a syntactically invalid rustfmt.toml.
Rustfmt will fail to parse it and immediately crash.

**Comment by calebcartwright** [comment]
The recommendation in these cases is for those projects to add a config that leverages the `ignore` option

https://rust-lang.github.io/rustfmt/?version=v1.4.35&search=#ignore

> If you want to ignore every file under the directory where you put your rustfmt.toml:
>
> ignore = ["/"]
