### ISSUE TITLE
Rustfmt deletes comments in 'use {}'

### ISSUE THREAD

**Issue by darakshan** [rust-lang/rustfmt#4708]
**Describe the bug**

**To Reproduce**
run rustfmt on the following code:

use {std::env::args /* this comment gets removed */};
fn main() {println!("hello from {}!", args().next().unwrap());}

**Expected behavior**

comment should be preserved

**Meta**

- rustfmt version: rustfmt 1.4.30-stable (8c6769d7 2021-01-18)
- From where did you install rustfmt? :rustup
- How do you run rustfmt: Cargo-fmt and VScode

**Comment by kangalioo** [comment]
Here's a slightly more common example of where this bug results in an annoyance:

```rust
pub use serenity::model::{
	// channel::{Message, Reaction, ReactionType},
	// gateway::Ready,
	// guild::{Member, Role},
	// id::{ChannelId, GuildId, MessageId, RoleId, UserId},
	// permissions::Permissions,
	prelude::*,
	// user::User,
};
```

Upon invoking rustfmt, all the commented-out lines disappeared

**Comment by AndrewKvalheim** [comment]
Is this the same as #3984?

**Comment by ytmimi** [comment]
@AndrewKvalheim it seems like they are the same. Thanks for pointing that out 😁

**Comment by ytmimi** [comment]
This was completed in https://github.com/rust-lang/rustfmt/pull/5853
