### ISSUE TITLE
Macro indenting again

### ISSUE THREAD

**Issue by adsharma** [rust-lang/rustfmt#4712]
Context: 
https://github.com/adsharma/py2many is a transpiler which generates weirdly formatted code in different languages and expects the language specific formatter to make it readable, both for humans and for automated tests.

rustfmt works great most of the time, except for this issue. This is essentially the same as #1885, but may be a bit narrower.

**Input**

```use flagset::flags;
use flagset::FlagSet;
use std::os::raw::c_int;

flags! {
    enum Permissions: c_int {
R = 1,
W = 2,
X = 16,
}
}

```

**Output**

```no change
```

**Expected output**

```
use flagset::flags;
use flagset::FlagSet;
use std::os::raw::c_int;

flags! {
    enum Permissions: c_int {
        R = 1,
        W = 2,
        X = 16,
    }
}
```

**Comment by calebcartwright** [comment]
Thanks for reaching out but going close this. rustfmt support for formatting macro calls is still fairly limited, and in cases where the brace delims are used we don't do any formatting at all. #8 is the general macro-related issue folks may want to subscribe to for updates, but to be fully transparent I don't anticipate we'll be formatting these types of mac calls any time soon

**Comment by adsharma** [comment]
No worries. Worked around it in the transpiler.

https://github.com/adsharma/py2many/commit/532e7820fc15184221ef23fb3a74a75d9297d21f

Thanks for looking into it.
