### ISSUE TITLE
Noncompilable output on attribute containing string literal containing brace

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rustfmt#4724]
As of current master (2e1a9823d84fbb8e39059b7d4af6d074ced7c6fd):

```console
$  echo 'struct x{/** */#[x="{"]x:x}' | CFG_RELEASE_CHANNEL=dev CFG_RELEASE=1 cargo run --features rustfmt --bin rustfmt

struct x {
    /** */#[x="{
    /** */
    #[x = "{"]
    x: x,
}
```

That output has mismatched `"` and some duplication of parts of the input.

It seems to do a better job if you swap "{" to "}". But my expectation would be that the formatting is the same regardless of which string is in the attribute.

```console
$  echo 'struct x{/** */#[x="}"]x:x}' | CFG_RELEASE_CHANNEL=dev CFG_RELEASE=1 cargo run --features rustfmt --bin rustfmt

struct x {
    /** */
    #[x = "}"]
    x: x,
}
```

#4452 appears similar but is specific to attributes on expressions, so I am filing this separately.

**Comment by calebcartwright** [comment]
Thanks for the report. The differing behavior between opening and closing braces makes me think it's likely a bug in our searching for the body opening vs. the type of span issue that caused #4452 so agreed on separate issue :+1: 

Have a little free time so will look at this one shortly
