### ISSUE TITLE
`pub` on `macro_rules!` not supported

### ISSUE THREAD

**Issue by JulianKnodt** [rust-lang/rustfmt#4728]
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=71be237d1aed61df9bbdb665bbd5a056`

I expected to be able to format with rustfmt,

but when running rustfmt there is an error despite compilation succeeding.

The implementation PR is [82296](https://github.com/rust-lang/rust/pull/82296), but unsure if there's a RFC for the original idea.

**Comment by calebcartwright** [comment]
Thanks for the report. We consume the rustc internals via the auto publish crates, so we always lag behind rustc changes somewhat. This should be a straightforward update on our side but may take a little while to pull in and apply the upstream updates

**Comment by calebcartwright** [comment]
Closing as this no longer seems relevant given the upstream state (though I expect that if the feature and syntax support are brought back the visibility will be maintained now that we consume the rustc internals via rustc-dev)
