### ISSUE TITLE
Explicitly tell rustfmt which sections to format

### ISSUE THREAD

**Issue by qrnch-jan** [rust-lang/rustfmt#4729]
When we use the `tokio::select! { }` macro, the arms aren't formatted by rustfmt .. which is understandable.

But the arms do actually contain valid Rust code, so it would be nice if it were possible to tell rustfmt that certain sections are actually valid Rust and should be formatted as such, even though they may appear to be within a context where it normally shouldn't.

**Comment by calebcartwright** [comment]
Thanks for reaching out but going to close this as a duplicate/in favor of #8.

Due the nature of how macro calls and defs are represented in the rustc AST, rustfmt would really need to be able format everything. Adding additional moving parts on top of the current machinery to only be able to sometimes format some parts would only add complexity and increase the surface for bugs and butchering of code.

We need a more holistic way of being able to process the token stream but that's a big undertaking that's not an immediate priority. Any updates/communications will be posted on #8
