### ISSUE TITLE
Advertise version property in the Readme

### ISSUE THREAD

**Issue by camsteffen** [rust-lang/rustfmt#4732]
IIUC, rustfmt 2.0 is not coming any time soon, and until then, de-facto usage of rustfmt is to specify `version = "Two"` to include bug fixes, especially for new projects. So this should be explained in the Readme in the default branch.

**Comment by calebcartwright** [comment]
Thanks for sharing your perspective, but going to close as there's no bug here nor will we take the requested action.

Configuration options exist to allow consumers to override default behavior, and we're never going to get into the position of prescribing things that diverge from the default. Additionally, `version` is not available on stable/beta.

The `version` option doesn't have anything to do with bug fixes. It controls whether or not to keep emitted formatting exactly the same or, if the user desires, opt-in to potential formatting changes as rustfmt evolves. Bug fixes, be they in rustfmt or rustc, are always applied regardless.

As described in the configuration option documentation on https://rust-lang.github.io/rustfmt/?version=v1.4.36
> Which version of the formatting rules to use. Version::One is backwards-compatible with Rustfmt 1.0. Other versions are only backwards compatible within a major version number.

It's up to a given user/team whether they want to opt-in to a non-default value for `version` and periodically see formatting changes, we're not going to prescribe that folks do so.

**Comment by camsteffen** [comment]
Fair enough. FWIW I only reported this as a bug because it was the closest fitting issue template.
