### ISSUE TITLE
Inline an "if let" the same way as a "match" inside of an outer "match" arm

### ISSUE THREAD

**Issue by wheelerlaw** [rust-lang/rustfmt#4742]
When one uses a match expression inside of an outer match arm that encloses the inner `match` with braces, `rustfmt` will automatically remove the braces and inline it, like so:

```rust
            None => {
                match replace(&mut self.val, None) {
                    Some => {
                        self.val -= 1;
                        Some(c)
                    }
                }
            }
```

Becomes:

```rust
            None => match replace(&mut self.val, None) {
                Some => {
                    self.val -= 1;
                    Some(c)
                }
            },
```

It would be nice if I used an `if let` instead of a `match`, that the same formatting behavior was preserved:

# 1 
**Input**

```rust
            None => {
                if let Some(c) = replace(&mut self.val, None) {
                    self.val -= 1;
                    Some(c)
                }
            }
```

**Output**

```rust
            None => {
                if let Some(c) = replace(&mut self.val, None) {
                    self.val -= 1;
                    Some(c)
                }
            }
```

**Expected output**

```rust
            None => if let Some(c) = replace(&mut self.val, None) {
                self.val -= 1;
                Some(c)
            }
```

# 2
**Input**

```rust
            None => if let Some(c) = replace(&mut self.val, None) {
                self.val -= 1;
                Some(c)
            }
```

**Output**

```rust
            None => {
                if let Some(c) = replace(&mut self.val, None) {
                    self.val -= 1;
                    Some(c)
                }
            }
```

**Expected output**

```rust
            None => if let Some(c) = replace(&mut self.val, None) {
                self.val -= 1;
                Some(c)
            }
```

**Meta**

- rustfmt version: rustfmt 1.4.30-stable (8c6769d 2021-01-18)
- From where did you install rustfmt?: rustup

**Comment by calebcartwright** [comment]
Thanks for reaching out, but this is the expected formatting as dictated by the Rust Style Guide, relevant section on match formatting shared below for reference

https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/expressions.md#match

> If the body is a single expression with no line comments and not a control flow expression, then it may be started on the same line as the left-hand side. If not, then it must be in a block
