### ISSUE TITLE
Rustfmt eats comments inside unit type in struct/enum definitions

### ISSUE THREAD

**Issue by HactarCE** [rust-lang/rustfmt#4749]
**Describe the bug**

Rustfmt eats comments inside the unit type `()` in struct and enum definitions. I sometimes find it useful to put comments there when I am not sure what type something will be, but I know I will need it later.

**To Reproduce**

Run Rustfmt on the following code:

```
struct S {
    x: (/* type */),
}

struct S2((/* type */));

enum E {
    Variant1 {
        x: (/* type */),
    },
    Variant2((/* type */)),
}
```

[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=61030a9a75a263e454885e9ffb673386)

**Expected behavior**

All four comments should remain intact.

**Meta**

- rustfmt version: 1.4.36-nightly (2021-02-07 7de6968)
- From where did you install rustfmt?: Rust Playground
- How do you run rustfmt: Tools -> Rustfmt

**Comment by calebcartwright** [comment]
Thanks for the report!

**Comment by whizsid** [comment]
I am working on this issue.
