### ISSUE TITLE
Have option to auto-indent closure block as new scope

### ISSUE THREAD

**Issue by DoumanAsh** [rust-lang/rustfmt#4760]
Have option to indent closure block as new scope according to tabulation

For example instead of

```rust
        let mut this = scope_guard::scope_guard!(|this| {
                                                     if this.state.app.maintenance.billbox.is_none() {
                                                         this.state.app.maintenance.billbox = Some(Default::default());
                                                     }
                                                 },
                                                 self);
```

I would prefer to have option to preserve ident as if closure content starts new scope:

```rust
        let mut this = scope_guard::scope_guard!(|this| {
            if this.state.app.maintenance.billbox.is_none() {
                this.state.app.maintenance.billbox = Some(Default::default());
            },
            self
        }
```
Where tab is 4 spaces

As you can see my suggestion makes it as closure is just new scope instead of having it far away making it plain ugly.

**Comment by DoumanAsh** [comment]
Never mind, using visual style for blocks is difficult to control right now

**Comment by calebcartwright** [comment]
> As you can see my suggestion makes it as closure is just new scope instead of having it far away making it plain ugly.

I'm not really sure what this is in reference to. The default formatting that is emitted is based upon the [official Rust Style guide](https://github.com/rust-dev-tools/fmt-rfcs/), and does not look like your snippet. It looks like this:

```rust
    let mut this = scope_guard::scope_guard!(
        |this| {
            if this.state.app.maintenance.billbox.is_none() {
                this.state.app.maintenance.billbox = Some(Default::default());
            }
        },
        self
    );
```

https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/expressions.md#multi-line-calls
https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/expressions.md#closures

**Comment by DoumanAsh** [comment]
Official Rust style guide is ugly then.
For me it should look like I described

**Comment by calebcartwright** [comment]
> Official Rust style guide is ugly then.
It should look like I described

These types of comments are neither helpful nor constructive, and I'd ask that you refrain from making them.

The autoformatting tool is designed to reformat code in a predictable, consistent way that works reasonably well in most scenarios so that developers don't have to spend time debating personal stylistic preferences. It is not designed, nor is it a goal to to emit code that every single developer finds "beautiful" in all situations; there is no such style.
