### ISSUE TITLE
rustfmt fails with thread 'main' panicked at 'bad span: `.`: ``'

### ISSUE THREAD

**Issue by willemml** [rust-lang/rustfmt#4761]
**Describe the bug**

When I try to format my project using `cargo fmt` in the root directory it fails with the following error:
```
❯ cargo fmt                                     
thread 'main' panicked at 'bad span: `.`: ``', /Users/willem/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-1.4.21/src/source_map.rs:52:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This error only occurs when the file `httpapi.rs` has it's full contents, if everything in that file is removed and replaced with `pub(crate) async fn server(bind_address: &str) -> std::io::Result<()> { Ok(()) }` then `cargo fmt` works properly with no errors.

**To Reproduce**

- Make sure that cargo and rustfmt-nightly are installed.
- Clone https://github.com/wicrs/server
- Run `cargo fmt` in the project's root.

**Expected behavior**

The project should be successfully formatted (with no errors).

**Meta**

- rustfmt version: rustfmt 1.4.21-nightly ( )
- How did you install rustfmt?: `CFG_RELEASE=1.49.0-nightly CFG_RELEASE_CHANNEL=nightly cargo +nightly install --force rustfmt-nightly`
- How do you run rustfmt: `cargo fmt`, VS Code (`rust-analyzer`)

**Comment by calebcartwright** [comment]
You are installing the wrong version of rustfmt. Please uninstall that version, and use rustup to install and manage rustfmt

**Comment by willemml** [comment]
Oh ok that worked, although I had some trouble where it was not adding the `rustfmt` binary to a directory in my path when I ran `rustup component add rustfmt`. So I added `~/.rustup/toolchains/nightly-x86_64-apple-darwin/bin` to my path and now it works, no errors when running `cargo fmt` anymore.
