### ISSUE TITLE
Formatting stops on read-only file with errors

### ISSUE THREAD

**Issue by notoria** [rust-lang/rustfmt#4785]
**Describe the bug**
`rustfmt` cannot format a project if there is a readonly file.

**To Reproduce**
Any project and  make a file readonly, then all the files that come after it won't be formatted.

**Expected behavior**
`rustfmt` reads only the file but doesn't attempt to change a readonly file and continues formatting of the other files.

**Meta**

- rustfmt version:  `rustfmt 1.4.36-nightly (7de6968 2021-02-07)`
- From where did you install rustfmt?:  `rustup`
- How do you run rustfmt:  `cargo fmt`

**Comment by calebcartwright** [comment]
hi, thanks for reaching out. Could you help me understand what your use case is for having a project of rust code, making some of the .rs files readonly, and then running the formatter in the mode that overwrites the input files?

While I suppose we could technically support this, it seems like a rather unrealistic use case and without sufficient rationalization I just don't think the overhead/tradeoffs of attempting to do so would be worthwhile.

**Comment by notoria** [comment]
The code I compiled has a file that is generated by `lalrpop` and it's read-only.

**Comment by calebcartwright** [comment]
Generated files are typically configured to have rustfmt ignore them. You're always going to have rustfmt exit with a non-zero code if you ask it to rewrite a file that's read-only, regardless of what does or does not happen with other files in the project.

Many generators will insert a `#![rustfmt::skip]` to the file(s) to avoid this, but if lalrpop isn't or can't then you can either use the [ignore](https://rust-lang.github.io/rustfmt/?version=v1.4.36&search=#ignore) configuration option in your rustfmt config file, or add the rustfmt skip attribute as an outer attribute on the import of the generated file (which I presume you have somewhere in your project)

**Comment by notoria** [comment]
It's an old code (2017). Thank you, the `ignore` configuration option solved.
