### ISSUE TITLE
Left behind trailing whitespace in mix of macros, long line, closure

### ISSUE THREAD

**Issue by HeroicKatora** [rust-lang/rustfmt#4790]
**Describe the bug**

The tool exists with an error output:

```
error[internal]: left behind trailing whitespace
 --> /playground/src/main.rs:3:3:0
  |
3 |         
  | ^^^^^^^^
  |

warning: rustfmt has failed to format. See previous 1 errors.
```

**To Reproduce**

This has been minimalized from a file within [pdf_derive](https://github.com/pdf-rs/pdf/blob/c05ed813cbc3dcaf5e7a304da58259ce600203d3/pdf_derive/src/lib.rs). Replacing the expression `f.m` by `m` alone fixes the issue. As does using a block instead of a closure. As does shortening the line within `q!` by a single character.

```rust
fn b() {
    f.m(|| {
        
        q! {
            { <#ty as pdf::object::Object>::from_primitive(pdf::primitive::Primitive::Nul, resolve) }
        }
    });
}
```

**Expected behavior**

The whitespace line 3 should be removed.

**Meta**

- rustfmt version: 1.4.36-nightly (2021-02-07 7de6968)
- From where did you install rustfmt?: rustup
- How do you run rustfmt: `rustfmt src/lib.rs`

**Comment by calebcartwright** [comment]
Hi thanks for reaching out but I'm going to close this as a duplicate. #4778 is nearly identical and contains a pretty thorough explanation.
