### ISSUE TITLE
Comma deleted if followed by empty line

### ISSUE THREAD

**Issue by ente76** [rust-lang/rustfmt#4791]
**Describe the bug**

Define a struct with empty lines, as shown below:
```
pub struct Segment {
    header: SegmentHeader,
    
    end:    SegmentEnd
}
```

format the document (using IDE functionality which relies on rustfmt or by calling `cargo fmt`). Result looks like:
```
pub struct Segment {
    header: SegmentHeader

    end: SegmentEnd
}
```

**To Reproduce**

Start on a brand new project. Have all your standard project template setup and ready to start (incl. rustfmt.toml). Feel totally overwhelmed by all the new information you just gathered. Setup some basic structs. Put an empty line between two struct elements and format the document.

**Expected behavior**

rustfmt reformats the document. While doing so, some artificial intelligence hidden deep inside rustfmt realizes that Segment actually is a wrong point to start at. For such reason rustfmt deletes the comma and all the struct just before it magically implements some perfectly working UN/edifact serialization code.

**Meta**

- rustfmt version: rustfmt 1.4.36-nightly (7de6968 2021-02-07)
- From where did you install rustfmt?: I guess rustup, but system is running stable for years now... i.e., I am not sure
- How do you run rustfmt: IDE (vscode with rust-analyzer) calls rustfmt directly, cargo fmt was executed for test
- my rustfmt.toml:
```
edition = "2018" 
enum_discrim_align_threshold = 30
format_macro_matchers = true 
imports_indent = "Visual"
license_template_path = ".license.template"
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
struct_field_align_threshold = 30
trailing_comma = "Never"
unstable_features = true
where_single_line = true
max_width = 200
```

**Comment by calebcartwright** [comment]
Thanks for the report!

Minimal repro config seems to just be setting `struct_field_align_threshold`. This appears to be fixed in source on the master branch so quite possibly just a bug fix that needs to be backported and released

**Comment by ytmimi** [comment]
@calebcartwright since you recently merged a fix for this can we update the label to `backport:complete`?

**Comment by calebcartwright** [comment]
Sure can!
