### ISSUE TITLE
Can rustfmt be installed by cargo as a dev dependency?

### ISSUE THREAD

**Issue by dclong** [rust-lang/rustfmt#4813]
:clipboard: **Description**

Is this possible?

**Comment by dclong** [comment]
Sorry about the confusion in the question. I was asking whether users can add rustfmt into the Cargo.toml manifest file as a dev dependency to install it.

**Comment by calebcartwright** [comment]
No worries, thanks for the clarification. The answer is no, and there's two aspects to that answer.

The first one is that Cargo doesn't support installing bins via the toml manifest file, at least that's still the case AFAIK. So you can't use Cargo.toml for installing executable dev tools like one might with npm/package.json or pip/requirements.txt, and instead folks would need to run `cargo install foo`.

The second part is that the primary distribution channel for official tools is via rustup (`rustup component add rustfmt`). This has the added benefits of not needing to compile the tools and have an appropriate toolchain on your system. We also don't really distribute rustfmt through crates.io anymore either, though the crate and older versions are of course still out there.

You could consider using a [rust-toolchain file](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) if you want to specify some dev-related components like rustfmt or clippy in a version controlled file.

```toml
[toolchain]
channel = "stable"
components = ["rustfmt"]
```
Hope that helps, going to go ahead and close this
