### ISSUE TITLE
Soon-to-be-stabilized extended_key_value_attributes is not supported

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rustfmt#4834]
Formatting fails when presented with code that utilizes the soon-to-be-stable extended_key_value_attributes feature (https://github.com/rust-lang/rust/pull/83366):

```
error: unexpected token: `include_str`
 --> src/lib.rs:5:10
  |
5 | #![doc = include_str!("../README.md")]
  |          ^^^^^^^^^^^
```

Version: rustfmt 1.4.25-nightly

**Comment by jyn514** [comment]
That's a super old version, the latest is 1.4.38.

**Comment by nagisa** [comment]
Ah, hm. I've installs from 1.49 and nightly in my path at the same time. I'll just trust that it works in latest then.
