### ISSUE TITLE
Help: Rustfmt exit with error 'Operation not permitted'

### ISSUE THREAD

**Issue by Fancyflame** [rust-lang/rustfmt#4837]
When I executed `rustfmt main.rs` rustfmt printed `Operation not permitted` but I am root user with full permissions. It's seems most likely because of my environment which is Ubuntu 20.04 installed in Termux on Android platform. But cargo and rustc are working normally.

**Platform**: Ubuntu 20.04 (on Android)
**Toolchain**: stable-aarch64-unknown-linux-gnu
**Version**: rustfmt 1.4.36-stable (7de6968 2021-02-07) (Updated with rustc together whose version is 1.52.0)

Here is a part of the output of executing `strace -o rustfmt.log rustfmt main.rs`
![Screenshot_20210513_192544_com termux](https://user-images.githubusercontent.com/31250625/118120105-f0b13d80-b421-11eb-94f6-a21b893e2470.jpg)

And below is where the error occurred, at line 433:
`statx(AT_FDCWD, "/root/web-include/src/.rustfmt.toml", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7fe917b1d0) = -1 EPERM (Operation not permitted)`

**Can anybody tell me what's the exact cause of the error? Thanks!!**

**Comment by calebcartwright** [comment]
Thanks for the question.

When running rustfmt against a set of `*.rs` files, rustfmt unsurprisingly needs to be able to read those files, and if running rustfmt with the emit mode that writes back to the files (the default) then rustfmt needs write access as well. In cases where a user has defined a rustfmt configuration file, rustfmt needs read access to that file too.

It seems like you've defined such a configuration file but have some permission issues on your local system. I'd advise reviewing those, and potentially deleting and recreating the file if you're unable to resolve. We don't really have the bandwidth to help folks with their file system permissions, however, so I am going to go ahead and close this.

**Comment by Fancyflame** [comment]
@calebcartwright I'm sorry but I indeed didn't have defined `.rustfmt.toml`, afterwards I created `.rustfmt.toml` but it still didn't work. I don't know what is the exact cause, `rustc` , `cargo` and my own applications built in Rust worked well, only `rustfmt` ran into problems.

**Comment by kkocdko** [comment]
I also found this error, on `Fedora 34 -Termux - Android 10 - Kernel 4.9`. I debug the rustfmt and found an interesting thing:

When I use `fs::metadata` on an invaild path, rust returns wrong `PermissionDenied` instead of `NotFound`. This only happen on Termux and everything is normal on my PC's Fedora 34.

I also `straced` it (my own minimum test program) and got this: <https://paste.ubuntu.com/p/BkVFFpxjXv/>

Test code:

```rust
fn main() {
    std::fs::metadata("noexist_file.txt").unwrap();
}
```

But if I replace `fs::metadata` with `fs::read`, everything well, It returns the `NotFound` correctly.

Is this a bug with Termux or Rust std?

**Comment by kkocdko** [comment]
Error happens here:

https://github.com/rust-lang/rustfmt/blob/778f03530f8fba92ae0d87644b8cef71d351a859/src/config/mod.rs#L360-L366
