### ISSUE TITLE
Build rustfmt for `wasm32-unknown-unknown`

### ISSUE THREAD

**Issue by thomaseizinger** [rust-lang/rustfmt#4845]
[Recently](https://github.com/rust-lang/rustfmt/commit/61ee1089f0286e86efc268e970df62a7bbe6636f), rustfmt changed from depending on `rustc-ap-*` crates to depend on the `rustc-dev` component instead. I assume this makes rustfmt development a lot easier because you no longer need to sync crate versions with the nightly compiler you are using.

Unfortunately though, `rustc-dev` is not available for wasm: https://rust-lang.github.io/rustup-components-history/wasm32-unknown-unknown.html
I've never heard of `rustc-dev` before but the rustup documentation states that it is the entire compiler as a library: https://rust-lang.github.io/rustup/concepts/components.html

I am not sure where to ask for this but is there any chance rustc-dev will be available for the `wasm32-unknown-unknown` target so that rustfmt can be compiled to wasm again?

**Comment by calebcartwright** [comment]
> I am not sure where to ask for this but is there any chance rustc-dev will be available for the wasm32-unknown-unknown target 

I'm not sure if that's feasible/what it would take to make that happen. In general questions about those components should be directed to https://github.com/rust-lang/rust, though perhaps someone from @rust-lang/infra could answer or move this issue to the r-l/rust repo for you

> I assume this makes rustfmt development a lot easier because you no longer need to sync crate versions with the nightly compiler you are using.

The change is not about the development of rustfmt. It's about the strategy relative to the auto publish crates/the goal to remove our dogfooding of those crates within the shipped tools, as well as ensuring a better end user experience for the entire community of rustfmt users as we'd discussed over in #4343.

Sorry to hear this change caused some challenges for you all, but seems like a good opportunity to reconsider some of those alternative options for consuming/utilizing rustfmt.

**Comment by thomaseizinger** [comment]
Opened a follow-up issue here: https://github.com/rust-lang/rust/issues/86122
