### ISSUE TITLE
Group use statments

### ISSUE THREAD

**Issue by burdges** [rust-lang/rustfmt#4860]
A larger project should group their use statements semantically with blank lines between groups, so std/core first, crates.io second, crates in same repo third, and imports from the same crate last, and alphabetical within groups. 
```
use core::{..};
#[cfg(alloc)]
use alloc::{..}

use arrayref::ArrayRef;
use rand::thread_rng;

use sister_crate::foo;

use my_sub::bar;
use super::baz;
```

**Comment by calebcartwright** [comment]
Closing as a duplicate because there is already an existing `group_imports` configuration option, and the associated limitations/feature requests are discussed in several open issues (e.g. #4693, #4709)
