### ISSUE TITLE
Provide distinct names for different lints

### ISSUE THREAD

**Issue by missingdays** [rust-lang/rustfmt#4898]
I'm working on supporting rustfmt in TeamCity CI to report the results of the inspections in the build.
Currently, rustfmt output looks like this
```
Diff in /.../clippy2.rs at line 14:
     println!("{}", res);
 
     // https://rust-lang.github.io/rust-clippy/master/index.html#approx_constant
-  let x = 3.14;
+    let x = 3.14;
```
There is no description of the error, only lines that should be changed.
I'd like rustfmt to also report some description, for example in my case it could be "Indentation is wrong", in the other case "New line should be added to the end of the file". It would help us to show proper inspection description on our side.

**Comment by calebcartwright** [comment]
Thank you for reaching, but I'm going to close this.

rustfmt is a formatting tool, not a linting tool, and as such there are no "lints". rustfmt uses the parsed AST to emit a version of the code that is aligned to the [Rust Style Guide](https://github.com/rust-dev-tools/fmt-rfcs) that's independent from, and unconcerned with, the formatting of the original file. The diff view referenced in the description is a before/after comparison of the original file contents to what rustfmt would write to the file, there is no token-by-token processing against a set of "lints".

There are no code formatting tools I'm aware of that provide the type of formatting rationalization requested, and I'd assume the reasons are largely the same as they are for rustfmt. One major one is that there can be a multitude of reasons why the original formatting/style would be modified, from both local and non-local sources.

rustfmt provides various emitters for conveying whether it would modify the current files, and if so in what way. However, we're not going to have rustfmt emitters attempt to explain _why_.
