### ISSUE TITLE
Format a single file (ignore other modules)

### ISSUE THREAD

**Issue by orhun** [rust-lang/rustfmt#4900]
It might be an odd use case but is there an option for formatting a single file? I sometimes need it but unfortunately couldn't find that option. It basically needs to ignore other external module definitions and try to format a single `.rs` file.

**Comment by r00ster91** [comment]
`rustfmt src/x.rs` to format a single file seems to work just fine. Does that solve it for you?

**Comment by orhun** [comment]
> `rustfmt src/x.rs` to format a single file seems to work just fine. Does that solve it for you?

Not really. For example,

```rs
// contents of mod.rs

pub mod x;

fn format_this() -> String { String::from("this function will be formatted") }
```

```rs
// contents of x.rs

fn do_not_format_this() -> String { String::from("this function will be formatted as well") }
```

running `rustfmt mod.rs` will format `x.rs` as well. I only want `mod.rs` to be formatted.

**Comment by calebcartwright** [comment]
@orhun - use `--skip-children`, e.g. `rustfmt mod.rs --skip-children`

rustfmt is currently recursive by default, and needs `--skip-children` to be passed when you don't want to format any of the out-of-line mods imported by the provided input files. I'd like to invert this one day to make rustfmt non-recursive by default and require a `--recursive` flag when the recursive behavior is desired. `cargo fmt` just invokes `rustfmt` with a set of args so there'd be no impact/change to folks running `cargo fmt`, but based on what we've seen it seems that often times when users are running `rustfmt` directly they really just want to format the file/set of files they've specified.

Final note, `rustfmt`, just like `rustc`, is not Cargo-aware, so when running rustfmt directly you may need to specify other flags (e.g. `--edition 2018`) if you don't have a rustfmt.toml config file

**Comment by alshdavid** [comment]
> [@orhun](https://github.com/orhun) - use `--skip-children`, e.g. `rustfmt mod.rs --skip-children`

Hi, sorry for reviving an old thread. What happened to the `--skip-children` argument?

**Comment by alshdavid** [comment]
I've created a wrapper around `rustfmt` and `cargo fmt` that allows formatting a single file and also use nightly formatting features without nightly Rust.

[https://github.com/alshdavid/cargo-xfmt](https://github.com/alshdavid/cargo-xfmt)

```bash
cargo install cargo-xfmt

# format all files
cargo xfmt

# format one or many files
cargo xfmt --file ./src/main.rs --file ./src/foo.rs

# Or from stdin
cat ./src/main.rs | cargo xfmt > ./src/main_formatted.rs
```

And in vscode

```json
{
  "rust-analyzer.rustfmt.overrideCommand": [
    "cargo", "xfmt",
  ]
}
```
