### ISSUE TITLE
Lines are deleted only if they have whitespace

### ISSUE THREAD

**Issue by skondrashov** [rust-lang/rustfmt#4907]
This feels very inconsistent and I keep having to correct the formatter if I accidentally save while there's whitespace on a line I don't want to be deleted, that wouldn't otherwise be deleted. For example: 
```rust
struct A {}

#[derive(Debug)]
struct B {}
```

Line 2, the blank line, is deleted if the blank line has some spaces on it, but not otherwise. It doesn't seem like it should ever matter what trailing whitespace is on a line, the remove trailing whitespace step should happen before mostly anything else.

**Comment by calebcartwright** [comment]
Could you please provide a complete, reproducible example to more thoroughly convey your scenario and the behavior you are seeing?

**Comment by skondrashov** [comment]
@calebcartwright Edited to add an example. I'm experiencing this in vscode, so maybe it's unrelated to rustfmt, but pretty much any example works, putting a blank space on a line causes it to get deleted.

**Comment by skondrashov** [comment]
It must be unrelated, it doesn't happen if I just use rustfmt in the CLI but I definitely don't understand what's going on now... sorry for the false report!

**Comment by calebcartwright** [comment]
I can't reproduce this locally nor in the sandbox - https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=47b53ce95b4733308dcc2d997665eb6c

Are you sure you don't have VS Code settings or extensions which are modifying your files? You should try running rustfmt directly (e.g. `cargo fmt` or `rustfmt your_file.rs`) and try using your terminal or a simpler editor to ensure spaces

**Comment by calebcartwright** [comment]
> It must be unrelated, it doesn't happen if I just use rustfmt in the CLI but I definitely don't understand what's going on now... sorry for the false report!

Oops looks like our messages crossed on the wire :smile: No worries, thanks for reaching out anyway. Going to close this accordingly
