### ISSUE TITLE
cfg macro indentation off

### ISSUE THREAD

**Issue by pickfire** [rust-lang/rustfmt#4913]
https://github.com/helix-editor/helix/pull/464/files#diff-d9796de334de9f547d45fd8b7476be53c771200ab48f28266e5f62e3493b5df9R171
```rust
            #[cfg(not(windows))]
            tokio::select! {
                biased;

                event = reader.next() => {
                    self.handle_terminal_events(event)
                }
                Some(signal) = self.signals.next() => {
                    use helix_view::graphics::Rect;
                    match signal {
                        signal::SIGTSTP => {
                            self.restore_term().unwrap();
                            low_level::emulate_default_handler(signal::SIGTSTP).unwrap();
                        }                        signal::SIGCONT => {
```
Noticed the last line. It seemed to happen for quite a few `}`.

Playground link for a similar example. https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ff949fb617c3b00730fe0c2f06f4bcaa

**Comment by calebcartwright** [comment]
Thanks for sharing, but rustfmt has never supported formatting inside macro calls that use brace delimiters. On calls with paren and bracket delimiters rustfmt can only format if the params are valid rust code. Formatting support for the arbitrary/not-valid-Rust-code content (much more common with brace delim usage, hence the no formatting) is a non-trivial problem that's yet to be resolved, and that large bucket of work is being tracked under #8

Closing this accordingly
