### ISSUE TITLE
Add support for moving module imports into the same `use` statement as their children (with `self`)

### ISSUE THREAD

**Issue by zedseven** [rust-lang/rustfmt#4915]
When importing things, my IDE isn't very smart about how it adds new `use` statements. Thankfully *rustfmt* mostly cleans it up, but one thing it doesn't seem to do is move module imports into the same block as their children if some of their components are also imported.

A common case for me is when manually implementing `Debug` on something - I often end up with the following after *rustfmt* cleans up (with `imports_granularity = "Crate"`):
```rust
use std::{
	fmt,
	fmt::{Debug, Formatter},
};

...

impl Debug for MyStruct {
	fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
		f.debug_struct("MyStruct")
			...
			.finish()
	}
}
```

It would be nice to have an option (or default behaviour, I'm not sure) to have *rustfmt* format the imports as:
```rust
use std::fmt::{self, Debug, Formatter};

...
```

It saves space, looks cleaner, and in a big import tree, makes it easier to read imo.

**Comment by calebcartwright** [comment]
Thanks for reaching out, but I suspect this would run into the same non-semantics preserving behavior as described in https://github.com/rust-lang/rust/issues/60941 and is not something rustfmt would be able to do.

If you're confident that can be guaranteed to always preserve semantics then please let us know and we'll reconsider!

**Comment by zedseven** [comment]
Ah, I wasn't aware of that subtlety. You're right, it doesn't look possible for the moment.
Thanks for your reply!
