### ISSUE TITLE
Match branch with comma and comment not formatted

### ISSUE THREAD

**Issue by aDotInTheVoid** [rust-lang/rustfmt#4917]
```rust
fn execute_instruction(instruction: Instruction) {
    match instruction {
                 RotateAccRight => {}
,
            // RLA
            RotateAccLeftThroughCarry => {}
    }
}
```

Rustfmt doesnt format this: [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=92083d99a8f57871386cfea22eae95e7)

Interestinly: if you remove the `,` or `// RLA`, it does format the code

**Comment by gardrek** [comment]
To add to this, it seems it's not just the single branch, but the whole match statement that doesn't get formatted.

**Comment by calebcartwright** [comment]
Believe this is likely a dupe of #4119 but will leave open for now
