### ISSUE TITLE
Invalid value for `--edition`

### ISSUE THREAD

**Issue by Luro02** [rust-lang/rustfmt#4922]
I recently upgraded my project to rust 2021 edition, but rustfmt is no longer working (both on computer and ci with the latest nightly).

To reproduce:
```
> git clone https://github.com/Luro02/array-map
> cd array-map
> cargo fmt --all -- --check
Invalid value for `--edition`
```

This issue is not only limited to this project, one can also reproduce it by running `cargo new help` and changing the `Cargo.toml` to:
```diff
+ cargo-features = ["edition2021"]
+
[package]
name = "help"
version = "0.1.0"
+ edition = "2021"
- edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
```

This may be related to #4916

**Comment by Luro02** [comment]
Even simpler reproduction:

```
> rustfmt --edition 2021
Invalid value for `--edition`
```

**Comment by calebcartwright** [comment]
Thanks for reaching out but closing as a duplicate of an issue already covered by #4847.

It's been fixed in source but not yet released. Will be available in the following nightly after https://github.com/rust-lang/rust/pull/87468 lands
