### ISSUE TITLE
Use `brace_style` for struct instantiation

### ISSUE THREAD

**Issue by Iron-E** [rust-lang/rustfmt#4938]
New `struct` instances don't adhere to `brace_style`. For example, when `brace_style = "AlwaysNextLine"`, a new struct instance will look like this:

```rust
let value = MyStruct {
    something: 1
}
```

When it should look like this:

```rust
let value = MyStruct
{
    something: 1
}
```

___

Originally posted by @Sibz in https://github.com/rust-lang/rustfmt/issues/3376#issuecomment-70128656

**Comment by Iron-E** [comment]
This also applies when using macro variables:

```rust
$foo {
   bar: 1
}
```

**Comment by calebcartwright** [comment]
Thanks for opening all these, but I'm going to close all of them, at least for the time being, pending conclusion of the strategy discussion in #3376

**Comment by Iron-E** [comment]
Alright. Perhaps given the introduction of a new option fitting this scope they can be reopened 🤛🏻👍
