### ISSUE TITLE
Use `brace_style` for closures with blocks

### ISSUE THREAD

**Issue by Iron-E** [rust-lang/rustfmt#4939]
Closures with blocks don't adhere to `brace_style`. For example, when `brace_style = "AlwaysNextLine"`, a closure with a block will look like this:

```rust
foo.ok_or_else(|| {
  // closure
})
```

It should be:

```rust
foo.ok_or_else(|| 
{
  // closure
})
```

___

Originally posted by me in https://github.com/rust-lang/rustfmt/issues/3376#issuecomment-892952459

**Comment by calebcartwright** [comment]
Closing as per https://github.com/rust-lang/rustfmt/issues/4938#issuecomment-913862620
