### ISSUE TITLE
Use `brace_style` for `macro_rules!`

### ISSUE THREAD

**Issue by Iron-E** [rust-lang/rustfmt#4940]
Sorry for opening so many issues at once here!

New macros don't adhere to `brace_style`. For example, when `brace_style = "AlwaysNextLine"`, a `macro_rules!` will look like this:

```rust
macro_rules! filter_map_view {
  ($query:ident, $val:ident) => {
```

It should look like this:

```rust
macro_rules! filter_map_view
{
  ($query:ident, $val:ident) =>
  {
```

**Comment by calebcartwright** [comment]
Closing as per https://github.com/rust-lang/rustfmt/issues/4938#issuecomment-913862620
