### ISSUE TITLE
Use `brace_style` for `async` blocks

### ISSUE THREAD

**Issue by Iron-E** [rust-lang/rustfmt#4942]
I again apologize for how many issues I have opened at once. I just started using `rustfmt` on my project and have noticed a lot of things about `brace_style`, as an avid "AlwaysNextLine"-er.

`async` blocks don't adhere to `brace_style`. For example, the code snippet below is shown when running `rustfmt`:

```rust
async {
  // stuff
}
```

It should look like this:

```rust
async
{
  // stuff
}
```

**Comment by calebcartwright** [comment]
Closing as per https://github.com/rust-lang/rustfmt/issues/4938#issuecomment-913862620
