### ISSUE TITLE
Required lifetime bounds for GATs in where clauses get removed 

### ISSUE THREAD

**Issue by jam1garner** [rust-lang/rustfmt#4954]
Minimal reproduction ([playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=d730bd005a0cbdd34ac6a6c9748c62a8), hit 'format' then try building to see it in action):

**Before**
```rust
trait Foo {
    type Arg<'a>;
}

struct Bar<T>(T) where for<'a> T: Foo<Arg<'a> = ()>;
```

**After**
```rust
trait Foo {
    type Arg<'a>;
}

struct Bar<T>(T)
where
    for<'a> T: Foo<Arg = ()>;
//                             ^^^ note the lack of <'a> bound, which is needed
```

This will result in the following compiler error:

```
error[E0107]: missing generics for associated type `Foo::Arg`
 --> src/main.rs:9:20
  |
9 |     for<'a> T: Foo<Arg = ()>;
  |                    ^^^ expected 1 lifetime argument
  |
note: associated type defined here, with 1 lifetime parameter: `'a`
 --> src/main.rs:4:10
  |
4 |     type Arg<'a>;
  |          ^^^ --
help: add missing lifetime argument
  |
9 |     for<'a> T: Foo<Arg<'a> = ()>;
  |                    ~~~~~~~
```

**Comment by raftario** [comment]
Also running into this, will try and look into fixing it and open a PR if I can figure it out

**Comment by calebcartwright** [comment]
Thanks @raftario but this has already been fixed in source, just hasn't been released yet.

**Comment by calebcartwright** [comment]
we would benefit from getting more test cases added for the various issues that have been reported, can ping you if you're interested in working on that

**Comment by raftario** [comment]
Oh that's great to hear, thanks for letting me know. Wouldn't mind getting a couple of tests in if that can be of any help

**Comment by calebcartwright** [comment]
Closing as the issue was already resolved in source and test case has been added. No ETA yet on exactly when the fix will hit nightly, but it will be in the next release regardless

**Comment by chrisbouchard** [comment]
Any word when this fix will be available in nightly in light of the push for GAT stabilization?

**Comment by calebcartwright** [comment]
> Any word when this fix will be available in nightly in light of the push for GAT stabilization?

This has already been on nightly for quite some time

**Comment by chrisbouchard** [comment]
@calebcartwright Yep, you're right. My editor wasn't using nightly. Sorry for the noise!

**Comment by calebcartwright** [comment]
> @calebcartwright Yep, you're right. My editor wasn't using nightly rustfmt. Sorry for the noise!

No worries. FWIW I believe it'll land on stable with the 1.58 release too
