### ISSUE TITLE
if-let guard formatting

### ISSUE THREAD

**Issue by LeSeulArtichaut** [rust-lang/rustfmt#4955]
`if let` guard formatting seems to be unsupported in rustfmt:

```rust
// This isn't rewritten
fn main() {
    match foo {
        aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa if let Some(bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb) = ccccccccccccccccccccccccccccccccccccccccccccccccc => {}
    }
}
```

cc rust-lang/rfcs#2294 rust-lang/rust#51114

**Comment by calebcartwright** [comment]
Thanks for the report.

For anyone that takes a pass at working on this, please note that the length isn't an issue; the root issue i's a complete lack of handling the construct in the AST nodes.

**Comment by Nadrieril** [comment]
I understand that this issue is blocked on deciding how these should be formatted. However, the main problem for me rn is that when I use an if-let guard, the whole body of the arm stays unformatted. Whaveter the final style decision the body will get formatted the same way so this shouldn't be blocked on anything. Is this doable?

**Comment by ytmimi** [comment]
Closing as support for this was added in https://github.com/rust-lang/rustfmt/pull/5910

On the latest rustfmt master we now format the input:

**input**:

```rust
fn main() {
    match foo {
        aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa if let Some(bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb) = ccccccccccccccccccccccccccccccccccccccccccccccccc => {}
    }
}
```

**output**:

```rust
fn main() {
    match foo {
        aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
            if let Some(bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb) =
                ccccccccccccccccccccccccccccccccccccccccccccccccc => {}
    }
}
```
