### ISSUE TITLE
rustfmt should remove `format!("hello",);`'s comma

### ISSUE THREAD

**Issue by r00ster91** [rust-lang/rustfmt#4956]
```rs
fn main() {
    format!("hello",);
}
```
If I format this, I expect to get this:
```rs
fn main() {
    format!("hello");
}
```
But instead, nothing happens. It doesn't only apply to `format!`. For normal functions it works but for macros it doesn't because the comma could potentially be important input for the macro and rustfmt doesn't know that in this case the comma doesn't have a meaning.
I think we should do something about that.

1. Maybe rustfmt can be made smarter to know that the comma is useless there?
2. Maybe the definition can be changed to make it more specific and allow rustfmt to infer that trailing commas are unnecessary? https://doc.rust-lang.org/src/alloc/macros.rs.html#112
3. Maybe only standard library macros can be put in a special "list" that rustfmt considers and then it removes trailing commas and other unnecessary stuff only from those macros. It might be unfair for macro authors that make macros outside the `std`.
4. Some kind of attribute could be added that can be applied to macros to say that this macro's parameters are to be handled similarly like a normal function? `#[treat_parameters_as_function_parameters]` or something like that.
5. Macros 2.0 are coming. Can they do something about this? Maybe we should make sure that with 2.0 macros it becomes easier to define macros where rustfmt can infer that trailing commas can be removed?

**Comment by calebcartwright** [comment]
Thanks for reaching out, but going to close this as a duplicate as it's been discussed in various other issues where I'd want to keep the discussion (refs #3277, #3065, #8)
