### ISSUE TITLE
`group_imports` option to remove grouping

### ISSUE THREAD

**Issue by Heliozoa** [rust-lang/rustfmt#4962]
Hi,
thanks a lot for your work on rustfmt. I would like to have an option to always put all imports into a single group. I tried looking for an existing issue but I might have missed one 
```rust
use self::some_mod::SomeStruct;

use crate::my_module;

use diesel::prelude::*;

use rocket::serde::json::Json;

use std::env;

use uuid::Uuid;
```
would format to
```rust
use self::some_mod::SomeStruct;
use crate::my_module;
use diesel::prelude::*;
use rocket::serde::json::Json;
use std::env;
use uuid::Uuid;
```
The rationale is that I like the idea of rustfmt enforcing the grouping, but find it nicer to have them all together, ordered inside the group the way rustfmt currently does it.

If this is something that could be added to rustfmt, I could take a look at making a PR. At a glance it looks like I could just follow the implementation of the StdExternalCrate option and it wouldn't be too difficult.

As for the name, maybe something like "Together"?
```toml
group_imports = "Together"
```

**Comment by calebcartwright** [comment]
> I was going to close the issue since the PR was merged but I noticed the 2x port pending tag. What would be involved in implementing that? Does it just refer to compatibility with `version = Two`?

Thanks for the question. The port labels are primarily for the rustfmt team to help us deal with some branch-related management activities. I'm going to go ahead and close this given that your PR has been merged, thanks again!
