### ISSUE TITLE
Add any relevant test cases for reported GAT issues

### ISSUE THREAD

**Issue by calebcartwright** [rust-lang/rustfmt#4969]
We've had a few, and occasionally duplicative, reports of GAT related issues. To the best of my knowledge all the ones we're currently aware of have been resolved but I can't recall if we've added test cases for everything that's been reported. More generally, we could probably use some _more_ tests beyond what's been reported anyway.

For anyone interested in working on this, the tasks will largely consist of:

* reviewing the various GAT-related reports and checking the current tests (advise looking under `tests/target` as not all test inputs have a pair file under `tests/source`). If we're missing cases for any issues and/or if the tests need to be augmented then add/update the test files as needed
* consider whether there's any additional, untested use cases that should be added. Don't feel obligated to come up with something, but would be good take a look because if there's any remaining gaps/bugs it'd be better to catch them proactively vs. waiting for users to run into them. Remember that context matters when formatting, so e.g. it's possible for rustfmt to handle something correctly in a trait context but have a bug in an impl context.

See https://github.com/rust-lang/rustfmt/blob/master/Contributing.md#create-test-cases for more info on adding test cases

**Comment by calebcartwright** [comment]
@raftario - tagging you since in another thread you'd expressed interest in potentially working on this. if that's still the case you can use rustbot to claim the issue to indicate to folks that you're working on it (e.g. `@rustbot claim`)

**Comment by cowboy-bebug** [comment]
@calebcartwright @raftario I didn't see the comment above! Apologies 🙏
