### ISSUE TITLE
The formatter prefers long one-line composition executions. (conflict with the book)

### ISSUE THREAD

**Issue by yygrechka** [rust-lang/rustfmt#4975]
I'm going through "The Rust Programming Language" book. I'm on Chapter 12.2 and I wrote the following code:
```
use std::env;
use std::fs;

fn main() {
    // --snip--
    println!("In file {}", filename);

    let contents = fs::read_to_string(filename)
        .expect("Something went wrong reading the file");

    println!("With text:\n{}", contents);
}
```
However, after this was formatted with ```cargo fmt```, it looks like this:

```
use std::env;    
use std::fs;    
    
fn main() {    
    let args: Vec<String> = env::args().collect();    
    
    let query = &args[1];    
    let filename = &args[2];    
    
    println!("Searching for {}", query);    
    println!("In file {}", filename);    
    
    let contents = fs::read_to_string(filename).expect("Something went wrong reading the file");    
    
    println!("Width text:\n{}", contents);    
}  
```

I'm not sure if this is something configurable, but it seems to me that rustfmt should at least agree with the rust book.
cargo 1.54.0 (5ae8d74b3 2021-06-22)
rustup 1.24.3 (ce5817a94 2021-05-31)

**Comment by calebcartwright** [comment]
Thanks for reaching out, but I'm going to close this.

> but it seems to me that rustfmt should at least agree with the rust book.

I understand the initial reaction when first going through the book, but it's an incorrect assumption.

The Book does not define the style guide. The formatting specification is codified in the [Rust Style Guide](https://github.com/rust-dev-tools/fmt-rfcs), and that is what dictates the default formatting that rustfmt must emit.

It's not uncommon to find snippets in the Book and/or in other documentation or forums which haven't actually been formatted by rustfmt and are formatted however the author decided to manually style the snippet. All that means is that those cases haven't actually been put through the formatter, not that the formatter needs to change its spec to meet manual style.

> I'm not sure if this is something configurable

You can use the `chain_width` configuration option to control the upper width limit for a chain, beyond which rustfmt will always wrap the chain to ensure it stays below the limit (note that there are other scenarios as dictated by the style guide that can require wrapping too)

https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#chain_width

**Comment by yygrechka** [comment]
@calebcartwright 
Thank you for the reply, I am confused a bit confused about this chain_width parameter.

The line after formatting is 92 characters long. The chain_width default value is 60, the max_width looks like it is 100. Does that not mean that this chain is too long?

**Comment by calebcartwright** [comment]
`chain_width` and the other small heuristic related config options are specific to the respective construct, i.e. the chain itself and not things that precede or succeed it on the same line.

`max_width` is the absolute width/rightmost boundary and does take measure against the full length of each line.
