### ISSUE TITLE
Default value for const parameter is removed when using const_generics_defaults.

### ISSUE THREAD

**Issue by meowjesty** [rust-lang/rustfmt#4995]
[const_generics_defaults](https://github.com/rust-lang/rust/issues/44580) feature allows defining a default value for a const generic parameter, but this value is removed when running rustfmt.

Tested this on rustfmt version `1.4.37-nightly (2021-09-16 e4828d5)` (playground version), and on `1.4.37-nightly (b69fe572 2021-09-10)`.

[Playground example](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=60f8f3a3e6164f2c8ac98ad27fb663db)

**Comment by calebcartwright** [comment]
Thank you for sharing, but this has already been fixed in source and is simply pending release.
