### ISSUE TITLE
Formatting empty `where` clause with `trailing_comma = "Never"` leaves trailing whitespace, causing an error.

### ISSUE THREAD

**Issue by Esper89** [rust-lang/rustfmt#5012]
Formatting the following code with `trailing_comma = "Never"` will leave trailing whitespace:
```rs
pub struct Matrix<T, const R: usize, const C: usize>
where
    [T; R * C]: 
{
    contents: [T; R * C]
}
```
```rs
    [T; R * C]: 
               ^ right here
```
Without `trailing_comma = "Never"`, the line is formatted like this:
```rs
    [T; R * C]: ,
```
The trailing whitespace causes `rustfmt has failed to format`, resulting in the whole file not being formatted.

A workaround is to leave a comment at the end of the line like this:
```rs
    [T; R * C]:  //
```

**Comment by calebcartwright** [comment]
Thanks for the report!
