### ISSUE TITLE
Issue using `rustfmt_nightly` API with `nightly` toolchain

### ISSUE THREAD

**Issue by gabhijit** [rust-lang/rustfmt#5013]
I am trying to use `rustfmt_nightly` API, more specifically, `rustfmt_nightly::{config::Config, format_input, Input}` from inside my code to generate and format the generated code. 

While building the code with the published crate (version `v1.4.21`) I am getting the following error. 

```
error[E0557]: feature has been removed
 --> /home/gabhijit/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_index-677.0.0/src/lib.rs:3:12
  |
3 | #![feature(const_fn)]
  |            ^^^^^^^^ feature has been removed
  |
  = note: split into finer-grained feature gates

error[E0557]: feature has been removed
  --> /home/gabhijit/.cargo/registry/src/github.com-1ecc6299db9ec823/lock_api-0.3.4/src/lib.rs:91:42
   |
91 | #![cfg_attr(feature = "nightly", feature(const_fn))]
   |                                          ^^^^^^^^ feature has been removed
   |
   = note: split into finer-grained feature gates

error: aborting due to previous error
```

If instead I give a git based dependency (`v1.4.36`), I get the following error - 
```
   Compiling rustc-ap-rustc_index v705.0.0
error[E0557]: feature has been removed
 --> /home/gabhijit/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_index-705.0.0/src/lib.rs:2:12
  |
2 | #![feature(const_fn)]
  |            ^^^^^^^^ feature has been removed
  |
  = note: split into finer-grained feature gates

```

If instead I give a git based dependency (`branch = "master"`), I get the following error - 

```
error[E0463]: can't find crate for `rustc_ast`
  --> /home/gabhijit/.cargo/git/checkouts/rustfmt-c4b65366788d3254/e3203ef/src/lib.rs:16:1
   |
16 | extern crate rustc_ast;
   | ^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error
```

Even getting the same error after updating the nightly toolchain. --- 

```
installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-2021-07-23-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)
1.48.0-x86_64-unknown-linux-gnu

```

If on the other hand if I use `rustfmt` crate (deprecated - version `0.10.0`), I am at-least able to build on stable channel, but I would like to build on the `nightly` channel as well.

**Comment by calebcartwright** [comment]
Going to close. We haven't been publishing to crates.io for a long time, and the `rustfmt-nightly` crate on crates.io is going to be officially deprecated just like the `rustfmt` crate (refs #4937)

We don't directly support using rustfmt as a lib, and in general I'd advise against it. rustfmt relies on significant chunks of the compiler's internals that don't lend well for direct consumption. You of course always have the option of leveraging cargo's ability to consume dependencies via git references, but remember that you'll be constrained to the nightly versions that are supported. We track _a_ version in the [rust toolchain file](https://github.com/rust-lang/rustfmt/blob/master/rust-toolchain) in the repo root, but we'll update this as and when we need to without notice or warning.
