### ISSUE TITLE
Fails to format if a multiline comment is an a match arm

### ISSUE THREAD

**Issue by sigmaSd** [rust-lang/rustfmt#5021]
meta:
rustc 1.54.0 (a178d0322 2021-07-26)

code:
```rs
fn main() {
    match 1 {
        1 /*this comment make rustfmt unable to format anything*/ => {},
        _ =>          todo!()
    }
}
```

Removing that comment makes rustfmt work again.

**Comment by calebcartwright** [comment]
Thanks for reaching out with the report, but going to close as a duplicate of #4119
