### ISSUE TITLE
Visibility being removed on method impl item with attribute macro

### ISSUE THREAD

**Issue by sinhpham** [rust-lang/rustfmt#5046]
Original code

```
impl Struct {
    #[proc_macro_impl]
    pub fn method(&self) -> Self;
}
```

`rustfmt` removes the `pub` keyword after formatting.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=aac25daf2a228b9dceac7cab99fcab89

**Comment by calebcartwright** [comment]
I gather you're still using rustfmt v1.4.37? The linked snippet on the playground is fine the latest on nightly (1.4.38) and I cannot reproduce it locally either with the latest

**Comment by sinhpham** [comment]
Looks like it has been fixed in the latest nightly. Thank you.
