### ISSUE TITLE
`empty_item_single_line` should apply to trait definitions as well

### ISSUE THREAD

**Issue by nebulaeandstars** [rust-lang/rustfmt#5047]
1.4.37-nightly

Using this rustfmt.toml 

```toml
brace_style = "AlwaysNextLine"
empty_item_single_line = true
```
rustfmt will format the following code like this:

```rust
fn function() {}

struct Struct {}

enum Enum {}

trait Trait
{
}

impl<T> Trait for T {}
```

This is inconsistent, and empty traits end up sticking out like a sore thumb. Intended behaviour is probably this:

```rust
fn function() {}
struct Struct {}
enum Enum {}
trait Trait {}
impl<T> Trait for T {}
```

This is important, as empty traits are often quite useful. For instance, you might want something like this:

```rust
trait Trait: Send + Clone {}
impl<T: Send + Clone> Trait for T {}
```

which will look quite ugly at the moment.

**Comment by calebcartwright** [comment]
Thanks for the report. Seems the handling of `brace_style` when `AlwaysNextLine` isn't accounting for the configured `empty_item_single_line` value (which is `true` by default)

For anyone interested in working on this, suspect you'll probably want to start somewhere around here:

https://github.com/rust-lang/rustfmt/blob/bc46af97423cef7484a806e8282c545d7607889e/src/items.rs#L1125-L1172

The `format_impl` function in that same file may serve as a useful reference for how to account for those. When adding tests, please be sure to include a combination of cases that include where `empty_item_single_line` is true with `brace_style = AlwaysNextLine` as well as one where `empty_item_single_line` is false

**Comment by mujpao** [comment]
Hi. Can I try this one?

**Comment by calebcartwright** [comment]
> Hi. Can I try this one?

Absolutely!
