### ISSUE TITLE
`unnecessary_parens` false positive when calling function from match

### ISSUE THREAD

**Issue by SirJosh3917** [rust-lang/rustfmt#5057]
# Rust Information

`rustc --version`: `rustc 1.55.0-nightly (gentoo)`
`rustfmt --version`: `rustfmt 1.4.37-nightly ( )`
`cargo --version`: `cargo 1.55.0-nightly`
rust-analyzer version: `v0.3.794 preview` (nightly mode is enabled)

# Repro

```rs
pub enum Repro {
    A(i64),
    B(i64),
}

fn make(a: bool, data: i64) -> Repro {
    (match a {
        true => Repro::A,
        false => Repro::B,
    }(data))
}
```

# Issue

When I write my code as suggested, I get a warning for putting parenthesis around this match statement:

![the warning](https://user-images.githubusercontent.com/9854865/139593098-5cac3c80-ff9f-4e9d-b0f8-4a1366ef2b36.png)

However, upon doing what the warning says, I am then greeted with a compiler error (the error persists if I put the parenthesis next to the closing brace of the match statement, as expected)

![the compiler error](https://user-images.githubusercontent.com/9854865/139593117-a0fcaa0f-1d9d-4699-a593-34654bad9e75.png)

### Misc

Apologies if this is in the wrong repository. Not sure if it should go to clippy, or to rust as this seems like some sort of parser oversight.

**Comment by karyon** [comment]
Both the warning and the error come from rustc (the rust compiler), so I would suggest you open a bug report there. This repo here is rustfmt, a tool that auto-formats your code :) 

(The error is interesting! I don't really understand what's going on there. If you create a rustc bug report, please link it, I'm curious about the result!)

**Comment by SirJosh3917** [comment]
Ah, my bad for reporting it here &mdash; here's the link to the issue on the rustc repo since you're interested https://github.com/rust-lang/rust/issues/90456

**Comment by karyon** [comment]
no worries, and thanks!
