### ISSUE TITLE
[Feature request] Format strings using the `concat!` macro

### ISSUE THREAD

**Issue by Starwort** [rust-lang/rustfmt#5074]
Given that we already have the following options for string formatting:
```rs
// none at all
let x = "my very long string that goes on for ages";
// wrap with backslashes
let y = "my very long string that \
         goes on for ages";
```
I think it would be nice to have the following third option, for those who dislike the aesthetic of the unbalanced quotes on each line:
```rs
// wrap using concat!
let z = concat!(
    "my very long string that ",
    "goes on for ages",
);
```
Personally, I find the `concat!` style much more appealing, especially coming from C and Python which both have implicit string literal concatenation (`"this is " "one string"`) - it's obviously personal preference, but I feel that this style is much nicer than wrapped-with-backslash.

**Comment by calebcartwright** [comment]
While I understand the line of thinking and potential benefits, this type of conversion is really outside the scope of rustfmt whose core job is style/formatting as opposed to these types of substitutions.

As such I'm going to close, but thanks for reaching out and sharing your idea!
