### ISSUE TITLE
[Feature Request] Enforce std/core when there's an option

### ISSUE THREAD

**Issue by maboesanman** [rust-lang/rustfmt#5076]
for some set of imports like this:

```rust
use core::marker::PhantomData;
use std::collections::HashMap;
use std::pin::Pin;
```

it would be nice to have an fmt option to enforce either the lowest possible import, or always use std.

```rust
use core::marker::PhantomData;
use core::pin::Pin;
use std::collections::HashMap;
```

or

```rust
use std::marker::PhantomData;
use std::collections::HashMap;
use std::pin::Pin;
```

not sure how this would interact with alloc

**Comment by maboesanman** [comment]
this could also apply to qualified names

**Comment by calebcartwright** [comment]
Could you expand on what specifically you are asking for? It's not entirely clear what "lowest possible import" means. It'd also be helpful to explain your ask in relation to relevant existing configuration options, e.g. `reorder_imports`, `group_imports`, etc.

**Comment by maboesanman** [comment]
Lowest as in most specific. Really the setting would be a lint to specify how importing items available in core should be written. Should they be imported from std or core?

**Comment by maboesanman** [comment]
Additionally, this lint would happen before those two lints so sorting works correctly, and grouping is more effective.

**Comment by calebcartwright** [comment]
Gotcha thanks for the clarification. However, I am going to close as that's outside the scope of style/formatting and is too far beyond our core remit for me to be willing to consider incorporating in rustfmt.

Thanks again for the suggestion though!
