### ISSUE TITLE
Website doesn't display options

### ISSUE THREAD

**Issue by mainrs** [rust-lang/rustfmt#5079]
Visiting [the website](https://rust-lang.github.io/rustfmt/) results in a mostly empty webpage for me. I see the search field, the checkbox and the dropdown menu,but nothing else. Below is the console output I get when visiting the website.

```log
marked.min.js:6 Uncaught ReferenceError: exports is not defined
    at marked.min.js:6
vue.js:9049 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
vue.js:9058 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
vue-async-computed@3.8.1:201 Error evaluating async computed property: TypeError: marked.lexer is not a function
    at parseMarkdownAst (https://rust-lang.github.io/rustfmt/:285:34)
    at Vue.outputHtml (https://rust-lang.github.io/rustfmt/:144:25)
(anonymous) @ vue-async-computed@3.8.1:201
vue-async-computed@3.8.1:201 Error evaluating async computed property: TypeError: marked.lexer is not a function
    at parseMarkdownAst (https://rust-lang.github.io/rustfmt/:285:34)
    at Vue.outputHtml (https://rust-lang.github.io/rustfmt/:144:25)
(anonymous) @ vue-async-computed@3.8.1:201
```

Tried it with Firefox 93.0 and Chromium 94.0.4606.81, both without any extensions.

**Comment by calebcartwright** [comment]
I'm not able to reproduce this, despite testing with an array of browsers on both Linux and Windows, which makes me think this is most likely a localized problem.

Can you check the networking and see if your browser failed/declined to fetch the `marked.min.js` bundle?

**Comment by mainrs** [comment]
No clue what just happened. I still had the issue (even after cleaning my cache). I opened the development console, switched over to the network tab and wanted to see if it fetches the JS.

For some reason switching the tab and pressing the `reload` button that is displayed there fixed it....? Anyway, seems like this problem was just temporary.
