### ISSUE TITLE
Added comment line above any comment that starts with `-`

### ISSUE THREAD

**Issue by DevinR528** [rust-lang/rustfmt#5088]
Any place a comment is added like:
```rust
// - 16 because we push in the above seq of instructions
```
`rustfmt` turns it into
```rust
//
// - 16 because we push in the above seq of instructions
```
I'm not sure if it's trying to be smart and add newline before what it thinks is a list item in the markdown or something else?
```
cargo fmt --version
rustfmt 1.4.38-nightly (891ca5f 2021-11-15)
```

**Comment by calebcartwright** [comment]
Could you please provide a short, but reproducible example, and also include any non-default configuration options you are using?

I'm unable to reproduce this using as a standalone comment, so suspect there's config and/or context missing.

**Comment by DevinR528** [comment]
It's `wrap_comments = true` sorry this should have been obviously helpful info.

**Comment by ytmimi** [comment]
I'm able to reproduce this on the latest master ``rustfmt 1.4.38-nightly (eee8f041 2021-11-17)`` with the option ``wrap_comments=true`` using a slightly modified ``mcve``:

```rust
 // - a
```

When I run ``cargo run --bin rustfmt -- --check --config=wrap_comments=true`` I get this diff

```diff
+//
 // - a
```

And I get the following error:

```
error[internal]: left behind trailing whitespace
  |
1 | //
  |   ^
  |
  = note: set `error_on_unformatted = false` to suppress the warning against comments or string literals

warning: rustfmt has failed to format. See previous 1 errors.
```
