### ISSUE TITLE
Planned removal of `report_todo`

### ISSUE THREAD

**Issue by calebcartwright** [rust-lang/rustfmt#5101]
The purpose of this issue is to both communicate our intent to drop the unstable option [`report_todo`](https://rust-lang.github.io/rustfmt/?version=v1.4.38&search=#report_todo), as well as provide a forum for questions to be asked and/or concerns to be raised.

We do not yet have an exact deprecation date planned, but it will most likely occur in early 2022.

While we understand the utility this option provides, we've decided that rustfmt simply is not the right place/tool to provide this capability, and it's not an option that makes sense for us to try to stabilize and maintain/support long term.

If anyone is aware of any other community maintained tools/crates for detecting "TODO" strings in comments please feel free to post here for broader awareness.

**Comment by scott-ainsworth** [comment]
Just for clarity, and because `report_todo` and `report_fixme` are practicality synonymous to many people, is just `report_todo` being depreciated? Tx

**Comment by calebcartwright** [comment]
Thanks for the question, and yes `report_fixme` is being deprecated as well - #5102
