### ISSUE TITLE
Rustfmt edition 2018 is adding a space where where it shouldn't

### ISSUE THREAD

**Issue by oxarbitrage** [rust-lang/rustfmt#5123]
I am not totally sure if this is a bug or if there is any reason for it but i have some rust code as follows:

```
let var = func`().0.0;
```

When i run `rustfmt` it is adding an extra space to that line so it becomes:

```
let var = func`().0 .0;
```

For reference, in this example, `funct` is something as:

```
fn funct() -> (type1, type2)
```

and `type1` is something as:

```
struct type1(u32);
```

**Comment by calebcartwright** [comment]
Thanks for reaching out but to close as a duplicate. The behavior is explained, along with some available options, in the issues linked below.

https://github.com/rust-lang/rustfmt/issues/4355#issuecomment-723764276, #4779

**Comment by oxarbitrage** [comment]
Thanks, sorry i didn't checked the amount of already closed issues for the same problem before opening.
