### ISSUE TITLE
Error running rustfmt: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by pixelprogrammer** [rust-lang/rustfmt#5126]
I had a couple of issues running this command so not sure if they are related. If not, then I can create another issue for the second one.

1) When running `rustfmt src/main.rs -v` I get the following error:
```
Using rustfmt config file path/to/project/rustfmt.toml for /path/to/project/src/main.rs
Formatting /path/to/project/src/file.rs
Segmentation fault (core dumped)
```
2) I got a different error running this command so this is the one that could be a separate issue:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/tools/rustfmt/src/rewrite.rs:67:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

FYI: (1) happens consistently. (2) only happened once.

`rustfmt` fails in VS Code as well (as expected). There is a little different output message in case that is of any help:

```
[Error - 3:31:39 p.m.] Request textDocument/formatting failed.
  Message: rustfmt exited with:
                           Status: signal: 11 (core dumped)
                           stdout: 
                           stderr: 
  Code: -32900 
```

Is there any reason why `rustfmt` command would have a Segmentation fault error? What else can I provide for further debugging purposes?

Additional Information:
```
$ rustup --version
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.57.0 (f1edd0429 2021-11-29)`
------------------------------------
$ rustfmt --version
rustfmt 1.4.37-stable (f1edd04 2021-11-29)
------------------------------------
$ cat /etc/*-release
Fedora release 35 (Thirty Five)
NAME="Fedora Linux"
VERSION="35 (Workstation Edition)"
ID=fedora
VERSION_ID=35
VERSION_CODENAME=""
PLATFORM_ID="platform:f35"
PRETTY_NAME="Fedora Linux 35 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:35"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f35/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=35
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=35
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
Fedora release 35 (Thirty Five)
Fedora release 35 (Thirty Five)
```

This is on a fresh install of Fedora Workstation 35 and fresh install of Rust.

**Comment by calebcartwright** [comment]
> What else can I provide for further debugging purposes?

Could you please provide a minimal, complete and reproducible example? That would include the contents of your rustfmt config file and as minimal possible an input file that can be used to reproduce the issue

**Comment by pixelprogrammer** [comment]
@calebcartwright I am getting this error on all files and all projects that worked fine on my previous system.

Even the `hello world` example from `cargo init` is failing too.

```rust
fn main() {
    println!("Hello, world!");
}
```

**Comment by calebcartwright** [comment]
Did you install rustfmt via rustup?

**Comment by pixelprogrammer** [comment]
I installed rust from the instructions on the main rust install page:

https://www.rust-lang.org/tools/install

So yes.

**Comment by calebcartwright** [comment]
> So yes.

Just wanted to clarify because the act of installing rustup and the core components like the compiler, stdlib, etc. doesn't implicitly include dev tools which are available as optional components/including in broader profiles. We have plenty of folks that will still do things like build from source even though they downloaded rustup.

> @calebcartwright I am getting this error on all files and all projects that worked fine on my previous system.

This sounds much more likely to be an issue with your system, not with rustfmt as if it were the latter I would expect to be able to reproduce and that we've had heard plenty of reports by now.

Not really sure what to tell you, and obviously there's not anything we can do about a machine-specific issue. If I were you I'd probably try some other tools (e.g. `cargo clippy`), making sure you can build/run the app, etc. You could also try grabbing one a binary from one of our [Releases](https://github.com/rust-lang/rustfmt/releases) and see if the behavior is similar (if not I'd suspect a potential issue in your toolchain installation)

**Comment by pixelprogrammer** [comment]
@calebcartwright Ok, so I reinstalled rust by uninstalling and installing again. Same way I did previously. Now `rustfmt` works. Will close this issue now since it appears to be related to a faulty installation unique to my machine.

**Comment by calebcartwright** [comment]
Thanks for following up. You _may_ want to reach out to the rustup folks (either on Discord or in their GitHub repo) to see if there's any known issues, but either way glad it's sorted for you know.
