### ISSUE TITLE
Use a number-smart sorting function for imports

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rustfmt#5130]
Today, rustfmt reorders like this:
```diff
-use crate::num::{NonZeroI8, NonZeroI16, NonZeroI32, NonZeroI64, NonZeroI128, NonZeroIsize};
+use crate::num::{NonZeroI128, NonZeroI16, NonZeroI32, NonZeroI64, NonZeroI8, NonZeroIsize};
```
Playground to repro: <https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=69ff891f23f740c0602c91da88d40b3f>

I consider that ordering materially worse, since it's the biggest one, then three in ascending order, then the smallest one.

Because in type names people are unlikely to zero-pad, I think rustfmt should choose an ordering predicate that can pick up on numbers and sort that part numerically, as opposed to lexicographically-on-the-decimal-representation.

(Maybe do this along with #5075 that's also about the sorting predicate.)

**Comment by calebcartwright** [comment]
Thanks, though going to close as a duplicate in a desire to attempt to consolidate the discussion on this recurring topic in one place (https://github.com/rust-lang/rustfmt/issues/5075#issuecomment-995309519)

**Comment by scottmcm** [comment]
Ah, I see it came up in #3242 too.
