### ISSUE TITLE
bug: imports_granularity = "Module"/"Crate"/"One" crash code when de-duplicate dependencies

### ISSUE THREAD

**Issue by Sunt-ing** [rust-lang/rustfmt#5131]
Recently, I enabled a rustfmt rule:
```toml
imports_granularity = "Module"
```

After I re-fmt, the code failed to be compiled. And thus I found an unexpected rustfmt behaviour:

before fmt:
```rust
use risingwave_pb::data::DataType;
use risingwave_pb::data::DataType as DataTypeProst;
```

after fmt:
```rust
use risingwave_pb::data::DataType as DataTypeProst;
```

But the codes that use "DataType" are not changed.

I don't think that rustfmt should turn the correct code into incorrect in any condition.

**Comment by TennyZhuang** [comment]
Can you provide a reproducible example?

**Comment by Sunt-ing** [comment]
> Can you provide a reproducible example?

Ok, will do it soon.

**Comment by Sunt-ing** [comment]
> Can you provide a reproducible example?

I created a repo to reproduce this bug: https://github.com/Sunt-ing/rustfmt_bug_example

**Comment by skyzh** [comment]
> > Can you provide a reproducible example?
> 
> I created a repo to reproduce this bug: https://github.com/Sunt-ing/rustfmt_bug_example

Consider creating a single file for this issue, which is easier to test and reproduce. e.g.,

https://github.com/rust-lang/rustfmt/blob/master/tests/target/imports_granularity_crate.rs

**Comment by Sunt-ing** [comment]
@skyzh Good advice. I will try to do that.

**Comment by Sunt-ing** [comment]
@skyzh Since the bug occurs when imports_granularity = "Module", I think it's hard to reproduce it within a single file. I'd like to leave it to the one who wants to fix it after the bug is verified. He or she could create such a file as a test.

**Comment by TennyZhuang** [comment]
> @skyzh Since the bug occurs when imports_granularity = "Module", I think it's hard to reproduce it within a single file. I'd like to leave it to the one who wants to fix it after the bug is verified. He or she could create such a file as a test.

In fact, rustfmt always accept a single file as input, and `cargo fmt` call rustfmt on all files. So it should always reproduce on a single file.

**Comment by Sunt-ing** [comment]
OK, I created one. This code snippet will crash after you format the following code with any one of the following options:
- imports_granularity = "Module"
- imports_granularity = "One"
- imports_granularity = "Crate"

```rust
#![allow(dead_code)]
mod a {
    pub mod b {
        pub struct Data {
            pub a: i32,
        }
    }

    use crate::a::b::Data;
    use crate::a::b::Data as Data2;

    pub fn data(a: i32) -> Data {
        Data { a }
    }

    pub fn data2(a: i32) -> Data2 {
        Data2 { a }
    }

    #[cfg(test)]
    mod tests {
        use super::*;

        #[test]
        pub fn test() {
            data(1);
            data2(1);
        }
    }
}

```
