### ISSUE TITLE
Q: Skip formatting on module doc comment

### ISSUE THREAD

**Issue by bazaah** [rust-lang/rustfmt#5144]
Hi :wave: 

I'm looking for clarification here, as I couldn't find anything in previous issues. 

Is it possible to disable formatting of inner module doc comments but keep formatting for the rest of the module?

For example:

```rust
//! Some long poetic comment waxing lyrical on the merits of this module, over long lines.

// Leave the above alone ^

// But keep formatting for everything else in the module
struct Foo { /* ... */ }
```

I've tried the obvious solution, namely trying to add the attribute `#[rustfmt::skip]` to the comment, but rust doesn't like it very much. Am I missing something?

Thanks and enjoy the holidays!

**Comment by calebcartwright** [comment]
Thanks for the question, but no I don't think there's a way to get that selective with comments. The attributes aren't applied to other attributes/comments/etc. so you can't use the attribute to apply to a specific comment.

The only possible, albeit clunky, approach I could think of would be to leverage the `file-lines` feature to try to exclude that particular line (or lines depending on what the comment really looks like)
