### ISSUE TITLE
Format inside `if_chain!`

### ISSUE THREAD

**Issue by smoelius** [rust-lang/rustfmt#5146]
Is there a way to have `rustfmt` format inside `if_chain` invocations?

Consider this code:
```rust
use if_chain::if_chain;

fn main() {
    // Example "standard if"
    if "/home/user/Untitled.txt" == std::path::Path::new("/").join("home").join("user").join("Untitled.txt").to_string_lossy() {
        println!("equal");
    }

    // Example "standard then"
    if true {
        println!("{}", "/home/user/Untitled.txt" == std::path::Path::new("/").join("home").join("user").join("Untitled.txt").to_string_lossy());
    }

    // Example "if_chain if"
    if_chain! {
        if "/home/user/Untitled.txt" == std::path::Path::new("/").join("home").join("user").join("Untitled.txt").to_string_lossy();
        then {
            println!("equal");
        }
    }

    // Example "if_chain then"
    if_chain! {
        if true;
        then {
            println!("{}", "/home/user/Untitled.txt" == std::path::Path::new("/").join("home").join("user").join("Untitled.txt").to_string_lossy());
        }
    }
}
```

If you run `rustfmt` on it, the "standard if" and "standard then" examples with be formatted, but the "if_chain if" and "if_chain then" examples will not.

I'm sorry as this must have been asked before, but searching the issues for `if_chain` yields no hits.

**Comment by calebcartwright** [comment]
> I'm sorry as this must have been asked before, but searching the issues for if_chain yields no hits.

No worries! I can't recall any asks _specifically_ for `if_chain!`, but it's fundamentally the same underlying question/discussion as any other macro call.

The short answer is no, rustfmt can't format this and likely won't be able to any time soon.

rustfmt is a formatter for Rust code, it works directly with valid Rust syntax by processing the parsed AST of input programs. Args to mac calls _can_ be valid syntax, but often are not, as is the case with `if_chain`. rustfmt will attempt to format args that can be parsed as valid syntax for calls that use the paren or bracket delims, but can't do anything with non-parseable syntax.

How to deal with that proverbial can of worms is a long standing, unresolved question. Based on a cursory review of that crates docs, it does seem like it could be a reasonable candidate for special-case handling, though we're still not ready to open up that aforementioned can and deal with the potential flood of external/3rd party macros folks might want (as we'd have to develop and then maintain both parsing and formatting code).

As such I'm going to close this for the time being, though happy to revisit if and when we do open the door a bit for special case handling of non-stdlib macros
