### ISSUE TITLE
Multiline string literals kept on the same line

### ISSUE THREAD

**Issue by tvallotton** [rust-lang/rustfmt#5163]
The way I naturally format my code that contains multiline string literals is like this: 
```rust
   let sql = parse("
   CREATE TABLE foo (
       id int primary key
   );
   ");
```
But the way it gets formatted with `rustfmt` is this: 
```rust
    let sql = parse(
        "
    CREATE TABLE foo (
       id int primary key
    ); 
   ",
    );
```

It would be nicer if multiline strings weren't broken into a new line if the first character of the string is a new line. Alternatively, add a line break only the length threshold is met. Do you agree with me in this regard?

**Comment by calebcartwright** [comment]
Thanks for sharing your perspective, but I'm going to close this.

rustfmt's core purpose is to reformat and check formatting against the [Rust Style Guide](https://github.com/rust-dev-tools/fmt-rfcs/) with [this particular section](https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/expressions.md#multi-line-calls) describing the applicable rule in this case. Various configuration options are provided to support some variations to those rules, but it's not intended to be a tool to reformat according to individual subjective formatting styles. 

It's not going to be practical for us to support such specialized rules based on the contents within string lits, especially when you can still maintain "formatting" of code-like content within the string by adjusting the string contents to account for the Style Guide rules, e.g.:

```rust
fn foo() {
    let sql = parse(
        "CREATE TABLE foo (
            id int primary key
        );",
    );
}
```

**Comment by corneliusroemer** [comment]
Isn't the style guide section referring to Rust code rather than string literals, though? The heading is *Multi-line calls*

**Comment by ytmimi** [comment]
@corneliusroemer here's the relevant text from the `Multi-line calls` section (emphasis mine):

> If the function call is not small, it would otherwise over-run the max width, **or any argument or the callee is multi-line**, then the call should be formatted across multiple lines.

Since the string lit is multi-line the multi-line call rules kick in. rustfmt moves the opening line of the string lit to it's own line and block indents it. However, rustfmt can't add extra whitespace to the string lit as that would change the value of the string lit so the rest of the string is not block indented.

Hope that helps explain what's going on here 😁
