### ISSUE TITLE
Formatting @generated from stdin results in empty output

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rustfmt#5172]
This causes rust-analyzer to discard the entire file if you try to format it. See https://github.com/rust-analyzer/rust-analyzer/issues/11285.

```
$ echo "//@notgenerated\nfn   foo() {}" | rustfmt
//@notgenerated
fn foo() {}
$ echo "//@generated\nfn   foo() {}" | rustfmt
$ rustfmt -V
rustfmt 1.4.38-stable (02072b4 2022-01-11)
```

**Comment by calebcartwright** [comment]
> This causes rust-analyzer to discard the entire file

Just to clarify, are you seeing this strictly with stdin or both stdin _and_ files? I can reproduce the former, but not the latter

**Comment by Ten0** [comment]
Strictly with stdin. IIUC the *files* he refers to are files manipulated by rust-analyzer.

**Comment by bjorn3** [comment]
Indeed. Rust-analyzer writes the file to rustfmt's stdin as most of the time the changes made by the user haven't been saved yet.

**Comment by calebcartwright** [comment]
Thanks for clarifying. Will get the resolution for this pulled in after work today, and it'll get pulled into a 1.58.1 patch release that fortunately was already being considered/planned

**Comment by calebcartwright** [comment]
Going to close as there's nothing left to do now but wait for the releases to go out, thanks again for the reports!
