### ISSUE TITLE
Add support for let chains

### ISSUE THREAD

**Issue by c410-f3r** [rust-lang/rustfmt#5177]
See https://github.com/rust-lang/rust/pull/88642.

EDIT @ytmimi:  Also see https://github.com/rust-lang/fmt-rfcs/issues/169 for the discussion on how `let-chains` should be formatted. I encourage anyone in the community to share their thoughts on the styling rules in the linked RFC. The formatting logic cannot be implemented in rustfmt until the formatting rules have been decided.

**Comment by ytmimi** [comment]
Just wanted to call out that I think not having support for let chains right now is related to #4955 and the fact that we don't currently format ``ast::ExprKind::Let`` AST nodes.

https://github.com/rust-lang/rustfmt/blob/5c558e2c11f33e1e25932607458396be883d36b5/src/expr.rs#L130

If anyone is interested in taking this on right now, this is probably the place to start.

**Comment by c410-f3r** [comment]
Closing in favor of #4955

**Comment by c410-f3r** [comment]
I am housekeeping my dashboard closing issues that are not on my radar and will probably take some time to be resolved.

@ytmimi If that is of your interest, feel free to create another issue.

**Comment by momvart** [comment]
Any updates about tracking this issue? It looks like it's got stuck in the preferred style decision, isn't it?
