### ISSUE TITLE
Shouldn't mess with license headers.

### ISSUE THREAD

**Issue by Ms2ger** [rust-lang/rustfmt#518]
Not happy with this:

``` diff
-/* This Source Code Form is subject to the terms of the Mozilla Public
- * License, v. 2.0. If a copy of the MPL was not distributed with this
- * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
+// This Source Code Form is subject to the terms of the Mozilla Public
+// License, v. 2.0. If a copy of the MPL was not distributed with this
+// file, You can obtain one at http://mozilla.org/MPL/2.0/.
```

**Comment by nrc** [comment]
Hmm, not sure how to deal with this - how to identify block comments which are a license vs other block comments. Maybe we can just change all licenses to line comments?

**Comment by Ms2ger** [comment]
I'd be fine with just being able to turn the `//`-preference off.

**Comment by nrc** [comment]
I think the best solution here is to have an option for skipping the first comment in a file - should be easy to implement and do what we want here.

**Comment by davidalber** [comment]
This no longer repros, with default configuration, due to #681, I guess. That is, if I do `rustfmt --write-mode=diff FILENAME` on what's below there's no difference.

```rust
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

fn main() {}
```

> I think the best solution here is to have an option for skipping the first comment in a file

Is this still what you want to do, @nrc? I guess the situation that's not currently supported is leaving the license above alone when `normalize_comments=true`, but it seems like that's all right.

**Comment by nrc** [comment]
I guess `normalize_comments` could take a `Yes`/`No`/`SkipFirst` enum, rather than a bool. OTOH, it doesn't feel like a very good solution to just skip the first comment. I don't think I have a better idea right now though.

**Comment by scampi** [comment]
In addition to verifying headers, the option `license_template_path` could identify the comment style and keep the original, while still allowing the header to be formatted if deemed necessary by that option.
