### ISSUE TITLE
Formatting breaks on very long line in match expression

### ISSUE THREAD

**Issue by msvbg** [rust-lang/rustfmt#5184]
Reproduction snippet:
```rs
fn a() {
    match 0 {
        a::AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA => {
        },
        1 => {
            let a =
            0;
        }
    }
}
```
I would expect the `let a = 0;` binding to be formatted by `rustfmt`, but it isn't. If I shorten the line with `A`s, it formats as expected.

Using `rustfmt 1.4.38-nightly (777bb86 2022-01-20)`.

**Comment by calebcartwright** [comment]
Thanks for reaching out but going to close as a duplicate (forget the exact issue, but assure you it's something on our list already).

rustfmt needs to be able to process the entire match expression; partial processing isn't possible (rustfmt works with the AST, not your raw input files). The pattern length hits an issue that's currently unsupported which results in an inability to process that arm and thus the expression itself.
