### ISSUE TITLE
fn_call_width value not respected

### ISSUE THREAD

**Issue by tcharding** [rust-lang/rustfmt#5185]
I have a `rustfmt.toml` with
```
max_width = 100
fn_call_width = 99
```
I format this code (longest line ends at character width 90):
```
    if args.len() < 2 {
        eprintln!("not enough arguments. usage: {} <hex-encoded 32-byte seed>", &args[0]);
        process::exit(1);
    }
```

And the formatter reformats it to
```
    if args.len() < 2 {
        eprintln!(
            "not enough arguments. usage: {} <hex-encoded 32-byte seed>",
            &args[0]
        );
        process::exit(1);
    }
```
Am I missing something?

Thanks

**Comment by calebcartwright** [comment]
Could you please provide the full/valid snippet that can be used to reproduce the behavior you're describing, the version of rustfmt you are using (`rustfmt --version`), and share how you are running rustfmt?

The original snippet is incomplete/invalid in isolation, though the indentation level implies it's intended to be contained within a top level item, and I'm unable to reproduce the behavior you're describing in that context

**Comment by tcharding** [comment]
Upgrade of cargo from 1.4.27 -> 1.4.38 fixed it, apologies for wasting your time.

**Comment by calebcartwright** [comment]
no worries!
