### ISSUE TITLE
Feature request: match_arm_align_threshold

### ISSUE THREAD

**Issue by cehteh** [rust-lang/rustfmt#5197]
Since we already have:

enum_discrim_align_threshold 
struct_field_align_threshold

It would be nice to have a similar formatter for simple/one-line match arms that lines up the '=>' like:

```
match foo {
    Some(LongEntityName(name))  => 1,
    Some(Short(thing))          => 2,
    Some(_)                     => 3,
    None                        => 4,
}
```

**Comment by calebcartwright** [comment]
Closing as a duplicate of #894
