### ISSUE TITLE
Does not handle it when no path is provided

### ISSUE THREAD

**Issue by FooqX** [rust-lang/rustfmt#5200]
If you just enter rustfmt and press enter, it does nothing, pretty sure (it could), and this behaviour should be handled and an error message should be printed out.

**Comment by ytmimi** [comment]
Thanks for the report.

Just to be clear you're evoking rustfmt directly? When you get a chance could you please provide the exact command that you're running, the version of rustfmt you're using, and optionally any non default configuration options you might be using.

**Comment by calebcartwright** [comment]
Thanks for reaching out, but it sounds like you may just not be familiar with the fact that rustfmt supports formatting both from stdin and provided files; it's not an error, but waiting for the stdin buffer to be flushed (try typing some rust code and then ctrl+d on PC or whatever the equivalent is on a Mac)

https://github.com/rust-lang/rustfmt#running-rustfmt-directly
