### ISSUE TITLE
rustfmt binary path in usage string

### ISSUE THREAD

**Issue by tharun208** [rust-lang/rustfmt#5214]
`rustfmt` help command returns usage information in which `rustfmt` binary path is appended to the usage message. The usage message will be cleaner without the binary's path. I am happy to raise a pr for this if we are okay to remove the path from the usage string.
<img width="772" alt="Screenshot 2022-02-03 at 9 22 29 PM" src="https://user-images.githubusercontent.com/14926492/152378300-797f93f3-58f1-4c21-bd85-fccbbde5a572.png">

**Comment by calebcartwright** [comment]
Thanks for reaching out and your willingness to contribute! I agree it would be nice to clean that up, so feel free to take a pass at a PR.

Note you can add a comment containing the text `@rustbot claim` to get the issue assigned to you and indicate you'll be working on it
