### ISSUE TITLE
Tuple struct field comments consume the field itself, only with doc comment

### ISSUE THREAD

**Issue by danjl1100** [rust-lang/rustfmt#5215]
### Describe the bug

When using the sequence `/// doc comment`, `// regular comment`, \<field definition\> within a tuple struct definition, rustfmt joins the field with the regular comment above, removing the field from the struct definition.

#### Input

```
struct MyTuple(
    /// Doc Comments
    // TODO note to add more to Doc Comments
    u32,
);
```

#### Output - correctness issue
```
struct MyTuple(
    /// Doc Comments
    // TODO note to add more to Doc Commentsu32,
);
```

The same applies for `/* block comments */`, but in this case the issue is purely cosmetic (does not change the struct definition).

#### Input (block comment)

```
struct MyTuple(
    /// Doc Comments
    /* TODO note to add more to Doc Comments */
    u32,
);
```

#### Output (block comment) - cosmetic issue

```
struct MyTuple(
    /// Doc Comments
    /* TODO note to add more to Doc Comments */u32,
);
```
At the very least, I expect there to be a separating space between the block comment and the `u32`, similar to the [similar example with no doc comment](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=56caf79accd720ea8602769218ff5c73)
```diff
-    /* TODO note to add more to Doc Comments */u32,
+    /* TODO note to add more to Doc Comments */ u32,
```

### Working cases

However, this issue doesn't seem to appear when the `/// doc comment` is removed, nor in named-field structs:

* No doc comment - **works as expected**
    ```
    struct MyTuple(
        // TODO note to add more to Doc Comments
        u32,
    );
    ```
* Struct with named fields (non-tuple) - **works as expected**
    ```
    struct MyStruct {
        /// Doc Comments
        // TODO note to add more to Doc Comments
        field: u32,
    }
    ```

### To Reproduce

* Tuple struct with doc comment, single line comment (broken) - [Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=38b7784b0a617a94a79cda0ae39f8aed)
* Tuple struct with doc comment, block comment (broken, cosmetic only) - [Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=666959c08b89aaf6e603877f44c7c085)
* Tuple struct with single line comment, only (**not broken**, just for comparison) - [Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=34fc4198daa2989a861645b1219c5345)
* Struct (named fields) with doc comment, single line comment (**not broken,** just for comparison) - [Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=d59605361c61150ac05d0b354a5bbf56)

### Expected behavior

I expect rustfmt to never change the tuple struct definition (`MyStruct(u32)` --> `MyStruct()`), and also preserve cosmetic newlines in the block comment case.

### Meta

* rustfmt version: rustfmt 1.4.38-nightly (2022-02-02 27f5d83)
* From where did you install rustfmt?: using playground only
* How do you run rustfmt: using playground only

### Additional remarks
* I didn't find any existing issues matching this problem description, but #4643 may be similar.
* One of my first issues reported to rustfmt. Let me know if this is not actually a bug.

**Comment by ytmimi** [comment]
Thank you for the report!

There is a lot of great detail here! I appreciate how thorough the report is. I can confirm that I'm able to reproduce this on the current master ``rustfmt 1.4.38-nightly (8b0b213c 2022-01-29)``.

**Comment by ytmimi** [comment]
Did some digging into this. The issue is that we're making the assumption that the type, prefix, and attributes can all fit on a single line if the type is written on a single line. As demonstrated by this issue, we should also consider whether or not a comment was found between the attribute and the prefix.

If anyone's interested in taking this on this issue on they should look at [rewrite_struct_field](https://github.com/rust-lang/rustfmt/blob/368a9b7cef25c22c3e836453e73d8584b251b578/src/items.rs#L1689), but specifically these lines:

https://github.com/rust-lang/rustfmt/blob/368a9b7cef25c22c3e836453e73d8584b251b578/src/items.rs#L1735-L1739

**Comment by tharun208** [comment]
@ytmimi I like to work on this
