### ISSUE TITLE
Feature request: Customizable `SHORT_ITEM_THRESHOLD`

### ISSUE THREAD

**Issue by cmpute** [rust-lang/rustfmt#5225]
This is a follow up issue to #5219. I found that I cannot format 
```rust
pub const FORMAT_TEST: [u64; 5] = [
    0x0000000000000000,
    0xaaaaaaaaaaaaaaaa,
    0xbbbbbbbbbbbbbbbb,
    0xcccccccccccccccc,
    0xdddddddddddddddd,
];
```
to something like
```rust
pub const FORMAT_TEST: [u64; 5] = [
    0x0000000000000000, 0xaaaaaaaaaaaaaaaa, 0xbbbbbbbbbbbbbbbb,
    0xcccccccccccccccc, 0xdddddddddddddddd,
];
```
due to the limit set by [`SHORT_ITEM_THRESHOLD`](https://github.com/rust-lang/rustfmt/blob/0b8ffac0297a46d7d2d2f8328cbc49de7e7144f2/src/overflow.rs#L29). I tried changing this threshold to 20, and then I managed to get the array formatted as the latter style.

Therefore I would like to request the ability to customize this limit, or at least override it for integer literals specifically. Thanks!

**Comment by calebcartwright** [comment]
I was actually going to post on #5219 to ask you to open a separate issue, so thanks for doing this! I'm definitely open to supporting this with a config option, provided the default is kept the same and someone is willing to submit a PR. It should be a relatively easy one for anyone that's interested, some relevant code sections below:

- Add a new config option (feel free to proposal any name)
  - Probably add to the `misc` block, along with a test entry
  https://github.com/rust-lang/rustfmt/blob/5df8c8f7e554e036fcb14a2d93d145c92d56bc2e/src/config/mod.rs#L106-L108
  
  https://github.com/rust-lang/rustfmt/blob/5df8c8f7e554e036fcb14a2d93d145c92d56bc2e/src/config/mod.rs#L590-L591

  - Add an entry in the [Configuration docs](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md)

- Drop the existing constant and replace it's usage with the new config option
 https://github.com/rust-lang/rustfmt/blob/0b8ffac0297a46d7d2d2f8328cbc49de7e7144f2/src/overflow.rs#L29
https://github.com/rust-lang/rustfmt/blob/0b8ffac0297a46d7d2d2f8328cbc49de7e7144f2/src/overflow.rs#L758-L761

**Comment by 123vivekr** [comment]
@calebcartwright I'm new to Rust and would like to help out. Can you assign this to me?

**Comment by ytmimi** [comment]
@123vivekr feel free to comment [@rustbot claim](https://rustc-dev-guide.rust-lang.org/rustbot.html#issue-claiming) to have the issue assigned to you!
