### ISSUE TITLE
Does not format relm4 view macro

### ISSUE THREAD

**Issue by JMS55** [rust-lang/rustfmt#5227]
Using [Relm4's macros](https://aaronerhardt.github.io/relm4-book/book/widget_macro.html), anything inside of the `view! {}` block does not get formatted. I expect: fixing indentation, spacing around operators, adding trailing comma, etc.

I'm not sure if there's anything rustfmt can do here, as it's not completely standard syntax, but it would be a great help if rustfmt could handle this code. 

```rust
#[relm4_macros::widget]
impl Widgets<AppModel, ()> for AppWidgets {
    view! {
        gtk::ApplicationWindow {
            set_title: Some("Simple app"),
            set_default_width: 300,
            set_default_height: 100,
            set_child = Some(&gtk::Box) {
                set_orientation: gtk::Orientation::Vertical,
                set_margin_all: 5,
                set_spacing: 5,

                append = &gtk::Button {
                    set_label: "Increment",
                    connect_clicked(sender) => move |_| {
                        send!(sender, AppMsg::Increment);
                    },
                },
                append = &gtk::Button::with_label("Decrement") {
                    connect_clicked(sender) => move |_| {
                        send!(sender, AppMsg::Decrement);
                    },
                },
                append = &gtk::Label {
                    set_margin_all: 5,
                    set_label: watch! { &format!("Counter: {}", model.counter) },
                }
            },
        }
    }
}
```

**Comment by calebcartwright** [comment]
Thanks for reaching out but I'm going to close this. rustfmt does not format macro calls that use `{}` delimiters, and will only attempt to format calls that use bracket or paren delimiters if their args can be parsed as valid rust syntax.

It's not related to `view!` or any particular macro call, but simply the fact that rustfmt is a formatter of rust code while args to macro calls regularly are not.

Refs #8
