### ISSUE TITLE
Remove unnecessary parentheses

### ISSUE THREAD

**Issue by Zamiell** [rust-lang/rustfmt#5247]
`rustfmt` should change the following code:

```rs
println!("just an integer: {:?}", (5u32));
```

To this:

```rs
println!("just an integer: {:?}", 5u32);
```

Also see related but different issue: #3823

**Comment by calebcartwright** [comment]
Thanks for reaching out, but I'm going to close. While the ask is technically fine in the context of `println`, it's not necessarily safe in the general macro call case so it's not something we're going to do.
