### ISSUE TITLE
`#[rustfmt::skip::attributes(derive)]` not work.

### ISSUE THREAD

**Issue by rise0chen** [rust-lang/rustfmt#5270]
```rust
    #[rustfmt::skip::attributes(derive)]
    #[allow(dead_code)]
    #[derive(StructField)]
    #[derive(Clone)]
    struct Struct {
        field: String,
    }
```

It will merge `#derive(StructField)` and `#[derive(Clone)]` to `#derive(StructField, Clone)]`, when i run `cargo fmt`.

I don't want to merge `#derive(StructField)` and `#[derive(Clone)]`.

**Comment by ytmimi** [comment]
Thanks for the report!

Looks like the `#[rustfmt::skip::attributes(derive)]` isn't being honored when `merge_derives=true` is set. You might also consider setting `merge_derives=false`. Check out the config docs for [merge_derive](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#merge_derives)
