### ISSUE TITLE
Rustfmt can't parse new where clause location (deprecated_where_clause_location)

### ISSUE THREAD

**Issue by Thomasdezeeuw** [rust-lang/rustfmt#5272]
The syntax from the new feature/deprecation warning `deprecated_where_clause_location`, from https://github.com/rust-lang/rust/issues/89122, can't be parsed by rustfmt.

Error:

```
error: where clause not allowed here
   --> /home/runner/work/heph/heph/remote/src/net_relay/mod.rs:379:13
    |
378 |         type Iter<'a, T> = serde_json::StreamDeserializer<'a, serde_json::de::SliceRead<'a>, T>
    |                         - help: move it here: `where T: DeserializeOwned`
379 |             where T: DeserializeOwned;
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^

Error writing files: failed to resolve mod `net_relay`: cannot parse /home/runner/work/heph/heph/remote/src/net_relay/mod.rs
error: where clause not allowed here
   --> /home/runner/work/heph/heph/src/bytes.rs:436:33
    |
436 |     type Bufs<'b> = B::Bufs<'b> where Self: 'b;
    |                  -              ^^^^^^^^^^^^^^
    |                  |
    |                  help: move it here: `where Self: 'b`

error: where clause not allowed here
   --> /home/runner/work/heph/heph/src/bytes.rs:459:47
    |
459 |     type Bufs<'b> = [MaybeUninitSlice<'b>; N] where Self: 'b;
    |                  -                            ^^^^^^^^^^^^^^
    |                  |
    |                  help: move it here: `where Self: 'b`

error: where clause not allowed here
   --> /home/runner/work/heph/heph/src/bytes.rs:589:33
    |
589 |     type Bufs<'b> = B::Bufs<'b> where Self: 'b;
    |                  -              ^^^^^^^^^^^^^^
    |                  |
    |                  help: move it here: `where Self: 'b`

Error writing files: failed to resolve mod `bytes`: cannot parse /home/runner/work/heph/heph/src/bytes.rs
```

Related code: https://github.com/Thomasdezeeuw/heph/blob/31cd4dc9e3ed2ad3b45aaba427b4ae00660dc90f/src/bytes.rs#L381-L384

Old version (that worked):
https://github.com/Thomasdezeeuw/heph/blob/02cc9cf35134ff0a694e6b6b390aa4207e955ee9/src/bytes.rs#L381-L384

**Comment by ytmimi** [comment]
Thanks for the report!

What version of rustfmt are you using? That might help us track down what's going on.

**Comment by Thomasdezeeuw** [comment]
I'm not sure actually, it happen in https://github.com/Thomasdezeeuw/heph/runs/5611134484, which ran today and updated using Rustup. So today's `x86_64-unknown-linux-gnu`?

**Comment by ytmimi** [comment]
After cloning the repo I can confirm that I'm able to reproduce the issue with `rustfmt 1.4.38-stable (9d1b2106 2022-02-23)`, but after installing the latest nightly version `rustfmt 1.4.38-nightly (1bfe40d1 2022-03-18)` the issue seems to go away.

That's likely the case because behind the scenes we're using the `rustc` parser, so older versions of the parser don't understand the updated syntax.

**Comment by Thomasdezeeuw** [comment]
> That's likely the case because behind the scenes we're using the `rustc` parser, so older versions of the parser don't understand the updated syntax (at least that's my guess).

That makes sense. So the current work around would be to switch to a nightly version of rustfmt and wait until rustc parse update makes it way to stable Rust. Good enough a solution for me.

**Comment by calebcartwright** [comment]
> So the current work around would be to switch to a nightly version of rustfmt and wait until rustc parse update makes it way to stable Rust. Good enough a solution for me.

Correct, generally speaking if you need a nightly toolchain for compilation, clippy, etc. then you'll likely need it for rustfmt too, especially for more bleeding edge features and syntax.
