### ISSUE TITLE
Const expressions break formatting

### ISSUE THREAD

**Issue by DianaNites** [rust-lang/rustfmt#5273]
stable

`rustc --version`: `rustc 1.59.0 (9d1b2106e 2022-02-23)`
`rustfmt --version`: `rustfmt 1.4.38-stable (9d1b210 2022-02-23)`

nightly

`rustc --version`: `rustc 1.61.0-nightly (8d60bf427 2022-03-19)`
`rustfmt --version`: `rustfmt 1.4.38-nightly (8d60bf4 2022-03-19)`

Current stable and nightly `rustfmt`s format the following code incorrectly

```rust
struct Example<const N: usize = { 1048576 }> {
    //
}
```

to

```rust
struct Example<const N: usize = { 1048576 }> {
    1048576 }> {
//
}
```

Or, with `normalize_comments = true` set

```rust
struct Example<const N: usize = { 1048576 }> {
    // 1048576 }> {
}
```

In this case there is a new `// 1048576 }> {` prepended on every format operation

**Comment by ytmimi** [comment]
Thanks for the report!

looks like the `Span` we're using is off. A similar issue was seen with #5011, so I imagine the fix should be similar to that.
