### ISSUE TITLE
Lambda with long argument list should be formatted without indent_style="Visual"

### ISSUE THREAD

**Issue by KarelPeeters** [rust-lang/rustfmt#5284]
I have a couple of lambdas with parameters with complex types, which take up a lot of space. This means rustfmt splits up the parameters over multiple lines, but it does so as if `indent_style="Visual"`. A simple reproducing example, on `1.4.38-nightly (2022-03-19 8d60bf4)` (the current rust playground formatter):

```rust
fn main() {
    let long_lambda = |x: &mut usize,
                       y: &mut usize,
                       z: &mut usize,
                       w: &mut usize,
                       v: &mut usize,
                       a: &mut usize,
                       b: &mut usize| {
        println!("{}", x);
        println!("{}", y);
        println!("{}", z);
        println!("{}", w);
        println!("{}", a);
        println!("{}", b);
    };

    long_lambda(&mut 1, &mut 2, &mut 3, &mut 4, &mut 5, &mut 6, &mut 7);
}
```

This is inconsistent with the rest of rustfmt formatting, and doesn't play well with things like IDE type hints.

I think it would be better if lambda parameters were formatted more like `indent_style="Block"`, which is the default elsewhere, eg. function parameters.

```rust
fn main() {
    let long_lambda = |
        x: &mut usize,
        y: &mut usize,
        z: &mut usize,
        w: &mut usize,
        v: &mut usize,
        a: &mut usize,
        b: &mut usize
    | {
        println!("{}", x);
        println!("{}", y);
        println!("{}", z);
        println!("{}", w);
        println!("{}", a);
        println!("{}", b);
    };

    long_lambda(&mut 1, &mut 2, &mut 3, &mut 4, &mut 5, &mut 6, &mut 7);
}
```

**Comment by ytmimi** [comment]
Thanks for the report.

> This is inconsistent with the rest of rustfmt formatting, and doesn't play well with things like IDE type hints.

I just want to point out that the rules that dictate how rustfmt is meant to work are laid out in the [style guide](https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/guide.md). The relevant section on [closures](https://github.com/rust-dev-tools/fmt-rfcs/blob/9d50e2a08e8d4c085086333a2a95121c5754fdee/guide/expressions.md#closures), does seem to indicate that the formatting should be more consistent with functions.

**Comment by ytmimi** [comment]
confirming that on  `rustfmt 1.4.38-nightly (63acf900 2022-03-27)` given this input:

```rust
fn main() {
    let long_lambda = |
        x: &mut usize,
        y: &mut usize,
        z: &mut usize,
        w: &mut usize,
        v: &mut usize,
        a: &mut usize,
        b: &mut usize
    | {
        println!("{}", x);
        println!("{}", y);
        println!("{}", z);
        println!("{}", w);
        println!("{}", a);
        println!("{}", b);
    };

    long_lambda(&mut 1, &mut 2, &mut 3, &mut 4, &mut 5, &mut 6, &mut 7);
}
```

produces this output:

```rust
fn main() {
    let long_lambda = |x: &mut usize,
                       y: &mut usize,
                       z: &mut usize,
                       w: &mut usize,
                       v: &mut usize,
                       a: &mut usize,
                       b: &mut usize| {
        println!("{}", x);
        println!("{}", y);
        println!("{}", z);
        println!("{}", w);
        println!("{}", a);
        println!("{}", b);
    };

    long_lambda(&mut 1, &mut 2, &mut 3, &mut 4, &mut 5, &mut 6, &mut 7);
}
```

The `rustfmt.toml` used is the same as the one listed in the rustfmt repo:
```toml
error_on_line_overflow = true
error_on_unformatted = true
version = "Two"
```

**Comment by calebcartwright** [comment]
Thank you for the report but let's go ahead and close this as a duplicate
