### ISSUE TITLE
conditionals in options

### ISSUE THREAD

**Issue by OfekShochat** [rust-lang/rustfmt#5302]
hello! how about conditionals in options? for example:
```
imports_granularity = import_count > 5 ? "One" : "Module"
```
this would complicate things quite a bit but its really robust.
probably wont be accepted but just as a note so that maybe a better structure would be made.
thanks!

**Comment by ytmimi** [comment]
Thanks for the suggestion! Could you elaborate on why you think this change would be robust? I'm also wondering if you could point to other projects in the rust ecosystem (or in general) that have this sort of a conditional configuration system. A few more details on your use case would also be help me better understand why you think this would be beneficial.

This would definitely complicate things and I think that's the single biggest deterrent for us not being able to take this on.

**Comment by OfekShochat** [comment]
> Could you elaborate on why you think this change would be robust
well it allows for a lot more configuration and less options that need to be done on your side (well, after its implemented). 
> This would definitely complicate things and I think that's the single biggest deterrent for us not being able to take this on.
yep

**Comment by OfekShochat** [comment]
My use case is like the above, only use One import granularity when import count > 5, Im not aware of any projects doing this unfortunately...

**Comment by calebcartwright** [comment]
Thanks for sharing your suggestion, but as you alluded to in the description this isn't something we're willing to consider so I'm going to close.

There's two core, large issues with the notion that prevent it from being viable:

- Trying to define a TOML and CLI compliant config-based DSL, and associated parser is way too much work and way too outside the scope of rustfmt; not to mention more code that can increase the bug surface and which we have to maintain
- A decision was made long ago relative to Rust Style and formatting tools to strive for a consistent style across programs/codebases. Obviously we do support config options, but this request would essentially start to shift to the opposite end of the spectrum wherein things would be formatted differently _within_ a given codebase.

**Comment by OfekShochat** [comment]
Ok thanks!
