### ISSUE TITLE
Add `max_preserved_empty_lines` option

### ISSUE THREAD

**Issue by evilenzo** [rust-lang/rustfmt#5312]
By default, rustfmt force deletes any empty lines, ignoring any user choices. For example,

This:
```rust
use std::io;


fn main() {
    println!("Hello, world!");
}
```

Force becomes this:

```rust
use std::io;

fn main() {
    println!("Hello, world!");
}
```

This is quite annoying, especially when formatter is configured to run on save (especially in IDE with autosave like CLion).
What I propose is option `max_preserved_empty_lines`

## `max_preserved_empty_lines`

Max number of blank lines to preserve. 

- **Default value**: `1`
- **Possible values**: *unsigned integer, zero stands for preserving all of user inputed lines*

### Example
Original Code (rustfmt will not change it with option set to `3` or `0`):

```rust
use std::io;



fn main() {
    println!("Hello, world!");
}
```

#### `1`
```rust
use std::io;

fn main() {
    println!("Hello, world!");
}
```

#### `2`
```rust
use std::io;


fn main() {
    println!("Hello, world!");
}
```

**Comment by calebcartwright** [comment]
Thanks for reaching out but I'm going to close this.

Whether or not you choose to utilize an editor plugin's format-on-save behavior is really up to you and orthogonal to rustfmt. If you choose to utilize rustfmt, your subject to the formatting rules it applies based on the [Rust Style Guide]() and any configuration options you elect to modify.

Given the description above, I'd encourage you to check out the [blank_lines_upper_bound](https://rust-lang.github.io/rustfmt/?version=v1.4.38&search=#blank_lines_upper_bound) option which has existed, albeit with some bugs, for quite a while. This can already be used to provide precisely the behavior you've requested relative to a max/upper bound of blank lines in the input that it will attempt to preserve.
