### ISSUE TITLE
rustfmt removes comment between doc comment and generic params

### ISSUE THREAD

**Issue by ytmimi** [rust-lang/rustfmt#5320]
This was an issue discovered when implementing a fix for #5122 in PR https://github.com/rust-lang/rustfmt/pull/5124#issuecomment-1030806191. The issue is reproducible on `rustfmt 1.4.38-nightly (8572b343 2022-04-24)` and uses the `rustfmt.toml` defined in the rustfmt repo.

```toml
# rustfmt.toml
error_on_line_overflow = true
error_on_unformatted = true
version = "Two"
```

This input:

```rust
// Non-doc pre-comment of Foo
/// doc of Foo
// Non-doc post-comment of Foo
struct Foo<
    // Non-doc pre-comment of 'a
    /// doc of 'a
    // Non-doc post-comment of 'a
    'a,
    // Non-doc pre-comment of T
    /// doc of T
    // Non-doc post-comment of T
    T,
    // Non-doc pre-comment of N
    /// doc of N
    // Non-doc post-comment of N
    const N: item,
>;
```

Gets formatted as follows:

```rust
// Non-doc pre-comment of Foo
/// doc of Foo
// Non-doc post-comment of Foo
struct Foo<
    // Non-doc pre-comment of 'a
    /// doc of 'a
    'a,
    // Non-doc pre-comment of T
    /// doc of T
    T,
    // Non-doc pre-comment of N
    /// doc of N
    const N: item,
>;
```

**Comment by ytmimi** [comment]
#5215 deals with a similar issue for struct fields, and I imagine the approach to fixing the issue for the generic parameters would be the same.

**Comment by calebcartwright** [comment]
Thanks for capturing this so we don't lose track!

**Comment by ytmimi** [comment]
Just a happy coincidence that I came across this as I was making changes to #5305, and peeking into various issues / PRs to see if I could reword any of the CHANGELOG entries.

**Comment by Rudxain** [comment]
Related bug (inline block comment):

in
```rust
pub struct Foo;
impl /*core*/std::error::Error for Foo {}
```

out
```rust
pub struct Foo;
impl std::error::Error for Foo {}
```

**Comment by ytmimi** [comment]
@Rudxain thanks for reaching out! There are several places where rustfmt isn't expected to find comments and doesn't try to recover them when reformatting your code. Between the `impl` keyword and the trait name is one of them. Although you're observing a similar issue it's happening in a different context so it's unfortunately unrelated to this issue.

Feel free to open up a separate issue to cover the case you're running into.

**Comment by Rudxain** [comment]
> There are several places where rustfmt isn't expected to find comments and doesn't try to recover them when reformatting your code.

Oh. I didn't expect that 😅

> Feel free to open up a separate issue to cover the case you're running into.

I'll probably do that. I commented `/*core*/` to remind myself to replace `std` by `core` [when `core` `Error`s get stabilized](https://github.com/rust-lang/rust/issues/103765)

BTW, thanks for the info!
