### ISSUE TITLE
Format static [u64; 256] is incorrect

### ISSUE THREAD

**Issue by julianlalu** [rust-lang/rustfmt#5322]
When using cargo fmt on a file containing the following static slice
```Rust
static HASH_64_RESULTS : [u64; 256]  = [
    0x9ae16a3b2f90404f, 0xbe6056edf5e94b54, 0xc2a04665ed038d75, 0x94a13d22e9eba49a, 
    ....
];
```
Each value wraps to a new line, this is not a readable format
```Rust
static CITY_HASH_64_RESULTS : [u64; 256]  = [
    0x9ae16a3b2f90404f, 
    0xbe6056edf5e94b54, 
    0xc2a04665ed038d75,
    0x94a13d22e9eba49a, 
    ....
];
```
Behaviour is correct for u32 slice.
```Rust
static HASH_32_RESULTS: [u32; 256] = [
    0xdc56d17a, 0xc0a92754, 0x2a1678b6, 0xd7c992e2, 0x616e1132, 0xfe6e37d4, 0x5145897e, 0xcfea845d
    ...
]
```

**Comment by calebcartwright** [comment]
Thanks for sharing, but this is correct so I'm going to close.

Whether or not the elements get wrapped or unwrapped from a vertical layout is dependent upon the length of the elements. The exact value of that threshold was previously a private/internal configuration option, but the next release of rustfmt will include an option that can be used to control this value.

https://rust-lang.github.io/rustfmt/?version=master&search=short_array_element_width_threshold#short_array_element_width_threshold

**Comment by julianlalu** [comment]
This is a good news, I'm waiting for the next release :)
Thank you
