### ISSUE TITLE
os error 5

### ISSUE THREAD

**Issue by ID4rker112** [rust-lang/rustfmt#5344]
cant do anything, theres an os error 5 all the time

**Comment by calebcartwright** [comment]
Please elaborate with relevant details, such as the version of rustfmt you are using (`rustfmt --version`), how you are running rustfmt (`cargo fmt`, `rustfmt foo.rs`, editor-on-save, etc.), the actual error message you are seeing, etc.

As initially posted this issue isn't really actionable nor anything we can even discuss with any substance

**Comment by calebcartwright** [comment]
Closing due to lack of information
