### ISSUE TITLE
regression: rustfmt using input from stdin emits empty output when using `#![rustfmt::skip]`

### ISSUE THREAD

**Issue by jhgg** [rust-lang/rustfmt#5368]
Since #5094 - rustfmt now emits nothing to stdout if reading a file with `#![rustfmt::skip]` is provided via stdin.

For example, running `echo '#![rustfmt::skip]\n\nfn main() { }'  | rustfmt` no longer emits anything to stdout. 

Rust-analyzer uses rustfmt to format files, and sends rustfmt the file contents to format via stdin. 

This has caused an interesting issue, where rustfmt emits nothing, so rust-analyzer deletes the contents of the file being formatted: https://github.com/rust-lang/rust-analyzer/issues/12458

**Comment by calebcartwright** [comment]
Thank you for the report and bisection!

**Comment by calebcartwright** [comment]
As I recall the custom tool attributes have only been available on nightly for a while now, so I don't think there's any need to pursue any kind of backport. I'm hoping to cut a new release sometime within the next couple days, and once available on nightly I'll drop a note on the RA issue to share the version that contains the fix
