### ISSUE TITLE
Recent nightly rustfmt broke compatibility with stable rustfmt

### ISSUE THREAD

**Issue by fbecart** [rust-lang/rustfmt#5399]
Hi, I hope this is the right channel to discuss an issue I'm having with rustfmt nightly. In my team, we format our code with `cargo +nightly fmt`, as we use some nightly-only features. Our CI doesn't have the nightly toolchain installed, but this hasn't caused us any issue (so far) since the format produced by nightly rustfmt has been backwards-compatible with stable.

However, this stopped working on Monday. `nightly-2022-05-20` formats the code in a way stable rustfmt rejects. Here is an example of change in the formatting which is only compatible with nightly rustfmt:

```diff
         repo_conn.run(move |conn| {
             let is_live = matches!(bot_kind, ClientBotUserKind::Live);
-            let rows = client_bot_role::table
-                .select((client_bot_role::name, client_bot_role::approval_needed))
-                .filter(
-                    client_bot_role::is_live.eq(is_live).and(
+            let rows =
+                client_bot_role::table
+                    .select((client_bot_role::name, client_bot_role::approval_needed))
+                    .filter(client_bot_role::is_live.eq(is_live).and(
                         client_bot_role::client_id
                             .is_null()
                             .or(client_bot_role::client_id.eq(client_id.uuid())),
-                    ),
-                )
-                .load::<(String, bool)>(conn)?;
+                    ))
+                    .load::<(String, bool)>(conn)?;
```

This happens even without any unstable rustfmt flag.

How can I check what precisely changed in Monday's nightly, so I could track down the change which created this issue?

**Comment by calebcartwright** [comment]
Thank you for reaching out. Could I ask you for two things:

* Please provide a direct, minimal repro (not just a git diff or --check output)
* Please clarify which versions you are using, both stable and nightlies (you mentioned Monday, but then a nightly version that's a month+ old)

**Comment by ytmimi** [comment]
Hey @fbecart you might consider checking the [1.5.0  CHANGELOG](https://github.com/rust-lang/rustfmt/blob/master/CHANGELOG.md#150-2022-06-13) If none of those options work, you might need to use [git-bisect](https://git-scm.com/docs/git-bisect) to pinpoint the commit.

When you have a moment could you also update the description with any configuration options you might be using since you mention that you're using some nightly-only features and it would be good to know which ones.

> Please provide a direct, minimal repro (not just a git diff or --check output)

I'd also like to see this. diffs are great, but I've found having pre and post formatting snippets to be a little easier to work with. Considering that you mention an issue between nightly/stable it would be nice to see:
1) the original input snippet
2) how stable rustfmt formats the snippet
3) how nightly rustfmt formats the snippet

**Comment by calebcartwright** [comment]
> you might consider checking the [1.5.0 CHANGELOG](https://github.com/rust-lang/rustfmt/blob/master/CHANGELOG.md#150-2022-06-13) If none of those options work, you might need to use [git-bisect](https://git-scm.com/docs/git-bisect) to pinpoint the commit.

Let's just start with the snippets :wink: We can investigate on our end but there's a good amount of complexity trying to map commits in our repo to nightly versions given the release process and I'm not sure how readily map-able that'll be for end users.

**Comment by fbecart** [comment]
Thanks for the fast answer.

I bisected the nightlies. The first nightly which has the issue is `nightly-2022-06-15` (`nightly-2022-06-14` is fine).

`stable`/`nightly-2022-06-14`:

```rust
impl NotificationRepository {
    fn set_status_changed(
        &self,
        repo_tx_conn: &RepoTxConn,
        rid: &RoutableId,
        changed_at: NaiveDateTime,
    ) -> NukeResult<Option<NotificationStatus>> {
        repo_tx_conn.run(move |conn| {
            let res = diesel::update(client_notification::table)
                .filter(
                    client_notification::routable_id.eq(DieselRoutableId(rid.clone())).and(
                        client_notification::changed_at
                            .lt(changed_at)
                            .or(client_notification::changed_at.is_null()),
                    ),
                )
                .set(client_notification::changed_at.eq(changed_at))
                .returning((
                    client_notification::id,
                    client_notification::changed_at,
                    client_notification::polled_at,
                    client_notification::notified_at,
                ))
                .get_result::<(Uuid, Option<NaiveDateTime>, Option<NaiveDateTime>, Option<NaiveDateTime>)>(conn)
                .optional()?;

            match res {
                Some(row) => {
                    let client_id = client_contract::table
                        .inner_join(client_notification::table)
                        .filter(client_notification::id.eq(row.0))
                        .select(client_contract::client_id)
                        .get_result::<Uuid>(conn)?;

                    Ok(Some(NotificationStatus {
                        client_id: client_id.into(),
                        changed_at: row.1,
                        polled_at: row.2,
                        notified_at: row.3,
                    }))
                }
                None => Ok(None),
            }
        })
    }
}
```

`nightly-2022-06-15`:

```rust
impl NotificationRepository {
    fn set_status_changed(
        &self,
        repo_tx_conn: &RepoTxConn,
        rid: &RoutableId,
        changed_at: NaiveDateTime,
    ) -> NukeResult<Option<NotificationStatus>> {
        repo_tx_conn.run(move |conn| {
            let res =
                diesel::update(client_notification::table)
                    .filter(client_notification::routable_id.eq(DieselRoutableId(rid.clone())).and(
                        client_notification::changed_at
                            .lt(changed_at)
                            .or(client_notification::changed_at.is_null()),
                    ))
                    .set(client_notification::changed_at.eq(changed_at))
                    .returning((
                        client_notification::id,
                        client_notification::changed_at,
                        client_notification::polled_at,
                        client_notification::notified_at,
                    ))
                    .get_result::<(Uuid, Option<NaiveDateTime>, Option<NaiveDateTime>, Option<NaiveDateTime>)>(conn)
                    .optional()?;

            match res {
                Some(row) => {
                    let client_id = client_contract::table
                        .inner_join(client_notification::table)
                        .filter(client_notification::id.eq(row.0))
                        .select(client_contract::client_id)
                        .get_result::<Uuid>(conn)?;

                    Ok(Some(NotificationStatus {
                        client_id: client_id.into(),
                        changed_at: row.1,
                        polled_at: row.2,
                        notified_at: row.3,
                    }))
                }
                None => Ok(None),
            }
        })
    }
}
```

Diff:

```diff
         changed_at: NaiveDateTime,
     ) -> NukeResult<Option<NotificationStatus>> {
         repo_tx_conn.run(move |conn| {
-            let res = diesel::update(client_notification::table)
-                .filter(
-                    client_notification::routable_id.eq(DieselRoutableId(rid.clone())).and(
+            let res =
+                diesel::update(client_notification::table)
+                    .filter(client_notification::routable_id.eq(DieselRoutableId(rid.clone())).and(
                         client_notification::changed_at
                             .lt(changed_at)
                             .or(client_notification::changed_at.is_null()),
[...]
-                    ),
-                )
-                .set(client_notification::changed_at.eq(changed_at))
-                .returning((
-                    client_notification::id,
-                    client_notification::changed_at,
-                    client_notification::polled_at,
-                    client_notification::notified_at,
-                ))
-                .get_result::<(Uuid, Option<NaiveDateTime>, Option<NaiveDateTime>, Option<NaiveDateTime>)>(conn)
-                .optional()?;
+                    ))
+                    .set(client_notification::changed_at.eq(changed_at))
+                    .returning((
+                        client_notification::id,
+                        client_notification::changed_at,
+                        client_notification::polled_at,
+                        client_notification::notified_at,
+                    ))
+                    .get_result::<(Uuid, Option<NaiveDateTime>, Option<NaiveDateTime>, Option<NaiveDateTime>)>(conn)
+                    .optional()?;
 
             match res {
                 Some(row) => {
```

**Comment by calebcartwright** [comment]
Thanks, but we're still lacking clarity here. You mentioned experiencing this without using any unstable options, but you also mentioned that you were using options which has to be the case; rustfmt defaults would not emit any of the snippets you've shared regardless of version.

Please share your configuration file or enumerate the options and values if you are setting them from the command line

**Comment by fbecart** [comment]
@calebcartwright Sorry, I forgot about this part: there is one option necessary to reproduce the issue: `--config max_width=140`

**Comment by calebcartwright** [comment]
No worries, able to reproduce now, much appreciated!

@ytmimi - this is indeed stability breaking which is bad enough on nightly but even more so if it were to hit stable. nothing definitive comes to mind for me as a root cause, though I worry it could be the introduction of memoization on expressions. If you get a chance to look today that'd be great, if not I'll try to get to it tonight, but it's one we need to prioritize.

**Comment by ytmimi** [comment]
Your hunch regarding the memoization seems to be correct. I created `issue_5399.rs` with the contents from the `stable/nightly-2022-06-14` code snippet.

Checking out the commit that introduced the memoization reproduces the issue
```
git show a37d3ab0e1c7c05f1a6410fb7ddf5539f0d030f8
git checkout a37d3ab0e1c7c05f1a6410fb7ddf5539f0d030f8
cargo run --bin rustfmt -- --check --config=max_width=140 issue_5399.rs
(produces a diff)
```

moving one commit further back leaves the input snippet unchanged.
```
git checkout HEAD~1 
cargo run --bin rustfmt -- --check --config=max_width=140 issue_5399.rs
(no diff)
```

**Comment by ytmimi** [comment]
I've been playing around with some things and it seems like not memoizing method calls fixies the issue. Was just about to open up a PR with the following change in `format_expr`:

```rust
    // Memoizing method calls lead to cases where rustfmt's stability guarantees are violated.
    // See https://github.com/rust-lang/rustfmt/issues/5399
    if matches!(expr.kind, ast::ExprKind::MethodCall(..)) {
        return format_expr_inner(expr, expr_type, context, shape);
    }
```

We can certainly revert the offending commit if you think that's a better fix

**Comment by calebcartwright** [comment]
I think given the hour the earliest possible nightly this could land in would be 06-24 but I'll drop a note hear confirming with the first nightly that actually contains this

**Comment by fbecart** [comment]
I confirm the issue is fixed in the latest nightly. Thanks for your quick reaction :+1:
