### ISSUE TITLE
wrap_comments with a *numbered* markdown list

### ISSUE THREAD

**Issue by anforowicz** [rust-lang/rustfmt#5416]
# Repro steps

Step1: Prepare the following `main.rs` file as an input for `rustfmt`:

```rs
/// Bullet list:
///
/// - one one one one one one one one one one one one one one one one one one one one one one one
/// - two two two two two two two two two two two two two two two two two two two two two two two
///
/// Numbered list:
///
/// 1. one one one one one one one one one one one one one one one one one one one one one one one
/// 2. two two two two two two two two two two two two two two two two two two two two two two two
fn main() {
    println!("Hello, world!");
}
```

Note that the long lines are 98 characters long.

Step2: Run `rustfmt --config wrap_comments=true src/main.rs`

Note the usage of `wrap_comments=true`.

# Expected behavior

Lists remain formatted as lists.  This expectation is based on:

- https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html#markdown which says that doc comments use https://commonmark.org/ and
- https://commonmark.org/help which seems to indicate that numbered lists should be supported with the format I've used above.

# Actual behavior.

The list of bullet items remains formatted correctly, but the numbered list is no longer formatted as a list:

```rs
/// Bullet list:
///
/// - one one one one one one one one one one one one one one one one one one
///   one one one one one
/// - two two two two two two two two two two two two two two two two two two
///   two two two two two
///
/// Numbered list:
///
/// 1. one one one one one one one one one one one one one one one one one one
/// one one one one one 2. two two two two two two two two two two two two two
/// two two two two two two two two two two
fn main() {
    println!("Hello, world!");
}
```

I am observing the behavior above when using the following version of `rustfmt`:

```
$ rustfmt --version
rustfmt 1.4.38-nightly (4ca19e0 2022-04-19)
```

# Workarounds

I guess I can insert a new line between numbered list items.  Indentation will still get broken, but at least separate list items will remain separate.

# Older, similar issues

A collegue has kindly pointed that there was a similar issue in the past (dealing with lists of bullet items): https://github.com/rust-lang/rustfmt/issues/3224

**Comment by ytmimi** [comment]
Thanks for the report.

rustfmt's support for markdown constructs is fairly limited, and there isn't any support for numbered lists. We currently handle bulleted lists (`*` and `-`) and block quotes (`>`) using the `ItemizedBlock` struct. 

https://github.com/rust-lang/rustfmt/blob/c4416f20dcaec5d93077f72470e83e150fb923b1/src/comment.rs#L433-L446

Maybe there's a way to minimally rework it to support numbered lists, but I'm not sure how difficult that would be.

**Comment by xxchan** [comment]
This issue can be closed
