### ISSUE TITLE
Poor formatting of long slice pattern

### ISSUE THREAD

**Issue by jrose-signal** [rust-lang/rustfmt#5427]
The following (somewhat icky) code lays out the entire slice or array pattern on one line, rather than splitting it up like it would for an array literal or struct pattern.

```rust
fn test() {
    let mut magic_data = [0; 8];
    let [magic_data0, magic_data1, magic_data2, magic_data3, magic_data4, magic_data5, magic_data6, magic_data7] =
        &mut magic_data;
    let [magic_data0, magic_data1, magic_data2, magic_data3, magic_data4, magic_data5, magic_data6, ..] =
        &mut magic_data;
    // should format like literals do:
    let copy = [
        magic_data0,
        magic_data1,
        magic_data2,
        magic_data3,
        magic_data4,
        magic_data5,
        magic_data6,
    ];
}
```

**Comment by ytmimi** [comment]
@jrose-signal Thanks for reaching out.

It's not totally clear from your example, but you're saying you'd like each array to be formatted vertically?

**Comment by ytmimi** [comment]
If you're using nightly rustfmt you can set `version=Two` to get the vertical formatting that you're looking for.

**Comment by jrose-signal** [comment]
> It's not totally clear from your example, since there isn't an input and an output snippet, but what I understand is you'd like each array to be formatted vertically?

Sorry, yes. That's a snippet formatted the way rustfmt currently outputs it on stable (as tested on play.rust-lang.org), and I'd like the pattern matching lines to be formatted similarly to the line building up `copy`.

> If you're using nightly rustfmt you can set `version=Two` to get the vertical formatting that you're looking for.

Oh, sweet, thank you! I don't think it's worth the unstable option, but even so maybe this can be closed. Or maybe it should stay open for better handling in "=One" mode.

**Comment by calebcartwright** [comment]
Thank you both, but going to close. The various stability constraints prohibit us from being able to make such a change that's applied by default, which is most likely why this is gated behind the version flag.

At some point in the hopefully-not-too-terribly-distant future the output from version=Two will be the default, but there's no action that can be taken here.
