### ISSUE TITLE
Reordering based on visibility

### ISSUE THREAD

**Issue by c410-f3r** [rust-lang/rustfmt#5432]
In this issue, I will only focus on module declaration and imports.

Is there an available option (nightly, stable, whatever) to reorder based on the declared visibility? Couldn't find anything related.

It is very unpleasant to see mixed declarations.

```rust
pub mod a;
mod b;
pub mod c;
pub(crate) mod d;
pub(crate) mod e;

pub use a::A;
use b::B;
pub use c::C;
pub(crate) use d::D;
pub(crate) use e::E;
```

Also, It is very unpleasant to force a new line in every god damn module (Imagine several different modules).

```rust
// Most visible to less visible

pub mod a;
pub mod c;

pub(crate) mod d;
pub(crate) mod e;

mod b;

pub use a::A;
pub use c::C;

pub(crate) use d::D;
pub(crate) use e::E;

use b::B;
```

In a perfect world without pain, misery and sadness (I am joking, OK); the following would be preferable.

```rust
pub mod a;
pub mod c;
pub(crate) mod d;
pub(crate) mod e;
mod b;

pub use a::A;
pub use c::C;
pub(crate) use d::D;
pub(crate) use e::E;
use b::B;
```

**Comment by calebcartwright** [comment]
Thanks for reaching out.

First, I just want to share a friendly ask to be mindful of language so that we can be sure to keep the conversation constructive and technical. Cursing is allowed as per code of conduct, but code style is a highly subjective topic were people often resort to venting frustrations. This can result in our conversations spiraling off topic quickly, so we tend to try to proactive about steering away from the emotional/subjective parts.

As to your ask, my understanding is that you'd like the ability to reorder/sort, based on visibility, within the existing groups of imports you've defined. Does that sound like a fair/accurate characterization of your ask, or have I misunderstood?

**Comment by c410-f3r** [comment]
@calebcartwright Thank you for your response

> Is there an available option (nightly, stable, whatever) to reorder based on the declared visibility? Couldn't find anything related.

Answering my own stated question after length inspection, it seems that such option doesn't really exist.

> First, I just want to share a friendly ask to be mindful of language so that we can be sure to keep the conversation constructive and technical. Cursing is allowed as per code of conduct, but code style is a highly subjective topic were people often resort to venting frustrations. This can result in our conversations spiraling off topic quickly, so we tend to try to proactive about steering away from the emotional/subjective parts.

Now that it is probably clear the state of this behaviour, I will close this thread in order to avoid further controversial language.

Due to the current values, feel free to remove the entirety of this conversation if desired.

**Comment by calebcartwright** [comment]
> Now that it is probably clear the state of this behaviour, I will close this thread in order to avoid further controversial language.
>
> Due to the current values, feel free to remove the entirety of this conversation if desired.

It's alright, no hard feelings or anything. Just wanted to be proactive is all!

You are correct that this currently is it not possible. There are several existing options that do very related things, but there's no option/combination of existing options that would do exactly what you are looking for. Technically it would be possible to add this, so you're welcome to reopen if it's something you'd like to potentially see implemented.

As a disclaimer though, I think the trickiest part of implementing this will just be interoperating with the other existing options, like `group_imports` and `reorder_imports`. Additionally, we'd be happy to provide guidance to anyone that wanted to work on this, but I don't think it's something we'd ever have bandwidth/priority to work on ourselves
