### ISSUE TITLE
[unstable option] loop_brace_style

### ISSUE THREAD

**Issue by liam-clink** [rust-lang/rustfmt#5448]
Loops are not included in the brace_style or control_brace_style

**Comment by ytmimi** [comment]
Thanks for reaching out the [`control_brace_style`](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#control_brace_style) config option is meant to control braces for control flow constructs. As such, I think it might be better to use the existing option to control the brace style for loops instead of creating a new configuration option.

**Comment by ytmimi** [comment]
@liam-clink, let me know what your thoughts are. It would also be great to get a little more detail on your motivation for controling the brace style of `loops`.

I Also want to mention that rustfmt is an implementation of the [rust style guide](https://github.com/rust-dev-tools/fmt-rfcs/blob/ba17faa77e4d5a1c53046aea0901e72b6d0ec0f4/guide/guide.md), and the section on [`Control flow expressions`](https://github.com/rust-dev-tools/fmt-rfcs/blob/ba17faa77e4d5a1c53046aea0901e72b6d0ec0f4/guide/expressions.md#control-flow-expressions) mentions keeping the opening brace on the same line as the expression. This doesn't mean we wouldn't consider a PR to apply this option in the loop context, but we always want to keep the style guide in mind.

**Comment by liam-clink** [comment]
What I was saying is that there is no option to change loop brace style, not that control flow braces should affect that. I find vertically aligned braces to be more readable in general, that's all. I know what the style guide says, and if I were contributing to an existing project I would follow the existing style. Just want this for my own projects, and if anyone wants to contribute to them, keeping formatting consistent using rustfmt

**Comment by liam-clink** [comment]
I apologize, it seems that ordinary loops do already work, but I had a closure with a loop in it inside a function, which made me think loops weren't supported. The documentation doesn't mention loops, only functions structs and enums, so I believe this should be closed and an issue opened on the repo for the website, correct?

**Comment by ytmimi** [comment]
If [`control_brace_style`](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#control_brace_style) already controls loops I think it's best if we add those examples to the configuration docs found in the [`Configurations.md`](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md) file. Any interest in working on a PR for that?

It might also be worth opening up a separate issue to discuss the problem you encountered with the loop inside the closure. Without seeing a code snippet it's tough to say what's going on.

**Comment by calebcartwright** [comment]
Thanks for reaching out, but I am going to close given the above discussion.

@liam-clink - as @ytmimi already noted `control_brace_style` applies to all control flow type expressions (more info can be found [here](https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/expressions.md#control-flow-expressions)) which includes loop expressions. If you're not seeing that applied on a loop expression in standard Rust code (i.e. _not_ as part of args passed to a macro invocation) that would potentially be a bug that we'd like to know more about. It would be best to surface that as a new issue with a minimal reproducible example and relevant details (your version of rustfmt, config options, etc.)

There's broader discussion about brace style contexts in other positions in #3376
