### ISSUE TITLE
Handle captured identifiers in format strings

### ISSUE THREAD

**Issue by nyurik** [rust-lang/rustfmt#5450]
Since [1.58](https://blog.rust-lang.org/2022/01/13/Rust-1.58.0.html#captured-identifiers-in-format-strings) Rust allows `println!("Hello, {person}!");` style strings ([documentations](https://doc.rust-lang.org/std/fmt/)). I would like to propose `cargo fmt` to automatically convert `println!("Hello, {}!", person);` and other `format!`-like calls to the inlined versions, either by default, or, at least initially, as an opt-in.

Original code | After `cargo fmt` | Notes
---|---|---
`println!("{}", a)` | `println!("{a}")` | positional in-lining
`println!("{a}", a=b)` | `println!("{b}")` | named param
`println!("{a:0$}", width)` | `println!("{a:width$}")` | width param
`println!("{a:.0$}", prec)` | `println!("{a:.prec$}")` | precision param

**Comment by calebcartwright** [comment]
I wonder if rustfix might be a better venue for such transformations

**Comment by nyurik** [comment]
> I wonder if rustfix might be a better venue for such transformations

I just looked at [rustfix readme](https://github.com/rust-lang/rustfix#readme):   *The magic of rustfix is entirely dependent on the diagnostics implemented in the Rust compiler (and external lints, like [clippy](https://github.com/rust-lang-nursery/rust-clippy))*.

My understanding is that rustfix won't actually decide anything, but rather use whatever suggestion is made by rustc or clippy. I am not sure this type of fix would belong in the rustc itself. Do you think clippy would be a better target?

**Comment by calebcartwright** [comment]
I think clippy would probably be the best place to start, just to see if they happen to already have a lint or if they have one planned. If they do, then that's something rustfix could pick up.

**Comment by nyurik** [comment]
Thanks @calebcartwright , turns out clippy already has a similar (smaller-scoped) request, so closing in favor of https://github.com/rust-lang/rust-clippy/issues/8368

**Comment by calebcartwright** [comment]
Perfect, thanks for sharing!
