### ISSUE TITLE
Option for explicit `()` return type

### ISSUE THREAD

**Issue by cdmistman** [rust-lang/rustfmt#5466]
Something like:
```
explicit_unit_return_type = ["Never" | "Keep" | "Always"]
```

would result in reformatting:
```rs
// "Never" would turn
fn main() -> () {}
// into
fn main() {}

// "Always" would turn
fn main() {}
// into
fn main() -> () {}
```

the `Keep` option wouldn't affect the formatting of either, which is the current behavior

**Comment by calebcartwright** [comment]
Thank you for sharing, but I'm going to close.

The presence of the unnecessary unit is flaggable via an existing clippy lint ([unused_unit](https://rust-lang.github.io/rust-clippy/master/#unused_unit), and that means that one could remove such cases using [rustfix](https://github.com/rust-lang/rustfix/).

As such I see no reason why we should extend rustfmt to provide that duplicative functionality, and I'd be opposed to enhancing rustfmt simply to support adding an unnecessary unit.
