### ISSUE TITLE
rustfmt freezes on start

### ISSUE THREAD

**Issue by eezstreet** [rust-lang/rustfmt#5467]
Running the following results in the app hanging, and no files get formatted:
```
rustfmt
```

Running the following:
```
rustfmt --version
> rustfmt 1.4.38-nightly (ca122c7 2022-06-13)
```

**Comment by ytmimi** [comment]
Thanks for reaching out, but in order for this to be actionable we'll need to know what input source you're running rustfmt on and if you're using any non default configuration options. If you could come up with a minimal reproducible example that would be great. Any chance you're using `cfg-if!`?

**Comment by calebcartwright** [comment]
It's not frozen nor hung; it's waiting for stdin to be flushed - https://github.com/rust-lang/rustfmt#running-rustfmt-directly.

Closing accordingly
