### ISSUE TITLE
single_line_if_else_max_width not working

### ISSUE THREAD

**Issue by gorsat** [rust-lang/rustfmt#5494]
No matter what I do with config (both command line and rustfmt.toml) rustfmt breaks my if/else clauses onto multiple lines. I'm not seeing others report this, so I assume this has something to do with how my setup, but I can't figure it out. Ideally, between --print-config and --check this would be easy to diagnose. 

This is on Windows 11.
Here's the rustfmt version I'm running:
```
rustfmt --version
rustfmt 1.4.38-stable (e092d0b6 2022-07-16)
```

Here's an example of it breaking up if/else clauses:
```
rustfmt --check src/main.rs
...
 impl fmt::Display for Node {
     fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
         let g = |b: bool| -> char {
-            if b {'*'} else {'-'}
+            if b {
+                '*'
+            } else {
+                '-'
+            }
...
```
And here is the config that it claims it's using. You can see that use_small_heuristics is set to Max and single_line_if_else_max_width is set to 100. But this is the config that led to the change shown above. Is there some other setting in here that's overriding my intent? Is there some other config that it might be using (and not reporting via --print-config)? 
```
rustfmt --print-config current src/main.rs
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"
indent_style = "Block"
use_small_heuristics = "Max"
fn_call_width = 100
attr_fn_like_width = 100
struct_lit_width = 100
struct_variant_width = 100
array_width = 100
chain_width = 100
single_line_if_else_max_width = 100
wrap_comments = false
format_code_in_doc_comments = false
comment_width = 80
normalize_comments = false
normalize_doc_attributes = false
license_template_path = ""
format_strings = false
format_macro_matchers = false
format_macro_bodies = true
hex_literal_case = "Preserve"
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = false
where_single_line = false
imports_indent = "Block"
imports_layout = "Mixed"
imports_granularity = "Preserve"
group_imports = "Preserve"
reorder_imports = true
reorder_modules = true
reorder_impl_items = false
type_punctuation_density = "Wide"
space_before_colon = false
space_after_colon = true
spaces_around_ranges = false
binop_separator = "Front"
remove_nested_parens = true
combine_control_expr = true
short_array_element_width_threshold = 10
overflow_delimited_expr = false
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0
match_arm_blocks = true
match_arm_leading_pipes = "Never"
force_multiline_blocks = false
fn_args_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
trailing_semicolon = true
trailing_comma = "Vertical"
match_block_trailing_comma = false
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
edition = "2015"
version = "One"
inline_attribute_width = 0
format_generated_files = true
merge_derives = true
use_try_shorthand = false
use_field_init_shorthand = false
force_explicit_abi = true
condense_wildcard_suffixes = false
color = "Auto"
required_version = "1.4.38"
unstable_features = false
disable_all_formatting = false
skip_children = false
hide_parse_errors = false
error_on_line_overflow = false
error_on_unformatted = false
report_todo = "Never"
report_fixme = "Never"
ignore = []
emit_mode = "Files"
make_backup = false
```

**Comment by ytmimi** [comment]
You need to set `version=Two`. 

running `rustfmt -- --config=version=Two` with the following example, leaves the formatting unchanged:

```rust
impl fmt::Display for Node {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let g = |b: bool| -> char {
            if b {'*'} else {'-'}
        };
    }
}
```

running with `version=One` produces:

```rust
impl fmt::Display for Node {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let g = |b: bool| -> char {
            if b {
                '*'
            } else {
                '-'
            }
        };
    }
}
```

**Comment by calebcartwright** [comment]
And just to add on a bit of context, the reason for the version gate is because it was later discovered that exprs in certain positions could be treated differently but the formatting stability guarantee prohibited making changes that would introduce formatting diff. At some point down the road the version gate won't be necessary to get this behavior, but for now it is

**Comment by gorsat** [comment]
Thanks @calebcartwright and @ytmimi. I really appreciate the quick response!

More comments fwiw:
 
I've been looking around in the docs and haven't found this requirement (setting version=Two) spelled out clearly. But it looks as though it's necessary for features like single_line_if_else_max_width to work. I suggest adding really clear and obvious text to the "Configuring Rustfmt" page that explains which features require this setting. In fact, single_line_if_else_max_width is listed as stable (even though it requires the unstable version=Two setting?)

Also, I notice that I am unable to set version=Two in my rustfmt.toml file even though I can set it (and it works) on the command line as @ytmimi demonstrated. When it fails it warns about version=Two being unstable. But this strikes me as an odd restriction. Why can this be set this via one mechanism (command line) but not another (config file)?

**Comment by ytmimi** [comment]
> I've been looking around in the docs and haven't found this requirement (setting version=Two) spelled out clearly. But it looks as though it's necessary for features like single_line_if_else_max_width to work. I suggest adding really clear and obvious text to the "Configuring Rustfmt" page that explains which features require this setting. In fact, single_line_if_else_max_width is listed as stable (even though it requires the unstable version=Two setting?)

Agreed. I think we should probably enhance the section on `single_line_if_else_max_width` in the configuration docs. I'm also noticing that we don't have any tests in `tests/source/configs/` or `tests/target/configs/`. I actually don't think any test is using the option. Using `ripgrep (rg)` and running `rg "//rustfmt-single_line_if_else_max_width:" tests/` doesn't return anything.

> Also, I notice that I am unable to set version=Two in my rustfmt.toml file even though I can set it (and it works) on the command line as @ytmimi demonstrated. When it fails it warns about version=Two being unstable. But this strikes me as an odd restriction. Why can this be set this via one mechanism (command line) but not another (config file)?

I don't have all the context around why this behavior is possible. As far as I know it's always been possible to set unstable options via the CLI. I believe there have been discussions in the past about wether this is a feature or a bug, but those were had long before I joined the rustfmt team so unfortunately I can't link you to any of those discussions.
