### ISSUE TITLE
Unknown configuration option `fn_params_layout` in rustfmt 1.5.1

### ISSUE THREAD

**Issue by KonradHoeffner** [rust-lang/rustfmt#5498]
I use the newest rustfmt release 1.51 included in the Arch Linux `rust` 1-1.63.0-1 package released on 2022-08-11 but rustfmt does not recognize the `fn_params_layout` option:

```bash
$ cargo --version
cargo 1.63.0
$ rustc --version
rustc 1.63.0 (Arch Linux rust 1:1.63.0-1)
$ rustfmt --version
rustfmt 1.5.1-
$ cargo fmt
Warning: Unknown configuration option `fn_params_layout`
```
## rustfmt.toml

```toml
fn_params_layout = "Compressed"
```
According to the [documentation](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md), the `fn_params_layout` option is stable, so I expect it to be available in stable Rust.

**Comment by KonradHoeffner** [comment]
P.S.: I later realized that this was renamed from fn_args_layout after the release of rustfmt 1.5.1 and that I was looking at the documentation of the master branch but I will let this issue open because I'm not sure if it is correct that it is marked as "stable" when it is not available in the stable toolchain yet.

**Comment by ytmimi** [comment]
The `fn_params_layout` rename has not been released yet. It's only available on master. When checking for configuration values for a certain version of rustfmt I'd recommend looking at https://rust-lang.github.io/rustfmt/
