### ISSUE TITLE
rustfmt should be able to simplify use path::to::module::{self}

### ISSUE THREAD

**Issue by RuijieYu** [rust-lang/rustfmt#5510]
Currently rustfmt is able to simplify `use path::to::module::self` (which happens to be invalid syntax) into `use path::to::module`, and also to simplify `use path::to::sub::{module}` into `use path::to::sub::module`.

I want to suggest, based on these observations, that `use path::to::module::{self}` should simplify into `use path::to::module`.

---

A bigger example, using `rustfmt 1.4.38-stable (e092d0b 2022-07-16)`:

Before:
```rust
#![allow(unused_imports)]
use std::fs::{self}; // warn(unused_import_braces)
use std::io::self; // invalid syntax
use std::path::{PathBuf}; // warn(unused_import_braces)
```

After:
```rust
#![allow(unused_imports)]
use std::fs::{self}; // warn(unused_import_braces)
use std::io; // no warnings
use std::path::PathBuf; // no warnings
```

Proposed:
```rust
#![allow(unused_imports)]
use std::fs; // no warnings
use std::io; // no warnings
use std::path::PathBuf; // no warnings
```

**Comment by calebcartwright** [comment]
Thanks for reaching out but I am going to close as non-actionable and a duplicate (e.g. #5398).

The type of conversion you're suggesting is not valid/semantics preserving and can in some cases introduce compilation failures. 

See also #3568, #4681, and https://github.com/rust-lang/rust/issues/60941

> use path::to::module::self (which happens to be invalid syntax)

rustfmt works at the AST level, so the code only needs to be parseable in order for rustfmt to be able to operate, even if that parsed code will be failed by later stages of the compiler.
