### ISSUE TITLE
Unstable features can be used on a stable toolchain with `--config` option

### ISSUE THREAD

**Issue by gifnksm** [rust-lang/rustfmt#5511]
Unstable features can be used on a stable toolchain with `--config` option.

I think this behavior is a bug because [rustfmt documentation][rustfmt-doc] states the following:

> Stable options can always be used, while unstable options are only available on a nightly toolchain and must be opted into.
> To enable unstable options, set `unstable_features = true` in `rustfmt.toml` or pass `--unstable-features` to rustfmt.

# Steps to reproduce

1. create `foo.rs` with the following contents.

    ```rust
    // foo.rs
    use foo::b;
    use foo::b::{f, g};
    use foo::{a, c, d::e};
    use qux::{h, i};
    ```

2. run `rustfmt` with specifying unstable config.

   According [rustfmt documentation][rustfmt-doc-imports_granularity], `imports_granularity` is unstable.

    ```console
    $ rustfmt --config imports_granularity=crate foo.rs --check
    Diff in /home/nksm/tmp/foo.rs at line 1:
    -use foo::b;
    -use foo::b::{f, g};
    -use foo::{a, c, d::e};
    +use foo::{
    +    a, b,
    +    b::{f, g},
    +    c,
    +    d::e,
    +};
     use qux::{h, i};

    ```

# Environment

```console
$ rustup default
stable-x86_64-unknown-linux-gnu (default)

$ rustfmt --version
rustfmt 1.5.1-stable (4b91a6e 2022-08-08)
```

# Notes

If you specify unstable options in `rustfmt.toml`, `rustfmt` will work as expected.

```toml
# rustfmt.toml
imports_granularity = "crate"
```

```console
$ rustfmt --check foo.rs
Warning: can't set `imports_granularity = Crate`, unstable features are only available in nightly channel.
```

Curiously, unstable features can be used on the nightly toolchain without setting `unstatable_features = true`.
Is this a bug too?

```console
$ rustfmt +nightly --check foo.rs
Diff in /home/nksm/tmp/foo.rs at line 1:
-use foo::b;
-use foo::b::{f, g};
-use foo::{a, c, d::e};
+use foo::{
+    a, b,
+    b::{f, g},
+    c,
+    d::e,
+};
 use qux::{h, i};

```

[rustfmt-doc]: https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=
[rustfmt-doc-imports_granularity]: https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=#imports_granularity

**Comment by ytmimi** [comment]
Thanks for reaching out! I don't have any discussions to link you to but this behavior is actually intentional. @calebcartwright do you have anything to add?

**Comment by calebcartwright** [comment]
>  @calebcartwright do you have anything to add?

Not particularly. It's a known, long standing item. There's some conflicting views about it, but because it's been around so long any changes to it would be tantamount to a major breaking change which we can't readily make, so it continues to exist

**Comment by Veetaha** [comment]
I was confused by this first, but then I pondered. Maybe the design was such that unstable formatting features may have bus or unexpected behavior, and if you enable them in the config file then the autoformatting capability of rustfmt that writes changes to files running on a pre-commit hook may go wild and erase your some of your code.

So if you enable unstable features at the command line you have more explicitness and you know that you are using unstable. This way you would unstable features only on CI and only with the `--check` parameter that doesn't overwrite files, but only validates formatting.

**Comment by ytmimi** [comment]
@Veetaha to be completely honest I'm not sure what the rational behind allowing unstable features via `--config` is. That behavior pre-dates my time on the rustfmt team.
