### ISSUE TITLE
Format fails silently with long string

### ISSUE THREAD

**Issue by sampaioletti** [rust-lang/rustfmt#5517]
Hello,

When a file has a long line of text it fails silently without formatting the rest of the document

```rust
struct SomeStruct {
    inner: String,
}

impl SomeStruct {
    pub fn new() -> SomeStruct {
        SomeStruct
        { //<-intentional Format Mistake
            //fails silently
            inner: "Some long text Some long text Some long text Some long text Some long text Some long text Some long text".into()
            //works
            // inner: "Short text".into()
        }
    }
}
```

link with code in the playground...if you comment out the long inner line and use the shorter one..fmt works

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2d15a242e19893857057fb430005361f

Awesome project thank you very much

**Comment by ytmimi** [comment]
Try setting `error_on_unformatted=true` to get feedback. Odd that a warning isn't emitted when `error_on_unformatted=false`.

**Comment by ytmimi** [comment]
> fails silently without formatting the rest of the document

I don't believe the claim that we fail to format the rest of the document is correct. Can you please elaborate with a code snippet that shows that behavior.

Invoking rustfmt from the command line with the following input show that we still format things further on in the document even though we don't format the struct.

**input**
```rust
struct SomeStruct {
    inner: String,
}

impl SomeStruct {
    pub fn new() -> SomeStruct {
        SomeStruct
        { //<-intentional Format Mistake
            //fails silently
            inner: "Some long text Some long text Some long text Some long text Some long text Some long text Some long text".into()
            //works
            // inner: "Short text".into()
        }
    }
}

fn     main()       {
println!("hello world!");
}
```

**output**
```rust
struct SomeStruct {
    inner: String,
}

impl SomeStruct {
    pub fn new() -> SomeStruct {
        SomeStruct
        { //<-intentional Format Mistake
            //fails silently
            inner: "Some long text Some long text Some long text Some long text Some long text Some long text Some long text".into()
            //works
            // inner: "Short text".into()
        }
    }
}

fn main() {
    println!("hello world!");
}
```

**Comment by sampaioletti** [comment]
I'm sorry you are correct...it does format the rest of the document outside of the struct in question, I hadn't explored it further than what i show in the comments.

error_on_unformatted=true didn't make a difference for me

**Comment by sampaioletti** [comment]
You nailed it..sorry i searched for other issues but didn't come across that or the ones it references...I'll close this then since it's a duplicate..thank you for your help!

**Comment by ytmimi** [comment]
No worries! It never hurts to reach out! Please reach out if anything else comes up.

**Comment by sampaioletti** [comment]
Will do, Thanks!
