### ISSUE TITLE
rustfmt putting space between first and second tuple element indexing. is this intended?

### ISSUE THREAD

**Issue by akabinds** [rust-lang/rustfmt#5532]
I noticed that `rustfmt`, in some cases when using tuple indexing back to back such as `some_tuple.0.0` (`some_tuple.0` being another tuple or tuple struct of course), it would reformat it to `some_tuple.0 .0`. Is this behavior intended? If so, I would like an explanation on why `rustfmt` decides to format it this way. 

# Examples

Prior to running `cargo fmt`:
```rs
match self.peek().1.0 {
    ...
}
```

```rs
match self.advance().1.0 {
    ...
}
```

```rs
if self.peek().1.0 == expected {
   ...
}
```

After running `cargo fmt`:
```rs
match self.peek().1 .0 {
    ...
}
```

```rs
match self.advance().1 .0 {
    ...
}
```

```rs
if self.peek().1 .0 == expected {
   ...
}
```

**Comment by calebcartwright** [comment]
Please see - https://github.com/rust-lang/rustfmt/issues/4355#issuecomment-723764276

**Comment by akabinds** [comment]
> Please see - [#4355 (comment)](https://github.com/rust-lang/rustfmt/issues/4355#issuecomment-723764276)

Thank you.
