### ISSUE TITLE
tab as two spaces

### ISSUE THREAD

**Issue by gilaroni** [rust-lang/rustfmt#5540]
can I configure it s.t tabs will be two spaces instead of the default 4 ?

i.e.

fn main() {
  print!("hi")
}

rather than 

fn main() {
    print!("hi")
}

**Comment by ytmimi** [comment]
You can use the  [`tab_spaces`](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#tab_spaces) option. Set `tab_spaces=2`.
