### ISSUE TITLE
Formatting silently fails in edge-cases where line lengths extend past 100chars

### ISSUE THREAD

**Issue by Alfred-Mountfield** [rust-lang/rustfmt#5541]
I encountered a strange bug in our project where a multiline raw string was causing the rest of the expression to not format correctly (this was a chained set of calls, and the entire chain wasn't formatting, including the assignment where we were missing a space). To be clear **the expression was not formatting, but the rest of the file formatted fine and there were no errors from cargo fmt** (Even with `error_on_unformatted = true`)

I thought it was due to the raw string and investigated but it instead seems to be due to the line length. I've tried to isolate the problem but I honestly have no idea at this point. I apologise for the jumbled mess below but I hope the set of test-cases helps someone identify the cause of the problem because I do not know.

Each line has one key formatting error, missing spaces around the assignment operator, but other formatting fails too (like additional spaces, etc.)

I have tested this on stable and the `nightly-2022-09-15` and I believe it occurs on both.

```rust
#[derive(Clone)]
struct Foo {}

impl Foo {
    async fn bar(&self, _: &str) -> Self {
        self.clone()
    }
}

fn test(_: &str) {}

fn main() {
    let foo = Foo {};
    let i_am_a_really_long_variable_name_in_order_to_test_some_formatting_edge_cases_foo_foo_foo_foo_foo =
        "";
    //This formats fine
    let _ = foo.bar(
        r"
        some arbitrary amount of words to try and reach a desired line length, please, & thank you",
    );
    // This does not format correctly and is longer than 100 chars
    let _=foo.bar(
        r"
        some arbitrary amount of words to try and reach a desired line length, please, & thank youX",
    );

    // This formats fine, despite being longer than 100 chars
    let _ = test(
        r"
        some arbitrary amount of words to try and reach a desired line length, please, & thank youX",
    );

    // None of the below format correctly, just trying to isolate the case where it happens.. and failing to
    let _=test(
        i_am_a_really_long_variable_name_in_order_to_test_some_formatting_edge_cases_foo_foo_foo_foo_foo
    );
    let _=foo.bar(
        i_am_a_really_long_variable_name_in_order_to_test_some_formatting_edge_cases_foo_foo_foo_foo_foo
    );

    let _=test("some arbitrary amount of words to try and reach a desired line length, please, & thank you",);
    let _=foo.bar("some arbitrary amount of words to try and reach a desired line length, please, & thank you",);
    let _=foo
        .bar("some arbitrary amount of words to try and reach a desired line length, please, & thank you");
    let _=foo
        .bar(r"some arbitrary amount of words to try and reach a desired line length, please, & thank you",
        );
    let _=foo
        .bar(r#"
           some arbitrary amount of words to try and reach a desired line length, please, & thank you
           "#,
        );
}
```

**Comment by ytmimi** [comment]
Thanks for reaching out.

The `foo.bar()` cases are duplicates of https://github.com/rust-lang/rustfmt/issues/3863.

Rewriting function calls goes down a similar code path as array rewriting, so I believe those cases are duplicates of https://github.com/rust-lang/rustfmt/issues/4403.

If you're using nightly you can try setting `format_strings=true` to allow rustfmt to break long strings. However, there's not much you can do about the really long identifier names. Your best bet there is to increase the `max_width`.

**Comment by Alfred-Mountfield** [comment]
Thanks for the quick response, I looked but failed to find those issues.

> If you're using nightly you can try setting format_strings=true to allow rustfmt to break long strings. However, there's not much you can do about the really long identifier names. Your best bet there is to increase the max_width.

I think the issues you linked identify the issue properly, so I think I agree with closing this off, but just in case I wasn't clear in my original post; my problem isn't that rustfmt doesn't manage to somehow split the line and keep the appropriate line length (because that wouldn't be possible with the long identifier names), it's just that it completely gives up on other formatting things such as identation and whitespace around the equality.

I found it quite strange that some of the cases managed to format even though they went past the max width.

**Comment by calebcartwright** [comment]
> it's just that it completely gives up on other formatting such as identation and whitespace around the assignment operator.

it's not a matter of "giving up" other parts. rustfmt is strictly an AST-driven pretty printer and does not directly process input files and the tokens contained within. There's plenty of cases, such as with chains as detailed in the linked threads, where if rustfmt is unable to format a particular AST node, rustfmt is accordingly unable to safely format the containing/parent node, and it's the entire contents of the parent node that are emitted.
