### ISSUE TITLE
rustfmt eats dyn_star syntax

### ISSUE THREAD

**Issue by mejrs** [rust-lang/rustfmt#5542]
[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=4744115d7a207179d93ecba705d16daf)

Given:
```rust
#![feature(dyn_star)]
#![allow(incomplete_features)]

use core::fmt::Debug;

fn main() {
    let i = 42;
    let dyn_i = i as dyn* Debug;
    dbg!(dyn_i);
}
```

This is formatted to: 
```rust
#![feature(dyn_star)]
#![allow(incomplete_features)]

use core::fmt::Debug;

fn main() {
    let i = 42;
    let dyn_i = i as Debug;
    dbg!(dyn_i);
}
```

After formatting, this code no longer compiles.

**Comment by ytmimi** [comment]
Thanks for the report. Any chance you could link me to more info about `#![feature(dyn_star)]`?

I can confirm that I'm able to reproduce the issue on the playground, however when running with the latest master (ef91154250977b3b5d05448dafbca524a1168b47) this is the output that I get:

```rust
#![feature(dyn_star)]
#![allow(incomplete_features)]

use core::fmt::Debug;

fn main() {
    let i = 42;
    let dyn_i = i as dyn * Debug;
    dbg!(dyn_i);
}
```

**Comment by ytmimi** [comment]
Thanks for linking the `dyn*` PR. It looks like that PR didn't make changes to handle `dyn*` formatting in rustfmt, so I don't think it's fixed yet. Also the `dyn* Debug` from your original snippet is getting converted to `dyn * Debug`. Not sure if things still compile when formatted like that, but it looks like there's still work to do on the rustfmt side to support `dyn*`.

**Comment by eholk** [comment]
`dyn* Debug` and `dyn * Debug` will both parse and compile fine, but I prefer the `dyn*` version.
