### ISSUE TITLE
Cannot properly indent 121-or-more character line in a particular situation

### ISSUE THREAD

**Issue by ChaiTRex** [rust-lang/rustfmt#5562]
The indentation of the following is not corrected:

    impl X for Y {
        fn f() {
            for _ in {
                                    a./*a*/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                                }
                                .a
                                {
                                    a;
                                }
        }
    }

If I shorten the number of nonwhitespace characters in the longest line, it does seem to handle indentation properly.

**Comment by ytmimi** [comment]
@ChaiTRex could you provide the code snippet that is formatted correctly?

**Comment by ChaiTRex** [comment]
> @ChaiTRex could you provide the code snippet that is formatted correctly?

You can see it by removing an `a` or two from the long line, after which `rustfmt` produces:

    impl X for Y {
        fn f() {
            for _ in {
                a./*a*/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
            }
            .a
            {
                a;
            }
        }
    }

**Comment by ytmimi** [comment]
This is a `max_width` issue. There is no way for rustfmt to format the `a./*a*/aaa..` from the issue description within the default `max_width` of 100 characters, so rustfmt leaves the entire AST node unformatted. However, the snippet from the issue description can be formatted if you run rustfmt with a `max_width=101`. e.g: `rustfmt --config=max_width=101`.

Here's a little more context. Formatting for all expression begins in [`format_expr`](https://github.com/rust-lang/rustfmt/blob/ef91154250977b3b5d05448dafbca524a1168b47/src/expr.rs#L51), and we specifically handle control flow AST nodes like `ast::ExprKind::ForLoop` in the following match arm:

https://github.com/rust-lang/rustfmt/blob/ef91154250977b3b5d05448dafbca524a1168b47/src/expr.rs#L131-L135

**Comment by ChaiTRex** [comment]
@ytmimi That was only one example. It seems like there's an inline comment handling issue. If we move the dot and inline comment over several characters to the right, it still fails. If we replace `/*a*/` with `aaaaa`, we have the same number of characters, but it does handle it properly:

    impl X for Y {
        fn f() {
            for _ in {
                                    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa./*a*/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                                }
                                .a
                                {
                                    a;
                                }
        }
    }

produces no change, while:

    impl X for Y {
        fn f() {
            for _ in {
                                    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                                }
                                .a
                                {
                                    a;
                                }
        }
    }

produces a properly indented result:

    impl X for Y {
        fn f() {
            for _ in {
                aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    .aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
            }
            .a
            {
                a;
            }
        }
    }

**Comment by ytmimi** [comment]
Thanks for pointing that out 👍🏼 I opened #5563 to specifically cover the comment issue you've highlighted here.
