### ISSUE TITLE
Remove / simplify wildcard imports.

### ISSUE THREAD

**Issue by dessalines** [rust-lang/rustfmt#5569]
Is there any setting which could expand wildcard imports? There are a lot of `use xxx::*` that it'd be wonderful if rustfmt could automatically expand.

**Comment by ytmimi** [comment]
Thanks for reaching out. Unfortunately there isn't any option for this, and given rustfmt's design this request isn't possible. 

rustfmt only operates on the AST of your program and doesn't do any name resolution, so there isn't any way for rustfmt to know which symbols are coming from which module.
