### ISSUE TITLE
Internal error with closure containing a long line followed by a whitespace line: left behind trailing whitespace

### ISSUE THREAD

**Issue by rMazeiks** [rust-lang/rustfmt#5575]
When formatting a function call, with a closure argument, `rustfmt` errors if the closure contains a long line, followed by a line containing only whitespace.

Example (note that line 4 contains some whitespace):

```
fn main() {
    Some(0).or_else(|| {
        todo!("long text.....................................................................................")
   
    });
}
```

```
$ rustfmt +nightly -v --check src/main.rs 
Formatting /home/reinis/code/Personal/rust_playground/src/main.rs
Diff in /home/reinis/code/Personal/rust_playground/src/main.rs at line 4:
    ⏎
     });⏎
 }⏎
-⏎
 ⏎
Spent 0.000 secs in the parsing phase, and 0.000 secs in the formatting phase
error[internal]: left behind trailing whitespace
 --> /home/reinis/code/Personal/rust_playground/src/main.rs:4:4:1
  |
4 |    
  | ^^^
  |

warning: rustfmt has failed to format. See previous 1 errors.
```
(Same thing happens on latest nightly and stable)

**Comment by rMazeiks** [comment]
Thanks for the quick reply!

I can confirm that the issue goes away when replacing the method call with a standalone function call.

Though I'd like to note that the linked issue is subtly different in that it doesn't produce an internal error.

I'm happy to keep this closed as a duplicate of course, if the underlying cause is the same.

**Comment by ytmimi** [comment]
You've very welcome!

Both issues stem from the fact that rustfmt is unable to format the chained method call, but the internal error that you're seeing is an additional side-effect of the trailing whitespace in the code snippet you listed above.

To add a little more detail, when rustfmt fails to format any AST node it simply leaves that node unchanged, and in this case that also means leaving the trailing whitespace as it was in the source text. The internal error that rustfmt emits is a last ditch effort to alert the developer that there is trailing whitespace that requires manual intervention to remove.
