### ISSUE TITLE
Reorder constant items and static items from the current location to the beginning of the current scope

### ISSUE THREAD

**Issue by linqingyao** [rust-lang/rustfmt#5603]
# Format constant items and static items from the current location to the beginning of the current scope

## Why is it implemented:

**In Rust, Constant items and Static items are implicitly moved to the beginning of the current scope**, as in the following [example:](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=764e2cd980c55c4b8dccaeb3b3b929d3)

```rust
const A: usize = 10;

fn main() {
    // It is implicitly assumed that the constant is promoted to the beginning of the current scope:
    // const A: usize = 120;

    fn scope() {
        println!("{}", A);
    };
    scope(); // -> 120
    const A: usize = 120;
    scope(); // -> 120
}
```
The same goes for Static items.

### Before formatting 
```rust
fn main() {
    println!("{}", A);
    const A: usize = 10;
}
```
After passing the cargo fmt command.

### After formatting 
```rust
fn main() {
    const A: usize = 10;
    println!("{}", A);
}
```

## Note
**When items are in the global scope, there is no need to change their location.**

example:
```rust
// items: struct item、enum item e.g
// ...

static A: usize = 10;

fn main() {
    // Some code
    // ...
}
```
Nothing changes after passing the cargo fmt command.

**Comment by ytmimi** [comment]
Thanks for sharing your idea!

Reordering items is tricker than it might first appear. Even for the few things rustfmt currently support e.g. reordering imports, there are several bugs. Given the backlog and bandwidth of the team this isn't a feature request the rustfmt team will likely work on, but we'll certainly consider a PR if there's anyone sufficiently motivated to work on this.

I'll leave this open for now in case anyone wants to take a crack at adding this feature.

**Comment by calebcartwright** [comment]
Reordering nested trait or impl items is one thing, but we're not going to do reordering within an arbitrary item that could be intermingled with expressions, statements, etc. 

Closing this accordingly as too far outside rustfmt's core scope

**Comment by linqingyao** [comment]
Ok, thank you very much for your answer. I wish you a happy life, Rust is getting better and better.😊
