### ISSUE TITLE
Inconsistent formatting in destructuring nested structs

### ISSUE THREAD

**Issue by SUPERCILEX** [rust-lang/rustfmt#5610]
Here's how creation gets formatted:

```rust
Outer {
    ...
    inner: Inner {
        ...
    },
}
```

But here's what happens when you destructure in a method param:

```rust
fn foo(
    Outer {
        ...
        inner:
            Inner {
                ...
            },
    }: &Outer,
) {
```

Here's what it should look like to be consistent and not use excessive indentation:

```rust
fn foo(
    Outer {
        ...
        inner: Inner {
            ...
        },
    }: &Outer,
) {
```

**Comment by ytmimi** [comment]
Thanks for reaching out.

I think this may be related to #5117, possibly a duplicate as they both deal with struct literals vs struct patterns.

**Comment by SUPERCILEX** [comment]
Ah yep, I think that's the same issue.
