### ISSUE TITLE
Pass flags to cargo metadata

### ISSUE THREAD

**Issue by IsaccBarker** [rust-lang/rustfmt#5628]
Unsure if this is the correct place to post this, but here we go. I have a crate that requires the `bindeps` Cargo feature to be enabled via `-Zbindeps` on the command line. Looking through the `cargo fmt` help printout, it doesn't look there is any way to pass flags to cargo metadata. This normally wouldn't be an issue, except there is no way to enable the `bindeps` feature from inside `Cargo.toml`.

When running `cargo fmt`, I get this message.

```
`cargo metadata` exited with an error: error: failed to load manifest for workspace member `/Users/<username>/Developer/<crate>`

Caused by:
  failed to parse manifest at `/Users/<username>/Developer/<crate>/Cargo.toml`

Caused by:
  `artifact = …` requires `-Z bindeps` (<crate>)
```

Is there a workaround for this?

**Comment by ytmimi** [comment]
@IsaccBarker thanks for reaching out. I believe we've run into this before. Does the advice from https://github.com/rust-lang/rustfmt/issues/5332#issuecomment-1119990254 help?

**Comment by IsaccBarker** [comment]
Woops! Thank you! Sorry, I knew you could set it globally, but I never knew that `.cargo/config.toml` existed. The more you learn, haha!
