### ISSUE TITLE
if-else condition trailing comments

### ISSUE THREAD

**Issue by estk** [rust-lang/rustfmt#5651]
Hi!

I am curious why trailing comments on if-else conditions are not allowed with `rustfmt`.
Fwiw I searched the manual and gh issues to no avail.

As an example, the following code is reformatted.
```rust
if days_expired < 0 {           // Has yet to expire.
  Status::Valid
} else if grace_days_left > 0 { // In grace period.
  Status::Grace
} else {                        // Expired and outside of grace period.
  Status::Expired
}
```

```rust
if days_expired < 0 {                
  // has yet to expire
  Status::Valid
} else if grace_days_left > 0 {
  // in grace period
  Status::Grace
} else {                                      
  // Expired and outside of grace period
  Status::Expired
}
```

**Comment by ytmimi** [comment]
By trailing comments do you mean comments after the opening brace `{` like you've demonstrated in your example?

**Comment by ytmimi** [comment]
Thanks for filing the issue! I did some digging and it turns out this is a duplicate of #3255

**Comment by estk** [comment]
Amazing, thanks so much!
