### ISSUE TITLE
Option to configure how many lines down the @generated tag can be for format_generated_files?

### ISSUE THREAD

**Issue by captbaritone** [rust-lang/rustfmt#5658]
In [Relay](https://github.com/facebook/relay) we have a large number of generated files which are required by our business to being with a specific copyright header that is slightly more than five lines. This means we can't take advantage of the format_generated_files feature. 

Example file: https://github.com/facebook/relay/blob/603bb4bc2927bda8b7f0dac1d86cbc5ecbf50202/compiler/crates/relay-lsp/tests/hover_test.rs

Would it be possible to make the 5 lines limit configurable?

**Comment by ytmimi** [comment]
Thanks for reaching out. Seems like a reasonable enough request, and this should be a simple change.


* [create the new config option](https://github.com/rust-lang/rustfmt/blob/master/Contributing.md#configuration) that defaults to 5. **Note** all new configs are marked as unstable.
* Update the definition of [`is_generated_file`](https://github.com/rust-lang/rustfmt/blob/ee2bed96d60fd7e46b1fb868f6a8f27e3a8058d0/src/formatting/generated.rs#L2)
* [Update the call site to pass in the new config](https://github.com/rust-lang/rustfmt/blob/ee2bed96d60fd7e46b1fb868f6a8f27e3a8058d0/src/formatting.rs#L85-L87)

**Comment by IVIURRAY** [comment]
It looks like this can be closed as https://github.com/rust-lang/rustfmt/pull/5918 solves this?

**Comment by ytmimi** [comment]
@IVIURRAY the PR that you're referring to was closed but never merged. This issue should stay open.

**Comment by IVIURRAY** [comment]
@ytmimi whoops, thanks! - I've opened an MR to address this #5993 :)
