### ISSUE TITLE
Rustfmt fails to format large functions with lots of nesting and comments

### ISSUE THREAD

**Issue by yanchith** [rust-lang/rustfmt#5661]
I have a Rust source file with a couple of longer (~1000 lines) functions with deep nesting, and many comments.

I sometimes notice rustfmt give up and not modify some parts of the code, even when it's visually clear they should be modified (e.g. reindented). `rustfmt --check` doesn't report any errors.

Not sure how to repro publicly, because I can't share the code this happens on, but if I ever see it happen on an open codebase, I'll share.

Also let me know if you'd accept a patch fixing this, maybe I can debug in my spare time.

version: rustfmt 1.5.1-nightly (8a97b481 2022-12-22)
config:
```
group_imports = "StdExternalCrate"
hex_literal_case = "Lower"
imports_layout = "HorizontalVertical"
merge_derives = false
newline_style = "Unix"
use_field_init_shorthand = true
```

**Comment by ytmimi** [comment]
@yanchith Thanks for reaching out, but unless you can provide a code snippet to work off of then this isn't actionable. Additionally, what version of rustfmt are you ussing and are you using any non-default configuration options?

**Comment by yanchith** [comment]
Thanks. Yeah, I know this isn't great. I opened this hoping someone (possibly future me) will provide a repro case.

**Comment by ytmimi** [comment]
@yanchith can you take a section of code that isn't formatted and create a dummy example from it?

Given that this is deeply nested you're most likely running into issues with the `max_width`. You can try bumping the `max_width` to some sufficiently large number and then running rustfmt again. rustfmt is constrained to format your code within the `max_width`, and if it fails to do so then it will prevent formatting a given AST node.

If I had to guess, your issue is likely a duplicate of #3863, and if it's not related then the deeply nested nature of your program is the issue. Without seeing some code that reproduces the issue there isn't more I can do to help.

**Comment by yanchith** [comment]
Serendipity! It just happened, in a section of code I managed to isolate. Pasting the following to a file and using the config above should not change a single line, even though it is clearly misformatted.

I also tried `max_width` up to 1000, and it didn't fix the issue.

```rust
fn rewind_level(level: &mut Level) {
    level.move_queue.clear();
    level.move_queue_speed_factor = 1.0;

    if have_player_caused_transaction(&level.transactions) {
        if let Some(snapshot) = level.history.pop_snapshot() {
            log::debug!("Rewinding one snapshot back with {} entities", snapshot.len(),);
            level.entities.clear();

            let mut manual = level.entities.manual_mode();
            for entity in snapshot {
                manual.insert(entity.id, entity);
            }
            manual.commit();
        } else {
            log::error!("Expected to find one snapshot to rewind, but found none");
        }
    } else {
        let mut success = false;
        if let Some(_) = level.history.pop_snapshot() {
            success = true;
        } else {
            log::error!("Expected to find two snapshots to rewind, but found none");
        }

        if success && let Some(snapshot) = level.history.pop_snapshot() {
                        log::debug!(
                            "Rewinding two snapshots back with {} entities",
                            snapshot.len(),
                        );

                        level.entities.clear();

                        let mut manual = level.entities.manual_mode();
                        for entity in snapshot {
                            manual.insert(entity.id, entity);
                        }
                        manual.commit();
                    } else {
                        log::error!("Expected to find two snapshots to rewind, but found just one");
                    }
    }
}
```

**Comment by ytmimi** [comment]
Thanks for adding the code snippet. Yes, this issue is caused because rustfmt doesn't currently format `let-chains`. You can follow the tracking issue https://github.com/rust-lang/rustfmt/issues/5177 to be notified when support for the feature is added.
