### ISSUE TITLE
Build fails: error[E0463]: can't find crate for `rustc_ast`

### ISSUE THREAD

**Issue by yurivict** [rust-lang/rustfmt#5665]
```
error[E0463]: can't find crate for `rustc_ast`
  --> src/lib.rs:16:1
   |
16 | extern crate rustc_ast;
   | ^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
   |
   = help: maybe you need to install the missing components with: `rustup component add rust-src rustc-dev llvm-tools-preview`

error[E0463]: can't find crate for `rustc_ast_pretty`
  --> src/lib.rs:17:1
   |
17 | extern crate rustc_ast_pretty;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
   |
   = help: maybe you need to install the missing components with: `rustup component add rust-src rustc-dev llvm-tools-preview`

error[E0463]: can't find crate for `rustc_builtin_macros`
  --> src/lib.rs:18:1
   |
18 | extern crate rustc_builtin_macros;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
   |
   = help: maybe you need to install the missing components with: `rustup component add rust-src rustc-dev llvm-tools-preview`

```

Cargo.lock doesn't have these crates.

Version: 1.5.1
rust-1.66.1
FreeBSD 13.1

**Comment by calebcartwright** [comment]
Sorry our docs are a bit out of whack at the moment, but the compiler's help message has the key:

> = help: maybe you need to install the missing components with: `rustup component add rust-src rustc-dev llvm-tools-preview`

Like most of the various official Rust tools, you'll have to use a nightly toolchain to build from source with the requisite components. Also note that this needs to be a _compatible_ nightly and not _any_ nightly.

You can find those requirements enumerated in the toolchain file at whatever version of source you're trying to build from, e.g. latest on master would be:

https://github.com/rust-lang/rustfmt/blob/ee2bed96d60fd7e46b1fb868f6a8f27e3a8058d0/rust-toolchain#L1-L3

So grab that nightly (or one near it), add the `rustc-dev` component, and then try compiling again
