### ISSUE TITLE
rustfmt adding unnecessary parenthesis and commas.

### ISSUE THREAD

**Issue by apoorv569** [rust-lang/rustfmt#5672]
When I am run `cargo fmt` or `rustfmt` it adds unnecessary parenthesis and commas randomly somewhere.

Here is the output of `rustfmt --check` ran on a file,
```diff
❯ rustfmt --check src/sample_hive/gui/panels/side_panel.rs
Diff in /home/apoorv/repos/sample-hive-rs/src/sample_hive/gui/panels/side_panel.rs at line 67:
                 if path.is_dir() {
                     let header = egui::CollapsingHeader::new(format!(
                         "📁 {}",
-                       entry.file_name().to_string_lossy())
-                    )
+                        entry.file_name().to_string_lossy()
+                    ))
                     .default_open(false)
                     .show(ui, |ui| {
                         self.nested_collapsible_directory_structure(ui, &path);
Diff in /home/apoorv/repos/sample-hive-rs/src/sample_hive/gui/panels/side_panel.rs at line 77:
                     if ui
                         .selectable_label(
                             false,
-                            format!("📄 {}", &entry.file_name().to_string_lossy())
+                            format!("📄 {}", &entry.file_name().to_string_lossy()),
                         )
                         .drag_started()
                     {
```
as you can see it is trying to add extra parenthesis in the first section and a comma in the second section.

I am not sure but I think this mostly happens around lines with `unicode` or `emoji`  in the text or something as I did notice this in another place where I had `emoji`.

Also I only started noticing this issue today only, it was fine yesterday.

**Comment by calebcartwright** [comment]
Thanks for reaching out but I'm going to close.

In the first case, rustfmt isn't adding a parenthesis, but is simply _moving_ the closing paren from the end of one line (after the `to_string_lossy` call) to the next.

In the second case, rustfmt is adding a trailing comma

Both of these are the expected and correct behavior as dictated by the [Rust Style Guide](https://github.com/rust-lang/rust/tree/master/src/doc/style-guide/src) which rustfmt implements.

You can utilize the [trailing_comma](https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=#trailing_comma) config option if you'd like to modify the behavior of the latter; the former is not controllable.

> I am not sure but I think this mostly happens around lines with unicode or emoji in the text or something as I did notice this in another place where I had emoji.
>
> Also I only started noticing this issue today only, it was fine yesterday.

No, any string contents or unicode vs ascii aspects are unrelated and orthogonal to the behavior. This is long standing rustfmt behavior, and there's been no changes to rustfmt for quite some time so I can't speak to why you've not seen this before. It's possible the associated files weren't being formatted, or they were nested within some module/block/etc. that rustfmt wasn't touching for other reasons (e.g. not-yet-supported syntax like `let else`, bug in comment handling, etc.) but that some recent code changes have resulted in rustfmt finally getting to these portions of your code

**Comment by apoorv569** [comment]
> Thanks for reaching out but I'm going to close.
> 
> In the first case, rustfmt isn't adding a parenthesis, but is simply _moving_ the closing paren from the end of one line (after the `to_string_lossy` call) to the next.
> 
> In the second case, rustfmt is adding a trailing comma
> 
> Both of these are the expected and correct behavior as dictated by the [Rust Style Guide](https://github.com/rust-lang/rust/tree/master/src/doc/style-guide/src) which rustfmt implements.
> 
> You can utilize the [trailing_comma](https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=#trailing_comma) config option if you'd like to modify the behavior of the latter; the former is not controllable.
> 
> > I am not sure but I think this mostly happens around lines with unicode or emoji in the text or something as I did notice this in another place where I had emoji.
> > Also I only started noticing this issue today only, it was fine yesterday.
> 
> No, any string contents or unicode vs ascii aspects are unrelated and orthogonal to the behavior. This is long standing rustfmt behavior, and there's been no changes to rustfmt for quite some time so I can't speak to why you've not seen this before. It's possible the associated files weren't being formatted, or they were nested within some module/block/etc. that rustfmt wasn't touching for other reasons (e.g. not-yet-supported syntax like `let else`, bug in comment handling, etc.) but that some recent code changes have resulted in rustfmt finally getting to these portions of your code

I see.

But what about this,
https://user-images.githubusercontent.com/53279454/214372109-6806518a-cf2c-4604-8f5a-0769fa80d7fe.mp4

**Comment by calebcartwright** [comment]
> But what about this,

You are attempting to make an invalid comparison between two things that are very differently syntactically. A trailing comma after the last argument in a call is optional, but valid, Rust syntax. A comma token in some other arbitrary position (i.e. after the closing paren of a call and before the statement ending semicolon) is a completely different story, and is not valid syntactically.

**Comment by apoorv569** [comment]
> > But what about this,
> 
> You are attempting to make an invalid comparison between two things that are very differently syntactically. A trailing comma after the last argument in a call is optional, but valid, Rust syntax. A comma token in some other arbitrary position (i.e. after the closing paren of a call and before the statement ending semicolon) is a completely different story, and is not valid syntactically.

This compiles fine,
```rust
                ui.horizontal(|ui| {
                    ui.selectable_value(
                        &mut self.side_panel_section,
                        SidePanelSection::Browser,
                        "💻 Browser");
                    ui.selectable_value(
                        &mut self.side_panel_section,
                        SidePanelSection::Favorites,
                        "🖤 Favorites");
                });
```

But `rustfmt` does this to the section,
```rust
                ui.horizontal(|ui| {
                    ui.selectable_value(
                        &mut self.side_panel_section,
                        SidePanelSection::Browser,
                        "💻 Browser"),
                    ;
                    ui.selectable_value(
                        &mut self.side_panel_section,
                        SidePanelSection::Favorites,
                        "🖤 Favorites"),
                    ;
                });
```

and this doesn't compile.

**Comment by calebcartwright** [comment]
Sorry but I don't follow what you're saying. You've been bouncing around between a few items, as well as inline snippets and videos on a thread that's gotten long.

It sounds like you are now claiming that there is a case where rustfmt is turning valid input into an invalid output. While that would indeed be a problem we'd need to address, there's a lack of clarity around the specifics.

If that's indeed what you're claiming, then I'll need you to provide a minimal and complete snippet (not a diff nor a screen video of an editor/IDE) that can be used to reproduce the claimed issue by running rustfmt directly against the snippet. If you're able to construct such a snippet then please feel free to post a comment here or open a new issue and we'll be happy to take a look.

Otherwise in the absence of such a reproducible example I don't think there's much more to be said on this thread.

**Comment by apoorv569** [comment]
> Sorry but I don't follow what you're saying. You've been bouncing around between a few items, as well as inline snippets and videos on a thread that's gotten long.
> 
> It sounds like you are now claiming that there is a case where rustfmt is turning valid input into an invalid output. While that would indeed be a problem we'd need to address, there's a lack of clarity around the specifics.
> 
> If that's indeed what you're claiming, then I'll need you to provide a minimal and complete snippet (not a diff nor a screen video of an editor/IDE) that can be used to reproduce the claimed issue by running rustfmt directly against the snippet. If you're able to construct such a snippet then please feel free to post a comment here or open a new issue and we'll be happy to take a look.
> 
> Otherwise in the absence of such a reproducible example I don't think there's much more to be said on this thread.

I have been saying the same thing from start, that `rustfmt` was adding unnecessary stuff, it is what it did in my last response before this as well. Its just you told me for the problem I mentioned that, that was valid syntax.

Isn't my last response before this is a minimal snippet enough?
