### ISSUE TITLE
rust fmt fails to format specific files.

### ISSUE THREAD

**Issue by dogunbound** [rust-lang/rustfmt#5688]
https://user-images.githubusercontent.com/64436119/217716036-f3b2366f-80ad-4e5f-b7ee-1b98e697c31f.mp4

here is the repo:
https://github.com/dogunbound/PACRB

make sure you are on commit as this a rapidly changing repository: 0c5c7ec8717a930b5c0e021bedd0898f023d3f26

the problem files are `src/hsv_selector/hsv_selector_content.rs` and `src/config_selector/config_selector.rs`

If you put random whitespace in either of those files and try formatting or calling cargo fmt, cargo fmt will fail to run.

**Comment by ytmimi** [comment]
@dogunbound thanks for reaching out and including the video. Currently rustfmt doens't support formatting `let-else` statements, but it's actively being worked on! If you'd like you can follow the issue for let-else #4914

**Comment by dogunbound** [comment]
@ytmimi 

Thanks for letting me know. Hope progress continues smoothly.
