### ISSUE TITLE
rustfmt always insert a string at the start of file using neovim on arch linux

### ISSUE THREAD

**Issue by fristzzz** [rust-lang/rustfmt#5698]
I'm using same nvim config file on both my windows and arch linux device. It works fine on windows but would insert a string(I don't know what it means) at the start of file after formatting.

![2023-02-23_18-47](https://user-images.githubusercontent.com/91342166/220887054-13868390-efd1-4154-9f61-325b49dd4b84.png)

**Comment by fristzzz** [comment]
I'm using [formatter](https://github.com/mhartington/formatter.nvim).
After removing this tool and just use cargo fmt in command line, it works fine. Strange.

**Comment by ytmimi** [comment]
@fristzzz given that running `cargo fmt` directly didn't produce the error, I'm assuming this is an issue with [formatter](https://github.com/mhartington/formatter.nvim), and you should probably file an issue with that project.
