### ISSUE TITLE
Space before ?

### ISSUE THREAD

**Issue by burdges** [rust-lang/rustfmt#5719]
It appears rust fmt want `f()?;` instead of `f() ?;` but why?  Or what options control this?  There maybe situations where the `f()?;` meshes better with other concerns, but but overall `f() ?;` should be preferred, as it makes the error path slightly more visible.

**Comment by ytmimi** [comment]
Thanks for reaching out, but going to close this as a duplicate of #5595. There currently is no option to add a space before the try operator.
