### ISSUE TITLE
`rustfmt_skip` can't properly prevent `wrap_comments` from formatting a specific comment

### ISSUE THREAD

**Issue by e00E** [rust-lang/rustfmt#5725]
With `wrap_comments` rustfmt reformats comments. I have a comment that I do not want to be reformatted.

```rust
code_before_comment();
// comment that contains ascii art which would break with reformatting
code_after_comment();
```

The only way I have found to skip formatting of this comment is by putting `#[rustfmt::skip]` in front of it like so:

```rust
code_before_comment();
#[rustfmt::skip]
// comment that contains ascii art which would break with reformatting
code_after_comment();
```

This does not work as expected because it also applies to `code_after_comment`. For example, if I add extraneous space to this line like this:

```rust
code_after_comment()       ;
```

The space is usually removed by rustfmt but not when skipping formatting on the comment.

**Comment by ytmimi** [comment]
@e00E Thanks for reaching out. If I understand correctly you're using `wrap-comments=true` and the ascii art is getting wrapped?

The issues around using `#[rustfmt::skip]` to prevent comment formatting have been brought up before. For example #5440. This comment gives some more background and describes one solution the team would consider https://github.com/rust-lang/rustfmt/issues/5440#issuecomment-1183280504

**Comment by calebcartwright** [comment]
My preference would be that we actually close this one and reopen #5440, or perhaps open a net-new issue, to discuss mechanisms through which comments could be skipped; this one is too indexed on the skip attribute to be a good candidate for ideation around comment-specific mechanisms and associated search/discoverability in the issue tracker

**Comment by ytmimi** [comment]
Closing in favor of #5727
