### ISSUE TITLE
discussion: drop support for customization

### ISSUE THREAD

**Issue by mcandre** [rust-lang/rustfmt#5736]
One of the benefits of a modern code formatter is establishing a language-wide consensus on code formatting. This reduces friction between developers and makes it easier to work across multiple Rust projects. As Rob Pike says of gofmt, it's *nobody's favorite*. But the fact that we have a standard, carries a lot of practical value.

Should rustfmt allow customization? I could see a case for customization in terms of experimenting with future rustfmt default styling. But I don't want to have to learn another rustfmt config, and another, and another, when hopping between projects, unless the differences are strictly due to adopting newer rustfmt releases. What if we simply dropped support for customization? Anyone who wishes to depart from the norm is free to fork rustfmt, or otherwise use their own formatter implementation.

**Comment by calebcartwright** [comment]
Thanks for reaching out but I'm going to close. Removing support for configuration at this point is an absolute non-starter, and it's not going to happen. I do not think there's any value to be had in any debate on the subject, but I will provide a few responses.

> As Rob Pike says of gofmt, it's nobody's favorite. But the fact that we have a standard, carries a lot of practical value.

I'm familiar with the quote, but this conflates the notion of having a standard or default, which Rust [does](https://github.com/rust-lang/rust/tree/master/src/doc/style-guide/src), with whether individual users/projects have the ability to deviate from the standard. It was decided long, long ago that the Rust ecosystem would strongly encourage following the default, but also that the ability to configure would be provided, particularly as an acknowledgement of perpetually contentious topics like tabs vs. spaces. Fundamentally, the ship has already sailed on this, and you'd need a time machine to go back to try to prevent configuration from coming into existence in the first place.

> But I don't want to have to learn another rustfmt config, and another, and another, when hopping between projects, unless the differences are strictly due to adopting newer rustfmt releases

I don't think that "learning" whether a project uses any-default config options nor those config values is ever really necessary; all you need to do is run the formatter, and the way you run the formatter doesn't change from one project to the next (perhaps except in cases where a project opts to introduce a task runner-like tool). This is also part of the point. The project owners/maintainers have the ability to deviate from the standard style by setting what they want in the project config which automatically cascades to everyone. It's not something contributors ever really need to consider or digest unless they want to try to convince the owners/maintainers to style the project differently.

> Anyone who wishes to depart from the norm is free to fork rustfmt, or otherwise use their own formatter implementation.

Again at this point this possibility is both true and inherently self-defeating in my opinion. Given the realities of the present, there are far too many users and far too many projects which would be sufficiently motivated to take, or at least support this route. The practically inevitable outcome of this would be the continued existence of project-specific configuration (the same scenario your seek to avoid as a motivation for dropping this existing feature) along with the bifurcation of widely used formatters and respective features.
