### ISSUE TITLE
Build fails: error[E0432]: unresolved import `rustc_ast::tokenstream::Cursor`

### ISSUE THREAD

**Issue by yurivict** [rust-lang/rustfmt#5748]
```
error[E0432]: unresolved import `rustc_ast::tokenstream::Cursor`
  --> src/macros.rs:16:30
   |
16 | use rustc_ast::tokenstream::{Cursor, TokenStream, TokenTree};
   |                              ^^^^^^ no `Cursor` in `tokenstream`
   |
   = help: consider importing one of these items instead:
           crate::io::Cursor
           std::collections::linked_list::Cursor
           std::io::Cursor

```

The version 1.5.2 was released in 20230124, and rust nightly is from the later date 20230208, which makes it unlikely to depend on nightly version mismatch.

rustfmt releases should be buildable with rust releases, but there are errors too.

Version: 1.5.2
rust-nightly-1.69.0.20230208

**Comment by ytmimi** [comment]
In order to build rustfmt from source you need to use the nightly compiler version listed in our [rust-toolchain](https://github.com/rust-lang/rustfmt/blob/master/rust-toolchain) file. Additionally, you'll need to have the `llvm-tools` and  `rustc-dev` component which you can get from rustup.
