### ISSUE TITLE
Strange Line Break in variable declaration

### ISSUE THREAD

**Issue by REN-aissance** [rust-lang/rustfmt#5754]
Hello, I am using rustfmt and noticed this bizarre newline behavior. Is this expected behavior? Is it possible for me to override this in settings? I would expect this to instead break at "expects" not immediately after the equals sign

![image](https://user-images.githubusercontent.com/42751478/232177814-7efefcc8-4cb4-4f45-8d1e-203d322e4cbb.png)

**Comment by calebcartwright** [comment]
Yes this is expected, and yes it is correct (as per style guide prescriptions). No there's currently no option that will allow you to get the formatting you prefer, though one could eventually come to fruition (refs #4886)
