### ISSUE TITLE
File-lines seems to require stdin

### ISSUE THREAD

**Issue by barafael** [rust-lang/rustfmt#5762]
I ran `rustfmt` like this:

```
rustfmt --unstable-features ==file-lines '[{"file":"presentation.md","range":[31,33]}]'
```

This puts `rustfmt` in a prompt where it awaits terminal input. When I hit `CTRL+D` to terminate, I get:

```
Warning: Extra file listed in file_lines option '/path/to/example-project/presentation.md'
```

This also happens when the file in question ends with `.rs`.

This behaviour is similar to passing `"stdin"` as file.

I am wondering if I am using this incorrectly or what is going on here?

```
$> rustfmt --version
rustfmt 1.5.2-nightly (473f916 2023-05-03)
```

**Comment by ytmimi** [comment]
That being said, when you don't pass a file to rustfmt like `rustfmt /path/to/file.rs` rustfmt expects that the input you want to format will come from `stdin`. You can see this [comment](https://github.com/rust-lang/rustfmt/issues/5750#issuecomment-1505628969) and the following discussion for more details.
