### ISSUE TITLE
for consistency, stop lines from automatically collapsing even if such a joined line would not exceed max_width

### ISSUE THREAD

**Issue by effinsky** [rust-lang/rustfmt#5765]
For consistent formatting across multiple like statements, declarations, assignments etc, make it possible for separate lines to not unfold into a single line even if that line would be < max_width. This is inspired by own felt need/preference, the black Python formatter for Python, and the Zig formatter. 

In both `black` for Python and `zigfmt` if you put a trailing comma on a list of params, for instance, that'll be a cue for the formatter to not collapse multiple lines into a single line even if they could be since, say, they comprise a single statement and are below max line length.

Wish we could have a thing like that in `rustfmt`. First and foremost this would help readability in cases where you have a series of statements where one does not fit a single line and therefore will be broken down into multiple lines, but the rest do and therefore will not be broken down. For ease of visual pattern recognition I'd like to allow for breaking them all down into the same formatting scheme across multiple lines. 

Currently `rustfmt` formats this and like examples:
<img width="910" alt="Screenshot 2023-05-07 at 21 11 19" src="https://user-images.githubusercontent.com/54535543/236697848-80ab524f-e982-42a4-93cf-5c332786c927.png">

I'd like to force line breaking into this much nicer formatting without sprinkling fmt skip and such all over the place:
<img width="822" alt="Screenshot 2023-05-07 at 21 12 25" src="https://user-images.githubusercontent.com/54535543/236697906-da22f928-5cf9-463e-9f36-d611e90a0a80.png">

In Python's black... Unformatted:
<img width="1090" alt="Screenshot 2023-05-07 at 21 17 01" src="https://user-images.githubusercontent.com/54535543/236698117-6909a249-f2c7-48e2-9dd3-238590ed1e2e.png">

If I run black, it behaves similar to how `rustfmt` would, producing:
<img width="891" alt="Screenshot 2023-05-07 at 21 18 09" src="https://user-images.githubusercontent.com/54535543/236698159-4448e08e-554d-4ecb-a9e7-fca65f79fc38.png">

But if I add trailing commas manually here and here:
<img width="891" alt="Screenshot 2023-05-07 at 21 18 09" src="https://user-images.githubusercontent.com/54535543/236698269-06210283-c8ea-47b0-8a7d-216d5b63414c.png">

Then I get the nice result of:
<img width="766" alt="Screenshot 2023-05-07 at 21 21 32" src="https://user-images.githubusercontent.com/54535543/236698313-dde0a579-e5da-42e9-8bc9-451a282d9523.png">

What do you think?

**Comment by ytmimi** [comment]
@effinsky Thanks for reaching out. Not sure what version of rustfmt you're using, but you can try to set `short_array_element_width_threshold` to a sufficiently small value and that should force rustfmt to format the lists vertically.

Also want to note that something similar was brought up in https://github.com/rust-lang/rustfmt/issues/5190.

Hope that helps, but I'm going to close this as we don't usually want the existence or lack of a comma in the input to dictate how we layout lists.

**Comment by calebcartwright** [comment]
Thank you for reaching out, and taking the time to articulate your suggestion so thoroughly!

To add on to what Yacin said, this is not something we'd be willing to incorporate for a few reasons, the main one being that this would be a source of idempotence issues due to the presence of existing features that manipulate trailing commas.

Your best bet to get your preferred formatting style is likely going to be to utilize a combination of the [short_array_element_width_threshold](https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=#short_array_element_width_threshold) and line comments where necessary to force a vertical layout

**Comment by effinsky** [comment]
thanks, and fyi `rustfmt` 1.5.2-nightly

**Comment by effinsky** [comment]
how about adding a setting to preserve shorter lines even if more than a single statement or expression would otherwise fit on a single line? so no trailing comma manipulation, but a general setting or Preserve? or something like "max_line_length_within_limit" with a true, false, so that when I say false to that, I'll get to keep my shorter lines for alignment, readability etc? 

I mean quite clearly at present we do lose some readability sometimes where we have subsequent analogous lines formatted differently. I'd be cool to be able to have that consistent formatting line to line, as in the examples above.
