### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by jthulhu** [rust-lang/rustfmt#5771]
When running `cargo fmt`, I got the following error.
```rust
error[internal]: left behind trailing whitespace
   --> /.../earley.rs:585:585:15
    |
585 | 			    .err();
    |            ^
    |

warning: rustfmt has failed to format. See previous 1 errors.
```
Unfortunately, after formatting within my editor, I could not reproduce the error anymore, so I'm not too sure what more information I can provide.
```bash
$ rustfmt --version
rustfmt 1.5.2-nightly (696aaad 2023-04-09)
$ cargo --version
cargo 1.70.0-nightly (0e474cfd7 2023-03-31)
$
```

**Comment by ytmimi** [comment]
@jthulhu Thanks for reaching out. Could you please provide a minimal code snippet that reproduces the issue. Just from what you've posted I have a hunch you're dealing with a similar issue as #5769 and other linked issues.
