### ISSUE TITLE
Command changes EOL format in VSCode

### ISSUE THREAD

**Issue by Ewan88** [rust-lang/rustfmt#5774]
When running `cargo fmt` the command will change the EOL format from CRLF `\r\n` to LF `\n`

This happens in VSCode regardless of user or workspace settings. The user then has to manually change the EOL for each file the command touches.

If the user doesn't do this then they are warned by git `LF will be replaced by CRLF the next time Git touches it` each time they want to add format changes to their repo.

Edit: I haven't tested this with other editors.

**Comment by ytmimi** [comment]
@Ewan88 thanks for reaching out. Have you tried setting [newline_style](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#newline_style)? The setting is `Auto` by default.

Is it possible that the file you were editing had mixed line endings? If so, `Auto` will choose the first line ending that it finds and that might explain why `\r\n` were converted to `\n`? `newline_style=Native` or `newline_style=Windows` might be more appropriate for your use case.

**Comment by Ewan88** [comment]
Thanks @ytmimi manually setting the config seems to have fixed the issue.
