### ISSUE TITLE
Indentation in macro is increased in each run (non-idempotent)

### ISSUE THREAD

**Issue by JanBeh** [rust-lang/rustfmt#5778]
The following code is given:

```rust
macro_rules! m {
    ($x:tt) => {
        type T = $x
        where
            A: B;
    };
}
```

Running `rustfmt` results in:

```rust
macro_rules! m {
    ($x:tt) => {
        type T = $x
                where
                    A: B;
    };
}
```

Running it again:

```rust
macro_rules! m {
    ($x:tt) => {
        type T = $x
                        where
                            A: B;
    };
}
```

And so on.

The following smaller example is idempotent, however:

```diff
 macro_rules! m {
     ($x:tt) => {
-        type T = $x
+        type $x
         where
             A: B;
     };
```

I'm using:

```
rustfmt 1.5.2-nightly (b2b34bd8 2023-06-06)
```

The above example is a minimal example to reproduce the problem. The full code I used can be [found here](https://github.com/JanBeh/fmap/blob/6e56d7958a209f57dce885a5ea2a764feadeb034/src/impls/boxed_fn.rs).

**Comment by ytmimi** [comment]
@JanBeh thanks for reaching out!

This is related to rustfmt's lack of support for [associated types](https://doc.rust-lang.org/reference/items/associated-items.html#associated-types) using the new recommend style where the `where clause` come after the type name.

For example:

```rust
type Assoc<Params> = Type where WhereBounds;
type Assoc<Params> where WhereBounds = Type; // deprecated, prefer the form above
```

This is related to https://github.com/rust-lang/rustfmt/issues/5580

As a workaround you might consider using the deprecated style to avoid this issue (which rustfmt handles just fine):

```rust
macro_rules! m {
    ($x:tt) => {
        // FIXME: waiting till https://github.com/rust-lang/rustfmt/issues/5778 is resolved.
        type T
        where
            A: B,
        = $x;
    };
}
```

Alternatively, you could use the `#[rustfmt::skip]` attribute:

```rust
#[rustfmt::skip]
macro_rules! m {
    ($x:tt) => {
        type T = $x
        where
            A: B;
    };
}
```

**Comment by JanBeh** [comment]
Thank you very much for the references and the hint to use the old-style syntax. I figured there were somes issues with non-idempotence, but I wasn't sure which of those (if any) was covered by my case.
