### ISSUE TITLE
Method call on `0.` float literals formats to incorrect code

### ISSUE THREAD

**Issue by fee1-dead** [rust-lang/rustfmt#5791]
```rust
pub fn main() {
    0. .to_string();
}
```
formats currently to:

```rust
pub fn main() {
    0..to_string();
}
```

Ideally this should be reformatted to be:

```rust
pub fn main() {
    (0.).to_string();
}
```

so as to avoid confusion.

**Comment by ytmimi** [comment]
Does the following parse as a float literal and a method call? or a range?

```rust
pub fn main() {
    0..to_string();
}
```

If it's a range then it's definitely a bug.

**Comment by fee1-dead** [comment]
A range.

**Comment by ytmimi** [comment]
Got it! Thanks for the report!
