### ISSUE TITLE
Support --assume-filename to resolve .rustfmt.toml for stdin files

### ISSUE THREAD

**Issue by afq984** [rust-lang/rustfmt#5792]
Support an `--assume-filename`-like option to let rustfmt resolve rustfmt.toml if the input is passed from stdin.

clang-format has a `--assume-filename` option which let it knows where to find the format config file when the payload is passed from stdin:

```
--assume-filename=<string>     - Set filename used to determine the language and to find
                                   .clang-format file.
                                   Only used when reading from stdin.
```

This would allow meta-formatters to pass file content that doesn't exist in the file system (for our [use case](https://issuetracker.google.com/issues/288107883): git history), while still letting `rustfmt` to figure out which format config to use.

Caveat: if the `rustfmt.toml` config file changes in history, this doesn't work, but I think it happens rarely enough.

**Comment by calebcartwright** [comment]
Thanks for reaching out and sharing! This is something that's actually been requested previously, discussed, and partially implemented, so I'm going to close this one to minimize bifurcation of discussion.

However, I really like the specifics of the proposal, so I will also cross-link the details you've brought forward in those other threads
