### ISSUE TITLE
`trailing_semicolon = false` changes the meaning of code, non-idempotent

### ISSUE THREAD

**Issue by digama0** [rust-lang/rustfmt#5797]
The `trailing_semicolon = false` option, when run on this code:
```rust
fn foo() {}
fn main() {
    return;
    foo()
}
```
turns it into
```rust
fn foo() {}
fn main() {
    return
    foo()
}
```
which now runs `foo()` where it did not before, as a second run of `rustfmt` will make clearer:
```rust
fn foo() {}
fn main() {
    return foo()
}
```

Observed on `rustfmt 1.5.3-nightly (065a1f5 2023-06-21)`.

**Comment by calebcartwright** [comment]
thanks for the report! tagging tracking issue: #3378

**Comment by calebcartwright** [comment]
@CosmicHorrorDev & @HarrisonHemstreet this is another one that should be a relatively quick fix if either of you are interested in working.

As discussed in chat don't feel obligated to work on any of these, we're just tagging some that we think could be good opportunities.

I'm going to be a bit more lightweight in initial guidance on this one to give you more opportunity to poke around, so all I'll say for now is that you may want to start around here:

https://github.com/rust-lang/rustfmt/blob/9386b32f5a72bb276a97461d33aab415314201d8/src/utils.rs#L295-L309

**Comment by CosmicHorrorDev** [comment]
I'm up for digging into it this weekend if @HarrisonHemstreet is fine with that
