### ISSUE TITLE
Request: Option for normalizing imports

### ISSUE THREAD

**Issue by Bruflot** [rust-lang/rustfmt#5799]
I think it would be nice to have option that normalizes imports, i.e. converts all imports to either be relative (`use super::xyz;`) or absolute (`use crate::foo::xyz;`).

It should probably have at least three modes:
- Preserve: leave as-is.
- Relative: convert absolute imports to relative ones if possible.
- Absolute: convert all relative imports to absolute ones.

**Comment by calebcartwright** [comment]
Thank you for sharing your idea!

However, I don't think this will be feasible for rustfmt for the same reasons many of the other import related requests are not.

rustfmt operates within a much earlier phase of the compiler process, is often executed on a single file in isolation, and occasionally on a specific subset of lines within a single file. rustfmt has no knowledge about the workspace, dependency graph, etc. It's true that in theory some higher level invokers of `rustfmt` (e.g. `cargo fmt`) could gather some of that info and pass it along to rustfmt, however, even that would create scenarios where `cargo fmt --check` and `rustfmt src/main.rs --check` would disagree which would make for a maddening inner dev loop and CI duels.

As such, I'm going to close this as non-actionable. However, if you (or anyone else) disagrees and thinks this is in the realm of possibility then certainly feel free to experiment and send a PR; we'd consider taking a look at such a PR at some point down the road.
