### ISSUE TITLE
enum variant doc comments are wrapped before `comment_width`

### ISSUE THREAD

**Issue by InsertCreativityHere** [rust-lang/rustfmt#5801]
Using `rustfmt 1.5.3-nightly (5ea66686 2023-06-27)`, with the following configuration options:
```
comment_width = 120
wrap_comments = true
unstable_features = true
max_width = 120
```

Sometimes comments are wrapped after 119 columns instead of the 120 columns I'd expect. It also seems context dependent.

For example, both of these lines are 120 columns, and neither get wrapped.
```
/// This function is 120 columns wide and is left alone. This comment is 120 columns wide and the formatter is also fine
fn my_super_cool_function_name(my_very_cool_argument_name: String, my_other_very_cool_argument_name: String) -> String {
    unimplemented!()
}
```

But this comment's line is 120 columns long, and _does_ get wrapped:
```
pub enum Severity {
    /// But here, this comment is 120 columns wide and the formatter wants to split it up onto two separate lines still.
    Error,
}
```

----

I have a little repository demonstrating this: https://github.com/InsertCreativityHere/rustfmt-comment-width-weirdness

**Comment by ytmimi** [comment]
@InsertCreativityHere  Thanks for reaching out!

Looks like we're reducing the shape by 1 prematurely in preparation to rewriting the enum variant when we should use the complete shape to rewrite the doc comment.

@HarrisonHemstreet any interest in taking this one on?

https://github.com/rust-lang/rustfmt/blob/9386b32f5a72bb276a97461d33aab415314201d8/src/items.rs#L635-L637

**Comment by ytmimi** [comment]
@IVIURRAY I this would be a good one to get started with. The issue is that we're using the wrong `Shape`. This should involve minimal code changes to fix. As I mentioned https://github.com/rust-lang/rustfmt/issues/5801#issuecomment-1610244151, this change [needs to be version gated](https://github.com/rust-lang/rustfmt/blob/master/Contributing.md#version-gate-formatting-changes).

**Comment by IVIURRAY** [comment]
Hey, @ytmimi, thanks for picking this one out, I've started to take a look but I'm finding it rather difficult to get the debugger working for this project. I'm obviously doing something wrong, I posted in Rust's Zulip streams, so hopefully I will get some help there.

At the minute I'm spraying `println!()` statements everywhere which is not really a great use of my time 😆 

@rustbot claim
