### ISSUE TITLE
Internal error "left behind trailing whitespace" for function argument with trailing space

### ISSUE THREAD

**Issue by cdbennett** [rust-lang/rustfmt#5802]
Fails with internal error "left behind trailing whitespace". Happens when a trailing space is on one of the argument lines to a function call that's broken across several lines:

```text
$ rustfmt +nightly ./src/lib.rs 
error[internal]: left behind trailing whitespace
  --> src/lib.rs:27:27:14
   |
27 |     otherfun( 
   |              ^
   |

error[internal]: left behind trailing whitespace
  --> src/lib.rs:38:38:21
   |
38 |         &mut output, 
   |                     ^
   |

error[internal]: left behind trailing whitespace
  --> src/lib.rs:47:47:26
   |
47 |     otherfun(&mut output, 
   |                          ^
   |

warning: rustfmt has failed to format. See previous 3 errors.

$ rustfmt +nightly --version
rustfmt 1.5.3-nightly (8084f397 2023-06-25)
```

Code to demonstrate the failure (success and failure cases to help highlight what might be causing it):

```rust
pub fn format_ok_1() {
    let mut output = String::new();

    // This is ok. It will be reformatted.
    otherfun(&mut output, "This quick brown fox jumped over the lazy dog. This quick brown fox jumped over the lazy dog. This quick brown fox jumped over the lazy dog.");
}

pub fn format_ok_2() {
    let mut output = String::new();

    // This is ok. There is trailing space on the "quick brown fox" line.
    otherfun(
        &mut output,
        "This quick brown fox jumped over the lazy dog. This quick brown fox jumped over the lazy dog. This quick brown fox jumped over the lazy dog.", 
    );
}

// Failures print "error[internal]: left behind trailing whitespace"
// Verified fails on:
// - rustfmt 1.5.2-stable (90c54180 2023-05-31)
// - rustfmt 1.5.3-nightly (8084f397 2023-06-25)

pub fn format_fails_1() {
    let mut output = String::new();

    // This fails. Trailing space after `otherfun(`.
    otherfun( 
        &mut output,
        "This quick brown fox jumped over the lazy dog. This quick brown fox jumped over the lazy dog. This quick brown fox jumped over the lazy dog.",
    );
}

pub fn format_fails_2() {
    let mut output = String::new();

    // This fails... the line with `&mut output,` has a trailing space.
    otherfun(
        &mut output, 
        "This quick brown fox jumped over the lazy dog. This quick brown fox jumped over the lazy dog. This quick brown fox jumped over the lazy dog.",
    );
}

pub fn format_fails_3() {
    let mut output = String::new();

    // This fails... the line with `&mut output,` has a trailing space.
    otherfun(&mut output, 
                "This quick brown fox jumped over the lazy dog. This quick brown fox jumped over the lazy dog. This quick brown fox jumped over the lazy dog.",
            );
}

fn otherfun(_: &mut String, _: &str) {}
```

This is probably related to several other "error[internal]: left behind trailing whitespace" bug reports, but this one seemed slightly different, so it seemed worth reporting anyway.

**Comment by cdbennett** [comment]
Notably, if you make the string literal shorter, e.g. delete everything after the first period within the string, the issue disappears.

**Comment by ytmimi** [comment]
@cdbennett Thanks for reaching out.

In this case, There's not much rustfmt can do. rustfmt abides by the `max_width` and can't comply with the `max_width` constraint and reformat those function calls at the same time. When rustfmt fails to format code for any reason it copies that code verbatim into its output, trailing whitespace and all.

You have 3 options to deal with this issue:

1) Bump the `max_width`; A `max_width=151` did the trick for me and rustfmt was able to remove the trailing whitespace since the `max_width` constraint was not violated.
2) set `format_strings=true`. This allows rustfmt to break long string literals over multiple lines in an attempt to keep everything under the `max_width`. This was also a viable option that I tested.
3) Manually remove the trailing whitespace.

**Comment by cdbennett** [comment]
OK, thanks for the comment. Rustfmt is a fantastic tool... would be great if it was a tiny bit smarter about handling the max_width requirement, and not totally bailing out like this.  At least I haven't hit this issue frequently, so not a big deal.
