### ISSUE TITLE
`cargo fmt` ignores `rustfmt.toml` in subdirectory

### ISSUE THREAD

**Issue by not-my-profile** [rust-lang/rustfmt#5814]
When creating a `rustfmt.toml` in `src/` `cargo fmt` applies it to all contained files.

However when creating a rustfmt config file in a subdirectory e.g. `src/foo/rustfmt.toml` then `cargo fmt` apparently does not apply it to `src/foo/mod.rs` while `rustfmt src/foo/mod.rs` does apply it.

I think `cargo fmt` should either be updated to also pick up rustfmt config files in subdirectories or [the documentation](https://github.com/rust-lang/rustfmt/blob/d9a09925d7ecfb46fb6a218dbf5479b51acc67c6/Configurations.md) should be updated accordingly to clarify this difference in config resolution between `cargo fmt` and `rustfmt`. Because currently the documentation just says:

> Rustfmt is designed to be very configurable. You can create a TOML file called rustfmt.toml or .rustfmt.toml, place it in the project or any other parent directory and it will apply the options in that file.

**Comment by calebcartwright** [comment]
`cargo fmt` does nothing other than query the workspace for details, and then invoke `rustfmt ...` commands with those details on your behalf.

cargo-fmt does absolutely nothing regarding rustfmt configuration, that's all `rustfmt`.

As such I don't view this issue as actionable for us at the moment, but if you'd be willing to put together a complete and minimal repro for us then we'd be happy to take a look!

**Comment by not-my-profile** [comment]
Sure thing :)

[rust-mcve.tar.gz](https://github.com/rust-lang/rustfmt/files/11961373/rust-mcve.tar.gz)

```
$ tar xvf rust-mcve.tar.gz
$ cd rustfmt-mcve
$ git diff
$ cargo fmt
$ git diff
diff --git a/src/main.rs b/src/main.rs
index e7a11a9..8b70680 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -1,3 +1,3 @@
 fn main() {
-    println!("Hello, world!");
+        println!("Hello, world!");
 }
$ rustfmt src/foo/mod.rs
$ git diff              
diff --git a/src/foo/mod.rs b/src/foo/mod.rs
index e7a11a9..0bda21f 100644
--- a/src/foo/mod.rs
+++ b/src/foo/mod.rs
@@ -1,3 +1,3 @@
 fn main() {
-    println!("Hello, world!");
+                println!("Hello, world!");
 }
diff --git a/src/main.rs b/src/main.rs
index e7a11a9..8b70680 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -1,3 +1,3 @@
 fn main() {
-    println!("Hello, world!");
+        println!("Hello, world!");
 }
```

**Comment by not-my-profile** [comment]
[rustfmt-mcve.tar.gz](https://github.com/rust-lang/rustfmt/files/11961415/rustfmt-mcve.tar.gz)

Sure thing :)

```
$ tar xf tar rustfmt-mcve.tar.gz
$ cd  rustfmt-mcve
$ git diff
$ cargo fmt
$ git diff
diff --git a/src/foo/mod.rs b/src/foo/mod.rs
index e7a11a9..8b70680 100644
--- a/src/foo/mod.rs
+++ b/src/foo/mod.rs
@@ -1,3 +1,3 @@
 fn main() {
-    println!("Hello, world!");
+        println!("Hello, world!");
 }
diff --git a/src/main.rs b/src/main.rs
index 2d33bef..5b9c8d5 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -1,5 +1,5 @@
 mod foo;
 
 fn main() {
-    println!("Hello, world!");
+        println!("Hello, world!");
 }
$ rustfmt src/foo/mod.rs
$ git diff
$ diff --git a/src/foo/mod.rs b/src/foo/mod.rs
index e7a11a9..0bda21f 100644
--- a/src/foo/mod.rs
+++ b/src/foo/mod.rs
@@ -1,3 +1,3 @@
 fn main() {
-    println!("Hello, world!");
+                println!("Hello, world!");
 }
diff --git a/src/main.rs b/src/main.rs
index 2d33bef..5b9c8d5 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -1,5 +1,5 @@
 mod foo;
 
 fn main() {
-    println!("Hello, world!");
+        println!("Hello, world!");
 }
```

**Comment by calebcartwright** [comment]
Thanks for the follow up. I won't be at my machine for a while, but in the interim I'd encourage re-running both the `--verbose` flag being passed to `rustfmt` (e.g. `cargo fmt -- --verbose` and `rustfmt --verbose ...`) to see which config files are being picked up.

cargo fmt invokes rustfmt with the entry point files for all the package targets in the workspace, so in cases where users have multiple highly localized (subdirectory-level) configuration files and modules contained within multiple import trees from different entry points you can see different results. This happens because rustfmt is getting invoked with different/conflicting config contexts

**Comment by not-my-profile** [comment]
Right ... yeah that does explain the behavior :)

I am not sure if a more sophisticated config lookup mechanism would actually be worth the additional complexity. But I am certain that the Configurations.md I linked earlier could be clarified since "place it in the project" doesn't actually guarantee that a `rustfmt.toml` is picked up.

**Comment by calebcartwright** [comment]
I'm going to go ahead and close then

> But I am certain that the Configurations.md I linked earlier could be clarified since "place it in the project" doesn't actually guarantee that a rustfmt.toml is picked up.

Feel free to send a PR with proposed text modifications that you feel add clarity, and we'll be happy to take a look! However, I'd push back on your latter characterization as I feel like you're making an inference that, at least in my reading, the docs neither state nor imply.

To expand a bit with your specific example, you're actually running two very different commands:

* `rustfmt src/main.rs --edition 2021` (technically this is what's actually executed by the `cargo fmt` helper)
* `rustfmt src/foo/mod.rs`

In the first case, you've asked rustfmt to format the `src/main.rs` file using 2021 edition for parsing, and the default mode of "also format any other files that are imported" from `src/main.rs`. One of the very first things rustfmt does is perform the config file lookup for the provided file(s), which in this case is just `src/main.rs` It first looks in the containing directory (`./src`) where it resolves a config file for the provided input. The configuration matter is considered settled at that point, and that's the configuration used when formatting the input file, `src/main.rs` (and files imported)

Now it sounds like your expectation/interpretation of the docs, and specifically "place it in the project", is that rustfmt would _also_ attempt to resolve individual configuration files for .rs files that were imported from a specified file (e.g. `src/main.rs`) but which weren't explicitly provided to rustfmt (e.g. `src/foo/mod.rs`).

That's something that could technically be done (and perhaps should), though I don't think that type of behavior is inherent in the existing docs that are exclusively describing `rustfmt` behavior. Furthermore, even if rustfmt were modified to do so, it still wouldn't really solve the dueling/multiple passes config conflicts that can occur when running `cargo fmt`. You can actually see a similar behavior in your example with some slightly modified rustfmt invocations.

Compare the different outputs depending on the file ordering:

* `rustfmt src/main.rs src/mod/foo.rs --check --verbose`
* `rustfmt src/mod/foo.rs src/main.rs --check --verbose`

Obviously this is a simplified and contrived example, but this happens in real cases more often than one might initially expect, e.g. in multi-crate workspaces where you have a `foo` and `bar` crate that have their own, conflicting rustfmt config files, and both of which import some module `baz` (and `baz` doesn't have its own rustfmt config, so it wouldn't matter even if rustfmt _did_ attempt to resolve and use a baz-local config).

Ultimately, `cargo fmt` is a helper utility to make it as simple as possible to format lots of things in a large project/workspace, however, it may not be ideal in more complicated scenarios. This can be especially true where you want to have divergent formatting between different directories within the project, you may find that cargo-driven easy button doesn't work and that your best bet is going to be running structured `rustfmt ...` commands directly (perhaps with some type of task runner tool) where you can have more control and precision over the formatting commands.

I.e. `rustfmt +nightly src/main.rs src/foo/mod.rs --skip-children` is probably the command you'd want for a scenario like the simple mcve

FWIW some of the projects in the Rust org have utilized the aforementioned approach, e.g. in clippy (see https://doc.rust-lang.org/nightly/clippy/development/adding_lints.html?highlight=fmt#running-rustfmt and https://github.com/rust-lang/rust-clippy/blob/master/clippy_dev/src/fmt.rs) and the compiler (https://rustc-dev-guide.rust-lang.org/conventions.html?highlight=tidy#formatting-and-the-tidy-script and https://github.com/rust-lang/rust/blob/master/src/bootstrap/format.rs)
