### ISSUE TITLE
Comments within main.rs "break" cargo build, check, or any other cargo calls that I make.

### ISSUE THREAD

**Issue by MikeGitIt** [rust-lang/rustfmt#5819]
<img width="355" alt="Screenshot 2023-07-07 at 6 52 05 PM" src="https://github.com/rust-lang/rustfmt/assets/2125656/5a55f8d9-b256-423b-8aa9-2e84c816e284">
<img width="931" alt="Screenshot 2023-07-07 at 6 54 59 PM" src="https://github.com/rust-lang/rustfmt/assets/2125656/12c81a86-2345-499f-a9d7-6a235d4b6586">

Now mind you, when I simply remove the comment line from the main.rs file, the error simply goes away. I don't do anything else special to get it to go away.

I am running on:
<img width="280" alt="Screenshot 2023-07-07 at 6 57 42 PM" src="https://github.com/rust-lang/rustfmt/assets/2125656/479a30c0-4978-4c66-abd3-b00e00a414a8">

I am using Emacs as my IDE. But, I tried other editors in particular Sublime and VSCode. Below is a sample from VSCode. 
<img width="784" alt="Screenshot 2023-07-07 at 7 00 28 PM" src="https://github.com/rust-lang/rustfmt/assets/2125656/101fb3d5-46fa-4854-aa2d-3b8f28758789">

So, with that said, I also switched between 1.70+ and 1.72 nightly, to see if that would make much of a difference. It did not. I am running Rust Analyzer version: rust-analyzer 1.72.0-nightly (cb80ff13 2023-07-07). I run the relevant version for 1.70 as well. Same issue.

**Comment by ytmimi** [comment]
@MikeGitIt can you please post a minimal code snippet that we can use to reproduce the issue. Without one there's little that we can do to help you resolve this issue.

**Comment by MikeGitIt** [comment]
I cannot reproduce this in any other project but this one seems to behave this way, even if I copy it into another directory, run cargo clean, cargo build, and then add a comment to the main.rs file. It throws the error eventually but not always right away. I copied it to several different locations and followed the same simple steps as previously explained. When you say a minimal code snippet, what exactly are you thinking of? Like if the code is within main, you'd like me to share 50/100 lines or just the main function or what?  The main function uses various imports, as I am sure you're aware of, but those various imports are not shareable, per say. Are there some aspects of the artifacts which I can look into from my end and possible share compiler output with BACKTRACE set to full?

**Comment by MikeGitIt** [comment]
Another thing I notices is that if I use bat to output the code, this is what I get:
<img width="733" alt="Screenshot 2023-07-07 at 10 13 02 PM" src="https://github.com/rust-lang/rustfmt/assets/2125656/250a0be4-c403-482d-ac5a-9158f50b4206">

Those are windows carriage returns, supposedly and if I am to believe stackoverflow, but I haven't used nor created any of this code in Windows. So that makes absolutely no sense to me. I have stripped the main.rs file and copied into a new main.rs file, to temporarily remove the issue but it eventually shows up again. The line `use std::arch::aarch64::vrecpsq_f64` isn't even in the main.rs file, or rather, it isn't visibly inside of the main.rs file that I am working within. There are other use statements which aren't in the working file as well, or rather, aren't visibly within the working file. So, there's also that part.

**Comment by MikeGitIt** [comment]
Oh yeah, the column values are ranging from the hundreds to the thousands, if you look at my initial screenshots. That's really odd. It means it is counting beyond the visible columns of the code in my main.rs file. In the working file, the widest column is column 85 on line 13. Yet the code is showing values like main.rs 1:2640! How, Sway?! <-- slang

**Comment by ytmimi** [comment]
First, can you reproduce the error when invoking rustfmt directly, e.g. `rustfmt /path/to/main.rs`?

Also, just so we're absolutely clear what version of rustfmt you're using, can you post that here as well. I know you said you're using the 1.72 nightly, but having the exact version info could also be helpful. Please run `rustfmt --version` when you get a chance. 

> When you say a minimal code snippet, what exactly are you thinking of? Like if the code is within main, you'd like me to share 50/100 lines or just the main function or what?

Yes if you could share a link to a file on GitHub or literally post the code snippet inline like:

```rust
// All the content of the file that's producing the error, but ideally you'd spend some time
// trimming down the example to something smaller than 50-100 lines

struct Example {
    // Fields ...
}

fn example() {
    // content ...
}
```

> The main function uses various imports, as I am sure you're aware of, but those various imports are not shareable, per say.

That's fine, assuming those files aren't needed to reproduce the error.  Whatever you can share will help, but if you can't share anything then unfortunately there's little we can do. The screenshots you've posted are appreciated, but we can't take action on this using them. We really need something that we can copy paste locally to run rustfmt on to try and reproduce this issue.

> Oh yeah, the column values are ranging from the hundreds to the thousands, if you look at my initial screenshots. That's really odd. It means it is counting beyond the visible columns of the code in my main.rs file. In the working file, the widest column is column 85 on line 13. Yet the code is showing values like main.rs 1:2640! How, Sway?! <-- slang

Interesting observation 🤔. Now I'm more curious about what the file looks like.

**Comment by calebcartwright** [comment]
I also want to note that if you're seeing consistent behavior (parsing error from the compiler) when running rustc (directly or indirectly via `cargo build`, `cargo check`, etc.) then this doesn't sound like something related to rustfmt.

If anything, it looks like your line style comment is commenting out large chunks of your code, and thus making your program invalid to the point it can't even be parsed. Why that's the case, we couldn't tell you, but there might be folks who can in other forums.

**Comment by MikeGitIt** [comment]
> I also want to note that if you're seeing consistent behavior (parsing error from the compiler) when running rustc (directly or indirectly via `cargo build`, `cargo check`, etc.) then this doesn't sound like something related to rustfmt.
> 
> If anything, it looks like your line style comment is commenting out large chunks of your code, and thus making your program invalid to the point it can't even be parsed. Why that's the case, we couldn't tell you, but there might be folks who can in other forums.

I wasn't implying that it was rustfmt, or should I say, I was intending to imply that. So what I have done, and what seems to have "fixed" the problem is run `sed -e "s/\r//g" main.rs > main.rs.clean` to remove the CRLF issue, which apparently was the whole issue in the first place. I don't see the problem at all, even after pasting a large number of line comments. Somehow my main.rs got corrupted with a ton of ^M (Ctrl-M) characters. The only thing I can remotely point to, as a reason or cause for this, is that at one point I had a x86_64 toolchain installed and must have inadvertently used it (how, sway?), at some point. I don't know if Rosetta automatically emulated x86_64 in order for that to happen and I am not curious enough to test that out. I have the file in working order now, so I am going to move on from here.
