### ISSUE TITLE
In `use` blocks, prelude should come first

### ISSUE THREAD

**Issue by Kyllingene** [rust-lang/rustfmt#5820]
In blocks such as this (with more items):
```
use foo::{
	prelude::*,
	bar,
	baz::qux,
};
```

The `prelude` item should come first. However, `rustfmt` moves the prelude line to the end, like this:
```
use foo::{
	bar,
	baz::qux,
	prelude::*,
};
```

This may be an erroneous preference, but it makes sense to me.

**Comment by ytmimi** [comment]
@Kyllingene Just so we're clear, the reordering is just an esthetic issue for you and isn't actually leading to compilation errors, right? I don't think there's a difference about whether the prelude is imported first or last.

`reorder_imports = true` is set by default. If you'd like you can set it to `false`.

**Comment by ytmimi** [comment]
@Kyllingene just following up here to confirm that this doesn't lead to compilation issues.

**Comment by Kyllingene** [comment]
Apologies for not responding, I'm not certain why.

No, there are no compilation issues, and looking back I don't think this is a very suitable change for rustfmt. I'll take the liberty of closing this.
