### ISSUE TITLE
Import sorting breaks with long paths

### ISSUE THREAD

**Issue by lovesegfault** [rust-lang/rustfmt#5829]
Given the following code:

```rust
use zsome_other_crate_with_long_name::baz_baz_baz_baz_baz_baz_baz::baz_baz_baz_baz_baz::BazBazBazBazBaz;
use ayet_another_crate_with_a_really_big_name::bar_bar_bar_bar_bar_bar_bar_bar_bar::bar_bar_bar_bar_bar::BarBarBarBarBarBarBarBarBar;
```
[playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b9cc93f5432e5bf843d37d29f399c5af)

I would expect `rustfmt` to reorder those two, resulting in:

```rust
use ayet_another_crate_with_a_really_big_name::bar_bar_bar_bar_bar_bar_bar_bar_bar::bar_bar_bar_bar_bar::BarBarBarBarBarBarBarBarBar;
use zsome_other_crate_with_long_name::baz_baz_baz_baz_baz_baz_baz::baz_baz_baz_baz_baz::BazBazBazBazBaz;
```

However, if you test it, `rustfmt` leaves the ordering unchanged, which, I believe, is a bug.

**Comment by lovesegfault** [comment]
If you configure `max_width` to a large number, it works as expected.

**Comment by ytmimi** [comment]
@lovesegfault thanks for reaching out, and for digging into this a little yourself.

This is indeed a `max_width` issue. `max_width` is a hard constraint for rustfmt, and I don't think that's going to change anytime soon. Unfortunately this doesn't seem to be actionable at this time so I'm going to go ahead and close this.

**Comment by lovesegfault** [comment]
@ytmimi I don't think solving this necessarily requires fiddling with `max_width` though, right?

For example, it could attempt to format that long import as:
```rust
use ayet_another_crate_with_a_really_big_name::{
    bar_bar_bar_bar_bar_bar_bar_bar_bar::{
        bar_bar_bar_bar_bar::BarBarBarBarBarBarBarBarBar;
    }
};
```

To keep it under `max_width`?

**Comment by ytmimi** [comment]
I believe something was similar was proposed in https://github.com/rust-lang/rustfmt/issues/4746, specifically https://github.com/rust-lang/rustfmt/issues/4746#issuecomment-812806493
