### ISSUE TITLE
#[rustfmt_skip] does not work for comments

### ISSUE THREAD

**Issue by shahn** [rust-lang/rustfmt#584]
To get around #583, I tried putting #[rustfmt_skip] in front of a /**/ style comment. Unfortunately, it seems that this doesn't get taken into account and the comment is reformatted anyway. I'm unaware of any other way of disabling comment reformatting or other workaround that'd be more appropriate.

**Comment by nrc** [comment]
This is a limitation of Rust attributes. I expect we can work around this by having a magic comment that only Rustfmt cares about.

**Comment by scampi** [comment]
With #583 fixed a magic comment shouldn't be needed anymore, or a new issue could be opened to make a case for it.

**Comment by gnzlbg** [comment]
@scampi does that work for top-level module comments?

**Comment by scampi** [comment]
With `normalize_comments` enabled (it is disabled by default), I get the following.

# Test

```rust
/*impl PartialEq for Variable {
    fn eq(&self, other: &Self) -> bool {
        return &self == &other;
    }
}*/

fn bar() -> usize {
    42
}
```

# Result

```diff
Diff in /home/yfful/documents/code/rustfmt/583.rs at line 1:
-/*impl PartialEq for Variable {
-    fn eq(&self, other: &Self) -> bool {
-        return &self == &other;
-    }
-}*/
+// impl PartialEq for Variable {
+// fn eq(&self, other: &Self) -> bool {
+// return &self == &other;
+// }
+// }

 fn bar() -> usize {
     42
```

**Comment by scampi** [comment]
it is unchanged with the default value
