### ISSUE TITLE
Suspicious formatting with string literals in macros

### ISSUE THREAD

**Issue by JaniM** [rust-lang/rustfmt#5855]
This isn't exactly a bug, but I feel the behavior is highly unexpected.

    let _style = css!("
        display: flex;
        flex-direction: column;
        ...
    ");

formats to

    let _style = css!(
        "
        display: flex;
        flex-direction: column;
        ...
    "
    );

I much prefer the original code.
Playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2e601d5bbc9f0103bf217f469c6dc0a1

**Comment by calebcartwright** [comment]
Thanks for sharing but going to close as this isn't a bug. You may want to follow https://github.com/rust-lang/rfcs/pull/3450 if you aren't already, as it contains some available alternatives for the string arg as well as proposed lang addition that would support these types of scenarios in a new way.
