### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rustfmt#5859]
`cargo check   --features generic-simd`

```
error: expected one of `!` or `::`, found keyword `mod`
   --> /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/packed_simd_2-0.3.7/src/lib.rs:347:7
    |
347 | crate mod llvm {
    |       ^^^ expected one of `!` or `::`

error: could not compile `packed_simd_2` (lib) due to previous error
```

**Comment by calebcartwright** [comment]
Could you add a little more context please? It's unclear how this relates to rustfmt from the initial issue description

**Comment by matthiaskrgr** [comment]
sorry, rustfmt has a features "generic-simd" that fails the rustfmt build when it is enabled.

This was found because we run clippy on rustfmt in our CI with `--all-targets --all-features`.

repro:
```
git clone https://github.com/rust-lang/rustfmt/
cd rustfmt
cargo check   --features generic-simd
```

**Comment by ytmimi** [comment]
Confirming I'm able to reproduce this. I'm also pretty sure it's related to https://github.com/llogiq/bytecount/issues/64. I think Bumping the version of `bytecount` would solve the problem 🤞🏼
