### ISSUE TITLE
Rustfmt doesn't format some code in a large file

### ISSUE THREAD

**Issue by gianzellweger** [rust-lang/rustfmt#5869]
I have a large file with about 1000 lines. If I try to format the code, be it through `cargo fmt` or `rustfmt`, most code formats, but some particularly messy/quite arbitrary sections don't format at all and stay how they are. Note that the code compiles and both methods don't produce any output and exit with code 0, indicating a successful format. I also put some of the code into the [Rust Playground](https://play.rust-lang.org)'s rustfmt, which I verified to be the exact same version (rustfmt 1.6.0-nightly (32303b21 2023-07-29)) as on my machine and some particularly messy sections formatted correctly, but the entire file didn't work. I don't want to post the entire code (because it's 1000 LOC), but I can if needed. 

I don't think it matters particularly, but I'm on `x86_64-apple-darwin` (Intel Mac).

**Comment by kevinji** [comment]
Is this another instance of #3863?

**Comment by gianzellweger** [comment]
@kevinji That would make sense, as the code contains very long lines.
