### ISSUE TITLE
error[internal]: left behind trailing whitespace on demo file

### ISSUE THREAD

**Issue by Kaladum** [rust-lang/rustfmt#5891]
Hello together,

I was working on a project using VSCode and rust-analyzer as an IDE when my autoformatting (format on save) stopped working.

While running `cargo fmt` I got the following message: `error[internal]: left behind trailing whitespace`.
I was able to build a minimal file that reproduces the error. The file can be found here: [demo.rs](https://github.com/rust-lang/rustfmt/files/12383384/demo.rs.txt)

The bug was reproducible by running `cargo fmt --check demo.rs` with version `rustfmt 1.5.2-stable (8ede3aae 2023-07-12)`  and the latest [master](https://github.com/rust-lang/rustfmt/tree/16db2a4be2488dac816a55f3f1c014d5a36cd88e).

I'm pretty sure the bug is caused by the arrow syntax of the [array_macro](https://docs.rs/array-macro/latest/array_macro/macro.array.html) crate.

Thanks for your awesome work on rust and its tools!
Kaladum

**Comment by c-git** [comment]
I got the same error but my case is different. I produced what I think is an MRE for my case. But in mine if I shorten the long line by one char from the string argument then the problem goes away. 

Maybe it's macros that are long or go beyond the end of the line. I further noticed that if I wrap that leg of the match in braces the problem also goes away even if I make the line longer.

I created a repo with my [MRE](https://github.com/c-git/rustmft_mre). 

Excerpt from main:

```rust
fn main() {
    match File::open("NON-EXISTENT") {    
        Ok(_) => {   
            "anything".to_string()
        }
        Err(_) => format!("1234567890+1234567890+1234567890+1234567890+1234567890+1234567890+1234567890+123456789"),
    };
    // If the text inside of the format string is 1 char shorter the problem goes away
}
```

My error message is:

```
error[internal]: left behind trailing whitespace
 --> /home/one/rustfmt_mre/src/main.rs:5:5:19
  |
5 |         Ok(_) => {   
  |                   ^^^
  |

warning: rustfmt has failed to format. See previous 1 errors.
```

If it is of any value the line I think in my real project that triggers the error is [this one](https://github.com/rust-practice/conn_mon/blob/f2f27d8f7733eb9ced0725035d216c2895907343/src/event_recorder.rs#L67)

**Comment by ytmimi** [comment]
@c-git Thanks for reaching out. The issue here is the long unbreakable string literal, and is unrelated to this report. The issue is that rustfmt is unable to format all the match arms within the `max_width`, and therefore fails to rewrite the entire match statement. Your best option is to increase the `max_width`.

I've also checked and using `version=Two` formats your code like this:

```rust
fn main() {
    match File::open("NON-EXISTENT") {
        Ok(_) => "anything".to_string(),
        Err(_) => format!(
            "1234567890+1234567890+1234567890+1234567890+1234567890+1234567890+1234567890+123456789"
        ),
    };
    // If the text inside of the format string is 1 char shorter the problem goes away
}
```

**Comment by ytmimi** [comment]
Inlining the code snippet posted by @Kaladum 

```rust
use super:: TMP;


const TEST: [FOO; 64] = array![i => {		
	bar(42,&[(0,1)]),				
};64];
```

and here's the error message:

```
error[internal]: left behind trailing whitespace
 --> <stdin>:3:3:38
  |
3 | const TEST: [FOO; 64] = array![i => {		
  |                                      
  |

warning: rustfmt has failed to format. See previous 1 errors.
```

> I'm pretty sure the bug is caused by the arrow syntax of the [array_macro](https://docs.rs/array-macro/latest/array_macro/macro.array.html) crate.

I'm also pretty sure it's the arrow syntax that's causing rustfmt to fail here. Macro formatting is difficult because macros can contain any valid tokens, not necessarily valid rust code. rustfmt is only able to format macros if their arguments parse as valid rust.

Your best option is to manually remove the trailing whitespace.
