### ISSUE TITLE
End line comment after formatting

### ISSUE THREAD

**Issue by zonglin-hub** [rust-lang/rustfmt#5897]
### Before formatting

![image](https://github.com/rust-lang/rustfmt/assets/87891147/9d0f89a7-6750-41b6-a5df-7b1cb0446e20)

### After formatting

![image](https://github.com/rust-lang/rustfmt/assets/87891147/2c2ead78-ae99-4091-89de-59e2dfe61290)

rustfmt 1.6.0-nightly (28eb857b 2023-08-12)

**Comment by ytmimi** [comment]
Thanks for the report! I'm going to close this as a duplicate of #3720
