### ISSUE TITLE
rustfmt always inserts newline before `else` in let-else statement with attribute

### ISSUE THREAD

**Issue by rhysd** [rust-lang/rustfmt#5901]
## Repro

This is a code rustfmt formatted.

```rust
fn main() {
    #[cfg(target_os = "linux")]
    let x = 42
    else {
        todo!()
    };

    // #[cfg(target_os = "linux")]
    let x = 42 else { todo!() };
}
```

With some attribute on a let-else statement, rustfmt always inserts newline before `else`. When removing the attribute, this doesn't happen and rustfmt works as intended.

## Expected behavior

My expectation is that rustfmt does not change formatting looking at the existence of attribute:

```rust
fn main() {
    #[cfg(target_os = "linux")]
    let x = 42 else { todo!() };

    // #[cfg(target_os = "linux")]
    let x = 42 else { todo!() };
}
```

## Environment

- rustfmt: 1.6.0-stable (5680fa18 2023-08-23)
  - Installed via rustup's stable toolchain
- Rust: 1.72.0
- OS: Windows 10

**Comment by rhysd** [comment]
@ytmimi Thank you for triaging quickly. I'm looking at the implementation and trying to fix this issue. I'll make a PR.

**Comment by calebcartwright** [comment]
> @calebcartwright I'm guessing we'll need to version gate this fix

Yeah we'll have to, can't rock formatting on stable again unfortunately. Mercifully the 2024 edition won't be too terribly far out so in practice this will get cleaned up by default before too long

**Comment by ytmimi** [comment]
Yup, that's what I thought
