### ISSUE TITLE
rustfmt binary doesn't seem to do anything on my machine

### ISSUE THREAD

**Issue by punowo** [rust-lang/rustfmt#5906]
Hello. 

I've added the binary downloaded from github to my path. I've tried both gnu and msvc. If I point it at a .rs file it won't format it. I'm confused and I'm not sure how to debug this further. I'm on Windows 10. I do not have Rust tooling installed. I just want to use rustfmt to format some rust files. 
```
PS C:\Users\pun> $LASTEXITCODE
PS C:\Users\pun> rustfmt --version
PS C:\Users\pun> $LASTEXITCODE
-1073741515
PS C:\Users\pun> rustfmt --help
PS C:\Users\pun> $LASTEXITCODE
-1073741515
```

**Comment by ytmimi** [comment]
Unfortunately you'll need to have a rust toolchain installed in order to run rustfmt, and the recommended way to get rustfmt is via rustup. You'll find some addition details in https://github.com/rust-lang/rustfmt/issues/5805#issuecomment-1616780512 and the other linked issues.
