### ISSUE TITLE
Rustfmt panic on formatting source code

### ISSUE THREAD

**Issue by rakshith-ravi** [rust-lang/rustfmt#5911]
Backtrace attached. Please let me know if anything else is needed

[rustc-ice-2023-09-15T14:33:25.58390881Z-1535772.txt](https://github.com/rust-lang/rustfmt/files/12620499/rustc-ice-2023-09-15T14.33.25.58390881Z-1535772.txt)

**Comment by ytmimi** [comment]
@rakshith-ravi please provide a minimal and complete code snippet that we can use to trigger the panic, thanks!

**Comment by ytmimi** [comment]
Closing this since we don't have enough information to look into the issue.
