### ISSUE TITLE
Plural forms of `imports_*` options

### ISSUE THREAD

**Issue by mgeisler** [rust-lang/rustfmt#5915]
There are several options concerning imports:

- [`imports_indent`](https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=imports_#imports_indent)
- [`imports_layout`](https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=imports_#imports_layout)
- [`imports_granularity`](https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=imports_#imports_granularity)

I'm not a native English speaker, but to the best of my understanding, the correct form for these would 

- `import_indent`
- `import_layout`
- `import_granularity`

To me, "imports granularity" sounds like "shoes-maker", when it should instead be "shoe-maker" (or actually "shoemaker").

Has anybody else thought the same thing when reading these option names?

**Comment by ytmimi** [comment]
@mgeisler thanks for sharing your thoughts on this. All of these options were added to the project before I joined the rustfmt team so I can't speak to the rational for having `imports` vs `import` in each of the names. That being said, it's unlikely that we'll rename these options any time soon if ever. Again, I appreciate you taking the time to open an issue, but I'm going to close this since there's nothing to take action on right now.

**Comment by calebcartwright** [comment]
Fwiw I agree, both with the initial observation/question as well as treating this as a no-op for the time being. I'd rather do a holistic review of the option names at the same time, especially when targeting consistency, so that we don't end up doing them in batches with push & pull along the way

**Comment by mgeisler** [comment]
Hi @ytmimi and @calebcartwright, thanks for looking at the issue!

> I'm going to close this since there's nothing to take action on right now.

I often see unactionable issues as a TODO for some future self: they represent something I (or someone else) should be aware of when doing a feature. Of course, now that two people from the project has through about the naming here, I guess it's  registered and will be remembered later if someone starts an option name cleanup 🙂

> I'd rather do a holistic review of the option names at the same time, especially when targeting consistency, so that we don't end up doing them in batches with push & pull along the way

Makes sense to me! It would be great to make all the unstable option names consistent.
