### ISSUE TITLE
cargo-fmt should format tests, including doc tests

### ISSUE THREAD

**Issue by JonathanLindsey** [rust-lang/rustfmt#5958]
Doc test code should be formatted. It is not being formatted.

Note that #803 and #1126 asked for test code (not necessarily doc tests) to be formatted and this was reportedly completed but in #803 [a comment](https://github.com/rust-lang/rustfmt/issues/803#issuecomment-331705125) suggests there was a regression.

**Comment by ytmimi** [comment]
@JonathanLindsey can you please post a code snippet and any configuration options that you're using that we can use to reproduce your issue. If you also could explain how you're invoking rustfmt / what version of rustfmt you're using that would also be helpful.

**Comment by JonathanLindsey** [comment]
## Steps to reproduce

1. Create a new rust project with `cargo new --lib <project_name>` and edit the `lib.rs` file to be:

```rust
/// # Example
/// 
/// ```
/// let result = add(2, 2);
/// assert_eq!(result, 4    );
/// ```
/// 
pub fn add(left: usize, right: usize) -> usize {
    left + right
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_works() {
        let result = add(2, 2);
        assert_eq!(result, 4    );
    }
}

```

Notice the extra spaces after the number 4 in the 2 `assert_eq!()` lines.

2. Then run `cargo fmt` in a terminal.
3. Notice the extra spaces in the `it_works()` function get removed but the extra spaces in the doc test don't get removed.

## Environment

* PopOS which is downstream of Ubuntu.
* Rust was installed using the official install command: `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
* `cargo --version` says `cargo 1.73.0 (9c4383fb5 2023-08-26)`

**Comment by ytmimi** [comment]
You need to set [`format_code_in_doc_comments=true`](https://rust-lang.github.io/rustfmt/?version=v1.7.0&search=#format_code_in_doc_comments)

When formatting your input with that option you get:

```rust
/// # Example
///
/// ```
/// let result = add(2, 2);
/// assert_eq!(result, 4);
/// ```
pub fn add(left: usize, right: usize) -> usize {
    left + right
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_works() {
        let result = add(2, 2);
        assert_eq!(result, 4);
    }
}
```
