### ISSUE TITLE
Allow for missing modules

### ISSUE THREAD

**Issue by abrisco** [rust-lang/rustfmt#5962]
I have a crate that uses some generated source code that fails whenever I run rustfmt before generating it with the following error
```
~/Code/rustfmthing (main ✗) rustfmt ./src/main.rs
Error writing files: failed to resolve mod `generated`: /Users/abrisco/Code/rustfmthing/src/generated.rs does not exist
```

The source file looks like this:
```rust
mod generated;

pub fn main() {
    generated::greeting();
}
```

Is there a way to have rustfmt not attempt to resolve modules and instead simply format the file I passed?

**Comment by ytmimi** [comment]
Thanks for reaching out. This is a similar request to https://github.com/rust-lang/rustfmt/issues/5609, and https://github.com/rust-lang/rustfmt/pull/5611 was opened to provide an option to ignore missing submodules.

You can subscribe to the PR to be notified when the team has a chance to revisit those proposed changes.

You could also use [`skip_children=true`](https://rust-lang.github.io/rustfmt/?version=v1.4.36&search=#skip_children) and rustfmt won't try to resolve any submodules. So in your example above only `main.rs` would be formatted. if you ran

```
rustfmt ./src/main.rs
```
