### ISSUE TITLE
Rustfmt removes comments after -> in function return type

### ISSUE THREAD

**Issue by wadi-chemkhi** [rust-lang/rustfmt#5970]
## Description

Line comments placed before the return type of a function get deleted when running rustfmt.

``` rust
fn do_something(p1: T1) -> 
// this peace of information will be lost if you run rustfmt
Result<Option<T2>, Error1> {
    let maybe=some_fn();
    Ok(maybe)
}

```

## How to reproduce
- go to [this snippet](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=bfa1855f171ab7b3747138dd5169cfcf)
- notice the comment placed before the `Result` type
- run rustfmt from the tools right menu
- notice that the comment dissapeared

**Comment by ytmimi** [comment]
@wadi-chemkhi what version of rustfmt are you on, and what platform are you running on?

**Comment by wadi-chemkhi** [comment]
> @wadi-chemkhi what version of rustfmt are you on, and what platform are you running on?

The version I am running is:
```
 ❯ rustfmt --version
rustfmt 1.6.0-stable (cc66ad4 2023-10-03)
``` 

the version on https://play.rust-lang.org is:
1.7.0-nightly (2023-11-29 b10cfcd)
