### ISSUE TITLE
Bug/quirk: newline inconsistencies in argument list

### ISSUE THREAD

**Issue by samtay** [rust-lang/rustfmt#5987]
It seems odd that these are inconsistent, especially since trace and debug are both five letter words:

```rust
use log::{debug, trace};

pub fn main() {
    trace!(
        "get some longer length in here yes yes {} {}",
        "hello",
        "world"
    );
    debug!(
        "get some longer length in here yes yes {} {}",
        "hello", "world"
    );
}
```

Notice the newline present in the `trace` arguments, but not in the `debug` arguments. Other functions seem to follow the same format as the former; perhaps this is something specific with `debug`? Not sure why that would be :shrug: 

Versions tested:
- stable: `rustfmt 1.6.0-stable (a28077b 2023-12-04)`
- nightly: `rustfmt 1.7.0-nightly (3d0e6be 2023-12-21)`

**Comment by ytmimi** [comment]
Looks like we forgot about `trace!` 😅

https://github.com/rust-lang/rustfmt/blob/d739d93787314690b5e7823d9e3aae2a8ffd2111/src/overflow.rs#L46-L51
