### ISSUE TITLE
`generic_const_items` syntax gets deleted

### ISSUE THREAD

**Issue by lukas-code** [rust-lang/rustfmt#5995]
```rust
#![feature(generic_const_items)]
const C<T>: Option<T> = None;
```
becomes
```rust
#![feature(generic_const_items)]
const C: Option<T> = None;
```

[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=0fdab6a74c2467f156335741872caed0)

**Comment by ytmimi** [comment]
@lukas-code thanks for the report. I made a note of it on the tracking issue https://github.com/rust-lang/rust/issues/113521

**Comment by fmease** [comment]
Should we close this issue now that rust-lang/rust#132540 has been merged?
Of course, that change hasn't been synced yet with this repo but I think that's acceptable.

The aforementioned PR doesn't implement formatting for GCIs at all but it prevents rustfmt from deleting syntax.
Codifying the style of GCIs (T-style, style guide) and impl'ing formatting (T-rustfmt) are already tracked in https://github.com/rust-lang/rust/issues/113521.

**Comment by calebcartwright** [comment]
yeah sounds reasonable, thanks for the follow up
