### ISSUE TITLE
Rule to anonymise trait imports that are not used directly

### ISSUE THREAD

**Issue by bayov** [rust-lang/rustfmt#6001]
Many times we need to import a trait to a certain scope just to be able to use the trait methods, but we don't actually refer to the trait's identifier:

```rust
fn foo() {
    use std::fmt::Write; // must be in scope, but doesn't need to be identifiable
    let mut s = String::new();
    s.write_char('x');
}
```

Which rustfmt can then turn into:
```rust
fn foo() {
    use std::fmt::Write as _; // anonymized
    let mut s = String::new();
    s.write_char('x');
}
```

**Comment by ytmimi** [comment]
@bayov thanks for reaching out. I want to make sure I understand you correctly. Are you asking that rustfmt turn 'use path::to::Trait;' into 'use path::to::Trait as _;'?

**Comment by bayov** [comment]
That's basically my suggestion.

If it's outside of what is considered an appropriate formatting rule by rustfmt, then could you point me to the right Rust tool?

Is it more appropriate for clippy to handle such a (lint) rule?

**Comment by ytmimi** [comment]
That's what I though. Thanks for clarifying.

To give a little background, rustfmt operates on the AST that it gets back from the rustc parser. All rustfmt knows when it sees `use path::to::item;` is that it's reformatting an import. The AST doesn't provide any information on whether the item being brought into scope is a trait, struct, enum, function, macro, etc. Given the lack of details in the AST rustfmt can't reasonably make this kind of transformation.

**Comment by ytmimi** [comment]
To be honest, I'm not sure where a more appropriate place to make this request would be. You might consider reaching out on Zulip. Maybe someone there would know better.

**Comment by bayov** [comment]
Thanks! I've also suggested a similar clippy lint: https://github.com/rust-lang/rust-clippy/issues/12072

Maybe they do have the needed context to address this.
