### ISSUE TITLE
Block with a function call outside is not formated when there is a long tracing macro inside it

### ISSUE THREAD

**Issue by Andrepuel** [rust-lang/rustfmt#6019]
I've tested on `rustfmt 1.7.0-nightly (a2d9d73 2024-01-10)` and `rustfmt 1.7.0-stable (82e1608 2023-12-21)`

This is the minimal code I've managed to come up that reproduces the issue:

    fn handle() {
        {
                let number = 3;

            tracing::debug!(ccccccccccccccccccbbbbbbbcbbbbbbcccc=%ccccccccccccccccccccccccccccccccccccc);
        }.func()
    }

Looks like the length of the macro invocation is related to the problem. As removing one single character makes the issue go away.
Removing the `.func()` just right after the block also made the problem disappear.

**Comment by ytmimi** [comment]
This is a duplicate of https://github.com/rust-lang/rustfmt/issues/3863. The `.func()` makes this a chain.

**Comment by Andrepuel** [comment]
@ytmimi , thanks. I've looked for duplicates but I didn't know what I was looking for.
