### ISSUE TITLE
[Feature request]: Allow for variable/function naming schemes; i18n write-up/RFC

### ISSUE THREAD

**Issue by feefladder** [rust-lang/rustfmt#6042]
I've been delving into internationalization for the past few days and raised this issue [here](https://github.com/rust-community/team/issues/178). It is inspired by what [koro](https://github.com/ChimeraCoder/koro) does, but allows for more fine-grained control, inspired partially by [babylscript](https://babylscript.plom.dev/browsertranslator.html)

cf. discussion [here](https://users.rust-lang.org/t/internationalization/77011/3), this would tackel one aspect: identifier naming.

Basically, I'd like to allow defining a grammar for my identifiers in a comment/macro above an identifier, match statement or block. which is enforced by `cargo fmt`. Consider the following:
```rust
enum Sign {
  Plus,
  Minus,
}

// struct name = { "Ratio" }
// struct members = { "numerator"[0..2], "denominator"[0..4] }
struct Ratio<T: Integer>{
  num: T,
  denom: T,
}

impl<T> Ratio<T>  {
  // some macro doing:
  // method name = {"power"[0..2]+"integer"[0]}
  // arguments = {"exponent"[0..2]}
  fn powi<I: Integer>(self, exp: I) -> Self {
    todo!()
  }


  // all following functions are { "get" + "_" + {name} }
  
  // method name = {"denominator"[0..4]}
  fn get_denom(&self) -> T {
    self.denom
  }
  // end
}
```
or in a match statement:
```rust
enum Fraction {
  Infinity(Sign)
  Rational(
}

fn some_function_that_is_very_intricate_and_uses_values_a_lot_so_i_have_short_names(input: Fraction, output: Fraction) {
  /// match scheme: { <type_name>[0]<var_name>[0] }
  match (input, output) {
    (Rational(si, ri), Rational(so, ro)) => {
      // perform calculations on si ri so ro
    }
  }
}
```
which would allow for translations and alternative formatting like:
```rust
// enum name = { "Ratio" }
// enum members = { "infinity", "rational" }
enum fraction {
  Infinity(Sign)
  Rational(Sign, Rational)
}


fn some_function_that_is_very_intricate_and_uses_values_a_lot_so_i_have_short_names(input: Fraction, output: Fraction) {
  // match scheme: { <type_name>_<var_name> }
  match (input, output) {
    (Rational(sign_input, ratio_input), Rational(sign_output, ratio_output)) => {
      // perform calculations on sign_input ratio_input sign_output ratio_output
    }
  }
}
```
or, after some non-cargo fmt has looked up translations, the `powi` function declaration will look like: 
```
// struct name = { "breuk" }
// struct members = { "teller"[0..2], "noem"[0..3] }
struct Ratio<T: Integer>{
  tel: T,
  noem: T,
}

impl<T> Ratio<T>  {
  // some macro doing:
  // method name = {"macht"[0..2]+"geheel_getal"[0]}
  // arguments = {"exponent"[0..2]}
  fn mach<I: Integer>(self, exp: I) -> Self {
    todo!()
  }


  // all following functions are { "krijg" + "_" + {name} }
  
  // method name = {"noemer"[0..3]}
  fn krijg_noem(&self) -> T {
    self.noem
  }
  // end
}
```
A huge hurdle would be how to handle imported crates, since working with a `powi` function from an external crate would be confusing. To me, this would greatly help in this case, because I find the English "numerator" and "denominator" highly confusing: is a fraction `numerator/denominator` or the other way around? Maybe a good start would be a match statement macro, but this is the fuller picture.

Maybe this is also outside the scope of cargo fmt, since it is renaming identifiers, while the compiler always nags about function names not being snake_case.

**Comment by ytmimi** [comment]
Thanks for reaching, but this isn't something rustfmt is going to support
