### ISSUE TITLE
Config in `rustfmt.toml` completely ignored on macOS

### ISSUE THREAD

**Issue by onbjerg** [rust-lang/rustfmt#6068]
Hi

I've had this issue for a while, but only on macOS. Using the formatter (`cargo fmt --all`) completely ignores any settings I have in `rustfmt.toml`. I do not have a global rustfmt.toml that interferes with my settings.

Details:

- I'm on an M2 (aarch64)
- I'm using the nightly toolchain, but this has been a persistent issue for me for over half a year

My rustfmt.toml:

```
reorder_imports = true
imports_granularity = "Crate"
use_small_heuristics = "Max"
comment_width = 100
wrap_comments = true
binop_separator = "Back"
trailing_comma = "Vertical"
trailing_semicolon = false
use_field_init_shorthand = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 100
```

Querying any config value shows that it is not respected:

```
❯ cargo fmt -- --print-config current . | grep binop
binop_separator = "Front"
❯ cargo fmt -- --print-config current . | grep comment_width
comment_width = 80
```

My toolchain versions:

```
❯ cargo fmt -- --version
rustfmt 1.7.0-nightly (98aa3624 2024-02-08)
❯ rustfmt --version
rustfmt 1.7.0-nightly (98aa3624 2024-02-08)
❯ cargo --version
cargo 1.78.0-nightly (ccc84ccec 2024-02-07)
❯ rustup show
Default host: aarch64-apple-darwin
rustup home:  /Users/onbjerg/.rustup

installed toolchains
--------------------

stable-aarch64-apple-darwin
nightly-aarch64-apple-darwin (default)
1.75-aarch64-apple-darwin

active toolchain
----------------

nightly-aarch64-apple-darwin (default)
rustc 1.78.0-nightly (98aa3624b 2024-02-08)
```

If I run with `--verbose`, rustfmt says that it *is* using my `rustfmt.toml`, but it is not, because it adds trailing semicolons and ignores other rules, which is very frustrating, as it works fine on CI.

```
❯ cargo fmt -- --verbose
Using rustfmt config file /Users/onbjerg/Projects/paradigmxyz/reth/rustfmt.toml for /Users/onbjerg/Projects/paradigmxyz/reth/bin/reth/src/lib.rs
Formatting /Users/onbjerg/Projects/paradigmxyz/reth/bin/reth/src/builder.rs
Formatting /Users/onbjerg/Projects/paradigmxyz/reth/bin/reth/src/cli/mod.rs
Formatting /Users/onbjerg/Projects/paradigmxyz/reth/bin/reth/src/commands/config_cmd.rs
Formatting /Users/onbjerg/Projects/paradigmxyz/reth/bin/reth/src/commands/db/clear.rs
Formatting /Users/onbjerg/Projects/paradigmxyz/reth/bin/reth/src/commands/db/diff.rs
[omitted for brevity]
```

**Comment by onbjerg** [comment]
FWIW I know of at least 2 others who have the exact same issue, also only on Mac.

**Comment by ytmimi** [comment]
@onbjerg thanks for reaching, and I'm sorry to hear that you're having issues. I'm pretty sure that `rustfmt --print-config current` expects a path to a file, not a directory. At least that's my assumption based on looking at the code:
https://github.com/rust-lang/rustfmt/blob/8486837d557c152fee52383852835d4941602423/src/bin/main.rs#L238-L252

The docs could probably be updated to make that clearer.  I'm curious, What do you get when you run `rustfmt --print-config current src/lib.rs`?

Also I appreciate all the effort you put into trying to explain the issue. Just so I know I'm understanding you correctly, you're saying that the correct `rustfmt.toml` isn't being located when you run `cargo fmt --all`?

**Comment by ytmimi** [comment]
I installed the same nightly toolchain as you `rustup install nightly-2024-02-09`, and cloned the [reth](https://github.com/paradigmxyz/reth) repo.

```
$: rustfmt +nightly-2024-02-09 --version
rustfmt 1.7.0-nightly (98aa3624 2024-02-08)

$: pwd
/Users/ytmimi/Documents/Projects/rust_projects/reth

$: cargo +nightly-2024-02-09 fmt -- --print-config current bin/reth/src/lib.rs | grep binop
binop_separator = "Back"

$: cargo +nightly-2024-02-09 fmt -- --print-config current bin/reth/src/lib.rs | grep comment_width
comment_width = 100
```

These seem to be the values coming from the `rustfmt.toml` in the root of `reth` repo.

**Comment by onbjerg** [comment]
Interesting, I see pointing to a file gives me the correct values, however, the formatter for some reason still *retains* (sometimes it inserts them but I can't reliably reproduce) semicolons, even though that shouldn't be the case:

```
❯ cargo +nightly fmt -- --print-config current bin/reth/src/lib.rs | grep trailing_semicolon
trailing_semicolon = false
```

Inserting a `;` at any place it could be omitted (e.g. L64 in `bin/reth/src/commands/db/list.rs`) and running `cargo +nightly fmt` over the file does not remove the semicolon, but it does on Linux.

**Comment by ytmimi** [comment]
@onbjerg are you manually invoking rustfmt (or cargo fmt) or is your editor? What directory are you in when you run rustfmt (or cargo fmt)? Above you mentioned `cargo fmt --all`, but none of your follow up examples have mentioned `cargo fmt --all`. Are there any other command line options that you're using when you try to format your project? Have you also experienced instances where formatting is applied properly?

Can you run `cargo fmt -v --all -- -v`. The first `-v` gets passed to `cargo fmt`, and the second `-v` (after the `--`) gets passed along to the underlying rustfmt invocation. If different configs are somehow getting used that should provide some additional details.

**Comment by onbjerg** [comment]
Sorry for the delayed response, I was flooded with notifications. I no longer experience this issue since I had to reinstall once again, so I'm not sure what the issue was 🤷🏻 I did not have any global config set as far as I could tell. Since I can't reproduce this anymore I'm closing the issue

Thank you for your time - and also sorry that I took some of it

**Comment by git-staus** [comment]
Please reopen this issue, I am experiencing the same problem.
```
$ cd ~/repos/xenharmony/
$ cat ~/.config/rustfmt/rustfmt.toml 
hard_tabs = true
$ cargo fmt -- --print-config current . | grep hard_tabs
hard_tabs = false
$ cargo fmt -- --version
rustfmt 1.8.0-nightly (160e7623e8 2025-08-26)
$ rustfmt --version
rustfmt 1.8.0-nightly (160e7623e8 2025-08-26)
$ cargo --version
cargo 1.91.0-nightly (623d53683 2025-08-22)
$ rustup show
Default host: x86_64-apple-darwin
rustup home:  /Users/me/.rustup

installed toolchains
--------------------
nightly-x86_64-apple-darwin (active, default)

active toolchain
----------------
name: nightly-x86_64-apple-darwin
active because: it's the default toolchain
installed targets:
  x86_64-apple-darwin
$ cargo fmt -- --verbose
Formatting /Users/me/repos/xenharmony/src/lib.rs
Formatting /Users/me/repos/xenharmony/src/orchestra.rs
Formatting /Users/me/repos/xenharmony/src/pitch.rs
Formatting /Users/me/repos/xenharmony/src/sample_ops.rs
Formatting /Users/me/repos/xenharmony/src/score_file.rs
Formatting /Users/me/repos/xenharmony/src/sound.rs
Formatting /Users/me/repos/xenharmony/src/wave_form.rs
Spent 0.003 secs in the parsing phase, and 0.006 secs in the formatting phase
Formatting /Users/me/repos/xenharmony/src/main.rs
Spent 0.000 secs in the parsing phase, and 0.001 secs in the formatting phase
$ 
```
In contrast to what @onbjerg observed, my `rustfmt` does not seem to even consider any configuration files.
 
Some context: I recently set up my Rust environment on this MacBook Pro by `git clone`ing my dotfiles from an Arch Linux machine on which `rustfmt` worked flawlessly. I am confident that no other configuration file somewhere is affecting `rustfmt`.

# Workaround

```
$ mv ~/.config/rustfmt/rustfmt.toml ~/.rustfmt.toml
$ cat ~/.rustfmt.toml
hard_tabs = true
$ cargo fmt -- --print-config current . | grep hard_tabs
hard_tabs = true
$ 
```
This is less clean because it pollutes my home directory (and in my case conflicts with my Git-based dotfile workflow).
