### ISSUE TITLE
Configure rustfmt to remove all whitespace

### ISSUE THREAD

**Issue by krakow10** [rust-lang/rustfmt#6077]
I like to write code with very little whitespace:
```Rust
pub fn read<R:Read>(input:R)->Result<DataStructure,ReadError>{
	let mut buf=std::io::BufReader::new(input);
	let peek=std::io::BufRead::fill_buf(&mut buf).map_err(ReadError::Io)?;
	match &peek[0..4]{
		b"<rob"=>Ok(DataStructure::Roblox(strafesnet_rbx_loader::read(buf).map_err(ReadError::Roblox)?)),
		b"VBSP"=>Ok(DataStructure::Source(strafesnet_bsp_loader::read(buf).map_err(ReadError::Source)?)),
		_=>Err(ReadError::UnknownFileFormat),
	}
}
```

I read through the configuration options and some issues relating to spaces, but could not find options to remove as much whitespace as possible.

According to this issue #4876 this is outside the scope of rustfmt.

Does this mean that my code style cannot be configured in `rustfmt.toml` and I cannot use rustfmt?

**Comment by ytmimi** [comment]
@krakow10 have you tried using `blank_lines_upper_bound=0`? That in combination with `use_small_heuristics=Max` might get you close. I hope that helps!

**Comment by ytmimi** [comment]
I ran your input with snippet with those options and setting `max_width=120` and this was the result:

configs used:
```toml
blank_lines_upper_bound=0
max_width=120
space_after_colon=false
use_small_heuristics="Max"
```

```rust
pub fn read<R:Read>(input:R) -> Result<DataStructure, ReadError> {
    let mut buf = std::io::BufReader::new(input);
    let peek = std::io::BufRead::fill_buf(&mut buf).map_err(ReadError::Io)?;
    match &peek[0..4] {
        b"<rob" => Ok(DataStructure::Roblox(strafesnet_rbx_loader::read(buf).map_err(ReadError::Roblox)?)),
        b"VBSP" => Ok(DataStructure::Source(strafesnet_bsp_loader::read(buf).map_err(ReadError::Source)?)),
        _ => Err(ReadError::UnknownFileFormat),
    }
}
```

**Comment by ytmimi** [comment]
Other configs you might consider using are:
* [type_punctuation_density="Compressed"](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#type_punctuation_density)
* [fn_params_layout ="Compressed"](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#fn_args_layout)
* [overflow_delimited_expr=true](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#overflow_delimited_expr)

**Comment by ytmimi** [comment]
For now at least I don't think we'll provide a blanket option to remove all unnecessary whitespace, but I hope these suggestions help.

**Comment by krakow10** [comment]
I was not expecting to find a blanket option, as I was scrolling through the rustfmt options I expected to find many options to include/exclude spaces around specific operators like arithmetic, match statements, blocks, etc, but I was surprised to not be able to configure it that way.
