### ISSUE TITLE
thread 'main' panicked at src/tools/rustfmt/src/parse/session.rs:42:9

### ISSUE THREAD

**Issue by emhane** [rust-lang/rustfmt#6081]
query stack during panic:
end of query stack

[rustc-ice-2024-02-18T21_13_56-96599.txt](https://github.com/rust-lang/rustfmt/files/14324913/rustc-ice-2024-02-18T21_13_56-96599.txt)

**Comment by ytmimi** [comment]
@emhane thanks for the report. Without a code snippet that we can run rustfmt on to reproduce the panic there's little we can do to help. It would also be very helpful to know what version of rustfmt you're using and what configurations you might be using.

**Comment by emhane** [comment]
`rustfmt 1.7.0-stable (07dca489 2024-02-04)`

sorry, I don't have a minimal repro at my disposal.

**Comment by ytmimi** [comment]
Unfortunately without that we can't really help 😔

**Comment by ytmimi** [comment]
@emhane just wanted to say thanks again for bringing this to our attention. After looking over the panic text that you linked this seems nearly identical to #6082. I believe the panic is related to a recent change in the compiler. Out of curiosity, were you running rustfmt on a public repository at the time when you experienced the panic?

**Comment by emhane** [comment]
sure, yes I was https://github.com/paradigmxyz/reth
