### ISSUE TITLE
Use statement: `self` stays inside braces

### ISSUE THREAD

**Issue by Oughie** [rust-lang/rustfmt#6129]
Consider the following example:

`use std::io::{self};`

rustfmt does not modify this.
Instead, it should automatically turn into:

`use std::io;`

**Comment by ytmimi** [comment]
@Oughie To the best of my knowledge `use std::io::{self};` and `use std::io;` are semantically different. See https://github.com/rust-lang/rustfmt/issues/3750 as an example. That's why rustfmt doesn't modify the code.
