### ISSUE TITLE
error[internal]: left behind trailing whitespace

### ISSUE THREAD

**Issue by skrobchik** [rust-lang/rustfmt#6141]
Hello 👋 

I'm getting an error when running `cargo fmt` in my project. Here's the [commit](https://github.com/skrobchik/calenda-rs/commit/b44a48b369f3e3d411a6bcc8c76a01eee7ffb29f).

Not sure if you need any logs? I didn't see any guidelines for filing bug reports, so please let me know if anything is needed 😄 

```
PS C:\Users\Robert\Desktop\Git Projects\calenda-rs> git clean -ffdx
PS C:\Users\Robert\Desktop\Git Projects\calenda-rs> git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
PS C:\Users\Robert\Desktop\Git Projects\calenda-rs> cargo fmt
error[internal]: left behind trailing whitespace
   --> \\?\C:\Users\Robert\Desktop\Git Projects\calenda-rs\crates\calendars_egui\src\class_editor.rs:132:132:1
    |
132 |
    | ^^^^
    |

error[internal]: left behind trailing whitespace
   --> \\?\C:\Users\Robert\Desktop\Git Projects\calenda-rs\crates\calendars_egui\src\class_editor.rs:145:145:1
    |
145 |
    | ^^^^
    |

warning: rustfmt has failed to format. See previous 2 errors.

PS C:\Users\Robert\Desktop\Git Projects\calenda-rs> rustfmt --version
rustfmt 1.7.0-nightly (9d5cdf75 2024-04-07)
PS C:\Users\Robert\Desktop\Git Projects\calenda-rs> rustc --version
rustc 1.79.0-nightly (9d5cdf75a 2024-04-07)
PS C:\Users\Robert\Desktop\Git Projects\calenda-rs> cargo --version
cargo 1.79.0-nightly (28e7b2bc0 2024-04-05)
PS C:\Users\Robert\Desktop\Git Projects\calenda-rs>
```

**Comment by ytmimi** [comment]
@skrobchik thanks for the report. When you get a chance, can you try to minimize the reproducible example to be as small as possible. Taking a look at the commit that you referenced I suspect this might be another duplicate of #3863 leading to rustfmt complaining about whitespace that exists within the source code.

**Comment by twhice** [comment]
this error also happen in my project, while formating chain-call, like:
``` rust
        let benches: Vec<_> = self[gidx]
            .res
            
            .iter()
```
then:
``` shell
yiyue@terc ~/Pin1Yin1-Compiler-Rust (main)> rustfmt py-ast/src/semantic/declare/map.rs
error[internal]: left behind trailing whitespace
  --> /home/yiyue/Pin1Yin1-Compiler-Rust/py-ast/src/semantic/declare/map.rs:72:72:1
   |
72 |             
   | ^^^^^^^^^^^^
   |

warning: rustfmt has failed to format. See previous 1 errors.
```
because i always use vscode's format on save to format my code, it's hard to not notice that the code is not formated after i changed the code

although i can get error by using cli, there are not any log are printed...

**Comment by konstin** [comment]
Here's a semi minimal example (make sure your ide doesn't remove trailing whitespace by default):

```rust
impl Preferences {
    fn from_iter() -> Self {
        Self(
            preferences
                .filter_map(|preference| {
                    trace!(
                        "Excluding {} from preferences due to unmatched markers.", requirement.name
                    );
                    match requirement {
                        UvSource => {
                            if *ve {
                                trace!(
                                    "Excluding {} from preferences due to inexact version specifier.", requirement.name
                                );
                            }
                        }
                    }

                    

                })
                .collect(),
        )
    }
}
```
Playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=01c66f1e423afb96d09aaebbbf5f7e33

**Comment by ytmimi** [comment]
@konstin your example is definitely a duplicate of #3863. `preferences.filter_map().collect()` is a chain, and there are lines that exceed the `max_width`.

Because of the nested nature of the code, the line with the string literal exceeds the default width of 100.

```rust
                                trace!(
                                    "Excluding {} from preferences due to inexact version specifier.", requirement.name
                                );
```

You have 3 options:
1. bump the `max_width`
2. manually break the string literal over multiple lines
3. if you're using nightly rustfmt you can try using `format_strings=true`

**Comment by ytmimi** [comment]
@skrobchik having just reviewed the commit it would seem that this line 👇🏼 is causing the `ui.vertical(|ui| {}) call on line 60 from being formatted, therefore failing to remove whitespace that exists in the program.

```
              "El programa intentara asignar una aula de las categorias seleccionadas a esta clase.",
```

Taking a look at [the file](https://github.com/skrobchik/calenda-rs/blob/b44a48b369f3e3d411a6bcc8c76a01eee7ffb29f/crates/calendars_egui/src/class_editor.rs) shows that there is indeed trailing whitespace in the commit:

<img width="726" alt="Screen Shot 2024-04-17 at 11 25 21 AM" src="https://github.com/rust-lang/rustfmt/assets/29028348/dbea0d0a-3567-41ac-abfc-4eff4b412e06">

**Comment by konstin** [comment]
Would it be possible to disable the trailing whitespace check if rustfmt gave up on a too long line? Rustfmt not touching a piece of the AST is fine, the current error makes it look like you discovered a bad rustfmt bug
