### ISSUE TITLE
array pattern formatting does not honour column limit

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rustfmt#6145]
Consider following code:

```rust
fn main() {
    let [
        mut insert_count, 
        mut set_count, 
        mut update_rc_count, 
        mut delete_count, 
        mut delete_all_count, 
        mut delete_range_count
    ] = [0u64; 6];
}
```

[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=a73d02e3cb1b2c058a2ce26892287812)

Rustfmt will put the whole pattern on a single line, even though it well exceeds the 100 columns rustfmt should target.

**Comment by ytmimi** [comment]
@nagisa [this fixed when using `Version=Two`](https://github.com/rust-lang/rustfmt/issues/5577#issuecomment-1322955255)

**Comment by nagisa** [comment]
One thing I'm missing in the referenced issue is why Version=Two scheme was necessitated? Is there a writeup on this somewhere? Could that be linked from a message (ideally the first one) in the referenced issue?

**Comment by ytmimi** [comment]
@nagisa I tracked this down to https://github.com/rust-lang/rustfmt/pull/4994, and we needed `version=Two` because it would have been a breaking change to introduce this to all users at the time. https://github.com/rust-lang/rustfmt/pull/4994#issuecomment-926295069
