### ISSUE TITLE
Silent removal of comments

### ISSUE THREAD

**Issue by VorfeedCanal** [rust-lang/rustfmt#6190]
Is it normal that `cargo fmt` sometimes just silently removes comments like they were not there?

Here is simple reproducer:
```
trait 𝔉𝔬𝔬<𝓽𝔂𝓹𝓮: ?Sized> /* : 𝔅𝔞𝔯 */ {}
```
Trait `𝔉𝔬𝔬` exists while `𝔅𝔞𝔯` is not yet implemented so I commented it out.

After I run it through `rustfmt` the output looks like this:
```
trait 𝔉𝔬𝔬<𝓽𝔂𝓹𝓮: ?Sized> {}
```

Like comment was never there. Nor warnings or any other hints that something was removed.

**Comment by calebcartwright** [comment]
Thanks for reaching out, going to close as a duplicate as it's a known issue with more nuance and TBD items than one might initially suspect (e.g. https://github.com/rust-lang/style-team/issues/191).

We're currently focused on critical items for Edition 2024, but I'm hopeful we can make an adjustment here to at least avoid the removal of the comment even if we're not fully prepared to format items containing comments within the header
