### ISSUE TITLE
rustfmt report "rewriting static"

### ISSUE THREAD

**Issue by Sherlock-Holo** [rust-lang/rustfmt#6213]
```rust
static A: i32 = 10;
static B: i32 = 10;
```

this codes has 2 static variables, then `rustfmt --edition 2021 /tmp/ttt/aaa/src/lib.rs` report

> rewriting static
> rewriting static

it looks like it reports `rewriting static` as many times as I have static variables

the rustfmt version is `rustfmt 1.7.1-nightly (bcf94de 2024-06-23)`

that didn't happen in previous version, such as `rustfmt 1.7.0-nightly (c1b336c 2024-06-21)`

also, use `cargo fmt` to format also has this problem

**Comment by djmitche** [comment]
[https://github.com/rust-lang/rustfmt/issues/6213 /](https://github.com/rust-lang/rustfmt/blob/e4944185ae09c99f59b460e358909f329010ea9c/src/items.rs#L1997) looks like a likely culprit.

**Comment by djmitche** [comment]
https://github.com/rust-lang/rust/pull/126888 fixes
