### ISSUE TITLE
How to force new line before `else` in `let else` statements?

### ISSUE THREAD

**Issue by Houtamelo** [rust-lang/rustfmt#6221]
I'm have rustfmt 1.7.1, configured with: `single_line_let_else_max_width = 0`

Considering a simple `let else` statement:
```rs
let DynamicArray::Owned(vec) = self else { unreachable!() };
```

I expected the configuration to always put the else in the next line:
```rs
let DynamicArray::Owned(vec) = self 
else { unreachable!() };
```

Instead, it includes a new line after the else's opening brace:
```rs
let DynamicArray::Owned(vec) = self else { 
    unreachable!()
};
```

Is this by design? If so, is there a way to configure it?

**Comment by ytmimi** [comment]
Yes this is by design. [See the style guide](https://doc.rust-lang.org/nightly/style-guide/statements.html#else-blocks-let-else-statements). At the moment the only configuration is `single_line_let_else_max_width` to control when the entire statement can fit on one line.
