### ISSUE TITLE
Allow use of unstable features from rustfmt.toml

### ISSUE THREAD

**Issue by proski** [rust-lang/rustfmt#6257]
Some unstable features can be used on the command line but not in `rustfmt.toml`. Let's try a newly created crate:

```
proski@ins1:~/src/hello$ cargo fmt -- --config imports_granularity=module
proski@ins1:~/src/hello$ echo 'imports_granularity = "module"' >rustfmt.toml
proski@ins1:~/src/hello$ cargo fmt
Warning: can't set `imports_granularity = Module`, unstable features are only available in nightly channel.
```

Sadly, adding `unstable_features = true` to `rustfmt.toml` makes no difference.

I'd like to have a way to enable unstable features in `rustfmt.toml` as long as they can be enabled on the command line. I wouldn't mind warnings, as long as the features are not ignored.

Rationale:

* I'm using version control and continuous integration. Even if rustfmt damages my code beyond repair, there is a way for me to detect it early and recover.

* I trust rustfmt not to damage anything other than the code it's asked to format, even when using unstable features.

* `rustfmt.toml` can be added to version control, reviewed by other developers and updated as needed. Wrappers around `cargo fmt` can be under version control too, but it's harder to ensure that every developer is using the current version.

* It's just illogical to treat command line arguments so differently from the configuration files. Some difference can be expected, but disabling functionality is too much.

**Comment by calebcartwright** [comment]
Thanks for reaching out but I'm going to close as this is unplanned.

Regardless of my personal perspective on the matter, there's a Project-wide posture relative to the availability of unstable features from stable toolchains, and any cases where they have slipped through are viewed as bugs (see the semi-recent removal of json formatting support for libtest that had slipped through to stable).

This is something that's been known for a while, and it wasn't a deliberate decision to allow unstable options but only from certain input sources. At some point we're probably going to be forced to remove the ability for these to be provided from the CLI, but that's a change that we know would have a decent sized blast radius and I'm trying to defer it as long as possible.

**Comment by nablabla** [comment]
So do I see this correctly, that "unstable_features = true" was removed? So some settings in my rustfmt.tom do no longer work and now i have to reformat my whole project (to a format that is less clear) and check it all in?

**Comment by proski** [comment]
I don't think it's productive to discuss anything in a closed ticket. But I'd like to reiterate that was asking to add support for unstable feature to the rustfmt configuration. That support did not exist at the time when I made the request. I have no evidence that it was supported at any time and then got removed.

**Comment by nablabla** [comment]
But it would be nice to know how to enable it. For vs code, I tried the following .vscode/settings.json:
```
"rust-analyzer.rustfmt.extraArgs": ["--unstable-features"],
    "rust-analyzer.rustfmt.overrideCommand": [
        "rustfmt", "+nightly", "--unstable-features"
    ],
    "[rust]": {
        "editor.defaultFormatter": "rust-lang.rust-analyzer",
        "editor.formatOnSave": true
    }
```
I am not shure which did the trick, since removing it seems not undo it
