### ISSUE TITLE
Strange formatting when comments are interspersed in an expression.

### ISSUE THREAD

**Issue by JulianKnodt** [rust-lang/rustfmt#6269]
Minimal(ish) repo:
```
fn main() {
    let v = 1 + 1 +
  // test
  3;
  
    let test = 3;
    // o
}
```

I would expect the comment `// test` to have the correct indentation and 3 to also be indented.
The later lines are indented correctly.

Tested on current playground, Rust 1.70 Stable
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b7abe453f272fbf2bd4e8dfeac344ddb

**Comment by ytmimi** [comment]
I believe this is the same underlying issue as #3591 and #3167. rustfmt doesn't handle comments well within binary operators.
