### ISSUE TITLE
Format derive attributes alphabetically

### ISSUE THREAD

**Issue by maksym-arutyunyan** [rust-lang/rustfmt#6298]
[Feature Request] 

Please add a feature to automatically format `#[derive(...)]` attributes in alphabetical order by default.

```rs
// Current (not sorted):
#[derive(Ord, PartialEq, Eq, Hash, Debug, Clone)]

// Desired (sorted):
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq)]
```

Thank you!

**Comment by ytmimi** [comment]
Closing this as a duplicate of https://github.com/rust-lang/rustfmt/issues/4112.
