### ISSUE TITLE
Breaking change in type alias with bound

### ISSUE THREAD

**Issue by robertbastian** [rust-lang/rustfmt#6348]
The formatting of the declaration

```rust
type W<'a> = T::W<'a> where T: 'a;
```

changed in nightly-2024-09-22. The above code is formatted on stable, now it gets formatted to

```rust
type W<'a>
    = T::W<'a>
where
    T: 'a;
```

**Comment by ytmimi** [comment]
This was an expected change. Previously rustfmt didn't format type aliases that had trailing where clauses and now it does based on the [prescription in the style guide](https://doc.rust-lang.org/nightly/style-guide/items.html#type-aliases).

[For a full list of things that changed in the 1.8.0 release see the changelog](https://github.com/rust-lang/rustfmt/blob/master/CHANGELOG.md#180-2024-09-20).
