### ISSUE TITLE
`rustfmt` doesn't always remove unecessary `where` clause

### ISSUE THREAD

**Issue by kennykerr** [rust-lang/rustfmt#6385]
Given:

```rust
fn test() where {}
```

`rustfmt` will correctly produce:

```rust
fn test() {}
```

But given:

```rust
fn test() -> () where {}
```

`rustfmt` will fail to remove the unecessary `where` clause.

**Comment by ytmimi** [comment]
Duplicate of https://github.com/rust-lang/rustfmt/issues/4649.

**Comment by riverar** [comment]
@ytmimi Not sure that's an appropriate issue to dupe on. That issue is concerned with incorrect _removal_ of the where clause. This issue is concerned with incorrect _preservation_ of the where clause.
