### ISSUE TITLE
"`version` option is deprecated", but documented as valid

### ISSUE THREAD

**Issue by ethanmsl** [rust-lang/rustfmt#6401]
**rustfmt.toml** contains the following line:
```toml
version = "Two"
```

When I run `cargo fmt` I get the following warning:
> *Warning: the version\` option is deprecated. Use \`style_edition\` instead.*

However, the "**version**" is documented in this github repo's documentation here:
[Configuring rustfmt: version](https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=#version)

> [version](https://rust-lang.github.io/rustfmt/#version)
>
>Which version of the formatting rules to use. Version::One is backwards-compatible with Rustfmt > 1.0. Other versions are only backwards compatible within a major version number.
>
> Default value: One
> Possible values: One, Two
> Stable: No (tracking issue: [#3383](https://github.com/rust-lang/rustfmt/issues/3383))

But there is no entry for "**style_edition**".

However, looking at the tracing issue listed above (3383) we see that "version" is now listed as "not planned".

________________

This may simply be a matter of needing to link to up-to-date docs on the github site, but bears mentioning.

Edit: Ah, I see, the link defaults to **v1.6**.  Perhaps that's reasonable.  I'm on nightly and this may be the source of confusion.  I'm not sure what version stable uses.
![Image](https://github.com/user-attachments/assets/b5d70064-5907-46a9-bf03-8bae70f7ec08)

**Comment by ytmimi** [comment]
Yeah, `style_edition` [is documented in v1.8.0](https://rust-lang.github.io/rustfmt/?version=v1.8.0&search=#style_edition). A more detailed description of how style_edition relates to version can be [found here](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#version).
