### ISSUE TITLE
document skip_children deprecation

### ISSUE THREAD

**Issue by ernieIzde8ski** [rust-lang/rustfmt#6402]
`skip_children` was deprecated in #3893, but this is not reflected in the documentation:

[Configurations.MD#skip_children](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#skip_children)

**Comment by ytmimi** [comment]
@ernieIzde8ski `skip_children` is not deprecated. A while back there was a plan to deprecate the option in a v2.0 release, but that never came to fruition. The option is still valid.
