### ISSUE TITLE
Rustfmt takes a long time to format with miniscule change

### ISSUE THREAD

**Issue by Paladynee** [rust-lang/rustfmt#6405]
This block formats instantly (no perceivable delay):
```rs
let a = ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||0;
```

however this block with 1 more closure SIGNIFICANTLY slows rustfmt down (takes 6-7 seconds on my computer):
```rs
let a = ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||0;
```

i could not get the next step to format.
```rs
let a = ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||0;
```

**Comment by ytmimi** [comment]
This gets parsed as a closure, inside of a closure, inside of a closure, inside of a closure, .etc, and is on a pretty slow recursive formatting path. You can see all the work rustfmt is doing by running  rustfmt with debug logging turning on.  

`RUSTFMT_LOG=debug rustfmt path/to/file`.

This is a duplicate of #5626
