### ISSUE TITLE
Simplify `use std::io::{self};`

### ISSUE THREAD

**Issue by iago-lito** [rust-lang/rustfmt#6415]
I sometimes end up with this kind of dummy import lines:

```rs
use std::io::{self};
```

Maybe `rustfmt` could simplify it into:
```rs
use std::io;
```
?

**Comment by ytmimi** [comment]
@iago-lito This has come up before. My understanding is that there are semantic differences between `use std::io::{self};` and `use std::io;`, so rustfmt can't safely make that change without potentially breaking your code. See #3568 and other linked issues.
