### ISSUE TITLE
rustfmt removes crucial code from macro calls (regression)

### ISSUE THREAD

**Issue by nazar-pc** [rust-lang/rustfmt#6424]
Probably related to https://github.com/rust-lang/rustfmt/issues/6418, but not 100% sure.

rustfmt recently started formatting code like this incorrectly:
```rust
frame_support::construct_runtime!(
    pub struct Test {
        System: frame_system = 0,
        SelfDomainId: pallet_domain_id = 1,
    }
);
```

Specifically, it removes `= NUMBER` for some reason, resulting in this:
```rust
frame_support::construct_runtime!(
    pub struct Test {
        System: frame_system,
        SelfDomainId: pallet_domain_id,
    }
);
```

This is incorrect and not an equivalent change.

Affected version:
```
rustfmt 1.8.0-nightly (426d173423 2024-12-21)
```

Version that I used previously and that worked correctly:
```
rustfmt 1.8.0-nightly (4392847410 2024-10-21)
```

**Comment by ytmimi** [comment]
Thanks for the report. I tracked this change in behavior back to https://github.com/rust-lang/rust/pull/129514

**Comment by nazar-pc** [comment]
Note that it also removes values which are not contiguous (let's say if `= 0` is replaced with `= 60`), it just removes them all regardless.

**Comment by ytmimi** [comment]
@nazar-pc sorry, but I'm having a hard time understanding what you're getting at. Could you provide a code snippet?

**Comment by nazar-pc** [comment]
Sure:
```rust
frame_support::construct_runtime!(
    pub struct Test {
        System: frame_system = 60,
        SelfDomainId: pallet_domain_id = 1,
    }
);
```

In this case both will be removed too. I just assumed that in some cases it might remove things due to considering them being "the default", but no.

**Comment by ytmimi** [comment]
Thanks for the update. No, I don't think that's the case. An explanation for what's going on here can be found at https://github.com/rust-lang/rust/pull/134668

**Comment by nazar-pc** [comment]
Works correctly again in this version:
```
rustfmt 1.8.0-nightly (bdc6b3de48 2024-12-23)
```
