### ISSUE TITLE
Improvements to cargo-fmt

### ISSUE THREAD

**Issue by JanLikar** [rust-lang/rustfmt#702]
This is a tracking issue for the improvements I wish to make to the `cargo-fmt` binary.
- [X] Add a way to pass arguments to the `rustfmt` binary
- [x] Add verbose mode
- [x] Add quiet mode (suppresses rustfmt's stdout)
- [x] Coloured output
- [ ] Add optional flags to format `build.rs` and files in `tests` and `examples` directories
- [X] Add a way to override `--write-mode=overwrite`
- [ ] Decouple cargo-fmt from rustfmt binary

**Comment by nrc** [comment]
I would like for `rustfmt` and `cargo fmt` to share more code, in particular with arguments so that users can move from `rustfmt` to `cargo fmt` easily.

**Comment by JanLikar** [comment]
Could you elaborate?

**Comment by nrc** [comment]
Seems like a lot of the options one would pass to either rustfmt or cargo fmt are the same, so it would be the nice if they could share code. Also some of the more generic code to set up the rustfmt lib.

**Comment by JanLikar** [comment]
Do you think we could use docopt instead of getopts?

**Comment by nrc** [comment]
Yeah, I think so? I don't have much experience with docopt, but if you think it is better, than I am not against changing.

**Comment by JanLikar** [comment]
It's not necessarily better, but in this case code would be a bit less verbose.
