### ISSUE TITLE
Support for comma-first style

### ISSUE THREAD

**Issue by hawkw** [rust-lang/rustfmt#752]
I prefer the [comma-first coding style](https://gist.github.com/isaacs/357981)  and like using it in my Rust projects. I'd love to see a config option in `rustfmt` to allow this style.

**Comment by hawkw** [comment]
I'd be quite happy to implement this feature myself, but I am not terribly familiar with how `rustfmt` works under the hood. If I could get a couple pointers in the right direction, I'll fork the project and try to add this feature.

**Comment by nrc** [comment]
@hawkw have you seen https://github.com/rust-lang-nursery/rustfmt/blob/master/Contributing.md#a-quick-tour-of-rustfmt ? I imagine you could implement this by changing code in lists.rs, unfortunately that is some of the more complex parts of rustfmt. Once you've had a look, feel free to ask questions here or on irc.

**Comment by topecongiro** [comment]
We are unlikely to support this, sorry.
