### ISSUE TITLE
Prevent modification of a comment section.

### ISSUE THREAD

**Issue by dpc** [rust-lang/rustfmt#763]
How do I prevent rustfmt from changing my comment? Sometimes people need to do some tricky stuff inside comments, and they have a reason for keeping them the way there are.

**Comment by nrc** [comment]
We don't have a way yet. We'd like a comment equivalent of rustfmt_skip.

**Comment by nrc** [comment]
We now skip comments by default.

**Comment by dpc** [comment]
Any way to make it selective? I actually would be happy to have to comments changed except for rare cases.

**Comment by nrc** [comment]
not yet, I would like to add such a feature at some point though
